// content/y11/geography/islands/x06.js — Year 11 Geography Topic 6 expansion: Exam Technique: 6 & 9-Mark Questions. All original.

FLASHCARDS.push(
  // g11i-06-1 — Describe & Explain Questions (continuing from -5)
  {id:"g11fc-06-1-6", islandId:"g11i-06-1", front:"What is the 'point-evidence-explain' (PEE) structure?", back:"A way to develop each paragraph of a 6-mark answer:\n• Point — make a clear statement\n• Evidence — back it with data, a fact or a place name\n• Explain — link it to the question with a reason\n\nExample: 'Erosion is rapid at Holderness (point). Cliffs retreat 1.8 m/year (evidence) because the soft boulder clay is easily undercut (explain).'", difficulty:2, category:"concept"},
  {id:"g11fc-06-1-7", islandId:"g11i-06-1", front:"Roughly how long should you spend on a 6-mark question?", back:"About 1 to 1.5 minutes per mark, so around 7–9 minutes.\n\nThis includes a few seconds to read the command word and plan three points. Spending much longer risks running out of time on later questions.", difficulty:2, category:"application"},
  {id:"g11fc-06-1-8", islandId:"g11i-06-1", front:"How do you use a named example in a 'describe and explain' answer?", back:"Anchor your points to a specific, real place rather than writing in general terms.\n\nInstead of 'rivers cause flooding', write 'the River Calder flooded Hebden Bridge in 2015'. A named example shows you can apply knowledge and lifts the answer into the higher mark band.", difficulty:2, category:"application"}
);

QUESTIONS["g11i-06-1"] = (QUESTIONS["g11i-06-1"] || []).concat([
  {q:"In the PEE structure, the 'E' for 'evidence' means you should:", opts:["Include specific data, a fact or a place name","Make a general statement","Write a conclusion","Give your opinion"], c:0, e:"Evidence means specific support such as a statistic or place name; a general statement is the 'Point', not the evidence."},
  {q:"Which is the best example of 'explain' rather than 'describe'?", opts:["Temperatures fall with altitude","The graph shows a peak in July","Rainfall is heavy because warm air rises and cools","The river is 50 km long"], c:2, e:"'Because warm air rises and cools' gives a reason, which is explanation; the others simply state facts (description)."},
  {q:"A student answers a 'describe the distribution' question by giving reasons for the pattern. This:", opts:["Earns full marks anyway","Is the correct approach","Earns SPaG marks instead","Risks losing marks because it does not match the command word"], c:3, e:"Describe asks WHAT the pattern is, not WHY; giving reasons addresses 'explain' and misses the set task. Content being correct does not rescue a mismatched command word."},
  {q:"Roughly how much time should a 6-mark question take?", opts:["About 7–9 minutes","About 30 seconds","About 20 minutes","The whole exam"], c:0, e:"At around 1 to 1.5 minutes per mark a 6-mark answer needs roughly 7–9 minutes; 30 seconds is far too little to develop three points."},
  {q:"'Describe the trend shown in Figure 2' tells you to:", opts:["Explain why the trend happens","Evaluate the data's reliability","State what the data shows, using figures","Define the term trend"], c:2, e:"Describe + a figure means state the pattern and quote values; explaining why would answer a different command word."},
  {q:"A student writes: 'It is hot. It rains. There are trees.' The main weakness is that it:", opts:["Uses too much terminology","Lists undeveloped facts with no explanation or evidence","Is too long","Includes a named example"], c:1, e:"The answer lists facts without developing them with reasons or data, so it stays in the lowest band; it is the opposite of over-long or over-technical."},
  {q:"How many fully developed points typically secure full marks on a 6-mark explain question?", opts:["Six short points","One long point","Ten brief points","Three developed points"], c:3, e:"Three developed PEE points usually reach the top; six shallow points or one undeveloped point do not show enough reasoning."},
  {q:"Adding 'the River Calder flooded Hebden Bridge in 2015' to an answer is good because it:", opts:["Provides a specific named example","Wastes words","Replaces the need to explain","Counts as SPaG only"], c:0, e:"A named real place anchors the point and shows applied knowledge; it supports, rather than replaces, the explanation."},
  {q:"Which sentence best 'links back to the question' for 'Explain why deforestation increases flooding'?", opts:["Trees are tall","With fewer trees to intercept rain, more water reaches rivers quickly, raising flood risk","This is interesting","Deforestation is bad"], c:1, e:"The chosen option ends with a reason tied to flood risk, completing the explanation; the others are vague and never connect to flooding."},
  {q:"The command word in a question matters most because it:", opts:["Tells you which case study to use","Tells you what the examiner wants you to do","Sets the time limit","Decides the SPaG marks"], c:1, e:"The command word defines the task (describe, explain, etc.); the case study and timing follow from understanding it, but they are not what the word itself signals."}
]);

FLASHCARDS.push(
  // g11i-06-2 — Evaluate & Assess Questions (continuing from -5)
  {id:"g11fc-06-2-6", islandId:"g11i-06-2", front:"What are AO1, AO2 and AO3 in a 9-mark answer?", back:"Assessment Objectives the mark scheme rewards:\n• AO1 — knowledge (facts, terms, case-study detail)\n• AO2 — understanding/application (linking ideas to the question)\n• AO3 — analysis and evaluation (weighing up and judging)\n\nA top 9-mark answer must do all three, not just recall AO1 facts.", difficulty:3, category:"concept"},
  {id:"g11fc-06-2-7", islandId:"g11i-06-2", front:"Why must you use data and figures in an evaluate answer?", back:"Specific figures turn a vague claim into supported evaluation.\n\n'Sea walls are expensive' is weak. 'Sea walls cost £5000–10000 per metre' is precise evidence the examiner can credit, and it strengthens your judgement.", difficulty:3, category:"application"},
  {id:"g11fc-06-2-8", islandId:"g11i-06-2", front:"How is a 'judgement' different from a 'summary'?", back:"A summary just restates what you wrote. A judgement decides and justifies.\n\nSummary: 'There are advantages and disadvantages.'\nJudgement: 'On balance hard engineering is effective for high-value towns but too costly for long stretches, so I judge it only partly effective.'", difficulty:3, category:"application"}
);

QUESTIONS["g11i-06-2"] = (QUESTIONS["g11i-06-2"] || []).concat([
  {q:"In the mark scheme, AO3 mainly rewards:", opts:["Recalling facts","Analysis and evaluation leading to a judgement","Spelling and grammar","Drawing a diagram"], c:1, e:"AO3 covers analysis and evaluation; recalling facts is AO1 and spelling sits under SPaG, not AO3."},
  {q:"A 9-mark answer that only lists facts about a case study will:", opts:["Stay in a lower band because it lacks evaluation","Reach the top band","Lose all AO1 marks","Gain extra SPaG marks"], c:0, e:"Facts alone show AO1 but not the AO3 evaluation needed for the top band; the AO1 knowledge is still credited, just not enough on its own."},
  {q:"Which sentence shows a clear judgement rather than a summary?", opts:["There are pros and cons to consider","Many factors are involved","On balance the scheme is effective for towns but too costly elsewhere, so it is only partly successful","I have discussed both sides"], c:2, e:"The chosen option commits to a justified verdict; the others merely note that two sides exist without deciding."},
  {q:"'Assess the importance of relief in causing rainfall' asks you to:", opts:["List types of rainfall","Describe a mountain","Define rainfall","Judge how significant relief is compared with other causes"], c:3, e:"Assess means weigh the significance of relief against other factors and judge; describing or listing misses the evaluative task."},
  {q:"Why should you include figures such as '£5000–10000 per metre' in an evaluation?", opts:["To turn a vague claim into supported, creditable evidence","To fill space","Because SPaG needs numbers","To avoid writing a conclusion"], c:0, e:"Precise data supports the point and can be credited as evidence; it is not padding and does not remove the need for a conclusion."},
  {q:"A student's 9-mark answer argues only the 'for' side with no counter-argument. The likely result is:", opts:["Top marks for focus","Disqualification","A capped, lower mark because it lacks balance","Extra AO1 marks"], c:2, e:"Evaluate/assess answers need balance before judging, so a one-sided response is capped below the top band; it is not disqualified, just limited."},
  {q:"Which connective best introduces a counter-argument in an evaluate answer?", opts:["Firstly","However, critics argue that","In addition","Therefore"], c:1, e:"'However, critics argue that' signals the opposing view; 'in addition' and 'firstly' add same-side points and 'therefore' draws a conclusion."},
  {q:"AO2 (application) is best demonstrated when you:", opts:["List definitions","Copy the question","Write longer sentences","Link your knowledge directly to the specific question or resource"], c:3, e:"AO2 rewards applying knowledge to the exact question; listing definitions is AO1 recall and copying the question shows nothing."},
  {q:"The strongest conclusion to 'Evaluate the success of a flood scheme' would:", opts:["Repeat every point made","Introduce a brand-new case study","State an overall verdict and justify it with the strongest evidence","Ask the reader to decide"], c:2, e:"A top conclusion judges and justifies using evidence already given; repeating points or adding new material weakens it, and the student, not the reader, must decide."},
  {q:"A balanced 9-mark answer is best planned by:", opts:["Writing immediately with no plan","Memorising the answer","Only listing 'for' points","Quickly noting 'for' and 'against' points before deciding a position"], c:3, e:"A brief for/against plan ensures balance and a clear line of argument; writing with no plan risks a one-sided, rambling answer."}
]);

FLASHCARDS.push(
  // g11i-06-3 — 'To What Extent' & SPaG (continuing from -5)
  {id:"g11fc-06-3-6", islandId:"g11i-06-3", front:"Where do the three SPaG marks come from on a 9-mark question?", back:"They are awarded for technical accuracy across the whole answer, not a separate paragraph:\n• Accurate spelling, especially of geographical terms\n• Correct punctuation and full sentences\n• Accurate, well-used subject terminology\n\nYou earn them by writing well throughout, then proofreading for 2 minutes.", difficulty:2, category:"concept"},
  {id:"g11fc-06-3-7", islandId:"g11i-06-3", front:"How do you phrase a 'to what extent' conclusion?", back:"Place your verdict on a scale of agreement and justify it.\n\nUse a stem such as: 'To a large extent I agree, because…' or 'I agree only to a limited extent, since…'. Avoid 'I'm not sure' — the examiner needs a clear degree of agreement.", difficulty:3, category:"application"},
  {id:"g11fc-06-3-8", islandId:"g11i-06-3", front:"How does time allocation work for a 9-mark question?", back:"At about 1 minute per mark, allow roughly 9 minutes plus a little for the +3 SPaG marks, so around 11–12 minutes.\n\nReserve the final 2 minutes to proofread. Going over time here can cost you whole questions later in the paper.", difficulty:2, category:"application"}
);

QUESTIONS["g11i-06-3"] = (QUESTIONS["g11i-06-3"] || []).concat([
  {q:"A 'to what extent' conclusion should:", opts:["Place your view on a scale of agreement and justify it","Avoid taking a side","Repeat the question","List both sides without judging"], c:0, e:"You must judge HOW FAR the statement is true and justify it; sitting on the fence or just listing sides misses the command word."},
  {q:"SPaG marks reward accurate use of:", opts:["Long words for their own sake","Diagrams","Geographical terminology, spelling and punctuation","Bullet points only"], c:2, e:"SPaG credits correct spelling, punctuation and precise terminology; using long words wrongly does not help and bullet points alone are not full sentences."},
  {q:"A student writes 'erosian' and 'enviroment' throughout a 9-mark answer. This mainly costs:", opts:["AO1 marks","AO3 marks","SPaG marks","No marks at all"], c:2, e:"Misspelling key geographical terms loses SPaG marks specifically; the geographical content may still earn AO1/AO3 but the technical accuracy marks are lost."},
  {q:"Roughly how long should a 9-mark question (with SPaG) take?", opts:["About 2 minutes","About 30 minutes","About 5 seconds","About 11–12 minutes"], c:3, e:"Around 1 minute per mark plus time for SPaG and proofreading gives roughly 11–12 minutes; 2 minutes is far too little for a balanced, judged answer."},
  {q:"Which conclusion stem best fits a 'to what extent' question?", opts:["'In conclusion, I am unsure'","'There are many points'","'The end'","'To a large extent I agree, because…'"], c:3, e:"'To a large extent I agree, because…' places the answer on the agreement scale and signals justification; 'I am unsure' gives no judgement."},
  {q:"The best way to use your final 2 minutes in a 9-mark answer is to:", opts:["Rewrite the whole answer","Proofread for spelling, punctuation and incomplete sentences","Add a new case study","Cross everything out"], c:1, e:"A quick proofread fixes errors that cost SPaG marks; rewriting or adding new material risks running out of time and unbalancing the answer."},
  {q:"A quick for/against plan before a 'to what extent' answer mainly helps you to:", opts:["Use up time","Avoid a rambling, unstructured response and decide your position","Avoid using evidence","Skip the conclusion"], c:1, e:"Planning gives a clear structure and an early decision on your line of argument; it saves time overall and still requires evidence and a conclusion."},
  {q:"Which phrase shows the highest degree of agreement?", opts:["Not at all","To a small extent","Largely","Slightly"], c:2, e:"'Largely' signals strong agreement on the scale; 'not at all', 'slightly' and 'to a small extent' all sit at the low end."},
  {q:"Writing in full sentences with paragraphs rather than bullet points helps a 9-mark answer because:", opts:["It looks neater only","Bullets are banned everywhere","It is needed to access SPaG marks and show a developed argument","It saves time"], c:2, e:"SPaG and the top bands expect connected prose that develops an argument; bullet points cannot show the same flow, though they are fine for quick planning."},
  {q:"A student spends 25 minutes on one 9-mark question. The main risk is that they:", opts:["Earn bonus marks","Improve their SPaG","Lose their case study","Run out of time for other questions worth more in total"], c:3, e:"Overrunning on one answer leaves too little time for the rest of the paper, where more marks are available; extra minutes rarely add many marks to a single answer."}
]);
