// content/y11/geography/islands/x07.js — Year 11 Geography Topic 7 expansion: Revision & Case Studies (islands g11i-07-1/2/3). All original. British English.

FLASHCARDS.push(
  // g11i-07-1 — Case Study Recall (continues from g11fc-07-1-5)
  {id:"g11fc-07-1-6", islandId:"g11i-07-1", front:"What is the difference between a 'case study' and an 'example' in AQA Geography?", back:"A case study is a place studied in real depth — you should know its causes, effects, responses and a cluster of named facts and statistics.\n\nAn example is a quick named instance used to support a point, needing only a place name and one or two details. Both add place-specific credit, but case studies carry the detailed 9-mark questions.", difficulty:3, category:"concept"},
  {id:"g11fc-07-1-7", islandId:"g11i-07-1", front:"How does spaced repetition strengthen case study recall?", back:"You revisit the same facts with growing gaps between sessions (e.g. day 1, day 3, day 7, day 14).\n\nEach time you retrieve a fact from memory just before you would forget it, the memory is reinforced. This beats cramming, which fades quickly after the exam.", difficulty:2, category:"application"},
  {id:"g11fc-07-1-8", islandId:"g11i-07-1", front:"Which paper does each case study type belong to?", back:"Physical case studies (tectonic hazard, tropical storm, ecosystem, UK river/coast) sit in Paper 1.\n\nHuman case studies (UK major city, NEE such as Nigeria, resource management) sit in Paper 2. Knowing the paper helps you target revision before each exam.", difficulty:2, category:"definition"},
  // g11i-07-2 — Exam Practice (continues from g11fc-07-2-5)
  {id:"g11fc-07-2-6", islandId:"g11i-07-2", front:"What does Paper 3 (Geographical Applications) actually test?", back:"Section A is the issue evaluation, based on a pre-release resource booklet you receive before the exam.\n\nSection B is fieldwork — questions on your own enquiry and an unfamiliar one. It carries 6 SPaG marks and rewards skills and decision-making, not just recall.", difficulty:2, category:"definition"},
  {id:"g11fc-07-2-7", islandId:"g11i-07-2", front:"Why match your answer to the command word?", back:"Command words tell you the skill being tested: 'describe' wants what you see, 'explain' wants reasons, 'assess'/'evaluate' want a judgement.\n\nWriting a description when the question says 'evaluate' caps you in the lower levels however much you write.", difficulty:3, category:"concept"},
  {id:"g11fc-07-2-8", islandId:"g11i-07-2", front:"How should you practise with past papers?", back:"Do them under timed, closed-book conditions, then mark with the official mark scheme.\n\nLog every topic you lost marks on and re-revise it. Repeating a paper you have already seen the answers to mostly tests memory of that paper, not exam skill.", difficulty:2, category:"application"},
  // g11i-07-3 — Timed Answers & Strategy (continues from g11fc-07-3-5)
  {id:"g11fc-07-3-6", islandId:"g11i-07-3", front:"How should you use the levels of response in a 9-mark answer?", back:"Level 3 needs a developed, balanced argument with a clear conclusion that makes a justified judgement.\n\nPlan two or three points each way, support them with case-study evidence, then commit to a view. A one-sided answer rarely reaches the top level.", difficulty:3, category:"concept"},
  {id:"g11fc-07-3-7", islandId:"g11i-07-3", front:"What is the safest order to answer questions in?", back:"Work through in order to avoid missing pages, but if a high-mark question stalls you, leave space and move on.\n\nSecure the marks you can do quickly first, then return. Never let one extended question eat the time that several others need.", difficulty:2, category:"application"},
  {id:"g11fc-07-3-8", islandId:"g11i-07-3", front:"How do you avoid running out of time on the final long answer?", back:"Track the clock against the 1-mark-per-minute plan at each section, not just at the end.\n\nIf you are behind, tighten your low-mark answers rather than sacrificing the 9-mark question, where the most marks are still available.", difficulty:3, category:"application"}
);

QUESTIONS["g11i-07-1"] = (QUESTIONS["g11i-07-1"] || []).concat([
  {q:"Which best describes the difference between a case study and an example?", opts:["A case study is studied in depth; an example is a brief named instance","They are identical terms","An example must be longer than a case study","Only examples earn marks"], c:0, e:"Case studies carry detailed causes-effects-responses; examples just support a point with a name. The tempting wrong choice is that they are identical — they are not, and the depth expected differs."},
  {q:"A 9-mark 'to what extent' question on Nigeria is most likely to appear on:", opts:["Paper 3 fieldwork","Paper 2 (human environment)","Paper 1 (physical environment)","A non-exam unit"], c:1, e:"Nigeria is the NEE human case study, so it sits in Paper 2. Paper 1 is physical, so it is the most tempting but incorrect choice here."},
  {q:"Why is spaced repetition more effective than cramming for case study facts?", opts:["It uses brighter highlighters","It avoids ever testing yourself","It only works the night before","Retrieving facts over growing gaps strengthens long-term memory"], c:3, e:"Spacing forces retrieval just before forgetting, which builds durable recall. Cramming the night before fades fast, so the 'night before' option is the trap."},
  {q:"Which response fact for the Nepal 2015 earthquake is exam-ready?", opts:["Lots of money was sent","Help arrived eventually","International aid of around 4.1 billion dollars was pledged","Some shelters were built somewhere"], c:2, e:"A named, quantified response scores in the higher bands. 'Lots of money was sent' is the tempting paraphrase but lacks the figure the mark scheme rewards."},
  {q:"A student writes 'a country in Asia had a big storm'. The main weakness is:", opts:["The spelling","It is too long","It uses the wrong command word","No place-specific detail — no name, date or statistic"], c:3, e:"The answer is generic, so it cannot reach higher bands. Spelling is not the issue; the missing named place, date and data is."},
  {q:"For a tropical storm case study, the strongest revision structure is:", opts:["Causes (formation) then effects then responses","A random list of facts","Only the death toll","Just the storm's name"], c:0, e:"Causes-effects-responses maps onto how questions are set, so recall transfers straight to answers. A random list does not align with question wording."},
  {q:"Knowing which paper a case study belongs to helps you because:", opts:["Papers are marked by different examiners","It changes the mark scheme","You can target revision before each specific exam","It lets you skip the case study"], c:2, e:"Targeting Paper 1 physical or Paper 2 human case studies focuses your final revision. The examiner identity does not change what you must know."},
  {q:"Which is the better-developed effect for Typhoon Haiyan 2013?", opts:["It was bad","Wind happened","People were sad","Storm surge of over 5 metres flooded Tacloban, contributing to over 6000 deaths"], c:3, e:"A specific mechanism plus a statistic reaches the higher levels. 'It was bad' is vague and unscoreable, so it is the tempting but weak option."},
  {q:"The best way to check your case study notes are exam-ready is to:", opts:["Re-read them once more","Highlight them in three colours","Cover them and write the key facts from memory, then check","Copy them out neatly"], c:2, e:"Active recall reveals what you genuinely remember. Re-reading and copying feel productive but mostly test recognition, not retrieval."},
  {q:"An ecosystem case study such as the Amazon is best revised by linking facts to:", opts:["Causes, impacts and management of change","The exam invigilator's instructions","The font of your notes","The colour of the textbook"], c:0, e:"Deforestation case studies are examined through impacts and management, so structuring notes that way transfers to answers. Presentation details do not earn marks."}
]);

QUESTIONS["g11i-07-2"] = (QUESTIONS["g11i-07-2"] || []).concat([
  {q:"Section A of Paper 3 is based on:", opts:["A pre-release resource booklet","Your own fieldwork only","Paper 1 content","A textbook chapter"], c:0, e:"The issue evaluation uses a pre-release booklet you study beforehand. Fieldwork is Section B, so that is the tempting confusion."},
  {q:"A question beginning 'Assess the effectiveness of...' is mainly testing your ability to:", opts:["List facts only","Make and justify a judgement","Describe what you see","Define a term"], c:1, e:"'Assess' demands a weighed judgement with evidence. Simply describing or listing caps you in lower bands, which is the common trap."},
  {q:"The most useful way to practise past papers is to:", opts:["Read the mark scheme first","Copy out model answers","Only attempt the easy questions","Do them timed and closed-book, then mark them honestly"], c:3, e:"Timed, closed-book practice builds real exam skill, and marking finds gaps. Reading the mark scheme first only tests memory of the answers."},
  {q:"Which command word asks you to give reasons rather than just observations?", opts:["State","Describe","Explain","Identify"], c:2, e:"'Explain' requires causes and reasons. 'Describe' wants what you observe, so it is the closest tempting choice but stops short of reasons."},
  {q:"Section B of Paper 3 carries extra marks for:", opts:["Diagrams","Speed","SPaG (spelling, punctuation and grammar)","Length"], c:2, e:"Paper 3 includes SPaG marks in the fieldwork section. Diagrams may help but are not the source of the extra marks."},
  {q:"A student writes a long, detailed description for an 'evaluate' question. They will most likely:", opts:["Score full marks","Gain bonus marks for length","Match the command word","Be limited to lower levels for not making a judgement"], c:3, e:"Length cannot rescue a missing judgement, so the answer is capped. Believing length earns marks is the classic misconception."},
  {q:"Why log the topics where you lost marks on a practice paper?", opts:["To target re-revision at your actual weaknesses","To prove you tried","To fill in your planner","To compare with friends"], c:0, e:"A loss log turns practice into focused improvement. Simply proving effort or comparing scores does not close the knowledge gap."},
  {q:"Paper 1 and Paper 2 are each worth:", opts:["76 marks","88 marks","100 marks","50 marks"], c:1, e:"Both written papers are 88 marks; Paper 3 is 76. The 76 figure belongs to Paper 3, making it the tempting mix-up."},
  {q:"Fieldwork questions on Paper 3 reward you for discussing:", opts:["Only the weather on the day","Other students' projects","Your data collection methods, results and an honest evaluation of the enquiry","The textbook case study"], c:2, e:"Examiners want method, results and evaluation of your own enquiry. The weather alone does not show geographical understanding."},
  {q:"Matching depth to marks means a 2-mark question should get:", opts:["Two clear developed points and no more","A full essay","A single word","A 9-mark style answer"], c:0, e:"Two marks need two creditworthy points; over-writing wastes time. Writing an essay for 2 marks is the time-trap version of the error."}
]);

QUESTIONS["g11i-07-3"] = (QUESTIONS["g11i-07-3"] || []).concat([
  {q:"To reach Level 3 on a 9-mark question you should:", opts:["Write only one side of the argument","Avoid any conclusion","Give a balanced, evidenced argument and a justified conclusion","List unconnected facts"], c:2, e:"Top-level answers weigh both sides and conclude with a judgement. A one-sided answer rarely reaches Level 3, which is the tempting shortcut."},
  {q:"If a high-mark question stalls you mid-paper, the best strategy is:", opts:["Stay on it until finished","Leave space, secure other marks, then return","Cross out everything","Stop writing for the rest of the paper"], c:1, e:"Securing easier marks first protects your total, and you can return later. Grinding on one stuck question risks losing many other marks."},
  {q:"Tracking the clock section by section rather than only at the end helps you:", opts:["Write faster","Skip the plan","Ignore low-mark questions","Spot if you are behind in time to adjust"], c:3, e:"Frequent checks let you correct pace before it is too late. A single check at the end gives no time to recover."},
  {q:"If you fall behind on time, you should protect marks by:", opts:["Cutting the 9-mark question","Tightening your low-mark answers and keeping time for the 9-mark question","Leaving the last page blank","Slowing down everywhere"], c:0, e:"The 9-mark question holds the most available marks, so guard it. Sacrificing it to finish small questions loses the most points."},
  {q:"A quick two-minute plan for a 9-mark answer mainly helps by:", opts:["Earning marks for the plan itself","Replacing the need for evidence","Keeping the argument structured and balanced","Making the answer longer"], c:2, e:"Planning keeps both sides and a conclusion in view. The plan is not marked, so 'marks for the plan' is the tempting but false reason."},
  {q:"Answering the command word directly in your first sentence is good practice because:", opts:["It pads the answer","Examiners only read sentence one","It guarantees Level 3","It signals you are on task and saves time developing the point"], c:3, e:"A direct opening focuses the answer and avoids waffle. It does not by itself guarantee the top level, which still needs development and evidence."},
  {q:"Spending eight minutes on a 2-mark question is a problem because:", opts:["It looks untidy","Two-mark questions are not marked","It steals time from high-mark questions where more is available","It uses too much ink"], c:2, e:"Over-investing in low-value questions starves the high-value ones. Neatness and ink are irrelevant to the marks lost."},
  {q:"Leaving five minutes to check at the end is most useful for:", opts:["Adding missing evidence and fixing SPaG in your longest answers","Starting a brand-new question","Rewriting the whole paper","Reading the front cover"], c:0, e:"Small fixes to 6- and 9-mark answers can gain several marks. Starting a new question in five minutes rarely produces a strong answer."},
  {q:"For an 88-mark paper in 90 minutes, the underlying pacing rule is:", opts:["Two marks per minute","Roughly one mark per minute","Five marks per minute","Time does not matter"], c:1, e:"One mark per minute leaves a small buffer to check. Two marks per minute would force rushed, undeveloped answers."},
  {q:"A balanced 9-mark answer that never reaches a conclusion will usually:", opts:["Score full marks","Earn SPaG marks only","Be marked as blank","Be held below the top level for lacking a judgement"], c:3, e:"Without a justified conclusion the judgement is missing, capping the level. The balanced content stops it being blank, but it still falls short of the top band."}
]);
