// content/y11/english/topics.js — Year 11 English: topic tiles + island definitions.
// Authored by the atlas-content skill. GCSE exam technique & revision year.
// Slot convention: 04 = Reading Comprehension (passages, deferred), 06 = Writing.

const ENGLISH_TOPICS_Y11 = [
  {id:"e11t-01", name:"Vocabulary Mastery", emoji:"📖", hasContent:true,
   description:"Refine analytical and creative vocabulary for top-band responses and deploy it under exam conditions."},
  {id:"e11t-02", name:"Grammar & Accuracy under Pressure", emoji:"🔤", hasContent:true,
   description:"Maintain grammatical control and accuracy in timed writing, avoiding common errors and achieving sophistication."},
  {id:"e11t-04", name:"Reading Comprehension", emoji:"📝", hasContent:true,
   description:"Full exam-length fiction and non-fiction reading practice with mark schemes and model answers, including paired Paper 2 sources for synthesis and comparison."},
  {id:"e11t-05", name:"Language Paper 1: Fiction Reading", emoji:"📕", hasContent:true,
   description:"Master the four AQA Language Paper 1 reading questions: locate, analyse language, analyse structure, evaluate."},
  {id:"e11t-06", name:"Language Paper 2: Non-fiction & Comparison", emoji:"📰", hasContent:true,
   description:"Master Language Paper 2 reading: true/false, summary, language analysis, and comparing viewpoints."},
  {id:"e11t-07", name:"Literature: Poetry Anthology & Unseen", emoji:"🌟", hasContent:true,
   description:"Write top-band anthology comparisons and unseen poetry responses under timed conditions."},
  {id:"e11t-08", name:"Literature: Novel & Play", emoji:"🎭", hasContent:true,
   description:"Write thesis-driven extract + whole-text literature essays on your studied novel and play."},
  {id:"e11t-09", name:"Writing for Exams", emoji:"✍️", hasContent:true,
   description:"Produce polished descriptive, narrative and transactional writing under timed exam conditions."},
  {id:"e11t-10", name:"An Inspector Calls (Priestley)", emoji:"🔔", hasContent:true,
   description:"AQA set text: plot, the Inspector, characters, themes, context and key quotations for An Inspector Calls (Literature Paper 2)."},
  {id:"e11t-11", name:"Power & Conflict Anthology", emoji:"⚔️", hasContent:true,
   description:"AQA set text: all 15 Power & Conflict poems — poets, ideas, methods, quotations and comparison skills (Literature Paper 2)."}
];

// ── Topic 1: Vocabulary Mastery (e11t-01) ────────────────────────────────────
CURRICULUM.push(
  {id:"e11i-01-1", name:"Analytical Vocabulary Bank", emoji:"🏷️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-01", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Build and deploy a bank of precise analytical vocabulary — tone words, evaluative verbs and subject terms.",
   learningOutcomes:["Recall and use 30+ tone words accurately","Use strong evaluative verbs in analysis","Deploy subject terminology precisely"],
   topics:["Tone words","Evaluative verbs","Subject terminology"], prerequisites:[]},
  {id:"e11i-01-2", name:"Creative & Transactional Vocabulary", emoji:"💎", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-01", yearGroup:"Year 11", difficulty:2, estimatedHours:1,
   description:"Choose sophisticated, apt vocabulary in creative and transactional exam writing.",
   learningOutcomes:["Select vocabulary that fits tone and audience","Use connotation deliberately","Avoid forced or misused words"],
   topics:["Audience-apt vocabulary","Connotation","Naturalness"], prerequisites:["e11i-01-1"]},
  {id:"e11i-01-3", name:"Tone & Mood Word Bank", emoji:"🎭", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-01", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Memorise a bank of precise tone and mood words and deploy them in analysis.",
   learningOutcomes:["Recall precise tone words grouped by feeling","Use active recall to memorise them","Upgrade vague descriptions to precise ones"],
   topics:["Tone clusters","Active recall","Precise word choice"], prerequisites:["e11i-01-1"]}
);

// ── Topic 2: Grammar & Accuracy under Pressure (e11t-02) ────────────────────
CURRICULUM.push(
  {id:"e11i-02-1", name:"Common Errors to Eliminate", emoji:"🚫", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-02", yearGroup:"Year 11", difficulty:1, estimatedHours:2,
   description:"Identify and fix the most common SPaG errors: homophones, comma splices, apostrophes and tense shifts.",
   learningOutcomes:["Spot and fix homophone errors (their/there/they're)","Fix comma splices and run-ons","Use apostrophes and tenses correctly"],
   topics:["Homophones","Comma splices","Apostrophes & tense"], prerequisites:[]},
  {id:"e11i-02-2", name:"Sophisticated Sentence Control", emoji:"⚙️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-02", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Write with a full range of sentence forms and punctuation accurately under timed conditions.",
   learningOutcomes:["Sustain varied sentence forms in timed writing","Use the full punctuation range accurately","Proofread efficiently"],
   topics:["Sentence forms","Punctuation range","Timed proofreading"], prerequisites:["e11i-02-1"]},
  {id:"e11i-02-3", name:"Punctuation for Effect & SPaG Marks", emoji:"✒️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-02", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Deploy the full punctuation range for effect under timed conditions and secure SPaG marks.",
   learningOutcomes:["Use semicolons, colons, dashes and ellipsis for effect","Explain how SPaG/AO6 marks are awarded","Eliminate common errors under pressure"],
   topics:["Punctuation for effect","SPaG marks","Errors to eliminate"], prerequisites:["e11i-02-1"]}
);

// ── Topic 5: Language Paper 1: Fiction Reading (e11t-05) ─────────────────────
CURRICULUM.push(
  {id:"e11i-05-1", name:"Q1–Q3: Locate, Language, Structure", emoji:"📕", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-05", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Answer AQA Paper 1 Q1 (locate), Q2 (language) and Q3 (structure) efficiently and with precision.",
   learningOutcomes:["List accurate information for Q1","Analyse language effects for Q2","Analyse structural features for Q3"],
   topics:["Q1 locate","Q2 language","Q3 structure"], prerequisites:[]},
  {id:"e11i-05-2", name:"Q4: Evaluate Critically", emoji:"🧭", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-05", yearGroup:"Year 11", difficulty:3, estimatedHours:2,
   description:"Write a sustained critical evaluation in response to a statement about a fiction extract (Q4, 20 marks).",
   learningOutcomes:["Respond to an evaluative statement with a clear position","Analyse methods and link to the reader's response","Sustain a personal critical voice"],
   topics:["Evaluative statement","Methods & effect","Critical voice"], prerequisites:["e11i-05-1"]},
  {id:"e11i-05-3", name:"Paper 1 Writing: Creative", emoji:"✍️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-05", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Write a polished descriptive or narrative piece for Paper 1 Section B under exam timing.",
   learningOutcomes:["Plan quickly and effectively","Write with crafted language and structure","Proofread for SPaG in the last minutes"],
   topics:["Quick planning","Crafted writing","Proofreading"], prerequisites:["e11i-05-1"]},
  {id:"e11i-05-4", name:"Q2: Language Analysis", emoji:"🔎", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-05", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Answer Paper 1 Q2 — how the writer uses language — with precise method-effect analysis.",
   learningOutcomes:["Select short quotations and name methods","Use the method-effect-response chain","Use subject terminology precisely"],
   topics:["Language methods","Method & effect","Terminology"], prerequisites:["e11i-05-1"]},
  {id:"e11i-05-5", name:"Q3: Analysing Structure", emoji:"🏗️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-05", yearGroup:"Year 11", difficulty:3, estimatedHours:2,
   description:"Answer Paper 1 Q3 by analysing structural features — the lowest-scoring question nationally.",
   learningOutcomes:["Identify structural (not language) features","Analyse shifts, zoom and cyclical structure","Write a focused structural paragraph"],
   topics:["Structural features","Shifts & zoom","Q3 technique"], prerequisites:["e11i-05-1"]}
);

// ── Topic 6: Language Paper 2: Non-fiction & Comparison (e11t-06) ────────────
CURRICULUM.push(
  {id:"e11i-06-1", name:"Q1–Q3: True/False, Summary, Language", emoji:"📰", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-06", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Answer Paper 2 Q1 (true/false), Q2 (summary/synthesis) and Q3 (language) efficiently.",
   learningOutcomes:["Select true statements accurately for Q1","Synthesise and compare information for Q2","Analyse language in a non-fiction source for Q3"],
   topics:["Q1 true/false","Q2 summary","Q3 language"], prerequisites:[]},
  {id:"e11i-06-2", name:"Q4: Compare Viewpoints", emoji:"⚖️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-06", yearGroup:"Year 11", difficulty:3, estimatedHours:2,
   description:"Compare how two writers present similar topics — their viewpoints and methods (Q4, 16 marks).",
   learningOutcomes:["Compare attitudes and viewpoints","Compare writers' methods, not just content","Sustain a comparative argument"],
   topics:["Comparing viewpoints","Comparing methods","Comparative argument"], prerequisites:["e11i-06-1"]},
  {id:"e11i-06-3", name:"Paper 2 Writing: Transactional", emoji:"📝", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-06", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Write a polished letter, article, speech or essay for Paper 2 Section B under exam timing.",
   learningOutcomes:["Match form, audience and purpose","Deploy rhetorical and structural skills","Maintain accuracy under time pressure"],
   topics:["FAP matching","Rhetoric & structure","Timed accuracy"], prerequisites:["e11i-06-1"]},
  {id:"e11i-06-4", name:"Q2: Summary & Synthesis", emoji:"🔗", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-06", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Answer Paper 2 Q2 by summarising and synthesising inferences across two sources.",
   learningOutcomes:["Summarise in your own words","Combine inferences from both sources","Select matching detail"],
   topics:["Summary & synthesis","Two sources","Inference"], prerequisites:["e11i-06-1"]},
  {id:"e11i-06-5", name:"Q3: Single-Source Language", emoji:"📰", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-06", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Answer Paper 2 Q3 by analysing how one non-fiction source uses language.",
   learningOutcomes:["Analyse one source (not a comparison)","Use the method-effect chain","Use precise terminology"],
   topics:["Single-source analysis","Method & effect","Terminology"], prerequisites:["e11i-06-1"]}
);

// ── Topic 7: Literature: Poetry Anthology & Unseen (e11t-07) ────────────────
CURRICULUM.push(
  {id:"e11i-07-1", name:"Anthology Comparison Essay", emoji:"⚖️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-07", yearGroup:"Year 11", difficulty:3, estimatedHours:2,
   description:"Write a top-band comparative essay on an anthology poem and a chosen partner poem.",
   learningOutcomes:["Plan and execute a comparative argument","Analyse language, form and structure in both poems","Integrate context where it illuminates meaning"],
   topics:["Comparative planning","Analysis across poems","Context integration"], prerequisites:[]},
  {id:"e11i-07-2", name:"Unseen Poetry Response", emoji:"📜", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-07", yearGroup:"Year 11", difficulty:3, estimatedHours:2,
   description:"Write a focused unseen poetry response and an unseen comparison under exam timing.",
   learningOutcomes:["Respond to an unseen poem analytically","Compare two unseen poems efficiently","Manage time across both parts"],
   topics:["Single unseen","Unseen comparison","Time management"], prerequisites:["e11i-07-1"]},
  {id:"e11i-07-3", name:"Unseen Poetry Comparison", emoji:"⚖️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-07", yearGroup:"Year 11", difficulty:3, estimatedHours:2,
   description:"Compare how two unseen poets present a theme using methods (the second unseen question).",
   learningOutcomes:["Compare methods across two unseen poems","Focus on one or two clear contrasts","Use comparative connectives"],
   topics:["Unseen comparison","Comparing methods","Connectives"], prerequisites:["e11i-07-2"]},
  {id:"e11i-07-4", name:"Planning & Timing the Poetry Exam", emoji:"⏱️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-07", yearGroup:"Year 11", difficulty:2, estimatedHours:1,
   description:"Manage the anthology comparison plus two unseen questions within the time.",
   learningOutcomes:["Know the mark weightings","Plan quickly (thesis + 3 points)","Split the time sensibly"],
   topics:["Mark weightings","Quick planning","Timing"], prerequisites:["e11i-07-1"]}
);

// ── Topic 8: Literature: Novel & Play (e11t-08) ─────────────────────────────
CURRICULUM.push(
  {id:"e11i-08-1", name:"Extract + Whole-Text Essay: Novel", emoji:"📚", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-08", yearGroup:"Year 11", difficulty:3, estimatedHours:2,
   description:"Write a thesis-driven essay on a 19th-century novel starting from an extract, then ranging across the whole text.",
   learningOutcomes:["Analyse the extract closely","Range across the whole text for wider evidence","Link analysis to context purposefully"],
   topics:["Extract analysis","Whole-text range","Context"], prerequisites:[]},
  {id:"e11i-08-2", name:"Extract + Whole-Text Essay: Play", emoji:"🎭", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-08", yearGroup:"Year 11", difficulty:3, estimatedHours:2,
   description:"Write a thesis-driven essay on your studied play starting from an extract, then ranging across the whole text.",
   learningOutcomes:["Analyse the extract with dramatic awareness","Range across the play for wider evidence","Integrate context and audience awareness"],
   topics:["Extract analysis","Whole-play range","Context & audience"], prerequisites:["e11i-08-1"]},
  {id:"e11i-08-3", name:"Essay Technique & Exam Practice", emoji:"🏆", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-08", yearGroup:"Year 11", difficulty:3, estimatedHours:2,
   description:"Plan and write a literature essay in timed conditions, applying all techniques with precision.",
   learningOutcomes:["Plan a thesis and structure in 5 minutes","Embed evidence and analyse methods fluently","Proofread and polish under time pressure"],
   topics:["Timed planning","Fluent analysis","Final polish"], prerequisites:["e11i-08-1"]}
);

// ── Topic 9: Writing for Exams (e11t-09, writingTopicId) ────────────────────
CURRICULUM.push(
  {id:"e11i-09-1", name:"Exam Creative Writing", emoji:"🎨", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-09", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Produce polished descriptive or narrative writing under exam conditions (Paper 1 Section B).",
   learningOutcomes:["Plan a descriptive or narrative piece in 5 minutes","Craft atmosphere and character under pressure","Edit for accuracy and impact"],
   topics:["Quick planning","Crafting under pressure","Final edit"], prerequisites:[]},
  {id:"e11i-09-2", name:"Exam Transactional Writing", emoji:"📝", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-09", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Produce polished transactional writing (letter, article, speech) under exam conditions (Paper 2 Section B).",
   learningOutcomes:["Match FAP and deploy rhetoric efficiently","Sustain a clear argument or viewpoint","Achieve accuracy and control under pressure"],
   topics:["FAP & rhetoric","Sustained argument","Timed accuracy"], prerequisites:["e11i-09-1"]},
  {id:"e11i-09-3", name:"Planning & Time Management for Writing", emoji:"🗓️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-09", yearGroup:"Year 11", difficulty:2, estimatedHours:1,
   description:"Plan a writing task in five minutes and manage time across reading and writing.",
   learningOutcomes:["Plan structure and key points in 5 minutes","Allocate time across the paper","Leave time to check"],
   topics:["Quick planning","Time allocation","Checking"], prerequisites:["e11i-09-1"]},
  {id:"e11i-09-4", name:"Hitting the Mark Scheme & Proofreading", emoji:"✅", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-09", yearGroup:"Year 11", difficulty:2, estimatedHours:1,
   description:"Target the AO5/AO6 mark scheme and proofread effectively in the last five minutes.",
   learningOutcomes:["Explain what AO5 and AO6 reward","Aim for top-band features","Use a proofreading checklist"],
   topics:["AO5 & AO6","Top-band features","Proofreading"], prerequisites:["e11i-09-1"]}
);

// ── Topic 10: An Inspector Calls — AQA set text (e11t-10) ────────────────────
CURRICULUM.push(
  {id:"e11i-10-1", name:"Plot & Structure", emoji:"📜", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-10", yearGroup:"Year 11", difficulty:1, estimatedHours:2,
   description:"Master the events of An Inspector Calls — the chain of responsibility for Eva Smith and the cyclical twist.",
   learningOutcomes:["Recall each character's link to Eva Smith","Understand the well-made-play structure","Explain the cyclical ending"],
   topics:["The chain of events","Well-made play","The twist"], prerequisites:[]},
  {id:"e11i-10-2", name:"The Inspector & Priestley's Message", emoji:"🔔", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-10", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Analyse Inspector Goole as Priestley's socialist mouthpiece and dramatic device.",
   learningOutcomes:["Explain the Inspector's central message","Analyse his control and symbolism","Link him to Priestley's purpose"],
   topics:["Collective responsibility","Goole as device","Key quotations"], prerequisites:["e11i-10-1"]},
  {id:"e11i-10-3", name:"The Birlings & Gerald", emoji:"👥", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-10", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Analyse Mr and Mrs Birling, Sheila, Eric and Gerald, and the generational divide between old and young.",
   learningOutcomes:["Contrast the older and younger generations","Analyse character through dramatic irony","Track who changes and who doesn't"],
   topics:["Older generation","Younger generation","Generational divide"], prerequisites:["e11i-10-1"]},
  {id:"e11i-10-4", name:"Themes", emoji:"🎯", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-10", yearGroup:"Year 11", difficulty:2, estimatedHours:3,
   description:"Explore social responsibility, class, gender, age and capitalism vs socialism — anchored to quotations.",
   learningOutcomes:["Explain the major themes with evidence","Link themes to Priestley's purpose","Select apt quotations per theme"],
   topics:["Social responsibility","Class & gender","Capitalism vs socialism"], prerequisites:["e11i-10-1"]},
  {id:"e11i-10-5", name:"Context", emoji:"🏛️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-10", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Understand the 1912 setting and 1945 writing, Priestley's socialism, and use dramatic irony in analysis.",
   learningOutcomes:["Explain the 1912 vs 1945 gap","Link context to Priestley's purpose","Analyse Birling's dramatic irony"],
   topics:["1912 vs 1945","Priestley's politics","Dramatic irony"], prerequisites:["e11i-10-1"]},
  {id:"e11i-10-6", name:"Key Quotations Bank", emoji:"💬", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-10", yearGroup:"Year 11", difficulty:3, estimatedHours:2,
   description:"Memorise and deploy essential quotations grouped by idea, ready for the closed-book Literature exam.",
   learningOutcomes:["Memorise key quotations by idea","Attribute each line to the right character","Embed and analyse quotations precisely"],
   topics:["Quotations by idea","Speaker & purpose","Embedding evidence"], prerequisites:["e11i-10-2","e11i-10-4"]},
  {id:"e11i-10-7", name:"Answering the Modern-Text Essay", emoji:"✍️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-10", yearGroup:"Year 11", difficulty:3, estimatedHours:3,
   description:"Exam skill: the modern-text essay (no extract). Build a thesis, range across the whole play, analyse Priestley's methods (AO2) and weave context (AO3) — then practise on AI-marked essay questions.",
   learningOutcomes:["Build a thesis-led, whole-text argument","Analyse Priestley's dramatic methods (AO2)","Weave context and structure the essay under time"],
   topics:["Whole-text argument","Method analysis (AO2)","Essay structure & timing"], prerequisites:["e11i-10-2","e11i-10-4"]}
);

// ── Topic 11: Power & Conflict Anthology — AQA set text (e11t-11) ────────────
CURRICULUM.push(
  {id:"e11i-11-1", name:"Power of Nature", emoji:"🏔️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-11", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Analyse Ozymandias, Extract from The Prelude and Storm on the Island — nature and time overpowering humans.",
   learningOutcomes:["Recall each poem's key idea and quotation","Analyse the poets' methods","Compare presentations of nature's power"],
   topics:["Ozymandias","The Prelude","Storm on the Island"], prerequisites:[]},
  {id:"e11i-11-2", name:"Power of Humans & Authority", emoji:"👑", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-11", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Analyse London, My Last Duchess and Tissue — the use and abuse of human power.",
   learningOutcomes:["Recall each poem's key idea and quotation","Analyse the poets' methods","Compare presentations of human power"],
   topics:["London","My Last Duchess","Tissue"], prerequisites:["e11i-11-1"]},
  {id:"e11i-11-3", name:"The Reality of War", emoji:"💥", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-11", yearGroup:"Year 11", difficulty:2, estimatedHours:2,
   description:"Analyse The Charge of the Light Brigade, Exposure and Bayonet Charge — heroism, futility and fear.",
   learningOutcomes:["Recall each poem's key idea and quotation","Contrast glory and futility","Compare presentations of war"],
   topics:["Charge of the Light Brigade","Exposure","Bayonet Charge"], prerequisites:["e11i-11-1"]},
  {id:"e11i-11-4", name:"Memory, Loss & Trauma", emoji:"🕯️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-11", yearGroup:"Year 11", difficulty:3, estimatedHours:2,
   description:"Analyse Remains, War Photographer, Poppies and Kamikaze — the lasting, personal aftermath of conflict.",
   learningOutcomes:["Recall each poem's key idea and quotation","Analyse trauma, witness and family loss","Compare aftermath poems"],
   topics:["Remains & War Photographer","Poppies & Kamikaze","Aftermath"], prerequisites:["e11i-11-1"]},
  {id:"e11i-11-5", name:"Identity & Place", emoji:"🌍", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-11", yearGroup:"Year 11", difficulty:3, estimatedHours:2,
   description:"Analyse The Emigrée and Checking Out Me History — identity, memory and resisting a controlling narrative.",
   learningOutcomes:["Recall each poem's key idea and quotation","Analyse form as resistance","Compare identity and place"],
   topics:["The Emigrée","Checking Out Me History","Identity"], prerequisites:["e11i-11-1"]},
  {id:"e11i-11-6", name:"Comparing the Cluster", emoji:"⚖️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-11", yearGroup:"Year 11", difficulty:3, estimatedHours:2,
   description:"Master the anthology comparison question — reliable pairings, planning by idea, and a key quotations bank.",
   learningOutcomes:["Plan a comparison by idea","Choose apt poem pairings quickly","Deploy key quotations across the cluster"],
   topics:["Comparison method","Reliable pairings","Quotations bank"], prerequisites:["e11i-11-1","e11i-11-2","e11i-11-3","e11i-11-4","e11i-11-5"]},
  {id:"e11i-11-7", name:"Comparing Poems in the Exam", emoji:"✍️", subject:"English", subjectId:"english", color:"#f59e0b",
   topicId:"e11t-11", yearGroup:"Year 11", difficulty:3, estimatedHours:3,
   description:"Exam skill: the anthology comparison essay. Plan around a shared idea, analyse and compare each poet's methods (AO2), sustain a comparative argument with discourse markers, and weave context (AO3) — then practise on AI-marked comparison questions.",
   learningOutcomes:["Plan a comparison around a shared idea","Analyse and compare poets' methods (AO2)","Sustain a comparative argument with apt quotations"],
   topics:["Comparison essay method","Comparing methods (AO2)","Comparative argument"], prerequisites:["e11i-11-6"]}
);
