// content/y11/science/islands/x01.js — EXPANSION: Topic 1 extra flashcards + questions.
// Loads AFTER t01.js. Authored by the atlas-content skill. All items original.

FLASHCARDS.push(
  // s11i-01-1 — Sexual & Asexual Reproduction
  {id:"s11fc-01-1-6",islandId:"s11i-01-1",front:"Why are gametes described as haploid?",
   back:"A haploid cell contains only one copy of each chromosome — half the number found in a normal body cell.\n\nIn humans a gamete has 23 chromosomes, while a diploid body cell has 46. When two gametes fuse at fertilisation, the full diploid number is restored.",difficulty:2,category:"definition"},
  {id:"s11fc-01-1-7",islandId:"s11i-01-1",front:"Name two organisms that can reproduce both sexually and asexually.",
   back:"Malarial parasites (Plasmodium), many fungi, and plants such as strawberries are examples.\n\nThey reproduce asexually to increase numbers quickly when conditions are favourable, and sexually to create variation when conditions become harsh.",difficulty:3,category:"application"},
  {id:"s11fc-01-1-8",islandId:"s11i-01-1",front:"How does mitosis differ from meiosis in the number and type of cells produced?",
   back:"Mitosis produces two genetically identical diploid cells, used for growth and repair.\n\nMeiosis produces four genetically different haploid cells, used only to make gametes.",difficulty:2,category:"concept"},

  // s11i-01-2 — DNA & Protein Synthesis
  {id:"s11fc-01-2-6",islandId:"s11i-01-2",front:"What is the difference between a gene and a chromosome?",
   back:"A chromosome is a long, coiled molecule of DNA found in the nucleus.\n\nA gene is a short section of that DNA that codes for a specific protein (or sequence of amino acids). One chromosome carries many genes.",difficulty:2,category:"definition"},
  {id:"s11fc-01-2-7",islandId:"s11i-01-2",front:"How can a mutation in a gene change the protein produced?",
   back:"A mutation changes the base sequence, which can alter the order of amino acids coded for.\n\nThis may change the shape of the protein. For an enzyme, a different active-site shape can stop the substrate binding, so the enzyme no longer works.",difficulty:3,category:"application"},
  {id:"s11fc-01-2-8",islandId:"s11i-01-2",front:"Which base does RNA use in place of thymine?",
   back:"RNA uses uracil (U) instead of thymine (T).\n\nSo during transcription, adenine on the DNA template pairs with uracil in the mRNA, not thymine.",difficulty:1,category:"definition"},

  // s11i-01-3 — Variation & Inherited Disorders
  {id:"s11fc-01-3-6",islandId:"s11i-01-3",front:"What is the difference between a dominant and a recessive allele?",
   back:"A dominant allele is expressed in the phenotype even if only one copy is present (shown by a capital letter, e.g. F).\n\nA recessive allele is only expressed when two copies are present (shown by a lower-case letter, e.g. f).",difficulty:1,category:"definition"},
  {id:"s11fc-01-3-7",islandId:"s11i-01-3",front:"Why can two unaffected parents have a child with a recessive disorder?",
   back:"Both parents can be carriers, each having one recessive allele (e.g. Ff) without showing the disorder.\n\nIf the child inherits the recessive allele from both parents (ff), it will have the disorder. The chance is 1 in 4.",difficulty:2,category:"application"},
  {id:"s11fc-01-3-8",islandId:"s11i-01-3",front:"What is meant by discontinuous and continuous variation?",
   back:"Discontinuous variation falls into distinct categories with no in-between values (e.g. blood group A, B, AB or O).\n\nContinuous variation has a range of values along a scale (e.g. height or mass) and is usually controlled by several genes plus the environment.",difficulty:2,category:"concept"}
);

QUESTIONS["s11i-01-1"] = (QUESTIONS["s11i-01-1"] || []).concat([
  {q:"What is a gamete?",opts:["A fertilised egg cell","A specialised sex cell","A type of body cell used for repair","A copy of a chromosome"],c:1,e:"A gamete is a specialised sex cell (sperm or egg) that fuses with another gamete at fertilisation. A fertilised egg is a zygote, not a gamete."},
  {q:"A human body cell contains 46 chromosomes. How many chromosomes are in a human sperm cell?",opts:["12","23","46","92"],c:1,e:"Gametes are haploid, carrying half the diploid number. 46 divided by 2 is 23. The figure 46 would be the diploid body-cell number, not the gamete number."},
  {q:"Which process restores the full chromosome number after meiosis has halved it?",opts:["Mitosis","Fertilisation","Crossing over","Binary fission"],c:1,e:"At fertilisation two haploid gametes fuse, combining their chromosomes to make a diploid zygote. Mitosis copies cells but does not combine gametes."},
  {q:"In a stable, unchanging environment, what is an advantage of asexual reproduction?",opts:["It creates lots of variation","Well-adapted parents quickly produce many identical, well-adapted offspring","It needs two parents","It always produces stronger offspring"],c:1,e:"If the parent is already well suited to a stable environment, identical clones will be too, and they can be made quickly. Asexual reproduction produces no variation, so the first option is wrong."},
  {q:"Binary fission in bacteria is an example of which type of reproduction?",opts:["Sexual","Asexual","Both at once","Neither"],c:1,e:"Binary fission involves one parent splitting into two identical cells, so it is asexual. No gametes fuse, so it is not sexual reproduction."},
  {q:"Why does sexual reproduction produce variation but asexual reproduction does not?",opts:["Sexual reproduction copies DNA more accurately","Sexual reproduction mixes alleles from two parents, while asexual offspring are clones of one parent","Asexual reproduction uses meiosis","Asexual reproduction always causes mutations"],c:1,e:"Sexual reproduction combines genetic material from two parents, giving new allele combinations. Asexual reproduction uses mitosis from a single parent, so offspring are genetically identical clones."},
  {q:"A plant cell has a diploid number of 14. How many chromosomes will be in each of its pollen gametes?",opts:["7","14","28","21"],c:0,e:"Meiosis halves the chromosome number, so 14 divided by 2 is 7. The value 14 is the diploid number, which only returns after fertilisation."},
  {q:"One cell undergoes meiosis. How many gametes are produced from that single cell?",opts:["One","Two","Four","Eight"],c:2,e:"Meiosis involves two divisions of one starting cell, giving four haploid gametes. Mitosis, by contrast, would give only two cells."},
  {q:"A gardener wants every new plant to be genetically identical to a prize parent plant. Which method should be used?",opts:["Growing from seed after pollination","Taking cuttings (asexual reproduction)","Crossing two different plants","Allowing wind pollination"],c:1,e:"Cuttings are asexual, so each new plant is a clone identical to the parent. Seeds form by sexual reproduction, which would introduce variation."},
  {q:"During meiosis, which two events are mainly responsible for creating genetically different gametes?",opts:["DNA replication and cytokinesis","Crossing over and independent assortment","Fertilisation and mutation","Transcription and translation"],c:1,e:"Crossing over swaps sections between chromosomes, and independent assortment lines them up randomly, both producing new combinations. Transcription and translation are stages of protein synthesis, not meiosis."}
]);

QUESTIONS["s11i-01-2"] = (QUESTIONS["s11i-01-2"] || []).concat([
  {q:"What is a gene?",opts:["A whole chromosome","A short section of DNA that codes for a protein","A single base in DNA","A type of sugar in a nucleotide"],c:1,e:"A gene is a section of DNA coding for a specific protein or sequence of amino acids. A chromosome is a much longer DNA molecule carrying many genes."},
  {q:"What molecule carries the genetic code from the nucleus to a ribosome?",opts:["DNA","mRNA","A chromosome","An amino acid"],c:1,e:"mRNA is made in transcription and carries a copy of the code to the ribosome because DNA is too large to leave the nucleus. DNA itself stays in the nucleus."},
  {q:"A DNA strand reads GGC ATA. What is the complementary DNA strand?",opts:["GGC ATA","CCG TAT","CCG UAU","TTG CGC"],c:1,e:"Pairing A with T and C with G: G->C, G->C, C->G, A->T, T->A, A->T gives CCG TAT. The option with U is wrong because uracil appears only in RNA, not DNA."},
  {q:"A DNA template strand reads TAC. What is the corresponding mRNA codon?",opts:["ATG","AUG","TAC","UAC"],c:1,e:"Transcription pairs A with U in RNA: T->A, A->U, C->G gives AUG. ATG is wrong because RNA uses uracil (U), not thymine (T)."},
  {q:"In a sample of DNA, 30% of the bases are adenine. What percentage are cytosine?",opts:["30%","20%","40%","70%"],c:1,e:"A pairs with T, so thymine is also 30%, giving A+T = 60%. The remaining 40% is shared equally by C and G, so cytosine is 20%. Picking 30% wrongly assumes all bases are equal."},
  {q:"A protein is made of 60 amino acids. How many mRNA bases are needed to code for it?",opts:["60","120","180","20"],c:2,e:"Each amino acid is coded by a triplet of three bases, so 60 multiplied by 3 is 180. Choosing 60 ignores that three bases code for one amino acid."},
  {q:"Why does a mutation in a gene sometimes have no effect on the organism?",opts:["Mutations never change DNA","The change may still code for the same amino acid or lie in non-coding DNA","All proteins are identical","Mutations only occur in gametes"],c:1,e:"Several triplets can code for the same amino acid, and much DNA does not code for protein, so many mutations are silent. Mutations do change DNA, so the first option is wrong."},
  {q:"A mutation changes one base in the gene for an enzyme. Why might the enzyme stop working?",opts:["The ribosome stops existing","The change can alter the amino acid sequence and so the shape of the active site","Enzymes are not made of protein","The DNA leaves the nucleus"],c:1,e:"A changed base can change an amino acid, altering the protein's shape so the substrate no longer fits the active site. Enzymes are proteins, so the option saying otherwise is wrong."},
  {q:"During translation, where in the cell are amino acids joined together to form a protein?",opts:["In the nucleus","At the ribosome","In the cell membrane","In the mitochondria"],c:1,e:"Translation happens at ribosomes in the cytoplasm, where the mRNA code is read and amino acids are joined. The nucleus is where transcription, not translation, takes place."},
  {q:"An mRNA molecule is 240 bases long. Assuming all of it codes for amino acids, how many amino acids will the protein contain?",opts:["240","120","80","720"],c:2,e:"Three bases code for one amino acid, so 240 divided by 3 is 80. Choosing 240 forgets that bases are read in triplets."}
]);

QUESTIONS["s11i-01-3"] = (QUESTIONS["s11i-01-3"] || []).concat([
  {q:"What does the term 'phenotype' mean?",opts:["The alleles an organism carries","The observable characteristics of an organism","A type of gamete","A diagram of a genetic cross"],c:1,e:"The phenotype is the physical characteristic that can be observed, such as eye colour. The combination of alleles is the genotype, not the phenotype."},
  {q:"Which genotype represents a heterozygous individual?",opts:["FF","ff","Ff","fff"],c:2,e:"Heterozygous means the two alleles are different, such as Ff. FF and ff are homozygous because both alleles are the same."},
  {q:"A purely environmental cause is responsible for which of these features?",opts:["Blood group","A scar from an injury","Eye colour","Inherited cystic fibrosis"],c:1,e:"A scar is caused by the environment (an injury), not by genes. Blood group, eye colour and cystic fibrosis are all determined by inherited alleles."},
  {q:"In a cross between a homozygous dominant parent (BB) and a homozygous recessive parent (bb), what are the genotypes of all the offspring?",opts:["All BB","All bb","All Bb","Half BB and half bb"],c:2,e:"Each offspring receives B from one parent and b from the other, so all are Bb. No offspring can be BB or bb because each parent can only pass on one type of allele."},
  {q:"Cystic fibrosis is recessive (f). One parent is a carrier (Ff) and the other is unaffected and not a carrier (FF). What is the chance their child has cystic fibrosis?",opts:["0%","25%","50%","100%"],c:0,e:"The cross gives FF, FF, Ff, Ff, so no child can be ff. Because one parent has no f allele to pass on, an affected child is impossible, making the chance 0%."},
  {q:"Two parents both have the genotype Tt for a gene where T (tall) is dominant. What fraction of their offspring are expected to be short (tt)?",opts:["1/4","1/2","3/4","0"],c:0,e:"The cross Tt x Tt gives TT, Tt, Tt, tt, so only 1 in 4 is tt and therefore short. The other three carry at least one T allele and are tall."},
  {q:"Polydactyly is caused by a dominant allele (D). Two parents are both Dd. What proportion of their children are expected to show polydactyly?",opts:["1/4","1/2","3/4","All"],c:2,e:"Dd x Dd gives DD, Dd, Dd, dd. Three of the four (DD, Dd, Dd) carry a dominant D and so show the condition, giving 3/4. Only the dd quarter is unaffected."},
  {q:"Height in humans shows a smooth range of values from short to tall. This is an example of what?",opts:["Discontinuous variation","Continuous variation","Asexual reproduction","A single-gene disorder"],c:1,e:"Continuous variation gives a range of values along a scale, as with height, and is controlled by several genes plus the environment. Discontinuous variation gives distinct categories, such as blood group."},
  {q:"In a Punnett square cross of Ff x ff, what fraction of the offspring are expected to be carriers (Ff)?",opts:["1/4","1/2","3/4","All"],c:1,e:"Ff x ff gives Ff, Ff, ff, ff, so 2 out of 4 (which is 1/2) are carriers. The other half are ff. No offspring can be FF because neither parent has two F alleles."},
  {q:"Why might a couple choose genetic screening of an embryo before deciding to continue a pregnancy?",opts:["It cures any inherited disorder found","It can show whether the embryo carries alleles for an inherited disorder","It guarantees the child will be healthy","It changes the embryo's DNA"],c:1,e:"Screening detects alleles linked to inherited disorders, informing the couple's decision. It does not cure or change the DNA, so those options are wrong; it identifies risk rather than removing it."}
]);
