// science-y11-x02.js — Year 11 Science Topic 2 EXPANSION: Evolution & Classification
// Islands: s11i-02-1 .. s11i-02-4
// Adds 3 extra flashcards and 10 extra questions per island.
// Flashcard ids continue from the highest existing number per island (start at 6).

// ── EXTRA FLASHCARDS ──────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s11i-02-1 — Natural Selection & Evolution
  {id:"s11fc-02-1-6",islandId:"s11i-02-1",front:"What is the source of new variation that natural selection acts on?",
   back:"Random mutations in DNA produce new alleles, which create new variation.\n\nSexual reproduction then shuffles existing alleles into new combinations. Natural selection cannot act on variation that does not already exist.",difficulty:2,category:"concept"},
  {id:"s11fc-02-1-7",islandId:"s11i-02-1",front:"Why was Darwin's theory only gradually accepted?",
   back:"1. It challenged the religious belief that God made all the animals and plants.\n2. There was not enough evidence at the time to convince many scientists.\n3. The mechanism of inheritance (genes and mutations) was not yet understood.",difficulty:3,category:"concept"},
  {id:"s11fc-02-1-8",islandId:"s11i-02-1",front:"How did Lamarck's theory of evolution differ from Darwin's?",
   back:"Lamarck thought characteristics acquired during an organism's lifetime (e.g. a stretched neck) were passed to offspring.\n\nThis is incorrect: only changes to the alleles in gametes can be inherited. Darwin's natural selection acts on inherited variation, not acquired traits.",difficulty:3,category:"concept"},

  // s11i-02-2 — Classification & Extinction
  {id:"s11fc-02-2-6",islandId:"s11i-02-2",front:"What is an evolutionary tree and what is it used for?",
   back:"An evolutionary tree is a diagram that shows how scientists think organisms are related and how they have evolved from common ancestors.\n\nThey are built using current classification data for living species and the fossil record for extinct species.",difficulty:2,category:"definition"},
  {id:"s11fc-02-2-7",islandId:"s11i-02-2",front:"How are binomial names written correctly?",
   back:"The two-part Latin name is written in italics (or underlined when handwritten).\n\nThe genus begins with a capital letter and the species name is all lower case, e.g. Homo sapiens or H. sapiens after first use.",difficulty:1,category:"definition"},
  {id:"s11fc-02-2-8",islandId:"s11i-02-2",front:"Why does classifying organisms by DNA give better groupings than appearance alone?",
   back:"DNA analysis shows true evolutionary relationships, because closely related species share more of their base sequences.\n\nOrganisms can look alike yet be unrelated (convergent evolution), so appearance can be misleading. Genetics reveals the actual common ancestry.",difficulty:3,category:"concept"},

  // s11i-02-3 — Selective Breeding & Genetic Engineering
  {id:"s11fc-02-3-6",islandId:"s11i-02-3",front:"Why are genes transferred to an organism at an early stage of development?",
   back:"If the gene is inserted into a very early embryo or fertilised egg, it is copied as the cells divide.\n\nThis means all the cells of the developing organism receive the new gene, so the whole organism expresses the desired characteristic.",difficulty:3,category:"application"},
  {id:"s11fc-02-3-7",islandId:"s11i-02-3",front:"Give two concerns people have about genetically modified (GM) crops.",
   back:"1. Effects on populations of wild flowers and insects (reduced biodiversity).\n2. Uncertainty about long-term effects on human health.\n\nSome people also worry that inserted genes could spread to wild plants.",difficulty:2,category:"concept"},
  {id:"s11fc-02-3-8",islandId:"s11i-02-3",front:"How can selective breeding be used to improve disease resistance in crops?",
   back:"Plants that show resistance to a disease are chosen as parents and bred together.\n\nThe most resistant offspring are then selected and bred again, repeating over many generations until the crop reliably resists the disease.",difficulty:2,category:"application"},

  // s11i-02-4 — Evidence for Evolution
  {id:"s11fc-02-4-6",islandId:"s11i-02-4",front:"What is the pentadactyl limb and why is it evidence for evolution?",
   back:"The pentadactyl limb is a five-digit limb found in mammals, amphibians, reptiles and birds.\n\nThe same basic bone arrangement suggests these groups share a common ancestor, even though the limb is now used for different functions (walking, flying, swimming).",difficulty:3,category:"concept"},
  {id:"s11fc-02-4-7",islandId:"s11i-02-4",front:"How can fossils be dated to show change over time?",
   back:"Fossils found in deeper rock layers are generally older than those in higher layers.\n\nBy comparing fossils from different layers, scientists can build up a sequence showing how features of organisms changed over millions of years.",difficulty:2,category:"concept"},
  {id:"s11fc-02-4-8",islandId:"s11i-02-4",front:"What does 'selection pressure' mean in the spread of antibiotic resistance?",
   back:"A selection pressure is a factor in the environment that affects which individuals survive and reproduce.\n\nUsing antibiotics is a selection pressure: it kills non-resistant bacteria, so resistant bacteria survive and become more common. Reducing antibiotic use lowers this pressure.",difficulty:2,category:"application"}
);

// ── EXTRA TEST QUESTIONS ───────────────────────────────────────────────────────
QUESTIONS["s11i-02-1"] = (QUESTIONS["s11i-02-1"] || []).concat([
  {q:"What is the ultimate source of the new variation on which natural selection acts?",opts:["Random mutations in DNA","An organism's effort to adapt","Changes caused directly by the environment","The needs of the population"],c:0,e:"New alleles arise from random mutations; sexual reproduction then mixes them. Variation is not produced by an organism trying to adapt or by the environment directly altering genes."},
  {q:"Which statement about Lamarck's idea of evolution is correct?",opts:["He suggested characteristics gained during life are passed to offspring","He discovered DNA","He proposed natural selection before Darwin","He showed mutations are random"],c:0,e:"Lamarck believed acquired characteristics, such as a muscle developed during life, could be inherited. This is wrong because only alleles in gametes are passed on; Darwin's theory of inherited variation replaced it."},
  {q:"Why was Darwin's theory not widely accepted when first published?",opts:["It had already been proven false","The mechanism of inheritance was not yet understood","No fossils had ever been found","Wallace disagreed with it"],c:1,e:"Genes and mutations were unknown in 1859, so Darwin could not explain how variation was inherited. It also conflicted with religious beliefs and lacked sufficient evidence at the time. Wallace actually supported the idea."},
  {q:"Whose later work on inheritance helped to support and explain Darwin's theory?",opts:["Louis Pasteur","Gregor Mendel","Carl Linnaeus","Robert Hooke"],c:1,e:"Mendel's experiments on pea plants showed how characteristics are inherited in units (later called genes), explaining how variation could be passed on. Pasteur worked on microbes and Linnaeus on classification."},
  {q:"Evolution is best defined as which of the following?",opts:["A sudden change in one organism during its life","A change in the inherited characteristics of a population over many generations","The death of the weakest individuals","Organisms moving to a new habitat"],c:1,e:"Evolution is the gradual change in inherited characteristics of a population over time. It applies to populations over generations, not to a single organism changing within its lifetime."},
  {q:"A bird population eats seeds of different sizes. A drought leaves only large, hard seeds. Over several generations the average beak size increases. Why?",opts:["Individual birds grew bigger beaks because they needed them","Birds with larger beaks could open the hard seeds, survived and reproduced","The drought caused mutations for large beaks","Small-beaked birds chose not to breed"],c:1,e:"Birds with larger beaks could feed on the hard seeds, so they were more likely to survive and pass on the large-beak alleles. The drought selected existing variation; it did not create the mutation or make birds grow larger beaks."},
  {q:"Two populations of lizards become separated by a new river. After many generations they can no longer interbreed. This is an example of:",opts:["Selective breeding","Extinction","Speciation","Genetic engineering"],c:2,e:"Geographic isolation led the populations to evolve under different selection pressures until they could no longer produce fertile offspring, which is speciation. No human selection or gene transfer is involved."},
  {q:"A scientist records that a resistant strain of insect rises from 2% to 85% of a population over ten years of pesticide use. Which conclusion is best supported?",opts:["The pesticide made the insects mutate","Natural selection increased the frequency of the resistance allele","The insects learned to avoid the pesticide","The population stopped reproducing"],c:1,e:"The resistance allele became more common because resistant insects survived the pesticide and reproduced. The pesticide selected, but did not cause, the resistance, and the data show reproduction continued."},
  {q:"Which feature of mutations makes them essential for evolution by natural selection?",opts:["They always benefit the organism","They occur in response to need","They occasionally produce useful new alleles","They are passed on even from body cells"],c:2,e:"Most mutations are neutral or harmful, but occasionally one produces a useful new allele that selection can favour. Mutations are random, not produced on demand, and only those in gametes are inherited."},
  {q:"Wallace's main contribution to the theory of evolution was that he:",opts:["Independently developed the idea of evolution by natural selection","Proved the Earth was very old","Invented the binomial naming system","First described the fossil record"],c:0,e:"Alfred Russel Wallace independently arrived at natural selection, prompting Darwin to publish. He did not devise binomial naming (Linnaeus) or originate the fossil record concept."}
]);

QUESTIONS["s11i-02-2"] = (QUESTIONS["s11i-02-2"] || []).concat([
  {q:"What is an evolutionary tree used to show?",opts:["The exact ages of all living species","How organisms are related and have evolved from common ancestors","Which species are most useful to humans","The order of the Linnaean ranks"],c:1,e:"Evolutionary trees show proposed relationships and common ancestry between organisms. They do not give exact ages, rank usefulness, or list the classification hierarchy."},
  {q:"Which is the correct way to write the binomial name for humans?",opts:["Homo sapiens","homo Sapiens","HOMO SAPIENS","Sapiens homo"],c:0,e:"The genus is capitalised and the species is lower case, written in italics: Homo sapiens. The genus must come first, so 'Sapiens homo' and the other forms are incorrect."},
  {q:"Two organisms share the same kingdom, phylum and class but different orders. What does this tell you?",opts:["They are the same species","They are quite closely related but less so than if they shared an order","They are not related at all","One must be extinct"],c:1,e:"Sharing more classification levels means a closer relationship, but differing at the order level shows they are less closely related than organisms sharing an order. Sharing groups does not make them the same species."},
  {q:"Why is DNA analysis considered more reliable than appearance for classifying organisms?",opts:["DNA is easier to see than body features","Closely related species share more of their DNA base sequence","All organisms have identical DNA","Appearance never changes over time"],c:1,e:"Closely related species share more base sequences, revealing true evolutionary relationships. Unrelated species can look similar through convergent evolution, so appearance can be misleading."},
  {q:"In which type of environment are many archaea found?",opts:["Only inside animal cells","Extreme environments such as hot springs and salt lakes","Only in fresh garden soil","Inside the nuclei of plant cells"],c:1,e:"Archaea are prokaryotes often found in extreme conditions like hot springs and salt lakes. They have no nucleus, so they cannot live inside one, and they are not restricted to ordinary soil."},
  {q:"A conservation group breeds the last few individuals of a rare frog in captivity. The species is best described as:",opts:["Extinct","Endangered","A new domain","Genetically engineered"],c:1,e:"Living individuals still remain but are at high risk, so the species is endangered, not extinct. Captive breeding is a conservation measure to prevent extinction; no gene transfer is involved."},
  {q:"Before the three-domain system, organisms were grouped into five kingdoms. Which of these was one of those kingdoms?",opts:["Archaea","Eukaryota","Protista","Bacteria and Archaea combined"],c:2,e:"The five-kingdom system included Protista (single-celled eukaryotes). Archaea and Eukaryota are domains in the newer system, not kingdoms of the older one."},
  {q:"A new microorganism is found to be prokaryotic but has cell biochemistry very different from known bacteria. Into which domain is it most likely placed?",opts:["Eukaryota","Bacteria","Archaea","Animalia"],c:2,e:"Prokaryotes with biochemistry distinct from true bacteria are classified as Archaea, exactly the discovery that led Woese to create the domain. It is not eukaryotic, and Animalia is a kingdom of eukaryotes."},
  {q:"Why can the fossil record help scientists build evolutionary trees for extinct organisms?",opts:["Fossils contain complete DNA for sequencing","Fossils show features that can be compared with living species","Fossils show the exact date of every extinction","Fossils prove organisms never change"],c:1,e:"Preserved features in fossils can be compared with living organisms to infer relationships. Usable DNA rarely survives in old fossils, and the record does not give exact extinction dates or show organisms as unchanging."},
  {q:"Which statement about classification is correct?",opts:["Species is the broadest level","Domains are more specific than species","Members of the same genus are less related than members of the same kingdom","Each step down the hierarchy contains organisms sharing more characteristics"],c:3,e:"Moving down the hierarchy from kingdom to species groups organisms that share more characteristics and are more closely related. Species is the most specific level, and domains are the broadest."}
]);

QUESTIONS["s11i-02-3"] = (QUESTIONS["s11i-02-3"] || []).concat([
  {q:"During genetic engineering, what is the role of enzymes at the start of the process?",opts:["To cut out (isolate) the required gene","To kill the target organism","To feed the bacteria","To copy the whole genome"],c:0,e:"Enzymes are used to cut the required gene out of the DNA so it can be isolated. They are not used to kill the organism or to feed bacteria."},
  {q:"Why are genes usually transferred into an organism at an early stage of its development?",opts:["So only the reproductive cells contain the gene","So all the cells of the organism receive and express the gene","Because older organisms cannot be modified","To make the organism grow faster"],c:1,e:"Inserting the gene early, into an embryo or egg, means it is copied as cells divide so every cell carries it. Transferring it later would leave most cells without the gene."},
  {q:"Which of these is a concern specifically raised about GM crops?",opts:["They cannot reproduce at all","Effects on wild flower and insect populations","They make selective breeding impossible","They always taste worse"],c:1,e:"A common concern is that GM crops may reduce biodiversity by affecting wild flowers and the insects that depend on them. There is no evidence they universally cannot reproduce or always taste worse."},
  {q:"A farmer wants disease-resistant wheat without transferring genes from another species. Which method should be used?",opts:["Genetic engineering","Selective breeding","Using a viral vector","Inserting a plasmid"],c:1,e:"Selective breeding uses genes already present in wheat, choosing and breeding the most resistant plants over generations. Vectors and plasmids are genetic engineering tools that transfer genes between organisms."},
  {q:"Repeated inbreeding during selective breeding can lead to which problem?",opts:["A higher chance of inherited disorders","A larger gene pool","Increased resistance to all diseases","Faster evolution of new species"],c:0,e:"Inbreeding reduces the gene pool, increasing the chance that harmful recessive alleles pair up and cause inherited disorders. It decreases, rather than increases, genetic variation and disease resistance."},
  {q:"Why are bacteria especially useful for producing a human protein such as insulin?",opts:["Bacteria naturally make human insulin","Bacteria reproduce rapidly so large amounts can be made cheaply","Bacteria are large and easy to handle individually","Bacteria cannot be genetically modified"],c:1,e:"Once the insulin gene is inserted, bacteria divide rapidly, so vast numbers can be grown cheaply to make pure human insulin. Bacteria do not naturally make human insulin and they are readily genetically modified."},
  {q:"What is the correct order of the main steps in genetic engineering?",opts:["Insert gene into vector, isolate gene, transfer to target cell","Isolate gene, insert into vector, transfer to target cell","Transfer to target cell, isolate gene, insert into vector","Isolate gene, transfer to target cell, insert into vector"],c:1,e:"The gene is first isolated, then inserted into a vector, which finally transfers it into the target organism's cells. The gene must be obtained before it can be placed in a vector."},
  {q:"A dog breed selected for a flat face suffers breathing problems. This shows which drawback of selective breeding?",opts:["It transfers genes between species","Choosing for one trait can fix harmful characteristics in the breed","It always produces sterile animals","It increases genetic variation"],c:1,e:"Strongly selecting for one appearance can also concentrate linked harmful traits, so the whole breed inherits health problems. Selective breeding uses the species' own genes and reduces variation."},
  {q:"Which describes a key difference between selective breeding and genetic engineering?",opts:["Only genetic engineering can transfer a gene from a different species","Only selective breeding uses a vector","Genetic engineering takes many more generations","Selective breeding changes the DNA base sequence directly"],c:0,e:"Genetic engineering can move a gene from a completely different species into an organism; selective breeding only uses genes already in that species. Vectors belong to genetic engineering, which acts in one step rather than over generations."},
  {q:"Golden rice was engineered to reduce a health problem. Which problem does it target?",opts:["Iron-deficiency anaemia","Protein deficiency","Vitamin C deficiency","Vitamin A deficiency"],c:3,e:"Golden rice produces beta-carotene, a source of vitamin A, to help reduce vitamin A deficiency where rice is a staple food. It was not engineered mainly for iron, protein or vitamin C."}
]);

QUESTIONS["s11i-02-4"] = (QUESTIONS["s11i-02-4"] || []).concat([
  {q:"How do many fossils of hard body parts such as bones form?",opts:["The bones are gradually replaced by minerals","The bones are eaten by decomposers","The bones float to the surface of rocks","The bones turn directly into living cells"],c:0,e:"Hard parts are often slowly replaced by minerals as they are buried, preserving their shape. Decomposers breaking parts down prevents fossilisation rather than causing it."},
  {q:"The pentadactyl limb found in many vertebrate groups is evidence for evolution because it suggests:",opts:["These groups evolved completely separately","These groups share a common ancestor","These groups cannot be related","Limbs never change function"],c:1,e:"The same five-digit bone arrangement adapted for different uses points to a shared common ancestor. Separate, unrelated origins would not be expected to produce the same underlying structure."},
  {q:"A footprint preserved in rock is an example of which kind of fossil?",opts:["A mineralised bone","A soft-bodied fossil","A trace fossil","A living fossil"],c:2,e:"Footprints, burrows and rootlet impressions are trace fossils, recording activity rather than body parts. A mineralised bone is a body fossil, not a trace."},
  {q:"Why can fossils in deeper rock layers usually be considered older?",opts:["Deeper rock is always warmer","Older organisms were heavier","Lower layers were generally laid down first","Minerals only form deep underground"],c:2,e:"Sediment builds up over time, so lower layers were normally deposited earlier and contain older fossils. Depth relates to age of deposition, not temperature or the mass of organisms."},
  {q:"Restricting antibiotic use in farming helps slow resistance because it:",opts:["Makes bacteria reproduce faster","Cures viral infections","Creates new antibiotics","Reduces the selection pressure favouring resistant bacteria"],c:3,e:"Less antibiotic use means resistant bacteria have less survival advantage, lowering the selection pressure that lets them spread. Antibiotics do not work on viruses or generate new drugs."},
  {q:"Which of these is an example of evolution that can be observed within a human lifetime?",opts:["The formation of the pentadactyl limb","The extinction of the dinosaurs","The fossilisation of ancient ferns","The spread of antibiotic-resistant bacteria"],c:3,e:"Antibiotic resistance can spread through bacterial populations in just a few years, so it is observable now. The limb's evolution, the dinosaurs' extinction and fossilisation occurred over very long timescales."},
  {q:"A study finds that two distantly classified animals have very similar DNA in one gene controlling eye structure. Combined with other evidence, this best supports the idea that:",opts:["The animals are identical species","They may share a distant common ancestor","DNA cannot be used as evidence","One animal created the other"],c:1,e:"Shared DNA sequences point to common ancestry and so support evolution. Similarity in one gene does not make them the same species, and it shows DNA is useful, not useless, as evidence."},
  {q:"Scientists find fossils of a horse-like animal showing toes reducing to a single hoof through successive rock layers. This sequence is evidence that:",opts:["Horses appeared suddenly with no change","The species gradually changed over time","Fossils form only in the youngest rocks","All horses are extinct"],c:1,e:"A graded series across rock layers shows the organism changed gradually over time, supporting evolution. It contradicts sudden appearance, and fossils form across many rock ages."},
  {q:"Why does failing to complete a course of antibiotics increase the risk of resistant bacteria?",opts:["It kills all the bacteria immediately","The hardest-to-kill bacteria may survive and reproduce","It turns antibiotics into nutrients","It causes the patient to mutate"],c:1,e:"Stopping early can leave the most resilient bacteria, which are more likely to carry resistance, alive to reproduce and pass it on. The mutation is in the bacteria, not the patient, and the course is not finished killing them."},
  {q:"Which combination of factors is most likely to drive a species to extinction?",opts:["A larger habitat and more genetic variation","A new disease together with rapid habitat destruction","More prey available and fewer predators","Stable climate and abundant food"],c:1,e:"A new disease the species cannot resist, plus rapid loss of habitat, gives little chance to adapt and can cause extinction. Larger habitats, greater variation and abundant resources all help a species survive."}
]);
