// science-y11-x03.js — Year 11 Science Topic 3 EXPANSION: Ecology: Populations & Sustainability
// Islands: s11i-03-1 .. s11i-03-6 (extends the banks defined in t03.js)
// Contains: 3 extra FLASHCARDS per island and 10 extra QUESTIONS per island.

// ── FLASHCARDS ──────────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s11i-03-1 — Trophic Levels & Biomass
  {id:"s11fc-03-1-6",islandId:"s11i-03-1",front:"How efficient are producers at capturing the Sun's energy?",
   back:"Plants and algae transfer only about 1% of the light energy that reaches them into biomass.\n\nMuch of the light misses the leaves, is reflected, passes straight through, or is the wrong wavelength for photosynthesis. The rest is lost during the reactions of photosynthesis.",difficulty:2,category:"concept"},
  {id:"s11fc-03-1-7",islandId:"s11i-03-1",front:"What is the difference between a pyramid of numbers and a pyramid of biomass?",
   back:"A pyramid of NUMBERS counts the individual organisms at each level — it can be inverted (e.g. one oak tree supporting many insects).\n\nA pyramid of BIOMASS shows the dry mass at each level — it accounts for the size of organisms and is almost never inverted.",difficulty:2,category:"concept"},
  {id:"s11fc-03-1-8",islandId:"s11i-03-1",front:"What happens to the biomass that is NOT passed on to the next trophic level?",
   back:"It is lost in several ways:\n\n• Used in respiration, with energy transferred to the surroundings as heat\n• Egested in faeces\n• Lost in urine (excretion)\n\nDecomposers then break down the waste and dead material, recycling the nutrients.",difficulty:2,category:"concept"},

  // s11i-03-2 — Food Security & Farming
  {id:"s11fc-03-2-6",islandId:"s11i-03-2",front:"What is biological control of pests?",
   back:"Using a natural predator, parasite or pathogen to reduce the numbers of a pest, instead of chemical pesticides.\n\nAdvantage: less chemical pollution and no bioaccumulation.\nRisk: the introduced control organism can itself become a pest if it has no natural enemies.",difficulty:2,category:"concept"},
  {id:"s11fc-03-2-7",islandId:"s11i-03-2",front:"What is mycoprotein and how is it produced?",
   back:"Mycoprotein is a protein-rich food suitable for vegetarians.\n\nIt is made from the fungus Fusarium, grown on glucose syrup in large fermenters under aerobic (oxygen-rich) conditions. The biomass is harvested and purified into food.",difficulty:2,category:"definition"},
  {id:"s11fc-03-2-8",islandId:"s11i-03-2",front:"What are the problems with intensive fish farming?",
   back:"• Disease and parasites spread quickly between crowded fish.\n• Waste and uneaten food pollute the surrounding water.\n• Escaped farmed fish can interbreed with wild fish.\n• Predators must be kept out, and young fish are often kept separate from adults.",difficulty:2,category:"application"},

  // s11i-03-3 — Water & Carbon Cycles
  {id:"s11fc-03-3-6",islandId:"s11i-03-3",front:"Why is the water cycle important to living organisms?",
   back:"It continually supplies fresh water on land for organisms to drink, for photosynthesis and for habitats.\n\nWhen seawater evaporates, only the water turns to vapour and the dissolved salts are left behind, so the precipitation that falls is fresh water.",difficulty:2,category:"concept"},
  {id:"s11fc-03-3-7",islandId:"s11i-03-3",front:"How are carbon dioxide levels naturally kept in balance?",
   back:"Photosynthesis removes CO₂ from the air, while respiration, decomposition and combustion return it.\n\nWhen these processes are roughly balanced, atmospheric CO₂ stays steady. Burning extra fossil fuels adds 'ancient' carbon and upsets this balance.",difficulty:2,category:"concept"},
  {id:"s11fc-03-3-8",islandId:"s11i-03-3",front:"How do microorganisms cycle carbon in the soil?",
   back:"Decomposers respire as they break down dead matter, releasing CO₂ back into the air.\n\nIn waterlogged, oxygen-poor (anaerobic) conditions, decomposition is very slow and methane may be produced instead — this is why peat builds up and stores carbon.",difficulty:2,category:"concept"},

  // s11i-03-4 — Biodiversity & Human Impact
  {id:"s11fc-03-4-6",islandId:"s11i-03-4",front:"How does pollution reduce biodiversity?",
   back:"Pollution kills organisms and damages habitats in three places:\n\n• Water — sewage and fertiliser run-off\n• Air — smoke and acidic gases (acid rain)\n• Land — toxic chemicals and landfill\n\nFewer species can survive, so biodiversity falls.",difficulty:2,category:"concept"},
  {id:"s11fc-03-4-7",islandId:"s11i-03-4",front:"How does global warming threaten biodiversity?",
   back:"A changing climate shifts where species can live.\n\nSome species migrate to new areas; others cannot adapt or move fast enough and may become extinct. Rising sea levels and changed rainfall patterns also destroy habitats.",difficulty:2,category:"concept"},
  {id:"s11fc-03-4-8",islandId:"s11i-03-4",front:"Why is large-scale deforestation carried out, and what are its effects?",
   back:"Forests are cleared to make land for farming (cattle and crops such as rice and biofuels) and to provide timber.\n\nEffects: habitats are destroyed and biodiversity falls; less photosynthesis and burning the wood both increase atmospheric CO₂.",difficulty:2,category:"application"},

  // s11i-03-5 — Maintaining Biodiversity
  {id:"s11fc-03-5-6",islandId:"s11i-03-5",front:"What is a seed bank and how does it protect biodiversity?",
   back:"A seed bank is a store of seeds from many plant species, kept in cool, dry conditions so they stay alive for a long time.\n\nIf a plant species becomes extinct in the wild, stored seeds can be grown to restore it.",difficulty:1,category:"definition"},
  {id:"s11fc-03-5-7",islandId:"s11i-03-5",front:"How can reducing carbon dioxide emissions help maintain biodiversity?",
   back:"Burning fewer fossil fuels and using more renewable energy slows global warming.\n\nWith less climate change, climates shift more slowly, so fewer habitats and species are lost. This helps protect biodiversity worldwide.",difficulty:2,category:"concept"},
  {id:"s11fc-03-5-8",islandId:"s11i-03-5",front:"Why are government and international programmes needed to protect biodiversity?",
   back:"Many threats — global warming, ocean pollution, overfishing — cross national borders, so countries must cooperate and agree shared targets.\n\nProgrammes must also balance conservation against human needs such as jobs and food, which can cause conflict.",difficulty:2,category:"application"},

  // s11i-03-6 — Decay, Anaerobic Decay & Biogas
  {id:"s11fc-03-6-6",islandId:"s11i-03-6",front:"How does turning a compost heap speed up decay?",
   back:"Turning the heap mixes in air, supplying oxygen for the decomposers' aerobic respiration.\n\nThis keeps the decomposers active, so the dead plant material breaks down faster into compost. The heap also needs warmth and moisture.",difficulty:2,category:"application"},
  {id:"s11fc-03-6-7",islandId:"s11i-03-6",front:"Give two advantages of using biogas as a fuel.",
   back:"• It is made from waste material (slurry, sewage, plant matter) that would otherwise be discarded.\n• Burning it releases CO₂ that plants took in recently, so it adds little net CO₂.\n• The leftover sludge can be used as a fertiliser.",difficulty:2,category:"application"},
  {id:"s11fc-03-6-8",islandId:"s11i-03-6",front:"When investigating temperature and decay, which variables should be controlled?",
   back:"To make it a fair test, keep the volume and type of food (e.g. milk), the volume of any indicator, the starting pH and the time the same.\n\nOnly the temperature should be changed — the rate of decay is the result you measure.",difficulty:2,category:"application"}
);

// ── TEST QUESTIONS ────────────────────────────────────────────────────────────
QUESTIONS["s11i-03-1"] = (QUESTIONS["s11i-03-1"] || []).concat([
  {q:"Which group of organisms always occupies the first trophic level?",opts:["Herbivores","Producers","Decomposers","Carnivores"],c:1,e:"Producers (plants and algae) make their own food by photosynthesis and form trophic level 1. Decomposers feed on dead material and are not counted as the first trophic level."},
  {q:"What term describes organisms such as bacteria and fungi that break down dead material and waste?",opts:["Producers","Primary consumers","Decomposers","Tertiary consumers"],c:2,e:"Decomposers (bacteria and fungi) break down dead organisms and waste, recycling nutrients. They feed on dead matter, unlike consumers, which feed on living organisms."},
  {q:"Algae in a pond store 60 000 kJ of biomass. Small fish feeding on the algae gain 9 000 kJ. What is the efficiency of biomass transfer?",opts:["9%","12%","15%","18%"],c:2,e:"Efficiency = (9000 ÷ 60000) × 100 = 15%. You compare the energy gained by the fish with the energy available in the algae, not with the original sunlight."},
  {q:"A trophic level contains 25 000 kJ of energy and passes 2 500 kJ on to the next level. What percentage of the energy is LOST at this level?",opts:["10%","25%","75%","90%"],c:3,e:"Energy passed on = (2500 ÷ 25000) × 100 = 10%, so energy lost = 100 − 10 = 90%. The 10% is the amount transferred, not the amount lost — read the question carefully."},
  {q:"A single oak tree supports thousands of insects. Why can a pyramid of numbers be inverted here while a pyramid of biomass is not?",opts:["The oak tree contains very little biomass","A single large producer has a small number but a very large biomass","The insects have more biomass than the tree","Pyramids of biomass are always inverted"],c:1,e:"The oak counts as one organism (small number) yet has an enormous biomass, so the numbers pyramid is narrow at the base while the biomass pyramid stays wide. Biomass allows for the size of organisms; numbers do not."},
  {q:"In a pyramid of biomass the producers hold 8 000 g/m², primary consumers 800 g/m² and secondary consumers 80 g/m². What is the approximate efficiency of transfer between each level?",opts:["8%","10%","12.5%","20%"],c:1,e:"Each level holds about one tenth of the level below it (800 ÷ 8000 = 10%; 80 ÷ 800 = 10%), so transfer is roughly 10%. The values fall by a factor of ten, not by 20%."},
  {q:"Why is biomass usually measured as dry mass rather than wet mass?",opts:["Dry mass is easier to weigh in the field","Water content varies, so removing it gives a fair comparison","Dry organisms contain more energy","Wet mass cannot be measured at all"],c:1,e:"Water content varies between organisms and over time, so measuring dry mass gives a fair, reliable comparison of living material. A drawback is that the organism must be killed to dry it."},
  {q:"Most of the energy lost between trophic levels is eventually transferred to the surroundings as:",opts:["heat","light","sound","electricity"],c:0,e:"Respiration releases energy that is transferred to the surroundings as heat (thermal energy). Light is the input to producers, not a loss passed between levels."},
  {q:"A farmer wants to feed the most people from a fixed area of land. Why is growing crops for people to eat more efficient than feeding the crops to cattle and eating beef?",opts:["Cattle add energy to the crops","Energy is lost at the extra trophic level when cattle eat the crops","Crops contain no energy","Beef contains more energy than crops"],c:1,e:"Each trophic level loses about 90% of its energy. Eating crops directly avoids the loss that occurs when cattle are added as an extra level, so more food energy reaches people."},
  {q:"Light energy reaching a crop is 1 000 000 kJ. The crop stores 10 000 kJ; cattle eating the crop store 1 000 kJ. What is the efficiency of transfer from crop to cattle?",opts:["1%","5%","10%","20%"],c:2,e:"Transfer from crop to cattle = (1000 ÷ 10000) × 100 = 10%. The 1 000 000 kJ of light is not used here — efficiency compares the cattle's gain with the crop's stored biomass."}
]);

QUESTIONS["s11i-03-2"] = (QUESTIONS["s11i-03-2"] || []).concat([
  {q:"A new disease spreads through a country's wheat fields. Why does this threaten food security?",opts:["It increases the wheat yield","It reduces the amount of food that can be produced","It improves soil fertility","It makes wheat cheaper to buy"],c:1,e:"Food security means having enough food at all times. A disease that destroys crops lowers the yield and the food available, threatening food security."},
  {q:"What is mycoprotein and where is it grown?",opts:["A protein from cattle, grown in fields","A protein-rich food made from a fungus grown in fermenters","A type of fertiliser added to soil","A pesticide made from bacteria"],c:1,e:"Mycoprotein is a protein-rich food made from the fungus Fusarium, grown on glucose syrup in large fermenters. It is suitable for vegetarians, unlike meat protein."},
  {q:"The fungus used to make mycoprotein is grown in aerobic conditions. Why must oxygen be supplied?",opts:["So the fungus can respire and grow","To kill all competing bacteria","To raise the temperature of the tank","To improve the taste of the protein"],c:0,e:"The fungus respires aerobically, needing oxygen to release energy for growth. Without oxygen it could not build up biomass efficiently."},
  {q:"What is biological control of crop pests?",opts:["Spraying chemical pesticides on the crop","Using a natural predator or parasite to control the pest","Removing every insect from the field","Adding extra fertiliser to the soil"],c:1,e:"Biological control uses a natural enemy (predator, parasite or pathogen) to reduce pest numbers, cutting the need for chemical pesticides. A risk is that the control organism may itself become a pest."},
  {q:"One problem with farming fish in crowded cages is that:",opts:["the fish grow too quickly","disease and parasites spread easily between fish","there is too much oxygen in the water","wild fish populations always increase"],c:1,e:"Crowding lets disease and parasites spread rapidly, and waste pollutes the water. This is why fish farms must be carefully managed, not because fish grow too fast."},
  {q:"Why are young fish on a fish farm often kept in separate tanks from the adults?",opts:["To stop adults eating the young and to control their feeding","To make the water warmer","To increase the pollution in the water","To reduce the total number of fish"],c:0,e:"Keeping young separate prevents adult fish (or predators) eating them and lets their feeding and growth be controlled, raising the yield of the farm."},
  {q:"A fertilised field yields 9 tonnes of wheat per hectare; an unfertilised field yields 6 tonnes per hectare. What is the percentage increase in yield from using fertiliser?",opts:["30%","33%","50%","150%"],c:2,e:"Increase = (9 − 6) ÷ 6 × 100 = 3 ÷ 6 × 100 = 50%. You compare the rise (3 tonnes) with the original value (6 tonnes), not with the new total."},
  {q:"A farmer keeps chickens indoors in warm sheds. Which statement best evaluates this method?",opts:["It is more energy-efficient but raises animal-welfare concerns","It always produces healthier meat","It uses more energy than free-range farming","It has no disadvantages at all"],c:0,e:"Restricting movement and keeping animals warm transfers more food energy to biomass (efficient), but it raises welfare concerns and can increase disease and antibiotic use. A balanced evaluation gives both sides."},
  {q:"Fishing quotas limit the mass of fish a boat may land. How do quotas help maintain fish stocks?",opts:["They leave enough mature fish to survive and breed","They increase the total number of fish caught","They remove all the predators from the sea","They make the fish grow faster"],c:0,e:"By capping the catch, quotas leave enough mature fish to reproduce, so the population can replenish. The aim is to balance the catch with the rate of natural breeding."},
  {q:"Laws control the mesh size of fishing nets. How does using a larger mesh size help sustainability?",opts:["It catches more fish in one trip","It lets young, smaller fish escape and grow to breed","It traps fish of every size","It increases pollution in the sea"],c:1,e:"A larger mesh lets immature fish slip through and survive to reproduce, protecting future stocks. A small mesh would remove young fish before they can breed."}
]);

QUESTIONS["s11i-03-3"] = (QUESTIONS["s11i-03-3"] || []).concat([
  {q:"Which process transfers water vapour from the leaves of plants into the atmosphere?",opts:["Condensation","Transpiration","Precipitation","Evaporation"],c:1,e:"Transpiration is the loss of water vapour from leaves through the stomata. Evaporation is the loss of water from open surfaces such as oceans, not from inside plants."},
  {q:"During condensation in the water cycle, water vapour:",opts:["turns into liquid droplets as it cools","turns into vapour as it warms","falls to the ground as rain","is absorbed by plant roots"],c:0,e:"Condensation is vapour cooling and changing into liquid droplets that form clouds. Vapour forming is evaporation, and water falling is precipitation."},
  {q:"Why is rainwater fresh even though much of it evaporates from salty oceans?",opts:["Salt evaporates faster than water","Rain dissolves salt as it falls","Only water evaporates, leaving the salts behind","Plants remove the salt from the rain"],c:2,e:"When seawater evaporates, only the water turns to vapour; the dissolved salts are left behind. So the precipitation that later falls is fresh water."},
  {q:"Which two processes return carbon dioxide to the atmosphere?",opts:["Photosynthesis and condensation","Respiration and combustion","Transpiration and evaporation","Photosynthesis and transpiration"],c:1,e:"Respiration by living organisms and combustion of fuels both release CO₂. Photosynthesis removes CO₂, while transpiration and evaporation are part of the water cycle."},
  {q:"How does carbon pass from a plant to a rabbit?",opts:["The rabbit eats the plant, taking in carbon compounds","The rabbit absorbs CO₂ given off by the plant","The plant respires carbon directly into the rabbit","Carbon passes between them through the soil"],c:0,e:"Carbon moves along food chains when organisms are eaten. The rabbit takes in carbon-containing molecules such as glucose by eating the plant."},
  {q:"Why does decomposition release carbon dioxide?",opts:["Decomposers photosynthesise as they feed","Decomposers respire as they break down dead matter","Decomposers burn the dead material","Decomposers absorb CO₂ from the soil"],c:1,e:"As decomposers break down dead organisms they respire, releasing CO₂. This returns carbon to the atmosphere as part of the carbon cycle."},
  {q:"A forest is cleared and the wood is burned. What is the effect on atmospheric carbon dioxide?",opts:["CO₂ falls because fewer trees respire","CO₂ stays exactly the same","CO₂ rises: burning releases CO₂ and fewer trees remain to absorb it","CO₂ rises only because the soil warms"],c:2,e:"Combustion releases the stored carbon as CO₂, and removing the trees means less photosynthesis to absorb CO₂. Both effects raise atmospheric CO₂."},
  {q:"In a sealed jar, pondweed and a snail survive longer than a snail kept alone. Why?",opts:["The snail feeds only on the pondweed","The pondweed's photosynthesis provides oxygen and removes the snail's CO₂","The pondweed stops the snail respiring","The snail provides light for the pondweed"],c:1,e:"The pondweed photosynthesises, producing the oxygen the snail needs and absorbing the CO₂ the snail breathes out. This recycling keeps both alive longer."},
  {q:"Atmospheric CO₂ rose from 280 ppm before industry to 420 ppm today. What is the percentage increase?",opts:["33%","50%","66%","140%"],c:1,e:"Increase = (420 − 280) ÷ 280 × 100 = 140 ÷ 280 × 100 = 50%. The rise (140 ppm) is compared with the original 280 ppm, not the new total."},
  {q:"Why does very little decomposition occur in a waterlogged, oxygen-poor bog?",opts:["Decomposers need oxygen for aerobic respiration, and there is little present","Decomposers cannot photosynthesise","It is always too hot for decomposers","There is no dead material in a bog"],c:0,e:"Aerobic decomposers need oxygen; in waterlogged, oxygen-poor conditions they cannot respire efficiently, so decay is very slow. This is why peat builds up and stores carbon."}
]);

QUESTIONS["s11i-03-4"] = (QUESTIONS["s11i-03-4"] || []).concat([
  {q:"Which of these would INCREASE the biodiversity of an area?",opts:["Clearing a forest to grow a single crop","Restoring a variety of native plants and habitats","Draining a wetland for building","Allowing oil to spill into a river"],c:1,e:"Restoring varied native habitats supports more species, raising biodiversity. The other options destroy habitats and reduce the variety of species."},
  {q:"Untreated sewage released into a river reduces biodiversity mainly because it:",opts:["adds extra oxygen to the water","encourages microbes that use up the oxygen, killing other organisms","increases the number of fish species","cools the water down"],c:1,e:"Sewage feeds microorganisms that multiply and use up dissolved oxygen as they respire. Other aquatic organisms then suffocate, lowering biodiversity."},
  {q:"Which gas released by burning fossil fuels contributes most to global warming?",opts:["Oxygen","Nitrogen","Carbon dioxide","Helium"],c:2,e:"Carbon dioxide is a greenhouse gas released by combustion. Rising CO₂ levels enhance the greenhouse effect and global warming; nitrogen and oxygen are not greenhouse gases."},
  {q:"How might global warming reduce biodiversity?",opts:["By creating identical climates everywhere","By changing climates so some species cannot survive or migrate in time","By increasing the numbers of every species","By cooling the polar regions"],c:1,e:"Global warming changes climates faster than some species can adapt or migrate, so they may die out, reducing biodiversity."},
  {q:"Tropical forests are most often cleared in order to:",opts:["make land for farming and to provide timber","increase the number of wild species","absorb more carbon dioxide","restore damaged peat bogs"],c:0,e:"Forests are commonly cleared for farming (cattle, crops, biofuels) and timber. This destroys habitats and reduces biodiversity, and burning the trees releases CO₂."},
  {q:"Why does deforestation increase the amount of carbon dioxide in the atmosphere?",opts:["Living trees release CO₂ all the time","The soil absorbs less rainwater afterwards","Fewer trees photosynthesise, and burning the wood releases CO₂","The remaining animals respire more"],c:2,e:"Removing trees cuts the photosynthesis that takes in CO₂, and burning the felled wood releases stored carbon as CO₂. Both raise atmospheric CO₂."},
  {q:"A woodland of 500 hectares is reduced to 350 hectares by clearing. What percentage of the woodland has been lost?",opts:["15%","30%","35%","70%"],c:1,e:"Loss = (500 − 350) ÷ 500 × 100 = 150 ÷ 500 × 100 = 30%. The remaining 350 ha is 70%, so 30% has been lost."},
  {q:"A survey records 40 species before a marsh is drained and 10 species afterwards. By what percentage has the number of species fallen?",opts:["25%","30%","70%","75%"],c:3,e:"Fall = (40 − 10) ÷ 40 × 100 = 30 ÷ 40 × 100 = 75%. Three quarters of the species were lost when the habitat was destroyed."},
  {q:"Why might a country with a rapidly rising population struggle to protect biodiversity?",opts:["It needs more land and resources, increasing pressure on habitats","It produces much less waste than before","It uses fewer raw materials over time","Its people gradually stop farming"],c:0,e:"A growing population demands more land, food and resources and creates more waste and pollution, all of which destroy habitats and reduce biodiversity."},
  {q:"Acid rain forms when gases from burning fossil fuels dissolve in rain. How does it reduce biodiversity?",opts:["It fertilises all plants equally","It damages trees and makes lakes too acidic for many organisms","It increases the oxygen in lakes","It only affects stone buildings"],c:1,e:"Acidic gases such as sulfur dioxide make rain acidic, which damages leaves and lowers the pH of lakes so that sensitive species die, reducing biodiversity."}
]);

QUESTIONS["s11i-03-5"] = (QUESTIONS["s11i-03-5"] || []).concat([
  {q:"What is the purpose of a seed bank?",opts:["To sell seeds to farmers for profit","To store seeds so plant species can be regrown if they are lost","To stop seeds from ever germinating","To breed endangered animals in captivity"],c:1,e:"A seed bank stores seeds from many species in cool, dry conditions. If a plant becomes extinct in the wild, the stored seeds can be grown to restore the species."},
  {q:"Captive breeding programmes for endangered animals are usually carried out in:",opts:["the open ocean","zoos and wildlife parks","deserts only","fossil-fuel power stations"],c:1,e:"Endangered species are often bred in zoos and wildlife parks, where conditions can be controlled. Offspring may later be released to boost wild populations."},
  {q:"How does using renewable energy instead of fossil fuels help biodiversity?",opts:["It releases much more carbon dioxide","It slows global warming, so fewer habitats are lost","It increases the rate of deforestation","It has no effect on habitats at all"],c:1,e:"Renewable energy releases little or no CO₂, slowing global warming. With less climate change, fewer habitats and species are lost, helping maintain biodiversity."},
  {q:"Why might international agreements be needed to protect biodiversity?",opts:["Pollution and climate change cross national borders","Every country's wildlife is identical","Only one country causes all the pollution","Damaged habitats can never recover"],c:0,e:"Threats such as global warming and ocean pollution affect many countries, so nations must cooperate and agree shared targets to protect ecosystems effectively."},
  {q:"Reintroducing hedgerows and field margins on farmland helps biodiversity because they:",opts:["remove all habitats for wildlife","provide habitats and food for many species","increase the area of a single crop","reduce the number of insects present"],c:1,e:"Hedgerows and margins offer shelter and food for insects, birds and mammals, supporting a greater variety of species than a single crop grown to the field edge."},
  {q:"Which action would best help to restore a damaged woodland habitat?",opts:["Replanting native trees and protecting the area","Building houses on the cleared land","Draining the nearby ponds","Removing all of the soil"],c:0,e:"Replanting native trees and protecting the land lets species return and the ecosystem recover. The other options would destroy habitats further."},
  {q:"A conservation plan protects a forest, but local people rely on logging for their income. What is the main conflict?",opts:["There is no real conflict","Protecting biodiversity may reduce people's livelihoods","Logging actually increases biodiversity","The forest simply cannot be protected"],c:1,e:"Conservation can clash with human needs: protecting the forest safeguards biodiversity but may cut local income from logging. Successful schemes try to balance both, for example with sustainable jobs."},
  {q:"Why might an animal bred entirely in captivity struggle when it is released into the wild?",opts:["It may not have learned to find food or avoid predators","It will always grow too large","Wild animals never accept it","It cannot reproduce at all"],c:0,e:"Captive-bred animals may lack the skills to find food, avoid predators or interact with others, so reintroduction must be planned carefully. This is a limitation of breeding programmes, not a reason to avoid them."},
  {q:"A breeding programme raises a population of rare birds from 40 to 130 over several years. What is the percentage increase?",opts:["90%","125%","225%","325%"],c:2,e:"Increase = (130 − 40) ÷ 40 × 100 = 90 ÷ 40 × 100 = 225%. The rise (90 birds) is compared with the starting number (40), not the final total."},
  {q:"A city plants 'green roofs' and wildflower verges. How does this help maintain biodiversity in a built-up area?",opts:["It removes all the remaining habitats","It creates new habitats and food for insects and birds","It increases the air pollution","It stops the plants photosynthesising"],c:1,e:"Green roofs and wildflower verges add habitats and food sources within a city, supporting pollinators and birds and raising urban biodiversity."}
]);

QUESTIONS["s11i-03-6"] = (QUESTIONS["s11i-03-6"] || []).concat([
  {q:"Decay returns important substances to the soil. Which substances are released for plants to reuse?",opts:["Mineral nutrients","Fossil fuels","Pesticides","Plastics"],c:0,e:"Decomposers release mineral nutrients (such as nitrates) from dead matter back into the soil, where plants absorb them again. This recycling is essential for plant growth."},
  {q:"Why does turning a compost heap make it decay faster?",opts:["It removes all of the water","It mixes in air, supplying oxygen for aerobic decomposers","It cools the heap down","It kills the decomposers"],c:1,e:"Turning the heap lets air in, supplying oxygen for the decomposers' aerobic respiration. More active decomposers break the waste down faster."},
  {q:"Above its optimum temperature, the rate of decay falls because:",opts:["the decomposers reproduce faster","the decomposers' enzymes are denatured","there is suddenly too much oxygen","the material freezes solid"],c:1,e:"Above the optimum, high temperatures denature the decomposers' enzymes (their active sites change shape), so reactions slow and decay decreases. Below the optimum, warmth speeds decay up."},
  {q:"Anaerobic decay in a biogas generator produces a gas that is mainly:",opts:["carbon dioxide","methane","oxygen","nitrogen"],c:1,e:"Anaerobic decay (without oxygen) produces biogas, which is mainly methane. The methane can be burned as a fuel for heating, cooking or generating electricity."},
  {q:"Which is an advantage of producing biogas from animal slurry?",opts:["It uses waste that would otherwise be discarded","It requires very large amounts of oxygen","It produces only solid waste","It works best when frozen"],c:0,e:"Biogas generators turn waste such as slurry into a useful fuel, and the leftover sludge can be used as fertiliser. They run by anaerobic decay, so they do not need oxygen."},
  {q:"Why must a biogas generator be kept warm?",opts:["to denature the enzymes","to keep the microorganisms active so decay continues","to add extra oxygen","to stop the waste decaying"],c:1,e:"A warm temperature keeps the anaerobic microorganisms active, so decay continues and biogas is produced steadily. Too cold and decay slows; too hot would denature their enzymes."},
  {q:"Milk at 30 °C falls from pH 6.6 to pH 4.6 in 4 days. What is the mean rate of pH change?",opts:["0.25 pH units per day","0.4 pH units per day","0.5 pH units per day","2.0 pH units per day"],c:2,e:"Change in pH = 6.6 − 4.6 = 2.0. Rate = change ÷ time = 2.0 ÷ 4 = 0.5 pH units per day. The acids made as the milk decays lower its pH."},
  {q:"Sample A loses 24 g in 3 days; sample B loses 30 g in 6 days. Which decays faster, and why?",opts:["A, because 8 g per day is faster than 5 g per day","B, because it lost more mass overall","They decay at exactly the same rate","B, because it took longer to decay"],c:0,e:"Rate = mass ÷ time. A = 24 ÷ 3 = 8 g/day; B = 30 ÷ 6 = 5 g/day. A has the higher rate, so it decays faster, even though B lost more mass in total."},
  {q:"In an investigation into the effect of temperature on decay, which variable should be kept the same?",opts:["the temperature of each sample","the volume and type of milk used","the rate of decay","the final pH reached"],c:1,e:"To make it a fair test, control variables such as the volume and type of milk; only the temperature should change. The rate of decay and final pH are results you measure, not controlled variables."},
  {q:"A continuous biogas generator is often better than a batch generator for a large farm because it:",opts:["produces gas only once","can have waste added all the time, giving a steady gas supply","needs no microorganisms","works without any warmth"],c:1,e:"A continuous generator has waste added constantly, so it makes biogas steadily — useful for a large, ongoing demand. A batch generator must be filled, left, then emptied, giving gas in bursts."}
]);
