// science-y11-x04.js — Year 11 Science Topic 4: Using Resources Sustainably (expansion pack)
// Islands: s11i-04-1 .. s11i-04-4
// Adds 3 extra FLASHCARDS and 10 extra test QUESTIONS per island.
// Loads after t04.js — flashcard ids continue from the existing numbering.

// ── FLASHCARDS (additions) ──────────────────────────────────────────────────
FLASHCARDS.push(
  // s11i-04-1 — Water Treatment & Sustainability
  {id:"s11fc-04-1-6",islandId:"s11i-04-1",front:"Outline the main stages of sewage (waste water) treatment.",
   back:"1. Screening and grit removal — large objects and grit are taken out.\n2. Sedimentation — the mixture settles into sewage sludge (sinks) and effluent (liquid on top).\n3. Anaerobic digestion of the sludge — bacteria break it down without oxygen, producing biogas and fertiliser.\n4. Aerobic biological treatment of the effluent — bacteria use oxygen to break down organic matter before the water is released.",difficulty:2,category:"concept"},
  {id:"s11fc-04-1-7",islandId:"s11i-04-1",front:"How can you test whether a sample of water is pure?",
   back:"Measure its boiling point: pure water boils at exactly 100 °C at standard atmospheric pressure. Dissolved substances raise the boiling point.\n\nYou can also evaporate a weighed sample to dryness — pure water leaves no solid residue behind, whereas water containing dissolved salts leaves crystals.",difficulty:2,category:"application"},
  {id:"s11fc-04-1-8",islandId:"s11i-04-1",front:"Compare distillation and reverse osmosis as methods of desalination.",
   back:"DISTILLATION: the salty water is boiled and the steam is condensed to give pure water. It needs a large amount of thermal energy.\n\nREVERSE OSMOSIS: salty water is forced at high pressure through a partially permeable membrane that holds back the dissolved salts. It needs electrical energy to generate the pressure, and the membranes must be replaced.\n\nBoth produce potable water from seawater, but both are energy-intensive.",difficulty:3,category:"concept"},

  // s11i-04-2 — The Haber Process & Fertilisers
  {id:"s11fc-04-2-6",islandId:"s11i-04-2",front:"Where do the raw materials for the Haber process come from?",
   back:"NITROGEN comes from the air, which is about 78% nitrogen by volume.\n\nHYDROGEN is mostly obtained by reacting methane (natural gas) with steam.\n\nBoth gases are purified before entering the reactor, because impurities can poison the iron catalyst.",difficulty:1,category:"definition"},
  {id:"s11fc-04-2-7",islandId:"s11i-04-2",front:"In the Haber process, how is ammonia separated from the reaction mixture, and what happens to the leftover gases?",
   back:"The gas mixture leaving the reactor is cooled. Ammonia has a much higher boiling point than nitrogen or hydrogen, so it condenses to a liquid and is removed.\n\nThe unreacted nitrogen and hydrogen stay as gases and are recycled back into the reactor, so no raw material is wasted.",difficulty:2,category:"concept"},
  {id:"s11fc-04-2-8",islandId:"s11i-04-2",front:"How are the three nutrients in an NPK fertiliser obtained?",
   back:"N (nitrogen): ammonia from the Haber process is reacted with nitric acid to make ammonium nitrate.\n\nP (phosphorus): phosphate rock is mined, but it is insoluble — it must be treated with an acid (e.g. sulfuric or nitric acid) to make soluble phosphate salts plants can absorb.\n\nK (potassium): potassium chloride and potassium sulfate are mined and can be used directly because they are already soluble.",difficulty:3,category:"application"},

  // s11i-04-3 — Life-Cycle Assessment & Recycling
  {id:"s11fc-04-3-6",islandId:"s11i-04-3",front:"For some products, the 'use' stage dominates the life-cycle assessment. Give an example and explain why.",
   back:"A car or an electric kettle uses far more energy during its working life than was needed to manufacture it.\n\nA petrol car burns fuel for years, so emissions during use dwarf the impact of making the steel body. For products like this, improving efficiency in use matters more than changing the packaging or manufacture.",difficulty:3,category:"application"},
  {id:"s11fc-04-3-7",islandId:"s11i-04-3",front:"How is scrap steel recycled, and why is this worthwhile?",
   back:"Scrap steel is sorted (it can be separated magnetically), then melted and added to the furnace when new steel is made.\n\nThis reduces the amount of iron ore that must be mined and reduced, saving energy, conserving a finite resource and cutting the waste sent to landfill.",difficulty:2,category:"concept"},
  {id:"s11fc-04-3-8",islandId:"s11i-04-3",front:"Compare landfill and incineration as ways of disposing of waste.",
   back:"LANDFILL: waste is buried. It takes up land, can pollute groundwater, and many plastics do not biodegrade so they persist for centuries.\n\nINCINERATION: waste is burned, reducing its volume, and the heat can generate electricity. However, burning releases carbon dioxide and can release toxic gases unless the fumes are carefully treated.\n\nBoth sit below reducing, reusing and recycling in the waste hierarchy.",difficulty:2,category:"application"},

  // s11i-04-4 — Corrosion & Using Materials
  {id:"s11fc-04-4-6",islandId:"s11i-04-4",front:"Aluminium is a reactive metal, yet aluminium window frames do not corrode away. Why?",
   back:"Aluminium reacts quickly with oxygen, but the aluminium oxide that forms makes a thin, tough layer that sticks tightly to the surface.\n\nThis oxide layer seals the metal underneath from any further attack by air and water. Iron is different: rust is flaky and falls away, constantly exposing fresh metal.",difficulty:2,category:"concept"},
  {id:"s11fc-04-4-7",islandId:"s11i-04-4",front:"Give the compositions of bronze, brass and 18-carat gold.",
   back:"BRONZE = copper + tin (hard-wearing; used for statues and ship propellers).\n\nBRASS = copper + zinc (workable; used for taps and door fittings).\n\nGOLD jewellery is alloyed with metals such as silver, copper and zinc to harden it. Pure gold is 24 carat, so 18-carat gold is 18/24 = 75% gold by mass.",difficulty:2,category:"definition"},
  {id:"s11fc-04-4-8",islandId:"s11i-04-4",front:"What is the difference between thermosoftening and thermosetting polymers?",
   back:"THERMOSOFTENING polymers are separate chains tangled together with only weak forces between them — they soften and melt when heated, so they can be remoulded and recycled.\n\nTHERMOSETTING polymers have strong covalent cross-links between the chains — they do not melt when heated; they char instead, so they are used where heat resistance matters (e.g. plug casings).",difficulty:3,category:"concept"}
);

// ── TEST QUESTIONS (additions) ───────────────────────────────────────────────
QUESTIONS["s11i-04-1"] = (QUESTIONS["s11i-04-1"] || []).concat([
  {q:"What is removed during the screening stage of sewage treatment?",opts:["Dissolved salts","Large solid objects and grit","Harmful bacteria","Nitrate ions"],c:1,e:"Screening uses metal grilles to take out large objects (twigs, rags) and grit at the very start. Bacteria are dealt with later — they are broken down during the biological treatment stages, not by screening."},
  {q:"In sewage treatment, the sludge that settles out is broken down by:",opts:["Aerobic bacteria using oxygen","Chlorination","Filtration through sand beds","Anaerobic bacteria in the absence of oxygen"],c:3,e:"Sewage sludge is digested anaerobically — bacteria break it down without oxygen, producing biogas and a residue usable as fertiliser. It is the liquid effluent, not the sludge, that receives aerobic treatment with oxygen."},
  {q:"After sedimentation of sewage, the liquid effluent is treated with aerobic bacteria. What do these bacteria need to be supplied with?",opts:["Air (oxygen)","Chlorine","Heat from burning biogas","Ultraviolet light"],c:0,e:"Aerobic means 'with oxygen', so air is bubbled through the effluent to let the bacteria break down the remaining organic matter. Chlorine would kill the useful bacteria rather than help them."},
  {q:"A student boils away 100 g of a water sample and a white solid is left in the basin. What does this show?",opts:["The water was potable","The water contained microorganisms","The water contained dissolved solids, so it was not pure","The water was acidic"],c:2,e:"Pure water leaves no residue when evaporated; a solid left behind must be dissolved salts, so the sample was not pure. The test says nothing about microorganisms — they would not appear as a visible white solid like this."},
  {q:"In reverse osmosis, salty water is forced through:",opts:["A bed of sand and gravel","A partially permeable membrane","A fractionating column","Activated charcoal"],c:1,e:"Reverse osmosis uses high pressure to push water molecules through a partially permeable membrane that holds back the dissolved salts. Sand and gravel beds only filter out insoluble particles — they cannot remove anything that is dissolved."},
  {q:"Which of these is a common source of fresh water for treatment in the UK?",opts:["Groundwater from aquifers","Seawater from the English Channel","Melted glacier ice","Bottled mineral water"],c:0,e:"UK potable water comes from fresh sources such as rivers, reservoirs and groundwater held in underground rocks (aquifers). Seawater is rarely used because desalination is far too expensive when fresh water is plentiful."},
  {q:"Rank these water sources from least to most processing needed to make potable water: fresh groundwater, salt water, waste (sewage) water.",opts:["Salt water, waste water, groundwater","Waste water, groundwater, salt water","Groundwater, salt water, waste water","Groundwater, waste water, salt water"],c:3,e:"Groundwater often needs only filtering and sterilising. Waste water needs several extra biological stages. Salt water needs energy-hungry desalination, making it the hardest to process. Waste water, despite sounding worst, still needs less energy than removing dissolved salt."},
  {q:"A coastal power station produces large amounts of waste heat. Which desalination method could make best use of this?",opts:["Reverse osmosis","Distillation","Filtration through sand","Adding chlorine"],c:1,e:"Distillation needs thermal energy to boil the seawater, so free waste heat from the power station cuts its biggest cost. Reverse osmosis needs electrical energy for high-pressure pumps, so spare heat would not help it directly."},
  {q:"Four samples are tested. Which result shows pure water?",opts:["Boils at 102.5 °C, leaves residue","Boils at 100.0 °C, leaves no residue","Boils at 100.0 °C, leaves residue","Boils at 98.0 °C at standard pressure, leaves no residue"],c:1,e:"Pure water boils at exactly 100 °C at standard pressure and leaves nothing behind on evaporation. A sample boiling at 100 °C but leaving residue is a trap — the residue proves dissolved solids were present, so it cannot be pure."},
  {q:"Why does sewage need more treatment stages than fresh water from a reservoir?",opts:["Sewage contains far more organic matter and harmful microorganisms","Sewage contains dissolved salt that must be distilled out","Reservoir water is already chemically pure","Sewage is too cold to treat quickly"],c:0,e:"Sewage carries large amounts of organic waste and dangerous microbes, so it needs screening, sedimentation and separate biological digestion of sludge and effluent. Sewage is not salty like seawater, so distillation is not the issue."}
]);

QUESTIONS["s11i-04-2"] = (QUESTIONS["s11i-04-2"] || []).concat([
  {q:"In the Haber process, where is the nitrogen obtained from?",opts:["Natural gas","Nitric acid","The air","Ammonium nitrate"],c:2,e:"Air is about 78% nitrogen, making it a cheap and plentiful source. Natural gas (methane) is the source of the hydrogen, not the nitrogen."},
  {q:"The hydrogen used in the Haber process is mainly produced by:",opts:["Reacting methane with steam","Electrolysis of ammonia","Fractional distillation of air","Burning hydrogen in oxygen"],c:0,e:"Hydrogen is made by reacting methane from natural gas with steam. Fractional distillation of air gives nitrogen, not hydrogen — air contains almost no hydrogen gas."},
  {q:"How is ammonia removed from the gas mixture leaving the Haber reactor?",opts:["It is filtered out as a solid","It is absorbed by the iron catalyst","It is burned off","The mixture is cooled so the ammonia condenses to a liquid"],c:3,e:"Ammonia liquefies at a much higher temperature than nitrogen or hydrogen, so cooling the mixture condenses only the ammonia, which is drained off. The catalyst speeds up the reaction; it does not absorb or store any product."},
  {q:"Ammonium nitrate fertiliser is made by reacting ammonia with:",opts:["Sulfuric acid","Nitric acid","Hydrochloric acid","Phosphoric acid"],c:1,e:"Ammonia neutralises nitric acid to give ammonium nitrate, which supplies nitrogen to crops. Sulfuric acid would give ammonium sulfate instead — a real fertiliser, but not ammonium nitrate."},
  {q:"In an NPK fertiliser, the letters N, P and K stand for:",opts:["Nitrogen, phosphorus, potassium","Nitrogen, plutonium, krypton","Nitrate, phosphate, carbonate","Nitrogen, potassium, phosphorus in that order"],c:0,e:"NPK fertilisers are formulations containing compounds of nitrogen (N), phosphorus (P) and potassium (K — from its Latin name kalium). The last option lists the right elements but pairs them with the wrong symbols: K is potassium, not phosphorus."},
  {q:"Why can mined phosphate rock not be spread straight onto fields as a fertiliser?",opts:["It is too acidic","It is insoluble, so plants cannot absorb it","It is radioactive","It contains no phosphorus"],c:1,e:"Phosphate rock does contain phosphorus, but it is insoluble in water, so plant roots cannot take it up. It is treated with acid to convert it into soluble phosphate salts first."},
  {q:"The Haber process runs at about 200 atmospheres. Why is a much higher pressure, such as 1000 atmospheres, not used even though it would raise the yield?",opts:["High pressure would shift equilibrium towards the reactants","High pressure poisons the iron catalyst","Building and running equipment to withstand such pressure is too expensive and hazardous","Ammonia decomposes above 200 atmospheres"],c:2,e:"Higher pressure does favour the ammonia side (fewer gas moles), but the thick-walled vessels, pumps and safety measures needed become uneconomic and dangerous. So 200 atm is an economic compromise, not a chemical limit — the first option has the equilibrium shift backwards."},
  {q:"A table shows the equilibrium yield of ammonia falling from 60% at 350 °C to 25% at 500 °C (constant pressure). What does this confirm about the forward reaction?",opts:["It is endothermic","It is impossible above 500 °C","It needs a catalyst to occur","It is exothermic"],c:3,e:"Raising the temperature shifts equilibrium in the endothermic direction; since heating lowers the ammonia yield, the reverse reaction must be endothermic and the forward reaction exothermic. The reaction still happens at 500 °C — just with a lower equilibrium yield."},
  {q:"Liquid ammonia is removed continuously as it forms. How does this affect the position of equilibrium in the reactor?",opts:["It shifts equilibrium towards the products, so more ammonia forms","It has no effect because equilibrium is fixed","It shifts equilibrium towards the reactants","It stops the reverse reaction completely"],c:0,e:"Removing a product lowers its concentration, so the system responds by making more of it — equilibrium shifts to the product side. The reverse reaction still occurs in the gas mixture; it is reduced, not switched off."},
  {q:"Plant A runs at 350 °C and plant B at 450 °C, both at 200 atm with an iron catalyst. Which statement best explains why industry prefers conditions like plant B?",opts:["Plant B gives a higher equilibrium yield of ammonia","Plant B reaches a profitable rate of production even though its equilibrium yield is lower","Plant B uses less energy for heating","The catalyst only works above 400 °C"],c:1,e:"The lower temperature in plant A actually gives the higher equilibrium yield, but the molecules react too slowly for the plant to be profitable. At 450 °C the yield per pass is smaller, yet ammonia is produced much faster — and unreacted gases are recycled, so overall output is better."}
]);

QUESTIONS["s11i-04-3"] = (QUESTIONS["s11i-04-3"] || []).concat([
  {q:"The electricity a washing machine consumes over its 10-year lifetime belongs to which stage of its life-cycle assessment?",opts:["Raw material extraction","Manufacturing","Disposal","Use"],c:3,e:"Energy consumed while the owner operates the product counts as the use stage. Manufacturing only covers the energy used to build the machine in the factory, which for appliances is often much smaller than a decade of running costs."},
  {q:"Which of these pieces of LCA data is easiest to measure objectively?",opts:["The harm a pollutant does to a river ecosystem","The litres of water used to manufacture one product","How guilty consumers feel about waste","The visual impact of a quarry on the landscape"],c:1,e:"Quantities such as water use, energy use and mass of raw material can be measured directly in numbers. Judging the harm done by a pollutant involves value judgements, which is exactly why full LCAs can be subjective."},
  {q:"Which of these is an example of reusing rather than recycling?",opts:["Refilling a glass milk bottle and returning it to the dairy","Melting drinks cans to make new aluminium sheet","Shredding plastic bottles into pellets for new products","Crushing glass into cullet for remelting"],c:0,e:"Reuse means the product is used again in its existing form — the bottle is simply washed and refilled. The other three all involve reprocessing the material into something new, which is recycling and still consumes energy."},
  {q:"When steel is recycled, the scrap can be:",opts:["Burned as a fuel","Dissolved in water and filtered","Added to the furnace when new steel is made, cutting the iron ore needed","Buried so it biodegrades into iron ore"],c:2,e:"Scrap steel is melted into the steelmaking process, reducing the ore that must be mined and reduced. Metals do not biodegrade — burying scrap simply wastes a finite resource."},
  {q:"Why must plastics be sorted into separate polymer types before recycling?",opts:["All plastics are biodegradable except one type","Different polymers have different properties and melting behaviour, so mixing them gives a poor-quality product","Sorting kills microorganisms on the plastic","Only sorted plastic is allowed in landfill"],c:1,e:"Each polymer melts and behaves differently, so a mixed melt produces weak, unusable material. Most common plastics are not biodegradable at all, which is one reason recycling them matters."},
  {q:"Which of these is a drawback of sending waste to landfill?",opts:["It generates electricity","Plastics in landfill persist because they do not biodegrade","It returns all materials to the supply chain","It uses no land"],c:1,e:"Landfill occupies land and most polymers stay there unchanged for centuries because microorganisms cannot break them down. Generating electricity from waste is a feature of incineration, not landfill."},
  {q:"An LCA compares bags: a paper bag needs more energy and water to manufacture, while a plastic bag persists far longer after disposal. What is the fairest conclusion?",opts:["The paper bag is better at every stage","The plastic bag is better at every stage","Neither bag is better at every stage — the choice depends on which impacts are judged more important","An LCA cannot compare two different materials"],c:2,e:"Each bag wins at different stages: paper costs more to make but breaks down; plastic is cheap to make but persists. Weighing manufacture against disposal needs a value judgement — that is exactly what comparing LCAs is for, so the last option is wrong."},
  {q:"A company publishes only the manufacturing-stage data from an LCA because its product scores well there. What is this an example of?",opts:["Selective use of data to make the product appear environmentally friendly","A complete cradle-to-grave assessment","Objective peer-reviewed science","The reduce, reuse, recycle hierarchy"],c:0,e:"Choosing only the flattering stage of an LCA for advertising is selective reporting, sometimes called greenwashing. A genuine LCA must cover raw materials, manufacture, use and disposal — not just one stage."},
  {q:"An LCA table shows bottle A uses 5 MJ to make and is used once; bottle B uses 90 MJ to make and is reused 100 times. Which conclusion does the data support?",opts:["Bottle A uses less energy per use","Bottle B uses less energy per use, at under 1 MJ per use","Both bottles have the same energy per use","Energy data cannot be compared between bottles"],c:1,e:"Dividing by the number of uses gives 5 MJ per use for A but 0.9 MJ per use for B. Comparing the raw manufacturing figures alone is the tempting mistake — what matters across a life cycle is the impact per use."},
  {q:"Recycling is placed below reducing and reusing in the waste hierarchy because recycling still:",opts:["Sends all material to landfill","Creates new raw materials from nothing","Requires energy to collect, sort, transport and reprocess materials","Has no effect on the environment"],c:2,e:"Recycling lorries, sorting plants and remelting furnaces all consume energy, so avoiding the waste in the first place (reduce) or using the item again (reuse) is better. Recycling is still far better than landfill — it just is not impact-free."}
]);

QUESTIONS["s11i-04-4"] = (QUESTIONS["s11i-04-4"] || []).concat([
  {q:"Aluminium does not corrode away even though it is more reactive than iron. Why?",opts:["Its oxide forms a thin protective layer that seals the surface from further attack","Aluminium never reacts with oxygen","Aluminium contains zinc","Aluminium is coated in oil at the factory"],c:0,e:"Aluminium reacts rapidly with oxygen, but the aluminium oxide layer is tough and sticks to the metal, stopping any further corrosion. Rust on iron, by contrast, flakes off and keeps exposing fresh metal."},
  {q:"Brass, used for taps and door handles, is an alloy of:",opts:["Copper and tin","Iron and carbon","Copper and zinc","Aluminium and magnesium"],c:2,e:"Brass is copper alloyed with zinc. Copper with tin is bronze — the classic mix-up — while iron with carbon is steel."},
  {q:"What percentage of an 18-carat gold ring is actually gold?",opts:["18%","100%","50%","75%"],c:3,e:"Pure gold is 24 carat, so 18-carat gold is 18 divided by 24, which is 75% gold by mass, alloyed with metals such as copper, silver and zinc for hardness. Reading 18 carat as 18% is the common error — carats are out of 24, not 100."},
  {q:"Compared with low-carbon steel, high-carbon steel is:",opts:["Softer and easier to press into shapes","Harder but more brittle","Rust-proof","A pure form of iron"],c:1,e:"More carbon distorts the iron layers further, making high-carbon steel very hard but brittle — good for cutting tools. Low-carbon steel is the softer, easily shaped one used for car bodies, and neither resists rust without protection."},
  {q:"Stainless steel resists corrosion because it is alloyed with:",opts:["Tin","Zinc","Chromium","Lead"],c:2,e:"Stainless steel contains chromium, which forms a stable oxide layer protecting the surface, making it ideal for cutlery and sinks. Zinc protects iron in galvanising as a coating, but it is not what makes stainless steel itself resistant."},
  {q:"Why can thermosoftening polymers be melted and remoulded while thermosetting polymers cannot?",opts:["Thermosoftening polymers have covalent cross-links between chains","Thermosetting polymers have weak forces between separate chains","Thermosoftening polymers have only weak forces between separate chains, so heating lets the chains slide apart","Thermosetting polymers are made of metal atoms"],c:2,e:"In thermosoftening polymers the tangled chains are held by weak intermolecular forces that heating overcomes, so they melt. It is the thermosetting polymers that have covalent cross-links — heating cannot break the network, so they char instead of melting."},
  {q:"Three sealed tubes each hold an iron nail: tube 1 has boiled water under a layer of oil, tube 2 has dry air over a drying agent, tube 3 has ordinary tap water open to air. After a week, which nail rusts and why?",opts:["Tube 1, because oil speeds up rusting","Tube 2, because dry air is reactive","Tube 3, because only that nail has both water and oxygen","All three rust equally"],c:2,e:"Rusting needs water and oxygen together. Boiling removed the dissolved oxygen in tube 1 and the oil keeps air out; the drying agent removes water in tube 2. Only tube 3 supplies both, so only that nail rusts."},
  {q:"Blocks of magnesium are bolted to a ship's steel hull. How do they protect the hull?",opts:["Magnesium is more reactive than iron, so it corrodes in preference to the steel","Magnesium forms a waterproof paint layer over the whole hull","Magnesium makes the seawater less salty","Magnesium reacts with the steel to form an alloy"],c:0,e:"This is sacrificial protection: the more reactive magnesium is oxidised instead of the iron, and the blocks are replaced when they are eaten away. The blocks only sit at certain points, so they are not acting as a barrier coating over the hull."},
  {q:"Poly(ethene) made at high pressure (LDPE) is soft and flexible, while poly(ethene) made with a catalyst at lower pressure (HDPE) is stiff and strong. What does this show?",opts:["LDPE and HDPE are made from different monomers","HDPE is a thermosetting polymer","LDPE contains no carbon","The same monomer can give polymers with different properties depending on the reaction conditions"],c:3,e:"Both plastics are built from ethene monomers; only the reaction conditions differ, changing how the chains pack together and hence the properties. Both are thermosoftening — HDPE's stiffness comes from chain packing, not cross-links."},
  {q:"A lab needs glassware that survives being heated strongly without cracking or softening. Which material should be chosen?",opts:["Soda-lime glass, because it is the cheapest","Clay ceramic, because it is transparent","Borosilicate glass, because it melts at a much higher temperature than soda-lime glass","LDPE, because it is flexible"],c:2,e:"Borosilicate glass, made from sand and boron trioxide, withstands high temperatures, which is why beakers and test tubes use it. Soda-lime glass is fine for bottles and windows but softens and cracks at lower temperatures, so cheapness is not the right deciding factor here."}
]);
