// science-y11-x05.js — Year 11 Science Topic 5: Chemical Analysis & Testing (Expansion)
// Islands: s11i-05-1 .. s11i-05-3
// Adds 3 new flashcards and 10 new test questions per island, extending t05.js.

// ── FLASHCARDS (expansion) ──────────────────────────────────────────────────
FLASHCARDS.push(
  // s11i-05-1 — Identifying Ions & Gases
  {id:"s11fc-05-1-6",islandId:"s11i-05-1",front:"How do you test for sulfate ions (SO₄²⁻) in solution?",
   back:"Add a few drops of dilute hydrochloric acid, then add barium chloride solution.\n\nIf sulfate ions are present, a white precipitate of barium sulfate forms.\n\nThe acid is added first to remove any carbonate ions, which would also give a white precipitate.",difficulty:2,category:"application"},
  {id:"s11fc-05-1-7",islandId:"s11i-05-1",front:"How do you test for halide ions (chloride, bromide, iodide) in solution?",
   back:"Add dilute nitric acid, then add silver nitrate solution. The colour of the precipitate identifies the halide:\n\nChloride — white precipitate (silver chloride)\nBromide — cream precipitate (silver bromide)\nIodide — yellow precipitate (silver iodide)",difficulty:2,category:"application"},
  {id:"s11fc-05-1-8",islandId:"s11i-05-1",front:"Why is dilute NITRIC acid, not hydrochloric acid, used to acidify the sample in the silver nitrate test?",
   back:"Hydrochloric acid contains chloride ions.\n\nThese would react with the silver nitrate to give a white precipitate of silver chloride, producing a false positive result even if the sample contained no halide ions.\n\nNitric acid adds no ions that interfere with the test.",difficulty:3,category:"concept"},

  // s11i-05-2 — Chromatography
  {id:"s11fc-05-2-6",islandId:"s11i-05-2",front:"In paper chromatography, what are the stationary phase and the mobile phase?",
   back:"Stationary phase — the chromatography paper, which does not move.\n\nMobile phase — the solvent (e.g. water or ethanol), which moves up through the paper carrying the dissolved substances with it.",difficulty:2,category:"definition"},
  {id:"s11fc-05-2-7",islandId:"s11i-05-2",front:"Why must the solvent level in the beaker be BELOW the pencil baseline at the start?",
   back:"If the solvent covered the baseline, the sample spots would dissolve straight into the solvent in the beaker instead of travelling up the paper.\n\nThe separation would fail and the results would be lost.",difficulty:2,category:"concept"},
  {id:"s11fc-05-2-8",islandId:"s11i-05-2",front:"What decides how far a substance travels up the paper in chromatography?",
   back:"Each substance is distributed between the two phases.\n\nA substance that is more soluble in the solvent (mobile phase) travels further up the paper.\n\nA substance more strongly attracted to the paper (stationary phase) travels a shorter distance, giving a lower Rf value.",difficulty:3,category:"concept"},

  // s11i-05-3 — Flame Tests & Instrumental Methods
  {id:"s11fc-05-3-6",islandId:"s11i-05-3",front:"Describe how to carry out a flame test on an unknown solid.",
   back:"1. Dip a nichrome wire loop in dilute hydrochloric acid, then hold it in a blue Bunsen flame until there is no colour change — this cleans the wire.\n2. Dip the clean loop into the sample.\n3. Hold the loop in the edge of a blue (non-luminous) Bunsen flame.\n4. Observe and record the flame colour.",difficulty:2,category:"application"},
  {id:"s11fc-05-3-7",islandId:"s11i-05-3",front:"Why must the wire loop be cleaned before each flame test?",
   back:"Traces of a previous sample left on the wire would also colour the flame, giving a misleading result.\n\nSodium contamination is a particular problem because its strong yellow colour can swamp the true flame colour of the sample being tested.",difficulty:2,category:"concept"},
  {id:"s11fc-05-3-8",islandId:"s11i-05-3",front:"In flame emission spectroscopy, what tells you (a) WHICH metal ions are present and (b) HOW MUCH of each ion is present?",
   back:"(a) The positions of the lines in the line spectrum — each element produces its own unique pattern of lines, like a fingerprint.\n\n(b) The intensity (brightness) of the lines — the more concentrated the ion, the more intense its lines.",difficulty:3,category:"concept"}
);

// ── TEST QUESTIONS (expansion) ────────────────────────────────────────────────

// s11i-05-1 — Identifying Ions & Gases
QUESTIONS["s11i-05-1"] = (QUESTIONS["s11i-05-1"] || []).concat([
  {q:"Which reagents are used to test for sulfate ions in solution?",opts:["Dilute nitric acid then silver nitrate solution","Dilute hydrochloric acid then barium chloride solution","Sodium hydroxide solution only","Limewater then dilute hydrochloric acid"],c:1,e:"Sulfate ions give a white precipitate of barium sulfate when dilute hydrochloric acid and then barium chloride solution are added. Nitric acid with silver nitrate is the test for halide ions, not sulfates."},
  {q:"A solution is acidified with dilute nitric acid, then silver nitrate solution is added. A yellow precipitate forms. Which ion is present?",opts:["Chloride","Bromide","Iodide","Sulfate"],c:2,e:"Iodide ions form a yellow precipitate of silver iodide. Bromide is the tempting alternative, but it gives a cream precipitate — paler than the yellow of silver iodide."},
  {q:"Why is the sample acidified with dilute acid before adding barium chloride in the sulfate test?",opts:["To make the precipitate brighter white","To remove carbonate ions that would also give a white precipitate","To dissolve the barium chloride","To speed up the reaction"],c:1,e:"Carbonate ions also form a white precipitate with barium chloride, so they must be removed (the acid reacts with them) to avoid a false positive. The acid does not change the appearance or speed of the genuine sulfate result."},
  {q:"Adding sodium hydroxide solution to a sample produces a green precipitate. Which ion is present?",opts:["Iron(III)","Copper(II)","Iron(II)","Aluminium"],c:2,e:"Iron(II) ions form a green precipitate of iron(II) hydroxide. Iron(III) is the common mix-up, but it gives a brown precipitate, not green."},
  {q:"In the silver nitrate test for halides, why would using hydrochloric acid instead of nitric acid spoil the result?",opts:["Hydrochloric acid would dissolve the silver nitrate","Hydrochloric acid contains chloride ions, which would give a false positive white precipitate","Hydrochloric acid is too weak to acidify the sample","Hydrochloric acid would turn the precipitate yellow"],c:1,e:"Hydrochloric acid supplies chloride ions, which react with silver nitrate to form white silver chloride even when the sample contains no halide. It is not a question of acid strength — nitric acid is used because it adds nothing that interferes."},
  {q:"Adding sodium hydroxide solution to a sample produces a brown precipitate. Which ion is present?",opts:["Iron(III)","Iron(II)","Copper(II)","Calcium"],c:0,e:"Iron(III) ions form a brown precipitate of iron(III) hydroxide. Iron(II) is the tempting distractor, but its hydroxide precipitate is green."},
  {q:"A white solid fizzes when dilute hydrochloric acid is added, and the gas turns limewater milky. A flame test on the solid gives an orange-red colour. What is the solid?",opts:["Sodium carbonate","Calcium carbonate","Calcium sulfate","Lithium chloride"],c:1,e:"Fizzing with acid and a gas that turns limewater milky shows carbonate ions; the orange-red flame shows calcium. Lithium chloride is tempting because lithium's crimson flame can be confused with calcium's orange-red, but a chloride would not fizz with acid."},
  {q:"A solution gives a white precipitate with sodium hydroxide that does NOT dissolve in excess, and a white precipitate with acidified barium chloride. What is the compound?",opts:["Aluminium sulfate","Calcium chloride","Calcium sulfate","Aluminium chloride"],c:2,e:"A white hydroxide precipitate that stays in excess NaOH identifies calcium (aluminium hydroxide would redissolve), and the barium chloride result shows sulfate. Aluminium sulfate is the trap — its precipitate would dissolve in excess NaOH."},
  {q:"Acidified silver nitrate solution is added to a sample and a cream precipitate forms. Which ion is present?",opts:["Iodide","Chloride","Sulfate","Bromide"],c:3,e:"Bromide ions form a cream precipitate of silver bromide — between the white of silver chloride and the yellow of silver iodide. Iodide is the closest distractor, but its precipitate is distinctly yellow."},
  {q:"A pale green gas is released during an experiment. Damp litmus paper held in the gas quickly turns white. What is the gas?",opts:["Chlorine","Carbon dioxide","Oxygen","Hydrogen"],c:0,e:"Chlorine bleaches damp litmus paper white (it may turn red briefly first). Carbon dioxide is the common wrong answer, but it only turns limewater milky — it does not bleach litmus and is colourless."}
]);

// s11i-05-2 — Chromatography
QUESTIONS["s11i-05-2"] = (QUESTIONS["s11i-05-2"] || []).concat([
  {q:"In paper chromatography, what is the stationary phase?",opts:["The solvent","The chromatography paper","The sample spots","The beaker"],c:1,e:"The stationary phase is the part that does not move — the paper. The solvent is the mobile phase, because it moves up the paper carrying the dissolved substances."},
  {q:"In paper chromatography, what is the mobile phase?",opts:["The pencil baseline","The chromatography paper","The solvent","The dye with the highest Rf value"],c:2,e:"The mobile phase is the solvent, which moves up through the paper. The paper itself is the stationary phase — a dye, even a fast-moving one, is just a substance carried by the mobile phase."},
  {q:"Why does one dye in a mixture travel further up the paper than another?",opts:["It is more soluble in the solvent than in attractions to the paper","It has a darker colour","It was spotted onto the paper first","It is a heavier molecule, so the solvent pushes it harder"],c:0,e:"How far a substance travels depends on how it is distributed between the phases: more soluble in the solvent means it spends more time moving and travels further. Colour, spotting order and a vague idea of being pushed have no effect on distance travelled."},
  {q:"Why is a lid usually placed on the container during chromatography?",opts:["To keep the paper upright","To stop the solvent evaporating from the container","To keep light out, which would fade the dyes","To increase the pressure and speed up separation"],c:1,e:"The lid keeps the atmosphere inside saturated with solvent vapour and stops the solvent evaporating, which would slow the run and distort results. It has nothing to do with light or pressure."},
  {q:"After a chromatography run, one substance has not moved from the baseline at all. What does this show?",opts:["The substance is insoluble in this solvent","The substance is a pure compound","The experiment was left running too long","The substance has an Rf value of 1"],c:0,e:"A spot that stays on the baseline did not dissolve in the mobile phase, so it is insoluble in this solvent (a different solvent could be tried). An Rf of 1 would mean the opposite — the spot travelled with the solvent front."},
  {q:"Why can an Rf value never be greater than 1?",opts:["Because Rf values are measured in centimetres","Because a substance cannot travel further than the solvent that carries it","Because the paper is too short","Because Rf values are percentages"],c:1,e:"A substance only moves because the solvent carries it, so it can never overtake the solvent front; the ratio of the two distances must be 1 or less. Rf is a ratio of two distances, so it has no units and is not a percentage."},
  {q:"On a chromatogram, a dye spot is 2.8 cm above the baseline and the solvent front is 8.0 cm above the baseline. What is the Rf value of the dye?",opts:["0.28","2.86","0.35","0.80"],c:2,e:"Rf = distance moved by substance ÷ distance moved by solvent = 2.8 ÷ 8.0 = 0.35. Dividing the wrong way round gives 2.86, which is impossible because Rf cannot exceed 1."},
  {q:"A substance has an Rf value of 0.25 in a solvent. If the solvent front moves 12.0 cm, how far from the baseline will the spot be?",opts:["3.0 cm","4.8 cm","0.25 cm","48 cm"],c:0,e:"Distance moved by substance = Rf multiplied by solvent distance = 0.25 x 12.0 = 3.0 cm. Choosing 48 cm comes from dividing 12.0 by 0.25 instead of multiplying — a spot can never be further than the solvent front."},
  {q:"In the chromatography required practical, why should the position of the solvent front be marked in pencil as soon as the paper is removed?",opts:["Because the paper shrinks as it dries","Because the solvent evaporates quickly, making the front invisible","Because the dyes keep moving after the paper is removed","Because the ruler only works on wet paper"],c:1,e:"The solvent evaporates from the paper rapidly, so the front soon disappears; without marking it you could not measure the solvent distance needed for Rf calculations. The dye spots themselves stay visible, so they can be measured later."},
  {q:"A white powder melts sharply at exactly 122 degrees Celsius, matching the data book value for benzoic acid. A second sample melts gradually between 109 and 117 degrees Celsius. What can you conclude?",opts:["Both samples are pure benzoic acid","The first sample is pure; the second is an impure mixture","The second sample is a different pure compound","Neither sample is pure"],c:1,e:"A pure substance melts sharply at a specific temperature, so the first sample is pure benzoic acid. Melting over a range, and below the true value, is the signature of an impure mixture — a different pure compound would still melt sharply at its own fixed temperature."}
]);

// s11i-05-3 — Flame Tests & Instrumental Methods
QUESTIONS["s11i-05-3"] = (QUESTIONS["s11i-05-3"] || []).concat([
  {q:"Before a flame test, the nichrome wire loop is dipped in dilute hydrochloric acid and heated until the flame stays blue. Why?",opts:["To sterilise the wire","To remove traces of previous samples that would colour the flame","To make the wire hot enough to ignite the sample","To coat the wire in acid so the sample sticks"],c:1,e:"Cleaning removes contamination from earlier samples, which would otherwise add their own flame colours and give a misleading result. The sample does not need to be ignited — the flame excites the metal ions directly."},
  {q:"A flame test produces a green flame. Which metal ion is most likely present?",opts:["Copper","Calcium","Lithium","Potassium"],c:0,e:"Copper ions give a green (or blue-green) flame. Calcium is the common confusion here, but it gives an orange-red flame, nothing like green."},
  {q:"Why should a flame test be carried out using a blue (non-luminous) Bunsen flame rather than a yellow safety flame?",opts:["The yellow flame is too cold to vaporise the sample","The yellow flame's own colour would hide the colour produced by the sample","The blue flame contains more oxygen ions","The yellow flame would melt the nichrome wire"],c:1,e:"The yellow safety flame is already strongly coloured, so it would mask the flame colour of the metal ions being tested. While the blue flame is also hotter, the key analytical reason is visibility of the sample's colour, not melting the wire."},
  {q:"Which flame colour is produced by calcium ions?",opts:["Lilac","Yellow","Orange-red","Green"],c:2,e:"Calcium ions give an orange-red flame. It is most often confused with lithium's crimson — calcium is more orange, lithium a deeper red — while lilac belongs to potassium."},
  {q:"In a line spectrum from flame emission spectroscopy, what does the intensity of the lines tell you?",opts:["The temperature of the flame","Which element is present","The concentration of the metal ions in the sample","The size of the atoms"],c:2,e:"Line intensity indicates concentration — brighter lines mean more of that ion. Identifying which element is present comes from the positions of the lines, not their brightness."},
  {q:"Why can a line spectrum be used to identify an element?",opts:["Every element produces its own unique pattern of lines","All metals produce the same lines at different brightnesses","The number of lines equals the atomic number","Only metals in Group 1 produce line spectra"],c:0,e:"Each element emits light at its own characteristic set of wavelengths, so the pattern of lines acts like a fingerprint. The number of lines is not simply the atomic number — it depends on the electron transitions available."},
  {q:"A solution gives only a yellow flame in a simple flame test, but flame emission spectroscopy shows the line patterns of both sodium and potassium. Explain the flame test result.",opts:["The potassium had evaporated before the flame test","Potassium does not produce a flame colour in mixtures","The intense yellow of sodium masked the lilac of potassium","The spectroscope contaminated the sample with potassium"],c:2,e:"Sodium's strong yellow emission swamps the fainter lilac of potassium, so the eye sees only yellow; the spectroscope still detects both elements' separate line patterns. Potassium ions do still emit in a mixture — the colour is hidden, not absent."},
  {q:"A water company needs to measure a very low concentration of calcium ions in thousands of samples. Why is flame emission spectroscopy more suitable than simple flame tests?",opts:["It is sensitive, rapid and gives the concentration as well as the identity","It needs no electrical equipment","It changes the calcium ions into a safer form","It is cheaper than a Bunsen burner and wire"],c:0,e:"Instrumental analysis is sensitive enough for tiny amounts, fast enough for many samples, and the line intensity gives the concentration. It is not cheap — the equipment is expensive and needs trained operators, which is its main drawback."},
  {q:"An unknown sample's emission spectrum is compared with reference spectra. Its lines appear at exactly the same positions as the reference spectrum for element X, plus extra lines matching element Y. What can you conclude?",opts:["The sample contains element X only","The sample contains both element X and element Y","The sample is a compound of X that no longer contains X atoms","The spectrum cannot identify elements in mixtures"],c:1,e:"Matching line positions identify each element present, and spectra of mixtures simply show the combined line patterns, so both X and Y are present. The strength of spectroscopy is precisely that it works on mixtures, where flame test colours would mask each other."},
  {q:"Which statement gives a genuine DISADVANTAGE of instrumental methods such as flame emission spectroscopy?",opts:["They cannot detect small concentrations of ions","The equipment is expensive and requires trained operators","They are slower than test-tube methods","They only work on pure, single-ion samples"],c:1,e:"The real drawbacks are cost and the need for skilled operators to run and interpret the analysis. The other options state the opposite of the truth — instrumental methods are fast, highly sensitive and work well on mixtures."}
]);
