// science-y11-x06.js — Year 11 Science Topic 6 EXPANSION: Atmospheric Chemistry & Climate
// Islands: s11i-06-1 .. s11i-06-2
// Adds: 3 extra FLASHCARDS and 10 extra test QUESTIONS per island.
// Loaded after t06.js — appends to the existing banks, never replaces them.

// ── EXTRA FLASHCARDS ────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s11i-06-1 — The Greenhouse Effect & Climate Change
  {id:"s11fc-06-1-6",islandId:"s11i-06-1",front:"What is a carbon footprint?",
   back:"A carbon footprint is the total amount of carbon dioxide and other greenhouse gases emitted over the full life cycle of a product, service or event.\n\nIt includes emissions from manufacture, transport, use and disposal — not just the obvious fuel burned at the point of use.",difficulty:1,category:"definition"},
  {id:"s11fc-06-1-7",islandId:"s11i-06-1",front:"Give three ways the carbon footprint of a product or activity can be reduced.",
   back:"1. Use renewable or nuclear energy instead of fossil fuels.\n2. Improve efficiency — less fuel or electricity used means less CO₂ released.\n3. Capture emissions — carbon capture and storage traps CO₂ from power stations before it reaches the atmosphere.\n\nOther options: taxes on emissions, carbon offsetting (e.g. tree planting), and changing behaviour such as flying less or eating less meat.",difficulty:2,category:"application"},
  {id:"s11fc-06-1-8",islandId:"s11i-06-1",front:"How did the level of carbon dioxide in Earth's early atmosphere decrease over billions of years?",
   back:"Earth's early atmosphere was thought to be mostly CO₂ (like Mars and Venus today). It decreased because:\n\n1. CO₂ dissolved in the newly formed oceans.\n2. Dissolved CO₂ was used by marine organisms to make shells, which became sedimentary rocks such as limestone.\n3. Photosynthesis by algae and plants absorbed CO₂ and released oxygen.\n4. Carbon was locked away in fossil fuels (coal, crude oil, natural gas).",difficulty:3,category:"concept"},

  // s11i-06-2 — Pollutant Gases
  {id:"s11fc-06-2-6",islandId:"s11i-06-2",front:"What problems are caused by particulates (soot and unburnt hydrocarbons) in the air?",
   back:"1. Health: tiny particles are breathed deep into the lungs, causing respiratory problems and increasing the risk of lung disease.\n2. Global dimming: particulates in the atmosphere reflect sunlight back into space, reducing the amount reaching the Earth's surface.\n\nParticulates come mainly from incomplete combustion, especially in diesel engines.",difficulty:2,category:"concept"},
  {id:"s11fc-06-2-7",islandId:"s11i-06-2",front:"How can sulfur dioxide emissions from power stations be reduced?",
   back:"1. Remove sulfur from the fuel before burning — petrol and diesel are desulfurised at the refinery.\n2. Remove SO₂ from the waste gases after burning — flue gases are passed through a slurry of an alkali such as calcium oxide or calcium carbonate, which neutralises the acidic SO₂.\n\nBoth approaches reduce acid rain.",difficulty:2,category:"application"},
  {id:"s11fc-06-2-8",islandId:"s11i-06-2",front:"What reactions happen inside a catalytic converter?",
   back:"A catalytic converter uses a hot platinum-based catalyst to turn harmful exhaust gases into less harmful ones:\n\n1. Carbon monoxide is oxidised to carbon dioxide.\n2. Nitrogen oxides are reduced to nitrogen (and oxygen).\n\nOverall example: 2CO + 2NO → 2CO₂ + N₂\n\nNote: it does NOT remove CO₂ — a converter reduces toxic emissions, not greenhouse emissions.",difficulty:3,category:"concept"}
);

// ── EXTRA TEST QUESTIONS ──────────────────────────────────────────────────────
QUESTIONS["s11i-06-1"] = (QUESTIONS["s11i-06-1"] || []).concat([
  {q:"What is meant by the carbon footprint of a product?",opts:["The mass of carbon in the product itself","The total greenhouse gases emitted over the product's full life cycle","The CO₂ released only while the product is being used","The amount of packaging the product uses"],c:1,e:"A carbon footprint covers the whole life cycle — raw materials, manufacture, transport, use and disposal. Counting only the emissions during use misses large contributions such as manufacturing energy."},
  {q:"Which type of radiation do greenhouse gases absorb and re-emit?",opts:["Ultraviolet radiation from the Sun","Visible light from the Sun","Infrared radiation emitted by the Earth's surface","Radio waves from space"],c:2,e:"The warm Earth re-emits energy as long-wavelength infrared radiation, which greenhouse gases absorb and re-radiate. Ultraviolet absorption is the job of the ozone layer — a separate process often confused with the greenhouse effect."},
  {q:"Which pair of human activities are major sources of methane?",opts:["Cattle farming and decaying waste in landfill sites","Burning coal and running petrol cars","Making cement and quarrying limestone","Using fridges and aerosol sprays"],c:0,e:"Methane is released by digestion in cattle, rice paddies and rotting organic matter in landfill. Burning coal and petrol mainly releases CO₂, not methane — that distractor mixes up the two main greenhouse gases."},
  {q:"Why is it difficult for scientists to predict the exact effects of climate change?",opts:["There is no evidence that the climate is changing","Temperatures have never been measured accurately","Scientists are not allowed to share their data","Global climate systems are very complex, so models are simplified and carry uncertainty"],c:3,e:"The climate involves many interacting factors (oceans, ice, clouds, ecosystems), so models must simplify and predictions carry uncertainty. That is not the same as having no evidence — the warming trend itself is very well supported."},
  {q:"A family wants to cut the carbon footprint of their weekly shop. Which change would help most?",opts:["Buying locally grown seasonal vegetables instead of air-freighted produce","Choosing food with brighter packaging","Shopping at night when it is cooler","Buying the same food but paying in cash"],c:0,e:"Air freight releases far more CO₂ per kilogram of food than local transport, so swapping to local, seasonal produce cuts emissions significantly. Packaging colour, time of day and payment method have no real effect on greenhouse gas output."},
  {q:"Deforestation raises atmospheric CO₂ in two ways. Which statement gives both correctly?",opts:["Trees stop reflecting sunlight and stop making methane","Fewer trees absorb CO₂ by photosynthesis, and burning or rotting wood releases stored carbon","Soil becomes warmer and rivers dry up","Fewer trees release oxygen, which turns into CO₂"],c:1,e:"Removing trees cuts CO₂ absorption, and the carbon stored in their wood is released when it is burned or decays. Oxygen does not 'turn into' CO₂ — that distractor muddles the gases involved in photosynthesis."},
  {q:"Earth's early atmosphere is thought to have been mostly carbon dioxide. What is the main basis for this idea?",opts:["Ancient written records describe the early air","Fossilised dinosaurs contain trapped CO₂","The present-day atmospheres of Mars and Venus are mostly CO₂, suggesting early Earth's was similar","Modern volcanoes only ever release nitrogen"],c:2,e:"Because the Earth formed 4.6 billion years ago, direct evidence is limited, so scientists use comparisons — Mars and Venus still have CO₂-rich atmospheres produced by volcanic activity. There are no written records from that time; that distractor ignores the timescale entirely."},
  {q:"Which process did NOT help remove carbon dioxide from Earth's early atmosphere?",opts:["CO₂ dissolving in the newly formed oceans","Marine organisms using dissolved CO₂ to build shells that became limestone","Photosynthesis by algae and plants","Volcanic eruptions adding gases to the air"],c:3,e:"Volcanoes were a source of CO₂, not a sink — they added gas to the atmosphere. The oceans, shell-building organisms and photosynthesis all locked carbon away, which is why CO₂ fell from being the main gas to a trace gas."},
  {q:"The table shows CO₂ emissions per passenger for a 500 km journey: plane 130 kg, car (driver only) 96 kg, coach 14 kg, train 18 kg. Which conclusion is valid?",opts:["The car is always the worst option for any group size","The train emits more than the plane","Flying is the greenest choice because planes carry more people","Travelling by coach gives the lowest carbon footprint per passenger for this journey"],c:3,e:"At 14 kg per passenger the coach is lowest in this data set. The car figure is per single occupant — with four passengers sharing, its per-person footprint would fall to about 24 kg, so 'always the worst' is not a safe conclusion either."},
  {q:"Ice core data show CO₂ concentration and global temperature rising and falling together over 400,000 years. Why can this correlation alone not prove that today's warming is human-caused?",opts:["Because correlation does not by itself show which factor causes which; extra evidence such as the source of the added CO₂ is needed","Because the ice cores must all be faulty","Because temperature and CO₂ are completely unrelated","Because climate only changed after humans evolved"],c:0,e:"A correlation shows two variables move together but not the direction of cause and effect. The human link is established with additional evidence — for example the rapid post-industrial CO₂ rise matching fossil fuel use. Dismissing the ice cores as faulty is not a scientific response to a correlation."}
]);

QUESTIONS["s11i-06-2"] = (QUESTIONS["s11i-06-2"] || []).concat([
  {q:"What is global dimming and what causes it?",opts:["A reduction in sunlight reaching the Earth's surface, caused by particulates reflecting solar radiation","Street lights being turned off to save energy","The greenhouse effect blocking sunlight","The ozone layer absorbing visible light"],c:0,e:"Tiny solid particles (soot and unburnt hydrocarbons) in the atmosphere reflect sunlight back into space, dimming the surface below. The greenhouse effect is different — it traps outgoing infrared rather than blocking incoming sunlight."},
  {q:"In a catalytic converter, carbon monoxide and nitrogen monoxide react together. What are the products?",opts:["Carbon and nitrogen dioxide","Carbon dioxide and nitrogen","Methane and oxygen","Soot and ammonia"],c:1,e:"The catalyst allows 2CO + 2NO → 2CO₂ + N₂: the toxic CO is oxidised to CO₂ while NO is reduced to harmless nitrogen. Carbon and nitrogen dioxide would mean the reaction had gone the wrong way for both gases."},
  {q:"Why does removing sulfur from petrol and diesel at the refinery reduce acid rain?",opts:["It makes the fuel burn at a lower temperature","It stops carbon dioxide being produced","It prevents the fuel from evaporating","No sulfur in the fuel means no sulfur dioxide can form when it burns"],c:3,e:"Sulfur dioxide can only form if sulfur atoms are present in the fuel, so desulfurisation removes the problem at source. It has no effect on CO₂, which comes from the carbon in the fuel itself."},
  {q:"A power station burns coal containing sulfur impurities. Which pollutant comes directly from those impurities?",opts:["Carbon monoxide","Nitrogen oxides","Sulfur dioxide","Methane"],c:2,e:"Sulfur in the coal is oxidised to SO₂ during combustion. Nitrogen oxides also form in the furnace, but they come from nitrogen in the air reacting at high temperature, not from the impurities in the fuel."},
  {q:"A Bunsen burner with its air hole closed gives a yellow, sooty flame. What does this show about the combustion?",opts:["Combustion is complete because the flame is hot","Combustion is incomplete because limited oxygen leaves unburnt carbon particles","The gas contains sulfur impurities","The gas is reacting with nitrogen"],c:1,e:"The yellow colour and soot are glowing carbon particles produced when there is not enough oxygen for complete combustion. Sulfur impurities would produce SO₂, an invisible gas — they do not make a flame sooty."},
  {q:"Why are households with gas boilers advised to fit a carbon monoxide alarm?",opts:["CO has a strong smell that the alarm confirms","CO makes the air visibly cloudy","CO cannot be detected by human senses, so an alarm is the only warning of a dangerous leak","Gas boilers always produce large amounts of CO"],c:2,e:"Carbon monoxide is colourless and odourless, so people can be poisoned without any warning — an alarm detects what senses cannot. A well-maintained boiler normally burns completely; CO is only produced when combustion goes wrong, which is exactly why monitoring matters."},
  {q:"Which row correctly matches a pollutant to its main source and effect?",opts:["Sulfur dioxide — high engine temperatures — global dimming","Carbon monoxide — incomplete combustion — toxic to humans","Nitrogen oxides — sulfur impurities in fuel — respiratory disease only","Particulates — complete combustion — acid rain"],c:1,e:"CO forms when fuel burns in limited oxygen and is toxic because it binds to haemoglobin. The other rows swap sources around: SO₂ comes from sulfur impurities (not engine heat), NOₓ from nitrogen in air at high temperature, and particulates from incomplete (not complete) combustion."},
  {q:"Exhaust gas tests on the same car show 4.0% carbon monoxide when idling in traffic but 0.5% when cruising on a motorway. What best explains the difference?",opts:["The petrol contains more carbon in traffic","Motorway driving produces no exhaust gases at all","The catalytic converter only works when the car is stationary","At idle the engine draws in less air, so combustion is more incomplete and more CO forms"],c:3,e:"An idling engine runs with a restricted air supply, so the fuel burns incompletely and CO levels rise; at cruising speed more air gives more complete combustion. Catalytic converters actually work better at speed, when they are hot — not when stationary."},
  {q:"A limestone statue in a city centre is wearing away faster than an identical one in the countryside. What is the most likely chemical explanation?",opts:["City air contains more oxygen, which oxidises the stone","City rain is colder, freezing the statue","Acid rain from SO₂ and NOₓ in city air reacts with the calcium carbonate in the limestone","The statue absorbs carbon monoxide and crumbles"],c:2,e:"Urban traffic and industry release SO₂ and NOₓ, which make local rain more acidic; the acids react with calcium carbonate, dissolving the stone surface. Carbon monoxide is toxic to people but does not attack limestone."},
  {q:"The table compares two fuels burned in the same power station: Fuel A contains 2.5% sulfur and Fuel B contains 0.1% sulfur, while both release similar CO₂ per tonne. Which conclusion is best supported?",opts:["Fuel B will cause much less acid rain but a similar contribution to climate change","Fuel B causes no pollution of any kind","Fuel A is better for the environment because it contains more sulfur","Switching to Fuel B would also remove all CO₂ emissions"],c:0,e:"Less sulfur means far less SO₂ and therefore less acid rain, but the near-identical CO₂ figures mean the climate impact is unchanged. Claiming Fuel B causes no pollution ignores its CO₂ and the NOₓ formed from air in any high-temperature furnace."}
]);
