// science-y11-x07.js — Year 11 Science Topic 7: Magnetism & Electromagnetism (expansion pack)
// Adds 3 flashcards and 10 test questions per island for s11i-07-1 .. s11i-07-5.
// Extends the banks defined in t07.js — load after that file.

// ── FLASHCARDS (expansion) ──────────────────────────────────────────────────
FLASHCARDS.push(
  // s11i-07-1 — Magnetic Fields
  {id:"s11fc-07-1-6",islandId:"s11i-07-1",front:"Which materials are magnetic, and what is the difference between steel and soft iron as magnets?",
   back:"Only iron, steel, cobalt and nickel are magnetic.\n\nSteel keeps its magnetism once magnetised, so it is used for permanent magnets.\n\nSoft iron is easily magnetised but loses its magnetism quickly, so it is used for temporary (induced) magnets such as electromagnet cores.",difficulty:1,category:"concept"},
  {id:"s11fc-07-1-7",islandId:"s11i-07-1",front:"How can a plotting compass be used to map the field around a bar magnet?",
   back:"A plotting compass contains a tiny bar magnet that lines up with the field at that point.\n\n1. Place the compass near the north pole and mark where the needle points.\n2. Move the compass so its tail sits on the mark, and mark again.\n3. Repeat and join the marks — this traces one field line.\n4. Start from different positions to build the whole pattern.",difficulty:2,category:"application"},
  {id:"s11fc-07-1-8",islandId:"s11i-07-1",front:"Why does a compass needle point north when no magnets are nearby?",
   back:"The needle is a small bar magnet, so it lines up with the Earth's own magnetic field.\n\nThe fact that compasses behave this way everywhere is evidence that the Earth's core is magnetic and produces a field similar to that of a giant bar magnet.",difficulty:1,category:"concept"},

  // s11i-07-2 — The Motor Effect
  {id:"s11fc-07-2-6",islandId:"s11i-07-2",front:"What is magnetic flux density, and what is its unit?",
   back:"Magnetic flux density (B) measures the strength of a magnetic field — the force acting per ampere of current per metre of wire, when the wire is at right angles to the field.\n\nRearranged from F = BIl:\nB = F / (I x l)\n\nUnit: the tesla (T). 1 T = 1 N per amp per metre.",difficulty:2,category:"calculation"},
  {id:"s11fc-07-2-7",islandId:"s11i-07-2",front:"A wire 0.10 m long sits at right angles to a 0.5 T field and feels a force of 0.2 N. Calculate the current.",
   back:"Rearrange F = BIl to give I = F / (B x l)\n\nI = 0.2 / (0.5 x 0.10) = 0.2 / 0.05 = 4 A\n\nAlways check the wire length is in metres before substituting.",difficulty:3,category:"calculation"},
  {id:"s11fc-07-2-8",islandId:"s11i-07-2",front:"What happens to the force on a current-carrying wire if you reverse the current? What if you reverse both the current and the field?",
   back:"Reversing the current alone reverses the direction of the force.\n\nReversing the field alone also reverses the force.\n\nReversing BOTH the current and the field leaves the force in its original direction — the two reversals cancel out. Check this with Fleming's left-hand rule.",difficulty:2,category:"concept"},

  // s11i-07-3 — Electromagnetic Induction
  {id:"s11fc-07-3-6",islandId:"s11i-07-3",front:"What does the magnetic field of an induced current always do?",
   back:"The induced current creates its own magnetic field, and that field always OPPOSES the change that caused it.\n\nExample: pushing a north pole into a coil makes the near end of the coil become a north pole, repelling the incoming magnet. That is why you must do work to push the magnet in.",difficulty:3,category:"concept"},
  {id:"s11fc-07-3-7",islandId:"s11i-07-3",front:"Describe how the induced potential difference of a rotating generator coil changes during one full turn.",
   back:"The p.d. rises and falls smoothly, reversing direction every half turn.\n\nIt is at a MAXIMUM when the coil sides are cutting field lines at the fastest rate, and ZERO at the instants when the coil sides move parallel to the field lines and cut none.",difficulty:3,category:"concept"},
  {id:"s11fc-07-3-8",islandId:"s11i-07-3",front:"Is a potential difference still induced if the coil is not connected in a complete circuit?",
   back:"Yes. Moving a conductor through a magnetic field (or changing the field around it) always induces a potential difference across it.\n\nA CURRENT, however, only flows if the conductor is part of a complete circuit. No circuit means a p.d. with no current.",difficulty:2,category:"concept"},

  // s11i-07-4 — Transformers
  {id:"s11fc-07-4-6",islandId:"s11i-07-4",front:"Why is a transformer core made from soft iron?",
   back:"Soft iron is very easily magnetised and demagnetised, so it can follow the rapidly changing field produced by the alternating current in the primary coil.\n\nThe core carries this changing magnetic field through the secondary coil, inducing a p.d. there. The two coils are linked magnetically, not electrically.",difficulty:2,category:"concept"},
  {id:"s11fc-07-4-7",islandId:"s11i-07-4",front:"A transformer has 400 primary turns and a primary p.d. of 230 V. The secondary p.d. is 11.5 V. How many turns are on the secondary coil?",
   back:"Vp / Vs = np / ns\n230 / 11.5 = 400 / ns\n20 = 400 / ns\nns = 400 / 20 = 20 turns\n\nA much smaller secondary p.d. needs far fewer secondary turns — this is a step-down transformer.",difficulty:3,category:"calculation"},
  {id:"s11fc-07-4-8",islandId:"s11i-07-4",front:"Why exactly does keeping the current low cut the energy wasted in National Grid cables?",
   back:"The heating power lost in a cable depends on the SQUARE of the current (P = I squared x R).\n\nSo halving the current cuts the wasted power to a quarter, and making the current ten times smaller cuts the waste to one hundredth. That is why voltages are stepped up so high for transmission.",difficulty:3,category:"application"},

  // s11i-07-5 — The Generator Effect: Alternators, Microphones & Loudspeakers
  {id:"s11fc-07-5-6",islandId:"s11i-07-5",front:"How do the oscilloscope traces of an alternator and a dynamo differ?",
   back:"Alternator (a.c.): a smooth wave that swings above AND below zero — the current keeps reversing direction.\n\nDynamo (d.c.): a series of bumps that rise and fall but stay on ONE side of zero — the current varies in size but never reverses.",difficulty:2,category:"concept"},
  {id:"s11fc-07-5-7",islandId:"s11i-07-5",front:"What happens to an alternator's output if the coil is spun faster?",
   back:"Two changes happen at once:\n\n1. The FREQUENCY of the a.c. increases — more complete turns each second.\n2. The PEAK potential difference increases — the coil sides cut field lines at a faster rate, so a larger p.d. is induced.",difficulty:3,category:"concept"},
  {id:"s11fc-07-5-8",islandId:"s11i-07-5",front:"How does an electric guitar pickup use the generator effect?",
   back:"The pickup is a coil wrapped around a small permanent magnet, placed under a steel guitar string.\n\nThe magnet magnetises the string. When the string vibrates, the magnetic field through the coil keeps changing, inducing a varying p.d. in the coil.\n\nThis electrical signal matches the string's vibration and is sent to an amplifier.",difficulty:2,category:"application"}
);

// ── TEST QUESTIONS (expansion) ──────────────────────────────────────────────
QUESTIONS["s11i-07-1"] = (QUESTIONS["s11i-07-1"] || []).concat([
  {q:"Which group of materials can be magnetised?",opts:["Copper, aluminium and zinc","Iron, cobalt and nickel","All metals","Carbon, silicon and sulfur"],c:1,e:"Only iron, steel, cobalt and nickel are magnetic. Many students assume all metals are attracted to magnets, but copper and aluminium are not magnetic at all."},
  {q:"Where is the magnetic field of a bar magnet strongest?",opts:["At the poles","At the centre of the magnet","Halfway along each long side","It is the same strength everywhere"],c:0,e:"The field lines are most concentrated at the poles, so the field is strongest there. It is not uniform — the field weakens rapidly with distance from the poles."},
  {q:"A plotting compass works because its needle is:",opts:["A piece of soft iron with no poles","An electromagnet powered by a tiny cell","A small permanent bar magnet that lines up with the field","A coil of wire carrying a current"],c:2,e:"The needle is a small permanent magnet, so it rotates until it lies along the field direction at that point. It needs no power supply — it is not an electromagnet."},
  {q:"A compass placed far from any magnets still points north. This is evidence that:",opts:["Compass needles always point at the Sun","The needle is attracted to cold air","Geographic north repels south poles","The Earth's core produces a magnetic field"],c:3,e:"With no nearby magnets, the needle must be responding to the Earth's own field, which behaves like that of a huge bar magnet generated in the core. The Sun plays no part in compass behaviour."},
  {q:"What is the shape of the magnetic field around a long straight wire carrying a current?",opts:["Concentric circles around the wire, weaker further away","Straight lines parallel to the wire","Straight lines pointing away from the wire","A uniform field like the inside of a solenoid"],c:0,e:"The field forms circles centred on the wire, and the circles get weaker with distance. Lines parallel to the wire would be the current direction, not the field direction."},
  {q:"What happens to a solenoid's magnetic field when the current direction through it is reversed?",opts:["The field disappears completely","The field doubles in strength","The north and south poles swap ends","Nothing changes"],c:2,e:"Reversing the current reverses the direction of every field line, so the poles swap ends. The field strength is unchanged — it still depends on current size, turns and the core."},
  {q:"Why is soft iron, rather than steel, used as the core of an electromagnet?",opts:["Soft iron is a better electrical conductor","Soft iron loses its magnetism quickly when the current is switched off","Steel cannot be magnetised at all","Soft iron is lighter than steel"],c:1,e:"An electromagnet must switch off cleanly, and soft iron demagnetises almost instantly when the current stops. Steel can certainly be magnetised — the problem is it stays magnetised, which would ruin the on-off control."},
  {q:"Why is an electromagnet, rather than a permanent magnet, used on a scrapyard crane?",opts:["Electromagnets are always weaker, which is safer","Permanent magnets cannot attract iron","Electromagnets do not need a power supply","It can be switched off to release the load"],c:3,e:"The crane must pick up scrap and then drop it on demand, so a magnet that can be switched on and off is essential. Electromagnets are not weaker — large ones are far stronger than any permanent magnet."},
  {q:"A vertical wire carries a current straight upwards. Viewed from above, the magnetic field around it points:",opts:["Anticlockwise in circles around the wire","Clockwise in circles around the wire","Straight up, parallel to the wire","Radially outwards from the wire"],c:0,e:"Using the right-hand grip rule, the thumb points up (with the current) and the fingers curl anticlockwise when viewed from above. A clockwise pattern would be correct only if the current flowed downwards."},
  {q:"On a field diagram, what does it mean when the field lines are drawn closer together?",opts:["The field is changing direction","The field is weaker there","The field is stronger there","The lines are about to cross"],c:2,e:"Line spacing represents strength: closely packed lines mean a strong field, widely spaced lines mean a weak one. Field lines never cross, because the field can only have one direction at any point."}
]);

QUESTIONS["s11i-07-2"] = (QUESTIONS["s11i-07-2"] || []).concat([
  {q:"A wire 0.40 m long carries a current of 2.0 A at right angles to a field of 0.05 T. What is the force on it?",opts:["0.40 N","0.025 N","0.040 N","4.0 N"],c:2,e:"F = BIl = 0.05 x 2.0 x 0.40 = 0.040 N. The answer 0.025 N comes from dividing instead of multiplying — all three quantities multiply together in this equation."},
  {q:"A 0.50 m wire carrying 4.0 A experiences a force of 0.60 N at right angles to a field. What is the magnetic flux density?",opts:["0.30 T","1.2 T","3.3 T","0.12 T"],c:0,e:"Rearranging F = BIl gives B = F / (Il) = 0.60 / (4.0 x 0.50) = 0.60 / 2.0 = 0.30 T. Multiplying everything together to get 1.2 T is the classic error — B must be found by division."},
  {q:"A wire carries 2.0 A at right angles to a 0.30 T field and feels a force of 0.12 N. What length of wire is in the field?",opts:["0.072 m","0.60 m","5.0 m","0.20 m"],c:3,e:"l = F / (BI) = 0.12 / (0.30 x 2.0) = 0.12 / 0.60 = 0.20 m. Dividing the wrong way round gives 5.0 m, which should fail a common-sense check for a wire between two small magnets."},
  {q:"A horizontal wire carries a current towards the east. The magnetic field points horizontally towards the south. Using Fleming's left-hand rule, the force on the wire acts:",opts:["Vertically upwards","Vertically downwards","Towards the north","Towards the east"],c:1,e:"First finger points south (field), second finger points east (current), so the thumb points vertically downwards. The force is always perpendicular to both the field and the current — it can never point along the current direction."},
  {q:"Both the current direction AND the magnetic field direction in a motor-effect experiment are reversed. What happens to the force on the wire?",opts:["The force reverses direction","The force becomes zero","The force doubles","The force stays in the same direction"],c:3,e:"Each reversal on its own flips the force, so two reversals together cancel out and the force keeps its original direction. The force certainly does not vanish — current still flows across a field."},
  {q:"Magnetic flux density is measured in:",opts:["Tesla","Newtons","Joules","Amperes"],c:0,e:"Flux density B is measured in tesla (T); one tesla gives one newton of force on each metre of wire carrying one ampere. Newtons measure the force itself, not the field strength."},
  {q:"The motor effect happens because:",opts:["The wire becomes a permanent magnet","The field of the current-carrying wire interacts with the magnet's field","The wire heats up and expands","Electrons are attracted to the north pole"],c:1,e:"The wire's own circular field interacts with the external field, producing a force on the wire. The wire does not become a permanent magnet, and heating is a separate effect that has nothing to do with the force."},
  {q:"In a DC motor, the two long sides of the coil are pushed in opposite directions because:",opts:["They are different lengths","They are at different temperatures","The current flows through them in opposite directions","One side is outside the magnetic field"],c:2,e:"Current flows up one side of the loop and down the other, so Fleming's left-hand rule gives oppositely directed forces — a turning effect. Both sides sit in the same field; it is the current direction that differs."},
  {q:"The current in a wire is doubled and the length of wire in the field is halved. The force on the wire:",opts:["Stays the same","Doubles","Halves","Becomes four times larger"],c:0,e:"F = BIl, so doubling I multiplies the force by 2 and halving l multiplies it by a half — the two changes cancel exactly. Students often consider only one change and answer that the force doubles."},
  {q:"Which change has NO effect on the size of the force on a current-carrying wire in a magnetic field?",opts:["Doubling the current","Using a thicker wire of the same length carrying the same current","Doubling the magnetic flux density","Doubling the length of wire in the field"],c:1,e:"F = BIl contains only flux density, current and length — wire thickness does not appear, so a fatter wire carrying the same current feels the same force. The other three options each double the force."}
]);

QUESTIONS["s11i-07-3"] = (QUESTIONS["s11i-07-3"] || []).concat([
  {q:"A transformer has 50 primary turns and 200 secondary turns. The primary p.d. is 10 V. What is the secondary p.d.?",opts:["2.5 V","4 V","40 V","80 V"],c:2,e:"Vp/Vs = Np/Ns, so 10/Vs = 50/200 and Vs = 10 x 4 = 40 V. The answer 2.5 V comes from using the turns ratio upside down — more secondary turns must give a larger secondary p.d."},
  {q:"A transformer with 1200 primary turns and 60 secondary turns has a primary p.d. of 240 V. What is the secondary p.d.?",opts:["12 V","20 V","4800 V","48 V"],c:0,e:"Vs = Vp x (Ns/Np) = 240 x (60/1200) = 240 x 0.05 = 12 V. A value of 4800 V comes from inverting the ratio — far fewer secondary turns means the p.d. must drop, not rise."},
  {q:"A magnet is pushed into a coil at twice the original speed. The induced potential difference:",opts:["Stays the same","Halves","Approximately doubles","Drops to zero"],c:2,e:"The size of the induced p.d. depends on how quickly the field through the coil changes; moving twice as fast roughly doubles that rate and so roughly doubles the p.d. The p.d. only stays the same if the rate of change is unchanged."},
  {q:"A magnet is pushed into a coil, then pulled back out at the same speed. Compared with pushing in, the induced current while pulling out:",opts:["Is twice as large in the same direction","Flows in the opposite direction","Is zero","Is the same in every way"],c:1,e:"Reversing the direction of movement reverses the direction of the induced current; the size is similar because the speed is the same. There is definitely still a current — the field through the coil is changing."},
  {q:"The magnetic field created by an induced current always:",opts:["Points north","Strengthens the change that caused it","Has no direction","Opposes the change that caused it"],c:3,e:"The induced current sets up a field that opposes the original change — pushing a north pole towards a coil makes the near face of the coil a north pole, repelling it. If it strengthened the change instead, the magnet would accelerate for free, breaking energy conservation."},
  {q:"An alternator produces a p.d. that reverses every half turn because:",opts:["Each side of the coil moves up past one pole and then down past it on the next half turn","The slip rings swap the connections every half turn","The magnetic field switches off twice per rotation","The coil changes length as it spins"],c:0,e:"As the coil rotates, each side cuts the field lines first one way then the other, so the induced p.d. reverses each half turn. Slip rings do NOT swap connections — that is exactly why the reversals pass through to the output as a.c."},
  {q:"A wire is moved through a magnetic field, but it is not connected to anything. What is induced?",opts:["A current but no potential difference","Nothing at all","A potential difference but no current","Both a large current and a large p.d."],c:2,e:"Cutting field lines always induces a p.d. across the wire, but a current can only flow around a complete circuit. Saying nothing is induced confuses the cause (the p.d.) with the effect that needs a circuit (the current)."},
  {q:"Which of these devices works using the generator effect?",opts:["An electric kettle","An electric motor","A filament lamp","A bicycle dynamo"],c:3,e:"A dynamo spins a magnet (or coil) so the changing field induces a p.d. that powers the bicycle's lights — the generator effect in action. An electric motor is the reverse process: it uses the motor effect to turn current into movement."},
  {q:"A 100% efficient transformer has a primary p.d. of 400 V, a primary current of 0.5 A and a secondary p.d. of 20 V. What is the secondary current?",opts:["0.025 A","2.5 A","10 A","100 A"],c:2,e:"Power is conserved: Vp x Ip = Vs x Is, so 400 x 0.5 = 200 W and Is = 200/20 = 10 A. The answer 0.025 A comes from scaling the current down with the voltage — in fact stepping the voltage down steps the current up."},
  {q:"A wire is moved so that it travels exactly parallel to the magnetic field lines. The induced p.d. is:",opts:["Zero, because no field lines are cut","At its maximum value","Equal to the field strength","Constantly reversing"],c:0,e:"Induction needs the conductor to cut across field lines; sliding along them changes nothing, so no p.d. is induced. Maximum p.d. happens in the perpendicular case, when lines are cut at the greatest rate."}
]);

QUESTIONS["s11i-07-4"] = (QUESTIONS["s11i-07-4"] || []).concat([
  {q:"A transformer has 60 primary turns and 1800 secondary turns. The primary p.d. is 8 V. What is the secondary p.d.?",opts:["0.27 V","240 V","8 V","30 V"],c:1,e:"Vs = Vp x (ns/np) = 8 x (1800/60) = 8 x 30 = 240 V. Getting 0.27 V means the turns ratio was inverted — with thirty times more secondary turns the p.d. must be stepped up, not down."},
  {q:"A transformer must step 12 V up to 120 V. The primary coil has 80 turns. How many turns does the secondary coil need?",opts:["8 turns","80 turns","800 turns","8000 turns"],c:2,e:"The p.d. increases tenfold, so the secondary needs ten times the turns: ns = 80 x (120/12) = 800 turns. Choosing 8 turns applies the ratio the wrong way and would step the voltage down instead."},
  {q:"A 100% efficient transformer has a primary p.d. of 230 V carrying 0.1 A, and a secondary p.d. of 11.5 V. What is the secondary current?",opts:["0.005 A","2.0 A","20 A","0.05 A"],c:1,e:"Vp x Ip = Vs x Is, so 230 x 0.1 = 23 W and Is = 23/11.5 = 2.0 A. The answer 0.005 A scales the current down along with the voltage, but power conservation means a lower voltage forces a higher current."},
  {q:"A National Grid transformer steps 25 000 V up to 400 000 V. Its primary coil has 500 turns. How many turns are on the secondary?",opts:["8000 turns","31 turns","500 turns","16 turns"],c:0,e:"The voltage rises by a factor of 400 000/25 000 = 16, so ns = 500 x 16 = 8000 turns. Choosing 31 turns divides by 16 instead of multiplying — a step-up transformer always has more secondary turns."},
  {q:"The core of a transformer is made of soft iron because soft iron:",opts:["Is a poor conductor of heat","Conducts the current between the two coils","Stays permanently magnetised","Is easily magnetised and demagnetised, carrying the changing field to the secondary coil"],c:3,e:"The core must follow the rapidly alternating field of the primary and deliver it through the secondary, which needs a material that magnetises and demagnetises easily. The core does not conduct current between the coils — they are linked magnetically, not electrically."},
  {q:"A transformer has exactly the same number of turns on its primary and secondary coils. With a 50 V a.c. input, the output is:",opts:["0 V","100 V","50 V a.c.","25 V"],c:2,e:"Equal turns means a 1:1 ratio, so the output p.d. equals the input p.d. Such isolation transformers are used for safety. The output is not zero — induction still happens because the input is a.c."},
  {q:"Where in the National Grid would you find a step-down transformer?",opts:["At a substation near homes, lowering the voltage to a safe level","At the power station, raising the voltage for transmission","Inside the transmission cables themselves","There are no step-down transformers in the Grid"],c:0,e:"Step-down transformers sit in substations near consumers, reducing the very high transmission voltage to the 230 V used in homes. The transformer at the power station end is a step-up transformer."},
  {q:"A battery (d.c.) is connected to a transformer's primary coil. What appears at the secondary coil?",opts:["A steady d.c. output","A steady a.c. output","A larger d.c. voltage than the input","A brief pulse of p.d. only at the moments of switching on or off"],c:3,e:"While the d.c. flows steadily the field is constant, so nothing is induced; only when switching on or off does the field change, giving a momentary pulse. A continuous output of any kind needs a continuously changing field, which d.c. cannot provide."},
  {q:"If the current in a transmission cable is doubled, the power wasted as heat in the cable:",opts:["Doubles","Becomes four times larger","Halves","Stays the same"],c:1,e:"Heating power depends on the square of the current (P = I x I x R), so doubling the current quadruples the waste. Thinking it merely doubles ignores the squared relationship — this is exactly why the Grid keeps currents as low as possible."},
  {q:"In a step-up transformer that is 100% efficient, the current in the secondary coil is:",opts:["Larger than the primary current","Equal to the primary current","Smaller than the primary current","Zero"],c:2,e:"Power in equals power out, so if the voltage is stepped up the current must be stepped down by the same factor. Assuming the current rises along with the voltage would mean the transformer creates power from nothing."}
]);

QUESTIONS["s11i-07-5"] = (QUESTIONS["s11i-07-5"] || []).concat([
  {q:"An alternator coil is spun twice as fast. What happens to its output?",opts:["Only the frequency increases","Only the peak p.d. increases","Both the frequency and the peak p.d. increase","The output becomes d.c."],c:2,e:"Faster rotation means more cycles per second (higher frequency) AND field lines cut at a greater rate (larger peak p.d.) — both change together. Answering frequency only misses that the rate of cutting field lines also sets the size of the p.d."},
  {q:"On an oscilloscope, the output of a dynamo appears as:",opts:["A smooth wave swinging above and below zero","A series of bumps that stay on one side of zero","A perfectly flat horizontal line","A vertical line"],c:1,e:"The split-ring commutator stops the output reversing, so the trace rises and falls but never crosses zero — varying d.c. A wave that swings above and below zero is the a.c. output of an alternator using slip rings."},
  {q:"To make a loudspeaker produce a LOUDER sound, the electrical signal should have:",opts:["A larger amplitude of current","A higher frequency","A lower frequency","A steady d.c. value"],c:0,e:"A larger current gives a larger force on the coil, so the cone vibrates with a bigger amplitude and the sound is louder. Changing the frequency alters the pitch, not the loudness."},
  {q:"Increasing the frequency of the alternating current supplied to a loudspeaker makes the sound:",opts:["Louder","Quieter","Stop completely","Higher in pitch"],c:3,e:"The cone vibrates at the frequency of the a.c., and a faster vibration is heard as a higher pitch. Loudness is controlled by the amplitude of the current, not its frequency."},
  {q:"A person speaks more loudly into a moving-coil microphone. The induced p.d. across the coil:",opts:["Stays exactly the same","Has a larger amplitude","Becomes a steady d.c. value","Drops to zero"],c:1,e:"Louder sound means bigger pressure variations, so the diaphragm and coil move further and faster, inducing a larger p.d. The output is never steady d.c. — it must vary to represent the sound wave."},
  {q:"In a moving-coil microphone, which part is moved directly by the sound waves?",opts:["The permanent magnet","The output wires","The diaphragm, with the coil attached to it","The iron core of an electromagnet"],c:2,e:"Sound pressure variations push the lightweight diaphragm back and forth, carrying the coil with it through the magnetic field. The magnet stays fixed — it is the coil that must move for a p.d. to be induced."},
  {q:"Why must the current supplied to a loudspeaker be alternating rather than steady?",opts:["The force on the coil must keep reversing so the cone vibrates back and forth","Steady current would melt the coil instantly","Alternating current is cheaper","The magnet only works with a.c."],c:0,e:"Sound needs the cone to oscillate, which requires a force that keeps changing direction — only a reversing (alternating) current does that. A steady current would just hold the cone in one displaced position, producing silence."},
  {q:"At which moment during its rotation is an alternator's induced p.d. exactly zero?",opts:["When the coil sides pass closest to the poles","Never — it is always at its maximum","When the current is largest","When the coil sides are moving parallel to the field lines"],c:3,e:"Moving parallel to the field lines means no lines are being cut, so for that instant the induced p.d. is zero — the trace crosses zero twice per rotation. It is not always at maximum; the output continuously rises and falls."},
  {q:"The current through a loudspeaker coil reverses direction. The force on the coil:",opts:["Stays in the same direction","Reverses direction","Becomes zero","Doubles"],c:1,e:"By Fleming's left-hand rule, reversing the current while the field stays the same reverses the force — this is what drives the cone outwards then inwards. The force does not vanish; current is still flowing across the magnetic field."},
  {q:"An electric guitar pickup generates a signal when a steel string vibrates because:",opts:["The string completes an electrical circuit with the coil","The string rubs against the coil, creating static charge","The vibrating magnetised string changes the field through the coil, inducing a p.d.","The pickup sends current into the string using the motor effect"],c:2,e:"The pickup's magnet magnetises the steel string; as the string vibrates, the field through the coil changes and a varying p.d. is induced — the generator effect. The string never touches the coil and carries no current itself."}
]);
