// science-y11-x08.js — Year 11 Science Topic 8: Space Physics (expansion pack)
// Islands: s11i-08-1 .. s11i-08-2
// Adds 3 new flashcards and 10 new test questions per island.
// Flashcard ids continue from the highest existing number in t08.js.

// ── FLASHCARDS (new) ─────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s11i-08-1 — The Solar System & Orbits
  {id:"s11fc-08-1-6",islandId:"s11i-08-1",front:"A satellite moves in a circular orbit at constant speed. Why is it still accelerating?",
   back:"Velocity is a vector: it has both size and direction.\n\nIn a circular orbit the direction of motion changes continuously, so the velocity is changing even though the speed stays the same.\n\nA changing velocity means an acceleration — here it is directed towards the centre of the orbit, caused by gravity.",difficulty:3,category:"concept"},
  {id:"s11fc-08-1-7",islandId:"s11i-08-1",front:"Describe the orbit of a comet and how its speed changes around the orbit.",
   back:"Comets follow highly elliptical (stretched) orbits around the Sun.\n\nA comet travels fastest when it is closest to the Sun, where the gravitational pull is strongest, and slowest at the far end of its orbit.\n\nThis contrasts with planets, whose orbits are only slightly elliptical so their speed barely changes.",difficulty:2,category:"concept"},
  {id:"s11fc-08-1-8",islandId:"s11i-08-1",front:"What must happen to a satellite's speed if it moves to an orbit with a smaller radius?",
   back:"Its speed must increase.\n\nFor a stable circular orbit, each orbital radius requires one particular speed. Closer in, gravity is stronger, so a higher speed is needed to keep the orbit stable.\n\nIf the speed of an orbiting body changes, the radius of its orbit must also change.",difficulty:3,category:"concept"},

  // s11i-08-2 — Life Cycle of Stars
  {id:"s11fc-08-2-6",islandId:"s11i-08-2",front:"What keeps a main sequence star stable for billions of years?",
   back:"A balance of two effects:\n\n1. Gravity pulling the star's material inwards.\n2. The outward pressure produced by the energy released from nuclear fusion in the core.\n\nWhile these are balanced, the star stays the same size — this is called equilibrium. The Sun is currently in this stable main sequence stage.",difficulty:2,category:"concept"},
  {id:"s11fc-08-2-7",islandId:"s11i-08-2",front:"What is a neutron star?",
   back:"The collapsed core left behind after a supernova, when the remnant is not massive enough to form a black hole.\n\nIt is incredibly dense — roughly the mass of the Sun squeezed into a sphere only a few kilometres across. A teaspoon of neutron star material would have a mass of billions of tonnes.",difficulty:2,category:"definition"},
  {id:"s11fc-08-2-8",islandId:"s11i-08-2",front:"How does the red shift of a galaxy depend on its distance from us?",
   back:"The further away a galaxy is, the greater its red shift.\n\nGreater red shift means the galaxy is receding faster, so the most distant galaxies are moving away most quickly.\n\nThis pattern is exactly what you would expect if all of space is expanding, and it points back to a single starting point — the Big Bang.",difficulty:3,category:"concept"}
);

// ── TEST QUESTIONS (new) ──────────────────────────────────────────────────────
QUESTIONS["s11i-08-1"] = (QUESTIONS["s11i-08-1"] || []).concat([
  {q:"The Sun is one star among billions in which galaxy?",opts:["The Milky Way","Andromeda","The Solar System","Orion"],c:0,e:"The Sun belongs to the Milky Way galaxy, which contains billions of stars. The Solar System is not a galaxy — it is just the Sun and the objects orbiting it, a tiny part of the Milky Way."},
  {q:"Which statement best describes a moon?",opts:["A small planet that orbits the Sun","A natural satellite that orbits a planet","Any rocky object in the asteroid belt","An artificial object placed in orbit"],c:1,e:"A moon is a natural satellite of a planet — Earth has one, while Jupiter has dozens. A small body orbiting the Sun directly would be a dwarf planet or asteroid, not a moon."},
  {q:"In which direction does the gravitational force act on a planet in a circular orbit?",opts:["In the direction the planet is moving","Outwards, away from the Sun","Towards the centre of the orbit","Opposite to the planet's motion"],c:2,e:"Gravity always pulls the planet towards the Sun at the centre of its orbit, acting as a centripetal force. There is no outward force in orbit — the feeling of being 'flung outwards' is a common misconception."},
  {q:"How do the orbits of comets differ from the orbits of planets?",opts:["Comets have highly elliptical orbits","Comets orbit planets rather than the Sun","Comets travel in perfectly circular orbits","Comets do not orbit anything"],c:0,e:"Comets follow very stretched, elliptical paths, swinging close to the Sun and then far out into the Solar System. Planets also have elliptical orbits, but theirs are very nearly circular — and comets orbit the Sun, not planets."},
  {q:"Where is the main asteroid belt found?",opts:["Between Earth and Mars","Beyond Neptune","Between the Sun and Mercury","Between Mars and Jupiter"],c:3,e:"The asteroid belt lies between the orbits of Mars and Jupiter, separating the rocky planets from the gas giants. The region beyond Neptune contains icy bodies such as Pluto, not the main asteroid belt."},
  {q:"How do the four outer planets differ from the four inner planets?",opts:["They are smaller and rocky","They orbit the Sun more quickly","They are large and made mostly of gas and ice","They are hotter because they are larger"],c:2,e:"Jupiter, Saturn, Uranus and Neptune are giant planets made mostly of gas and ice, unlike the small rocky inner planets. Being further from the Sun, the outer planets actually orbit more slowly and are colder, not hotter."},
  {q:"A satellite is moved from a low orbit to a much higher orbit around Earth. What happens to its orbital speed and orbital period?",opts:["Speed increases; period decreases","Speed decreases; period increases","Both speed and period decrease","Speed stays the same; period increases"],c:1,e:"At a larger radius, gravity is weaker, so a lower speed is needed for a stable orbit — and the satellite also has further to travel, so its period increases. It is tempting to think a 'higher' satellite must move faster, but the opposite is true."},
  {q:"A satellite orbits Earth in a circle at a steady 7 km/s. Which quantity is changing?",opts:["Its velocity","Its speed","Its mass","Its distance from Earth"],c:0,e:"Velocity includes direction, and in a circular orbit the direction of motion changes continuously, so the velocity changes even though the speed is constant. The distance from Earth stays fixed in a circular orbit, so that option is wrong."},
  {q:"For a satellite to remain in a stable circular orbit closer to Earth, its speed must be:",opts:["Lower, because there is less distance to cover","Zero, so gravity can hold it in place","The same at every radius","Higher, because gravity is stronger closer in"],c:3,e:"Each orbital radius has one particular speed for a stable circular orbit, and smaller radii need higher speeds to balance the stronger gravitational pull. A stationary satellite would simply fall straight down — gravity cannot 'hold' a motionless object in orbit."},
  {q:"A comet is observed at two points in its orbit: point X close to the Sun and point Y far from the Sun. Compare its speed at the two points.",opts:["Faster at Y, because it has had longer to speed up","The same at both, because orbits have constant speed","Faster at X, because the Sun's gravitational pull is stronger there","Slower at X, because it is about to turn around"],c:2,e:"As the comet falls towards the Sun it gains speed, moving fastest at closest approach where gravity is strongest; it slows as it climbs away again. Constant speed only applies to circular orbits — a comet's orbit is highly elliptical, so its speed varies a great deal."}
]);

QUESTIONS["s11i-08-2"] = (QUESTIONS["s11i-08-2"] || []).concat([
  {q:"What two effects are balanced in a stable main sequence star?",opts:["Magnetism and friction","Inward gravity and outward pressure from fusion","Air pressure and weight","Electrostatic attraction and repulsion"],c:1,e:"A main sequence star is in equilibrium: gravity pulls material inwards while the energy released by fusion creates an outward pressure. There is no air in a star, so 'air pressure' is not the right idea, even though it sounds similar."},
  {q:"Which nuclear process releases energy in a main sequence star?",opts:["Fission of uranium nuclei","Radioactive decay","Chemical burning of hydrogen gas","Fusion of hydrogen nuclei into helium"],c:3,e:"Main sequence stars fuse hydrogen nuclei together to form helium, releasing enormous amounts of energy. Stars do not 'burn' in the chemical sense — that is combustion, which needs oxygen and releases far less energy than fusion."},
  {q:"What causes a nebula to begin collapsing into a protostar?",opts:["Gravity pulling the dust and gas together","Fusion reactions in the cloud","Pressure from nearby planets","The cloud cooling and shrinking"],c:0,e:"Gravity acts between all the particles of dust and gas, slowly drawing them together; as the cloud collapses it heats up, forming a protostar. Fusion has not started yet at this stage — it only begins once the core becomes hot and dense enough."},
  {q:"What will be the final fate of the Sun?",opts:["It will explode as a supernova","It will collapse into a black hole","It will become a white dwarf that cools over time","It will become a neutron star"],c:2,e:"The Sun is not massive enough for a supernova: it will swell into a red giant, shed its outer layers and leave a white dwarf that eventually cools towards a black dwarf. Supernovae, neutron stars and black holes are reserved for much more massive stars."},
  {q:"What is a black dwarf?",opts:["A small black hole","A white dwarf that has cooled so much it no longer emits light","A star that failed to ignite","A planet made of dark rock"],c:1,e:"A black dwarf is the end point of a Sun-sized star: a white dwarf that has radiated away its remaining energy and gone dark. It is completely different from a black hole, which forms from the collapsed core of a far more massive star."},
  {q:"In which stage of its life is the Sun right now?",opts:["Red giant","Protostar","White dwarf","Main sequence"],c:3,e:"The Sun has been steadily fusing hydrogen into helium for about 4.6 billion years, which places it in the stable main sequence stage. It will not become a red giant for several billion years yet."},
  {q:"Which sequence shows the correct final stages for a star much more massive than the Sun?",opts:["Red giant → white dwarf → black dwarf","Red supergiant → supernova → neutron star or black hole","Supernova → red supergiant → neutron star","Main sequence → supernova → red supergiant"],c:1,e:"A massive star expands into a red supergiant, then explodes as a supernova, leaving either a neutron star or a black hole depending on the mass of the remaining core. The red giant to white dwarf path belongs to Sun-sized stars, and the supernova always comes after the supergiant stage, not before."},
  {q:"Galaxy A shows a greater red shift than galaxy B. What can be concluded?",opts:["Galaxy A is receding faster and is probably further away","Galaxy A is hotter than galaxy B","Galaxy A is moving towards us","Galaxy A emits redder light than galaxy B"],c:0,e:"Greater red shift means a galaxy is moving away from us more quickly, and observations show the fastest-receding galaxies are the most distant ones. Red shift is a stretching of the wavelengths we receive — it does not mean the galaxy's light is genuinely red, nor does it tell us about temperature."},
  {q:"If the light from a galaxy were found to be shifted towards the blue end of the spectrum, what would this show?",opts:["The galaxy is spinning rapidly","The universe has stopped expanding everywhere","The galaxy is very hot","The galaxy is moving towards us"],c:3,e:"A blue shift means the wavelengths have been compressed, which happens when a source moves towards the observer — Andromeda shows this because it is approaching the Milky Way. One nearby approaching galaxy does not contradict the overall expansion of the universe, so the universe has not 'stopped expanding'."},
  {q:"Why did the discovery of cosmic microwave background radiation strengthen the Big Bang theory?",opts:["It proved that galaxies emit microwaves","It showed that the universe is contracting","The Big Bang theory had predicted such leftover radiation, and rival theories could not explain it","It allowed astronomers to measure red shift more accurately"],c:2,e:"The Big Bang model predicted that radiation from the hot early universe should still fill space today, stretched into microwaves — and the CMBR matched this prediction, while competing ideas such as the Steady State theory could not account for it. CMBR is detected coming from all directions in space, not just from galaxies."}
]);
