// science-y11-x09.js — Year 11 Science Topic 9 expansion: Newton's Laws & Momentum (extra flashcards and test questions for islands s11i-09-1 .. s11i-09-5)

// ── EXTRA FLASHCARDS ─────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s11i-09-1 — Newton's Three Laws
  {id:"s11fc-09-1-6",islandId:"s11i-09-1",front:"A resultant force of 90 N gives a trolley an acceleration of 1.5 m/s². Calculate the mass of the trolley.",
   back:"F = ma, rearranged: m = F ÷ a\nm = 90 ÷ 1.5 = 60 kg\n\nCheck your rearrangement: mass is force divided by acceleration, not the other way round.",difficulty:2,category:"calculation"},
  {id:"s11fc-09-1-7",islandId:"s11i-09-1",front:"What is inertial mass? (Higher Tier)",
   back:"Inertial mass is a measure of how difficult it is to change an object's velocity.\n\nIt is defined as the ratio of force to acceleration:\nm = F ÷ a\n\nAn object with a large inertial mass needs a large force to produce a given acceleration.",difficulty:3,category:"definition"},
  {id:"s11fc-09-1-8",islandId:"s11i-09-1",front:"Use Newton's third law to explain how a rocket accelerates upwards.",
   back:"The rocket engine pushes exhaust gases downwards with a large force.\n\nBy Newton's third law, the gases push back on the rocket with an equal force in the opposite direction — upwards.\n\nIf this upward force is greater than the rocket's weight, there is a resultant upward force and the rocket accelerates.",difficulty:3,category:"application"},

  // s11i-09-2 — Momentum & Conservation
  {id:"s11fc-09-2-6",islandId:"s11i-09-2",front:"State the equation linking force, change in momentum and time. (Higher Tier)",
   back:"Force equals the rate of change of momentum:\n\nF = Δp ÷ Δt\n\nF = force (N)\nΔp = change in momentum (kg m/s)\nΔt = time taken for the change (s)\n\nA momentum change spread over a longer time produces a smaller force.",difficulty:3,category:"calculation"},
  {id:"s11fc-09-2-7",islandId:"s11i-09-2",front:"A trolley has a momentum of 36 kg m/s and a mass of 4 kg. Calculate its velocity.",
   back:"p = mv, rearranged: v = p ÷ m\nv = 36 ÷ 4 = 9 m/s\n\nVelocity is momentum divided by mass.",difficulty:2,category:"calculation"},
  {id:"s11fc-09-2-8",islandId:"s11i-09-2",front:"Use conservation of momentum to explain why a cannon recoils when it fires.",
   back:"Before firing, the total momentum of cannon plus cannonball is zero.\n\nWhen fired, the ball gains forward momentum, so the cannon must gain an equal amount of backward momentum to keep the total at zero.\n\nBecause the cannon has a much larger mass, its recoil velocity is much smaller than the ball's velocity.",difficulty:3,category:"application"},

  // s11i-09-3 — Stopping Distances & Safety
  {id:"s11fc-09-3-6",islandId:"s11i-09-3",front:"What is a typical human reaction time, and how can it be measured?",
   back:"A typical reaction time is between 0.2 s and 0.9 s.\n\nIt can be measured with the ruler drop test: a partner drops a ruler between your fingers without warning, and the distance it falls before you catch it is converted into a reaction time.\n\nComputer-based click tests can also be used.",difficulty:1,category:"fact"},
  {id:"s11fc-09-3-7",islandId:"s11i-09-3",front:"A car travels at 15 m/s. The driver's reaction time is 0.7 s. Calculate the thinking distance.",
   back:"During the reaction time the car travels at a steady speed, so use:\ndistance = speed × time\n\nthinking distance = 15 × 0.7 = 10.5 m\n\nThe car covers 10.5 m before the driver even touches the brakes.",difficulty:2,category:"calculation"},
  {id:"s11fc-09-3-8",islandId:"s11i-09-3",front:"Explain how an airbag protects a driver in a collision.",
   back:"The airbag inflates and cushions the driver's head and chest.\n\nIt increases the time taken for the driver to come to rest. Since force = change in momentum ÷ time, a longer stopping time means a smaller force on the body.\n\nIt also spreads the force over a larger area, reducing pressure on any one part of the body.",difficulty:2,category:"concept"},

  // s11i-09-4 — Acceleration & Velocity-Time Graphs
  {id:"s11fc-09-4-6",islandId:"s11i-09-4",front:"What is the acceleration of an object in free fall near the Earth's surface?",
   back:"About 9.8 m/s², directed downwards.\n\nThis means a freely falling object gains roughly 9.8 m/s of speed every second (ignoring air resistance).\n\nAll objects in free fall have this same acceleration, whatever their mass.",difficulty:1,category:"fact"},
  {id:"s11fc-09-4-7",islandId:"s11i-09-4",front:"A train travels at a constant 12 m/s for 5 s, then decelerates uniformly to rest in 4 s. Use the velocity-time graph to find the total distance.",
   back:"Distance = area under the velocity-time graph.\n\nRectangle (constant speed): 12 × 5 = 60 m\nTriangle (deceleration): ½ × 4 × 12 = 24 m\n\nTotal distance = 60 + 24 = 84 m",difficulty:3,category:"calculation"},
  {id:"s11fc-09-4-8",islandId:"s11i-09-4",front:"A van slows from 28 m/s to 10 m/s in 4.5 s. Calculate its acceleration.",
   back:"a = Δv ÷ t\nΔv = 10 − 28 = −18 m/s\na = −18 ÷ 4.5 = −4 m/s²\n\nThe negative sign shows the van is decelerating at 4 m/s².",difficulty:2,category:"calculation"},

  // s11i-09-5 — Terminal Velocity
  {id:"s11fc-09-5-6",islandId:"s11i-09-5",front:"Why does a feather reach a much lower terminal velocity than a stone?",
   back:"The feather has a very small weight and a large surface area for its mass.\n\nAir resistance grows with speed, so the feather only needs a low speed before drag balances its tiny weight — giving a low terminal velocity.\n\nThe stone's much larger weight needs far more drag to balance it, which only happens at a much higher speed.",difficulty:2,category:"application"},
  {id:"s11fc-09-5-7",islandId:"s11i-09-5",front:"During a fall through air, which force on the object changes and which stays the same?",
   back:"WEIGHT stays the same throughout the fall — it is mass × gravitational field strength, and neither changes.\n\nAIR RESISTANCE changes — it increases as the object speeds up.\n\nIt is the growing air resistance, not a changing weight, that eventually balances the forces.",difficulty:2,category:"concept"},
  {id:"s11fc-09-5-8",islandId:"s11i-09-5",front:"What happens to an object falling in a vacuum, where there is no air?",
   back:"With no air there is no air resistance, so the only force is weight.\n\nThe object never reaches terminal velocity — it keeps accelerating at about 9.8 m/s² for the whole fall.\n\nIn a vacuum, a hammer and a feather dropped together hit the ground at the same time.",difficulty:2,category:"concept"}
);

// ── EXTRA TEST QUESTIONS ─────────────────────────────────────────────────────
QUESTIONS["s11i-09-1"] = (QUESTIONS["s11i-09-1"] || []).concat([
  {q:"A resultant force of 150 N accelerates a crate at 5 m/s². What is the mass of the crate?",opts:["750 kg","30 kg","0.03 kg","155 kg"],c:1,e:"Rearrange F = ma to give m = F ÷ a = 150 ÷ 5 = 30 kg. Multiplying instead of dividing gives the wrong answer of 750 kg."},
  {q:"A book rests on a table. The table pushes up on the book. What is the Newton's third-law partner of this force?",opts:["The weight of the book","The book pushing down on the table","Gravity pulling on the table","Friction between the book and table"],c:1,e:"A third-law pair is the same type of force, reversed between the two objects: the table pushes the book up, so the book pushes the table down. The book's weight is a gravitational force, so it cannot be the pair of a contact force."},
  {q:"An ice hockey puck slides across smooth ice at a steady speed. Why does it keep moving without being pushed?",opts:["The ice gives it energy","A force is stored inside the puck","No resultant force is needed to keep an object moving at constant velocity","Gravity pushes it forwards"],c:2,e:"By Newton's first law, motion at constant velocity needs no resultant force — forces are only needed to change motion. The common error is thinking a continuous force is needed just to keep something moving."},
  {q:"The resultant force on an object is doubled while its mass stays the same. The acceleration will:",opts:["Stay the same","Halve","Quadruple","Double"],c:3,e:"From a = F ÷ m, acceleration is directly proportional to force when mass is constant, so doubling the force doubles the acceleration. It would only quadruple if force appeared squared in the equation, which it does not."},
  {q:"Two trolleys are pushed with the same force. Trolley B has half the mass of trolley A. Compared with A, trolley B's acceleration is:",opts:["Twice as large","Half as large","The same","Four times as large"],c:0,e:"a = F ÷ m, so for the same force, halving the mass doubles the acceleration. Do not invert this: smaller mass means larger acceleration, not smaller."},
  {q:"A 900 kg car slows from 20 m/s to rest in 4 s. What braking force acted on it?",opts:["180 N","45 000 N","4500 N","720 N"],c:2,e:"First find the deceleration: a = Δv ÷ t = 20 ÷ 4 = 5 m/s². Then F = ma = 900 × 5 = 4500 N. Multiplying mass by the velocity instead of the acceleration gives the tempting wrong answer 18 000 N or similar."},
  {q:"A bus brakes suddenly and the standing passengers lurch forwards. This is best explained by:",opts:["Newton's third law","The passengers' inertia — they continue moving while the bus slows","A forward force pushing the passengers","The brakes pushing the passengers forwards"],c:1,e:"By Newton's first law, the passengers' bodies keep moving at the original speed until a force (the floor, a handrail) slows them. No forward force acts on them — it only feels that way because the bus slows around them."},
  {q:"A jet engine pushes exhaust gases backwards. What pushes the aircraft forwards?",opts:["The exhaust gases pushing back on the engine","The surrounding air rushing in behind it","The pilot increasing the weight","The runway pushing on the wheels"],c:0,e:"Newton's third law: the engine exerts a backward force on the gases, so the gases exert an equal forward force on the engine. The aircraft does not need air behind it to push against — rockets work in space for the same reason."},
  {q:"A hockey stick applies a resultant force of 8 N to a 0.16 kg ball. What is the ball's acceleration?",opts:["1.28 m/s²","0.02 m/s²","8.16 m/s²","50 m/s²"],c:3,e:"a = F ÷ m = 8 ÷ 0.16 = 50 m/s². Multiplying 8 by 0.16 gives 1.28 — a common slip when the mass is less than 1 kg."},
  {q:"A 100 kg motorbike has a 500 N driving force and 200 N of total resistive force. What is its acceleration?",opts:["5 m/s²","3 m/s²","2 m/s²","7 m/s²"],c:1,e:"Use the RESULTANT force: 500 − 200 = 300 N, then a = 300 ÷ 100 = 3 m/s². Using the 500 N driving force alone gives 5 m/s², which ignores the resistive forces."}
]);

QUESTIONS["s11i-09-2"] = (QUESTIONS["s11i-09-2"] || []).concat([
  {q:"An object has a momentum of 45 kg m/s and a mass of 9 kg. What is its velocity?",opts:["405 m/s","0.2 m/s","5 m/s","54 m/s"],c:2,e:"Rearrange p = mv to give v = p ÷ m = 45 ÷ 9 = 5 m/s. Multiplying momentum by mass gives 405, which is the result of using the equation the wrong way round."},
  {q:"Two stationary ice skaters push apart. The 50 kg skater moves off at 2 m/s. At what speed does the 40 kg skater move?",opts:["2 m/s","2.5 m/s","1.6 m/s","4 m/s"],c:1,e:"Total momentum stays zero, so the momenta are equal and opposite: 50 × 2 = 40 × v, giving v = 100 ÷ 40 = 2.5 m/s. The lighter skater must move faster, not at the same speed."},
  {q:"What is the unit of momentum?",opts:["kg m/s","N/kg","m/s²","kg/m"],c:0,e:"Momentum = mass (kg) × velocity (m/s), so its unit is kg m/s. N/kg is the unit of gravitational field strength, not momentum."},
  {q:"A ball hits a wall at 6 m/s and bounces straight back at 6 m/s. Its momentum has:",opts:["Stayed exactly the same","Doubled in size","Become zero","The same size but the opposite direction"],c:3,e:"Momentum is a vector. The speed is unchanged but the direction has reversed, so the momentum is now equal in size and opposite in direction. Saying it is 'the same' ignores direction — the change in momentum is actually 2mv."},
  {q:"A 4 kg trolley moving at 6 m/s collides with a stationary 2 kg trolley and they stick together. What is their combined velocity?",opts:["6 m/s","4 m/s","3 m/s","2 m/s"],c:1,e:"Momentum before = 4 × 6 = 24 kg m/s. After: 24 = (4 + 2) × v, so v = 24 ÷ 6 = 4 m/s. Dividing by the moving trolley's mass alone (giving 6 m/s) forgets that the combined mass carries the momentum."},
  {q:"A 3 kg object moving right at 5 m/s collides head-on with a 2 kg object moving left at 5 m/s. They stick together. What happens? (Higher Tier)",opts:["They stop dead","They move right at 1 m/s","They move left at 1 m/s","They move right at 5 m/s"],c:1,e:"Taking right as positive: total momentum = (3 × 5) + (2 × −5) = 15 − 10 = 5 kg m/s. So v = 5 ÷ 5 = 1 m/s to the right. They cannot stop dead because the total momentum is not zero — forgetting the minus sign on the leftward velocity is the classic error."},
  {q:"A bat changes a ball's momentum by 6 kg m/s in a contact time of 0.02 s. What average force does the bat exert? (Higher Tier)",opts:["0.12 N","120 N","3.3 N","300 N"],c:3,e:"F = Δp ÷ Δt = 6 ÷ 0.02 = 300 N. Multiplying instead of dividing gives 0.12 N — remember that a short contact time makes the force LARGER, not smaller."},
  {q:"An object's mass is doubled and its velocity is halved. Its momentum:",opts:["Doubles","Halves","Stays the same","Quadruples"],c:2,e:"p = mv, so the new momentum is (2m) × (v ÷ 2) = mv — unchanged. The two changes cancel exactly; they do not add together."},
  {q:"When a cannon fires, the cannonball flies off quickly but the cannon recoils slowly. Why?",opts:["The cannon gains less momentum than the ball","Their momenta are equal in size, and the cannon's larger mass means a smaller velocity","Friction stops the cannon gaining any momentum","The explosion only pushes on the ball"],c:1,e:"Conservation of momentum: the cannon and ball gain equal-sized, opposite momenta. Since p = mv, the massive cannon needs only a small velocity to match the ball's momentum. The explosion pushes on both — Newton's third law."},
  {q:"Which of these objects has zero momentum?",opts:["A parked lorry, whatever its mass","A slow-moving feather","A fast electron","A falling raindrop"],c:0,e:"p = mv, so anything with zero velocity has zero momentum regardless of how large its mass is. The other three are all moving, so they all have some momentum, however small."}
]);

QUESTIONS["s11i-09-3"] = (QUESTIONS["s11i-09-3"] || []).concat([
  {q:"A car travels at 20 m/s and the driver's reaction time is 0.5 s. What is the thinking distance?",opts:["40 m","10 m","20.5 m","4 m"],c:1,e:"During the reaction time the speed is constant, so distance = speed × time = 20 × 0.5 = 10 m. Dividing speed by reaction time (giving 40) is the usual rearrangement slip."},
  {q:"Which factor increases braking distance but does NOT affect thinking distance?",opts:["Drinking alcohol","Using a mobile phone","An icy road surface","Driver tiredness"],c:2,e:"Ice reduces friction between the tyres and the road, so the car takes longer to slow once the brakes are applied — but it has no effect on how quickly the driver reacts. Alcohol, phones and tiredness all slow the driver's reactions instead."},
  {q:"In the ruler drop test, a shorter drop distance before catching the ruler indicates:",opts:["A faster reaction time","A slower reaction time","A longer thinking distance","Stronger fingers"],c:0,e:"The less the ruler falls before being caught, the less time has passed, so the reaction time is faster. It measures reaction time, not strength or any property of the car."},
  {q:"What is a typical reaction time for an alert human driver?",opts:["2 to 9 seconds","0.02 to 0.09 seconds","0.2 to 0.9 seconds","Exactly 1 second"],c:2,e:"Typical human reaction times range from about 0.2 s to 0.9 s. Whole seconds would be dangerously slow, and hundredths of a second is faster than nerve signals allow."},
  {q:"A driver's thinking distance is 12 m and the braking distance is 24 m. What is the total stopping distance?",opts:["12 m","24 m","288 m","36 m"],c:3,e:"Stopping distance = thinking distance + braking distance = 12 + 24 = 36 m. You add the two distances — multiplying them (288) has no physical meaning."},
  {q:"If a car's speed doubles, what happens to the thinking distance?",opts:["It doubles","It quadruples","It stays the same","It halves"],c:0,e:"Thinking distance = speed × reaction time, and reaction time does not change with speed, so doubling the speed doubles the thinking distance. It is the BRAKING distance that roughly quadruples, because kinetic energy depends on speed squared."},
  {q:"A car brakes uniformly from 18 m/s to rest in 3 s. Use the area under the velocity-time graph to find the braking distance.",opts:["54 m","27 m","6 m","21 m"],c:1,e:"The graph is a triangle: distance = ½ × 18 × 3 = 27 m. Using speed × time (54 m) ignores that the car is slowing down, so it overestimates the distance by double."},
  {q:"Why can very large decelerations during emergency braking be dangerous?",opts:["They reduce the car's kinetic energy","The brakes may overheat and the car may skid out of control","They make the thinking distance longer","They increase the car's momentum"],c:1,e:"A very large braking force causes a very large deceleration, which can overheat the brakes and cause the tyres to lose grip, leading to skidding. Reducing kinetic energy is the whole point of braking, not a danger."},
  {q:"A driver who has drunk alcohol is more likely to crash mainly because alcohol:",opts:["Increases the braking distance","Reduces the friction of the tyres","Increases reaction time, and so the thinking distance","Makes the car heavier"],c:2,e:"Alcohol slows the brain's processing, lengthening the reaction time and therefore the thinking distance. It does nothing to the car itself — tyres, brakes and mass are unchanged."},
  {q:"In a crash, a seatbelt brings a 70 kg passenger moving at 12 m/s to rest in 0.6 s. What average force does the belt exert? (Higher Tier)",opts:["1400 N","840 N","504 N","8400 N"],c:0,e:"Change in momentum = 70 × 12 = 840 kg m/s. Force = Δp ÷ Δt = 840 ÷ 0.6 = 1400 N. The value 840 is the momentum change itself, not the force — you must still divide by the time."}
]);

QUESTIONS["s11i-09-4"] = (QUESTIONS["s11i-09-4"] || []).concat([
  {q:"A lorry slows from 24 m/s to 6 m/s in 6 s. What is its acceleration?",opts:["3 m/s²","−3 m/s²","−4 m/s²","−18 m/s²"],c:1,e:"a = Δv ÷ t = (6 − 24) ÷ 6 = −18 ÷ 6 = −3 m/s². The negative sign matters: it shows deceleration. Forgetting to subtract in the right order gives +3 m/s², which would mean speeding up."},
  {q:"A cyclist starts from rest and accelerates at 3 m/s² over 24 m. Use v² = u² + 2as to find the final velocity.",opts:["72 m/s","144 m/s","12 m/s","8.5 m/s"],c:2,e:"v² = 0² + 2 × 3 × 24 = 144, so v = √144 = 12 m/s. Forgetting to take the square root leaves you with 144, which is v squared, not v."},
  {q:"A horizontal line above the time axis on a velocity-time graph shows that the object is:",opts:["Stationary","Decelerating","Moving at constant velocity","Accelerating uniformly"],c:2,e:"A horizontal line means the velocity is not changing — constant velocity. It only means 'stationary' on a DISTANCE-time graph; mixing up the two graph types is the most common error."},
  {q:"On a velocity-time graph, a straight line sloping downwards towards the time axis shows:",opts:["Constant deceleration","The object moving backwards","Increasing acceleration","The object returning to its start point"],c:0,e:"A constant negative gradient means the velocity is falling at a steady rate — uniform deceleration. While the line stays above the axis the object is still moving forwards, just more slowly."},
  {q:"A car accelerates uniformly from rest to 10 m/s in 8 s. Using the area under its velocity-time graph, how far does it travel?",opts:["80 m","18 m","40 m","1.25 m"],c:2,e:"The area is a triangle: ½ × base × height = ½ × 8 × 10 = 40 m. Using the full rectangle (80 m) assumes the car was at 10 m/s the whole time, which it was not."},
  {q:"A car moving at 5 m/s accelerates at 2 m/s² for 4 s. What is its final velocity?",opts:["11 m/s","13 m/s","40 m/s","8 m/s"],c:1,e:"The velocity gained is a × t = 2 × 4 = 8 m/s, so the final velocity = 5 + 8 = 13 m/s. Forgetting to add the initial 5 m/s gives just the change (8 m/s), not the final velocity."},
  {q:"On a velocity-time graph, a straight diagonal line starting at the origin shows:",opts:["Constant velocity","Increasing acceleration","Constant (uniform) acceleration from rest","The object slowing to a stop"],c:2,e:"A straight line has a constant gradient, and gradient = acceleration, so the acceleration is uniform; starting at the origin means it starts from rest. A curved line would be needed to show changing acceleration."},
  {q:"A motorbike accelerates from rest to 30 m/s with a uniform acceleration of 5 m/s². Use v² = u² + 2as to find the distance covered.",opts:["90 m","180 m","6 m","3 m"],c:0,e:"Rearranging: s = (v² − u²) ÷ 2a = (900 − 0) ÷ (2 × 5) = 900 ÷ 10 = 90 m. Dividing by a instead of 2a gives 180 m — keep the factor of 2 in the denominator."},
  {q:"An object is dropped and falls freely (ignore air resistance). After each second of falling, its speed increases by about:",opts:["9.8 m/s","98 m/s","1 m/s","9.8 m/s² of distance"],c:0,e:"Free-fall acceleration is about 9.8 m/s², which means the speed grows by about 9.8 m/s every second. Speed is measured in m/s — the unit m/s² belongs to the acceleration itself, not to the gain in speed."},
  {q:"A runner moves at a steady 6 m/s for 10 s. From the velocity-time graph, the distance covered is:",opts:["1.7 m","16 m","30 m","60 m"],c:3,e:"At constant velocity the area under the graph is a rectangle: 6 × 10 = 60 m. Halving it (30 m) would only be right for a triangle, which applies when the object starts from rest and accelerates."}
]);

QUESTIONS["s11i-09-5"] = (QUESTIONS["s11i-09-5"] || []).concat([
  {q:"At which point in a skydiver's fall is their acceleration greatest?",opts:["At terminal velocity","Just after leaving the aircraft, when they are moving slowly","Just before the parachute opens","When air resistance equals weight"],c:1,e:"Early in the fall the speed is low, so air resistance is small and the resultant force is nearly the full weight — giving the largest acceleration. At terminal velocity the acceleration is zero, the opposite extreme."},
  {q:"A skydiver of weight 800 N falls at terminal velocity. What is the size of the air resistance on them?",opts:["More than 800 N","Less than 800 N","Exactly 800 N","Zero"],c:2,e:"At terminal velocity the forces are balanced, so air resistance must exactly equal the 800 N weight. If it were larger the skydiver would slow down; air resistance never needs to exceed weight to give a constant speed."},
  {q:"An object falls in a vacuum. Which statement is correct?",opts:["It reaches terminal velocity almost instantly","It falls at a constant speed throughout","It never reaches terminal velocity and keeps accelerating","It does not fall, because there is no air to push it"],c:2,e:"Terminal velocity requires air resistance to balance weight. In a vacuum there is no air resistance, so the only force is weight and the object accelerates for the entire fall. Gravity, not air, makes things fall."},
  {q:"A skydiver dives head-first instead of falling flat. Their terminal velocity is higher because:",opts:["Their weight increases in this position","The smaller area means less drag at any speed, so a higher speed is needed to balance weight","Gravity acts more strongly on streamlined shapes","Air resistance disappears completely"],c:1,e:"The head-down position reduces the area pushing through the air, so drag at any given speed is smaller. The skydiver must fall faster before drag grows enough to balance weight. Their weight is unchanged — position cannot alter mass or gravity."},
  {q:"A 70 kg skydiver has a weight of 700 N. At one moment the air resistance is 350 N. What is their acceleration at that moment?",opts:["10 m/s²","0 m/s²","5 m/s²","15 m/s²"],c:2,e:"Resultant force = 700 − 350 = 350 N downwards. a = F ÷ m = 350 ÷ 70 = 5 m/s². Using the full weight (700 N) gives 10 m/s², but that ignores the air resistance acting upwards."},
  {q:"As an object falls faster and faster through the air, its weight:",opts:["Increases","Decreases","Stays the same","Falls to zero at terminal velocity"],c:2,e:"Weight = mass × gravitational field strength, and neither changes during the fall, so weight is constant. It is the air resistance that changes — the forces balance because drag rises to meet the weight, not because weight shrinks."},
  {q:"A skydiver is at terminal velocity when the parachute opens. Which best describes the velocity-time graph from that moment?",opts:["The line rises steeply then levels off","The line drops, then levels off at a lower constant velocity","The line immediately falls to zero","The line stays horizontal at the same velocity"],c:1,e:"The extra drag decelerates the skydiver, so the line slopes downwards; as they slow, drag decreases until it balances weight again, and the line levels off at a new, lower terminal velocity. It cannot drop to zero — they are still falling, just more slowly."},
  {q:"A small ball bearing is dropped into a tall column of thick oil. What happens?",opts:["It accelerates all the way to the bottom","It reaches a terminal velocity, because the oil exerts a drag force that grows with speed","It floats, because liquids cannot exert forces","It falls faster than it would through air"],c:1,e:"Liquids exert drag just as air does — usually much more strongly — so the bearing quickly reaches a (low) terminal velocity. Because the drag is larger than in air, it falls more slowly, not faster."},
  {q:"Why do raindrops reach the ground at safe, fairly low speeds despite falling from great heights?",opts:["Gravity is weaker high up in clouds","They reach a low terminal velocity because air resistance balances their small weight","They slow down just before landing","Clouds give them a slow starting speed"],c:1,e:"A raindrop's weight is tiny, so only a little air resistance is needed to balance it — reached at a low speed. Without air resistance, drops falling from cloud height would arrive dangerously fast; the starting speed and the strength of gravity are not the reason."},
  {q:"A skydiver falls at a terminal velocity of 50 m/s for 12 s. How far do they fall in this time?",opts:["600 m","4.2 m","62 m","300 m"],c:0,e:"At terminal velocity the speed is constant, so distance = speed × time = 50 × 12 = 600 m. Halving the answer (300 m) would only apply if the speed were changing uniformly from zero, but here it is steady."}
]);
