// science-y11-x10.js — Year 11 Science Topic 10 expansion: Energy: Efficiency & Resources (extra flashcards + questions for s11i-10-1 .. s11i-10-2)

// ── EXTRA FLASHCARDS ─────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s11i-10-1 — Energy Resources
  {id:"s11fc-10-1-6",islandId:"s11i-10-1",front:"Why is tidal power more predictable than wind power?",
   back:"Tides are caused by the gravitational pull of the Moon, so they rise and fall on a regular, known timetable — engineers can predict output years in advance.\n\nWind depends on the weather, which changes from day to day and cannot be guaranteed.\n\nHowever, tidal schemes are expensive and only suit a few coastal sites.",difficulty:2,category:"concept"},
  {id:"s11fc-10-1-7",islandId:"s11i-10-1",front:"Why are biofuels described as close to carbon-neutral?",
   back:"The plants used to make biofuel absorb CO₂ from the atmosphere as they grow.\n\nBurning the fuel releases roughly the same amount of CO₂ back, so the net change is small — provided new crops are planted to replace those harvested.\n\nDrawback: growing fuel crops uses land that could grow food.",difficulty:2,category:"concept"},
  {id:"s11fc-10-1-8",islandId:"s11i-10-1",front:"Give two reasons why countries are switching towards renewable resources, and two factors slowing the change.",
   back:"Reasons for the switch:\n1. Fossil fuels are finite and will eventually run out.\n2. Burning fossil fuels releases CO₂, driving climate change.\n\nFactors slowing the change:\n1. Cost — building new renewable plants and grid connections is expensive.\n2. Reliability — many renewables are intermittent, so back-up supply is still needed.",difficulty:2,category:"application"},

  // s11i-10-2 — The National Grid & Efficiency
  {id:"s11fc-10-2-6",islandId:"s11i-10-2",front:"State two ways to reduce unwanted energy transfers in a machine.",
   back:"1. Lubrication — oil or grease between moving parts reduces friction, so less energy is dissipated as heat.\n2. Thermal insulation — lagging or low-conductivity materials reduce heat transfer to the surroundings.\n\nStreamlining a moving object also cuts energy wasted doing work against air resistance.",difficulty:1,category:"concept"},
  {id:"s11fc-10-2-7",islandId:"s11i-10-2",front:"A motor draws 200 W of electrical power and delivers 150 W of useful mechanical power. Find its efficiency and the wasted power.",
   back:"Efficiency = (useful power ÷ total power) × 100\n= (150 ÷ 200) × 100 = 75%\n\nWasted power = 200 − 150 = 50 W, dissipated mainly as heat in the wires and bearings, plus a little sound.",difficulty:2,category:"calculation"},
  {id:"s11fc-10-2-8",islandId:"s11i-10-2",front:"Why must the voltage be stepped down before electricity enters homes?",
   back:"Transmission voltages (up to 400 000 V) would be extremely dangerous in a house — they could cause fatal shocks and damage appliances designed for mains voltage.\n\nStep-down transformers in local substations reduce the supply to 230 V, which is safe enough for domestic wiring while still powerful enough to run appliances.",difficulty:1,category:"concept"}
);

// ── EXTRA TEST QUESTIONS ─────────────────────────────────────────────────────
QUESTIONS["s11i-10-1"] = (QUESTIONS["s11i-10-1"] || []).concat([
  {q:"Tidal power output can be forecast years in advance because:",opts:["Tides depend on the weather forecast","Tides follow the regular gravitational pull of the Moon","Tidal barrages store electricity in batteries","Sea water never changes temperature"],c:1,e:"The Moon's gravity drives the tides on a fixed, repeating cycle, so the timing of high and low tide is known far ahead. The weather forecast is the tempting wrong answer, but tides are astronomical, not meteorological — that is exactly why they beat wind for predictability."},
  {q:"In a pumped storage hydroelectric scheme, water is pumped uphill during the night because:",opts:["The turbines only spin in darkness","Demand is low, so spare electricity can store energy for the morning peak","Water flows faster at night","Reservoirs leak during the day"],c:1,e:"At night demand is low, so cheap spare electricity lifts water into the upper reservoir, storing gravitational potential energy. Releasing it at peak times generates power on demand. The turbines work at any time of day, so darkness itself is irrelevant."},
  {q:"Geothermal power is only practical in certain countries, such as Iceland, because:",opts:["It needs hot rocks close to the Earth's surface","It only works near the equator","It requires large coal deposits nearby","It needs constant strong winds"],c:0,e:"Geothermal plants pump water down to hot rocks, and only volcanically active regions have such rocks near the surface. The equator answer is tempting because it sounds climate-related, but geothermal heat comes from inside the Earth, not from the Sun."},
  {q:"Which non-renewable resource releases no carbon dioxide while generating electricity?",opts:["Natural gas","Coal","Nuclear fuel","Oil"],c:2,e:"Nuclear fission releases energy without any combustion, so no CO₂ is produced during operation — its drawback is radioactive waste instead. Natural gas is the tempting distractor because it is the cleanest fossil fuel, but burning it still releases CO₂."},
  {q:"A diesel generator is chosen over solar panels for a hospital's emergency backup supply mainly because:",opts:["Diesel is a renewable fuel","Solar panels are illegal in hospitals","Diesel is better for the environment","The generator works on demand at any time, day or night"],c:3,e:"A backup supply must start instantly whenever a power cut happens, including at night — reliability matters more than running cost or emissions here. Diesel is certainly not renewable, and it is worse for the environment, so those options reverse the real trade-off."},
  {q:"A gas-fired power station has an output of 1600 MW. How many 2 MW wind turbines would be needed to match this output at full power?",opts:["80","320","800","3200"],c:2,e:"1600 ÷ 2 = 800 turbines. In practice even more would be needed, because turbines rarely run at full power. 320 comes from dividing by 5 and 80 from dividing by 20 — both are slips in the division."},
  {q:"One solar panel has a maximum output of 250 W. How many panels are needed to supply a peak demand of 3 kW?",opts:["6","12","24","120"],c:1,e:"3 kW = 3000 W, and 3000 ÷ 250 = 12 panels. The answer 120 comes from forgetting to convert kilowatts to watts correctly, while 6 and 24 are factor-of-two slips."},
  {q:"Burning 1 kg of coal releases about 30 MJ of energy. How much energy is released by burning 5 kg?",opts:["6 MJ","35 MJ","150 MJ","300 MJ"],c:2,e:"Energy = 30 × 5 = 150 MJ. The option 35 MJ comes from adding instead of multiplying, and 6 MJ from dividing — energy released scales up in proportion to the mass of fuel burned."},
  {q:"A wind farm has a maximum output of 100 MW but averages 40% of this over a year. What is its average output?",opts:["40 MW","60 MW","140 MW","400 MW"],c:0,e:"Average output = 100 × 0.40 = 40 MW. The 60 MW option is the share of capacity NOT delivered (100 − 40), an easy mix-up; the average can never exceed the 100 MW maximum, ruling out the larger values."},
  {q:"An island community must choose between a tidal scheme and a coal plant. Which statement gives a fair comparison?",opts:["Tidal has higher fuel costs than coal","Coal is predictable and tidal is not","Tidal has no fuel costs but a high building cost; coal has ongoing fuel costs and CO₂ emissions","Coal will never run out, unlike tidal energy"],c:2,e:"Tidal energy is free once the barrage is built, but construction is expensive; coal needs continual fuel purchases and emits CO₂. The second option is tempting but backwards — tides are highly predictable, while coal supply depends on imports and price changes."}
]);

QUESTIONS["s11i-10-2"] = (QUESTIONS["s11i-10-2"] || []).concat([
  {q:"Step-down transformers are placed in local substations in order to:",opts:["Increase the voltage for long cables","Reduce the voltage to 230 V for safe use in homes","Convert AC into DC","Generate extra electricity for peak demand"],c:1,e:"Homes need the mains supply at 230 V; transmission voltages would be lethal indoors. Transformers only change voltage — they cannot generate energy or convert AC to DC, which is the job of a rectifier."},
  {q:"If the current in a transmission cable is halved, the heat dissipated in the cable becomes:",opts:["Half as much","Twice as much","One quarter as much","The same"],c:2,e:"Heating in a cable depends on the square of the current (I²R), so halving I gives (1/2)² = 1/4 of the heat loss. \"Half as much\" is the tempting answer, but it ignores the squaring — this is exactly why high-voltage, low-current transmission saves so much energy."},
  {q:"Which change would improve the efficiency of an electric motor?",opts:["Lubricating its bearings to reduce friction","Painting the casing a brighter colour","Running it from a longer extension lead","Increasing the total energy supplied to it"],c:0,e:"Lubrication cuts friction, so less of the input energy is dissipated as heat and a larger share becomes useful motion. Supplying more energy raises the output but not the ratio of useful to total, so it does not change efficiency."},
  {q:"No device can be 100% efficient because:",opts:["Energy is destroyed inside every machine","Some energy is always dissipated to the surroundings, usually as heat","Manufacturers deliberately waste energy","Electricity always escapes from plug sockets"],c:1,e:"Friction, resistance and other processes always transfer some energy to the thermal store of the surroundings, where it is no longer useful. Energy is never destroyed — it is conserved — so the first option contradicts the conservation of energy."},
  {q:"A device receives 90 W of electrical power and wastes 36 W as heat. Its useful power output is:",opts:["126 W","36 W","45 W","54 W"],c:3,e:"Useful power = total − wasted = 90 − 36 = 54 W. The 126 W option adds instead of subtracting, which would break conservation of energy — output can never exceed input."},
  {q:"A filament lamp transfers 120 J of electrical energy and emits 30 J as light. Its efficiency is:",opts:["30%","25%","40%","75%"],c:1,e:"Efficiency = (30 ÷ 120) × 100 = 25%. The 30% answer just copies the number of joules of light, and 75% is the fraction wasted as heat rather than the fraction that is useful."},
  {q:"A kettle is 80% efficient. If it is supplied with 400 J, how much energy usefully heats the water?",opts:["80 J","500 J","320 J","480 J"],c:2,e:"Useful energy = 0.80 × 400 = 320 J. The 500 J answer comes from dividing 400 by 0.8, which would mean more useful energy out than total energy in — impossible by conservation of energy."},
  {q:"A machine is 40% efficient and delivers 60 J of useful work. How much total energy was supplied?",opts:["24 J","100 J","150 J","240 J"],c:2,e:"Total input = useful ÷ efficiency = 60 ÷ 0.40 = 150 J. The 24 J answer multiplies by 0.4 instead of dividing — but the input must be larger than the useful output, which rules it out immediately."},
  {q:"A television receives 2000 J of energy and operates at 65% efficiency. How much energy is wasted?",opts:["700 J","1300 J","650 J","1350 J"],c:0,e:"Useful energy = 0.65 × 2000 = 1300 J, so wasted = 2000 − 1300 = 700 J. The 1300 J option is the useful energy, not the wasted energy — read the question carefully to see which part is being asked for."},
  {q:"A step-up transformer raises the transmission voltage from 25 kV to 400 kV. Assuming the power stays the same, the current in the cables:",opts:["Increases by a factor of 16","Stays the same","Falls to one sixteenth of its original value","Falls to one quarter of its original value"],c:2,e:"400 ÷ 25 = 16, and since P = IV is unchanged, multiplying the voltage by 16 divides the current by 16. The one-quarter option mistakenly uses the square root of 16 — the I² relationship applies to heat loss, not to this current calculation."}
]);
