// science-y11-x11.js — Year 11 Science Topic 11 expansion: Biology Required Practicals (extra flashcards + questions)

// ── FLASHCARDS ──────────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s11i-11-1 — Biology Practicals 1 (continuing from s11fc-11-1-5)
  {id:"s11fc-11-1-6",islandId:"s11i-11-1",front:"How do you calculate the magnification of a cell viewed under a light microscope?",
   back:"Magnification = total magnification of the lenses used.\n\nTotal magnification = eyepiece magnification x objective magnification.\n\nExample: a x10 eyepiece with a x40 objective gives x400.\n\nTo work back to a real size: actual size = image size divided by magnification. Keep both measurements in the same units (e.g. micrometres) before dividing.",difficulty:2,category:"application"},
  {id:"s11fc-11-1-7",islandId:"s11i-11-1",front:"In the osmosis practical, why must each potato cylinder be blotted dry before weighing?",
   back:"Surface liquid clinging to the cylinder adds to its measured mass and is not part of the cylinder itself.\n\nIf you do not blot, a cylinder taken from a dilute solution carries extra water and appears heavier, exaggerating any mass gain.\n\nBlotting in a standard way (same number of dabs each time) keeps the measurement of mass fair and repeatable.",difficulty:2,category:"concept"},
  {id:"s11fc-11-1-8",islandId:"s11i-11-1",front:"Why is a buffer solution used in the amylase and pH practical?",
   back:"A buffer resists changes in pH, holding each tube at its set value throughout the reaction.\n\nWithout a buffer the pH could drift as the reaction proceeds, so you could not be sure the result reflects the pH you intended to test.\n\npH is the independent variable, so it must stay fixed for each tube to give a valid comparison.",difficulty:2,category:"concept"},

  // s11i-11-2 — Biology Practicals 2 (continuing from s11fc-11-2-5)
  {id:"s11fc-11-2-6",islandId:"s11i-11-2",front:"In the pondweed photosynthesis practical, why is collecting gas in a syringe better than counting bubbles?",
   back:"Counting bubbles is unreliable because bubbles vary in size and can be released too quickly to count accurately.\n\nCollecting the gas and measuring its volume gives a quantitative, continuous measurement of oxygen produced.\n\nThis improves the accuracy and repeatability of the rate measurement compared with a simple bubble count.",difficulty:2,category:"concept"},
  {id:"s11fc-11-2-7",islandId:"s11i-11-2",front:"How do you use a transect to study how plant distribution changes across a habitat?",
   back:"1. Lay a tape measure in a straight line across the area (e.g. from a path to a pond).\n2. Place quadrats at regular intervals along the line (a belt transect).\n3. Record the species or percentage cover in each quadrat.\n4. Plot the data against distance along the transect.\n\nA transect shows how distribution changes along an environmental gradient, rather than estimating a total population.",difficulty:2,category:"application"},
  {id:"s11fc-11-2-8",islandId:"s11i-11-2",front:"In the milk and lipase decay practical, why is a control tube with boiled lipase useful?",
   back:"Boiling denatures the lipase so it can no longer break down fat.\n\nThe control tube shows that any colour change in the test tubes is caused by working enzyme activity and not by something else in the milk.\n\nThis improves the validity of the conclusion that lipase is responsible for the change.",difficulty:2,category:"concept"}
);

// ── TEST QUESTIONS ────────────────────────────────────────────────────────────
QUESTIONS["s11i-11-1"] = (QUESTIONS["s11i-11-1"] || []).concat([
  {q:"A cell measures 20 mm across in an image taken at x500 magnification. What is its actual size?",opts:["40 micrometres","0.04 micrometres","10 000 micrometres","400 micrometres"],c:0,e:"Actual size = image size divided by magnification = 20 mm divided by 500 = 0.04 mm, which is 40 micrometres. Multiplying instead of dividing gives the wrong huge value of 10 000 micrometres."},
  {q:"Why should a coverslip be lowered slowly at an angle onto a wet specimen?",opts:["To stain the cells evenly","To reduce trapped air bubbles that obscure the view","To increase the magnification","To stop the slide cracking"],c:1,e:"Lowering at an angle lets liquid spread and pushes air out, avoiding bubbles that look like dark circles and hide the cells. The coverslip does not change magnification, which is set by the lenses."},
  {q:"A potato cylinder starts at 4.00 g and ends at 4.60 g. What is the percentage change in mass?",opts:["+15%","+0.6%","+60%","-15%"],c:0,e:"Percentage change = (4.60 - 4.00) divided by 4.00 x 100 = 0.60 divided by 4.00 x 100 = +15%. The sign is positive because the cylinder gained mass as water entered by osmosis, so -15% is wrong."},
  {q:"Why is iodine added when preparing onion cells, rather than viewing them unstained?",opts:["It magnifies the cells","It increases the contrast so structures are easier to see","It kills the cells instantly","It makes the cells photosynthesise"],c:1,e:"Iodine is a stain that adds colour and contrast, making the cell walls and other structures stand out against the background. It does not magnify; magnification is provided by the lenses."},
  {q:"In the amylase and pH investigation, the dependent variable is best described as the:",opts:["pH of the buffer","Volume of starch solution","Time taken for the iodine to stop turning blue-black","Concentration of amylase"],c:2,e:"The dependent variable is what you measure: the time for starch to be fully digested, shown when iodine no longer turns blue-black. pH is the independent variable and is deliberately changed, not measured."},
  {q:"A student weighs the potato cylinders on a balance reading to the nearest gram. How does this most likely affect the results?",opts:["It makes the percentage changes too large","Small mass changes may be missed, reducing accuracy","It changes the independent variable","It speeds up osmosis"],c:1,e:"Osmotic mass changes are small, so a balance reading only to the nearest gram cannot detect them precisely, reducing accuracy. A balance reading to two decimal places would resolve the small changes; the balance does not affect the rate of osmosis."},
  {q:"Why should each potato cylinder be left in its solution for the same length of time?",opts:["To use the same balance each time","Because time is a control variable that must be kept constant for a fair test","To change the independent variable","Because osmosis only works at fixed times"],c:1,e:"Time affects how much water moves, so it must be held constant so that only sucrose concentration causes the differences seen. Using the same balance is good practice but is a separate point from controlling time."},
  {q:"In a food test, why is it important to clean the dropper between testing different reagents?",opts:["To keep the dropper warm","To increase the reaction rate","To change the colour of the sample","To prevent cross-contamination giving a false result"],c:3,e:"Carrying traces of one reagent into another can trigger a colour change unrelated to the food being tested, giving a false positive. Cleaning has no effect on reaction rate or temperature."},
  {q:"A potato cylinder shows no change in mass. What does this most likely indicate about the solution?",opts:["It was pure water","Its water potential matched that of the potato cells","It was very concentrated sucrose","The potato was dead"],c:1,e:"No net mass change means no net movement of water, so the solution and the cells had equal water potential. Pure water would draw water in and increase mass, while concentrated sucrose would draw water out and reduce it."},
  {q:"When repeating the amylase practical, one tube gives a digestion time far longer than the others at the same pH. The best first step is to:",opts:["Delete the result without checking","Change the iodine for a different stain","Repeat that pH value to see if the anomaly is reproducible","Lower the temperature for that tube only"],c:2,e:"An anomalous result should be checked by repeating under the same conditions to see whether it recurs or was a one-off error. Simply deleting data or altering only one tube's conditions would not test the anomaly fairly."}
]);

QUESTIONS["s11i-11-2"] = (QUESTIONS["s11i-11-2"] || []).concat([
  {q:"A lamp is moved from 20 cm to 10 cm from the pondweed. Using light intensity proportional to 1 over distance squared, the intensity becomes:",opts:["Twice as great","Four times as great","Half as great","The same"],c:1,e:"Halving the distance from 20 cm to 10 cm multiplies intensity by 1 over (one half) squared = 4, so it becomes four times as great. It is not simply doubled because intensity depends on the square of the distance."},
  {q:"Why is a beaker of water (a heat shield) often placed between the lamp and the pondweed?",opts:["To increase the light intensity","To add carbon dioxide","To slow the bubble count","To absorb heat so temperature stays constant"],c:3,e:"The water absorbs infrared heat from the lamp, keeping temperature constant so it does not act as a second variable. It is there to control temperature, not to raise light intensity, which would confound the experiment."},
  {q:"A student records 9 oxygen bubbles in 30 seconds. What is the rate in bubbles per minute?",opts:["4.5","9","18","27"],c:2,e:"In 60 seconds there would be 9 x 2 = 18 bubbles, so the rate is 18 bubbles per minute. Dividing rather than scaling up the half-minute count gives the wrong value of 4.5."},
  {q:"A quadrat is 0.5 m by 0.5 m. A student finds a mean of 6 plantains per quadrat in a 400 m square field. The estimated total is:",opts:["2400","4800","9600","1200"],c:2,e:"Quadrat area = 0.5 x 0.5 = 0.25 metre squared, so density = 6 divided by 0.25 = 24 per metre squared, and total = 24 x 400 = 9600. Forgetting to convert the quadrat area and using 6 x 400 gives the wrong value of 2400."},
  {q:"Why should the same length and freshness of pondweed be used at every lamp distance?",opts:["To keep the amount of photosynthesising tissue constant","So the bubbles are larger","To increase carbon dioxide levels","To change the dependent variable"],c:0,e:"Using the same amount of healthy tissue keeps the photosynthesising surface constant so only light intensity affects the rate. Different pieces would vary the amount of tissue and confound the results, not simply change bubble size."},
  {q:"A belt transect is most appropriate when an investigator wants to study:",opts:["The total number of one species in a whole field","How species change across an environmental gradient","The mass change of potato cylinders","The pH of pond water"],c:1,e:"A belt transect records species at intervals along a line, revealing how distribution changes across a gradient such as light or moisture. Estimating a total population over a uniform area is better suited to random quadrats."},
  {q:"In the decay practical, why are all tubes kept at the same volume and concentration of milk?",opts:["To change the temperature","To denature the lipase","To stop the indicator working","So temperature is the only variable that differs between tubes"],c:3,e:"Keeping volume and concentration constant ensures temperature is the only factor that differs, so any difference in time is due to temperature. Varying the milk as well would make it impossible to attribute the result to temperature alone."},
  {q:"A student counts dandelions in only the sunny corner of a field. Why is the population estimate unreliable?",opts:["The quadrat was too large","The sample was not representative of the whole field","Dandelions cannot be counted","The field was too small"],c:1,e:"Sampling one favourable corner is biased and may not reflect the whole field, so scaling up gives an unreliable total. Random placement across the field would give a representative sample; quadrat size is not the issue here."},
  {q:"In the milk and lipase decay practical, the indicator changes from pink to colourless because:",opts:["Fat is built up making the mixture alkaline","Fatty acids are produced, lowering the pH","The lipase is denatured by the indicator","Oxygen is released"],c:1,e:"Lipase breaks fat into fatty acids, which lower the pH and turn phenolphthalein from pink to colourless. The reaction produces acid rather than making the mixture more alkaline, so the pink colour fades."},
  {q:"Two students repeat the photosynthesis count and get readings of 12 and 30 bubbles per minute at the same distance. The best response is to:",opts:["Average the two without checking","Take further repeats to identify which reading is anomalous","Record only the higher value","Move the lamp closer"],c:1,e:"The large gap suggests one reading may be anomalous, so taking more repeats shows which value to trust and improves repeatability. Averaging two very different readings or simply keeping the larger one would carry a likely error into the result."}
]);
