// science-y11-x12.js — Year 11 Science Topic 12 expansion: Chemistry Required Practicals (extra flashcards and questions)

// ── EXTRA FLASHCARDS ─────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s11i-12-1 — Chemistry Practicals 1
  {id:"s11fc-12-1-6",islandId:"s11i-12-1",front:"Why are graphite electrodes chosen for the electrolysis of copper sulfate solution?",
   back:"Graphite is inert (unreactive) and conducts electricity.\n\nBecause it does not react with the solution or the products, any changes observed must come from the electrolysis itself.\n\nIf a copper anode were used instead, the anode would dissolve (Cu → Cu²⁺ + 2e⁻) and no oxygen would be seen.",difficulty:2,category:"concept"},
  {id:"s11fc-12-1-7",islandId:"s11i-12-1",front:"List improvements that make the neutralisation temperature-change practical more accurate.",
   back:"1. Put a lid on the polystyrene cup — cuts heat loss by evaporation and convection.\n2. Stir continuously so the temperature is even throughout the liquid.\n3. Use a thermometer with 0.1 °C divisions (or a data logger) for higher resolution.\n4. Read the thermometer at eye level to avoid parallax error.\n5. Repeat each volume and calculate a mean to spot anomalies.",difficulty:2,category:"application"},
  {id:"s11fc-12-1-8",islandId:"s11i-12-1",front:"How does the method for making a soluble salt change if the base is soluble (an alkali such as sodium hydroxide)?",
   back:"You cannot add excess and filter, because the leftover alkali would stay dissolved in the solution.\n\nInstead, use a titration with an indicator to find the exact volume of acid that neutralises the alkali.\n\nThen repeat the mixing with those exact volumes but WITHOUT the indicator, so the salt is not contaminated, and crystallise the solution.",difficulty:3,category:"application"},

  // s11i-12-2 — Chemistry Practicals 2
  {id:"s11fc-12-2-6",islandId:"s11i-12-2",front:"Why is a single indicator (e.g. methyl orange) used in a titration rather than universal indicator?",
   back:"A single indicator gives one sharp, sudden colour change at the end point, so you can stop adding acid at exactly the right moment.\n\nUniversal indicator changes gradually through a whole range of colours as the pH falls, so there is no clear single point to stop at — the titre would be unreliable.",difficulty:2,category:"concept"},
  {id:"s11fc-12-2-7",islandId:"s11i-12-2",front:"Explain the key precautions when setting up a paper chromatogram.",
   back:"1. Draw the baseline in pencil — pencil is insoluble, so it will not run.\n2. Keep the solvent level BELOW the baseline — otherwise the spots dissolve straight into the solvent.\n3. Use small, concentrated spots so they do not spread and overlap.\n4. Put a lid on the container — stops the solvent evaporating and keeps the air saturated.\n5. Mark the solvent front in pencil as soon as the paper is removed.",difficulty:2,category:"application"},
  {id:"s11fc-12-2-8",islandId:"s11i-12-2",front:"How do you calculate the mean rate of a reaction, and what are suitable units?",
   back:"Mean rate = quantity of product formed (or reactant used) ÷ time taken.\n\nExample: 30 cm³ of gas collected in 25 s gives a mean rate of 30 ÷ 25 = 1.2 cm³/s.\n\nUnits depend on what you measure: cm³/s for gas volume, g/s for mass loss.",difficulty:2,category:"calculation"}
);

// ── EXTRA TEST QUESTIONS ─────────────────────────────────────────────────────
QUESTIONS["s11i-12-1"] = (QUESTIONS["s11i-12-1"] || []).concat([
  {q:"Why is the dilute sulfuric acid warmed before copper oxide is added when making copper sulfate?",opts:["To evaporate some of the water first","To speed up the reaction between the acid and the base","To sterilise the acid","To make the copper oxide dissolve without reacting"],c:1,e:"Copper oxide reacts very slowly with cold acid, so warming gives the particles more energy and speeds the reaction up. The water is not meant to evaporate at this stage — evaporation happens later, during crystallisation."},
  {q:"How can a student tell that enough copper oxide has been added to react with all of the acid?",opts:["The solution turns colourless","The mixture starts to fizz","The temperature stops changing","Some black solid remains undissolved after stirring and warming"],c:3,e:"Leftover undissolved copper oxide shows the base is in excess, so no acid can remain. The solution actually turns blue, not colourless, and this reaction does not fizz because no gas is made."},
  {q:"Why should the copper sulfate solution NOT be evaporated to complete dryness?",opts:["Hydrated crystals would lose their water of crystallisation, leaving a powder instead of proper crystals","All the copper would escape as a gas","The salt would turn back into acid","The evaporating basin would dissolve"],c:0,e:"Heating to dryness drives off the water of crystallisation, giving a pale anhydrous powder rather than well-formed blue crystals, and strong heating can decompose the salt. Copper compounds do not turn into gases at these temperatures."},
  {q:"Why can the 'add excess solid and filter' method NOT be used to make sodium chloride from sodium hydroxide?",opts:["Sodium hydroxide does not react with acids","Sodium chloride is insoluble in water","Sodium hydroxide is soluble, so the excess could not be removed by filtering","Filtering is too slow for this reaction"],c:2,e:"Excess sodium hydroxide would stay dissolved and pass straight through the filter paper, contaminating the salt, so a titration must be used to match the amounts exactly. Sodium hydroxide does react with acids — that is the whole point of the method."},
  {q:"A student repeats a neutralisation and records temperature rises of 6.4 °C, 6.6 °C and 6.5 °C. What is the mean temperature rise?",opts:["6.4 °C","6.5 °C","6.6 °C","19.5 °C"],c:1,e:"Mean = (6.4 + 6.6 + 6.5) ÷ 3 = 19.5 ÷ 3 = 6.5 °C. 19.5 °C is just the total of the three readings — you must divide by the number of repeats."},
  {q:"Why is the mixture stirred while alkali is added in the temperature-change practical?",opts:["So the heat is spread evenly and the thermometer reads the true temperature of the whole mixture","To stop the reaction happening too quickly","To add oxygen to the solution","To cool the mixture down"],c:0,e:"Without stirring, warm and cool regions form, so the thermometer might read only a local hot spot or miss the peak entirely. Stirring does not slow the reaction — if anything it helps the reactants mix and react fully."},
  {q:"What is the purpose of putting a lid on the polystyrene cup during the temperature-change practical?",opts:["To stop the reactants escaping as gas","To keep light out of the reaction","To reduce heat loss by evaporation and convection from the surface","To increase the pressure inside the cup"],c:2,e:"Most heat escapes from the open top of the cup, so a lid (with a small hole for the thermometer) reduces this loss and gives a higher, more accurate maximum temperature. Neutralisation of these solutions does not release a gas, so trapping gas is not the reason."},
  {q:"Which property is NOT a reason graphite is suitable as an electrode material?",opts:["It conducts electricity","It is inert, so it does not react with the electrolyte","It is cheap and easy to obtain","It dissolves slowly into the solution during electrolysis"],c:3,e:"A good inert electrode must NOT dissolve — if it entered the solution it would change the results. Conductivity, inertness and low cost are all genuine reasons graphite is chosen."},
  {q:"During electrolysis of copper sulfate solution with graphite electrodes, why does the blue colour of the solution gradually fade?",opts:["The water is being used up","Cu²⁺ ions, which cause the blue colour, are removed from solution as copper is deposited at the cathode","The graphite releases a bleaching agent","Oxygen gas dissolves and masks the colour"],c:1,e:"Each Cu²⁺ ion deposited as copper metal at the cathode leaves the solution, so the concentration of the blue ions falls and the colour fades. Graphite is inert and releases nothing into the solution."},
  {q:"How could a student confirm that the gas collected at the anode is oxygen?",opts:["Hold a lit splint to it and listen for a squeaky pop","Bubble it through limewater and look for cloudiness","Insert a glowing splint and check that it relights","Smell the gas carefully"],c:2,e:"Oxygen relights a glowing splint — this is the standard test. A squeaky pop is the test for hydrogen, and cloudy limewater is the test for carbon dioxide, neither of which is produced at the anode here."}
]);

QUESTIONS["s11i-12-2"] = (QUESTIONS["s11i-12-2"] || []).concat([
  {q:"Why is a pipette, rather than a measuring cylinder, used to transfer the alkali in a titration?",opts:["A pipette holds a larger volume","A pipette is easier to clean","A pipette measures one fixed volume far more accurately than a measuring cylinder","The alkali would react with a measuring cylinder"],c:2,e:"A volumetric pipette delivers a single precise volume (e.g. 25.0 cm³) with very small uncertainty, which a measuring cylinder cannot match. Alkali does not react with glassware in either case, so safety of the cylinder is not the issue."},
  {q:"Why is the conical flask placed on a white tile during a titration?",opts:["So the colour change of the indicator can be seen clearly and the end point judged accurately","To protect the bench from heat","To keep the flask level","To reflect light into the burette"],c:0,e:"The white background makes the indicator's colour change stand out, so the titration can be stopped at exactly the right moment. The flask is not heated, so bench protection from heat is not needed."},
  {q:"What is the purpose of carrying out a rough (trial) titration first?",opts:["To use up old chemicals","To check the indicator works","To clean the burette","To find the approximate titre so later titrations can be added drop by drop near the end point"],c:3,e:"The rough run shows roughly where the end point lies, so in accurate runs the acid can be added quickly at first and then dropwise near the end, avoiding overshooting. The indicator's behaviour is already known, so that is not what the trial is for."},
  {q:"A student records titres of 24.05 cm³, 23.95 cm³ and 24.60 cm³. What mean titre should be used?",opts:["24.20 cm³","24.00 cm³","24.60 cm³","23.95 cm³"],c:1,e:"24.60 cm³ is anomalous and must be discarded; the concordant titres 24.05 and 23.95 differ by only 0.10 cm³, and their mean is (24.05 + 23.95) ÷ 2 = 24.00 cm³. Averaging all three would give 24.20 cm³, which is distorted by the outlier."},
  {q:"In a titration, 25.0 cm³ of 0.100 mol/dm³ sodium hydroxide is exactly neutralised by 20.0 cm³ of hydrochloric acid. What is the concentration of the acid?",opts:["0.080 mol/dm³","0.100 mol/dm³","0.125 mol/dm³","0.500 mol/dm³"],c:2,e:"Moles of NaOH = 0.100 × (25.0 ÷ 1000) = 0.00250 mol. The 1:1 reaction means moles of HCl = 0.00250 mol, so concentration = 0.00250 ÷ 0.0200 = 0.125 mol/dm³. 0.080 mol/dm³ comes from dividing the volumes the wrong way round."},
  {q:"A reaction produces 48 cm³ of gas in the first 60 seconds. What is the mean rate over this period?",opts:["0.8 cm³/s","1.25 cm³/s","48 cm³/s","2880 cm³/s"],c:0,e:"Mean rate = volume ÷ time = 48 ÷ 60 = 0.8 cm³/s. 1.25 cm³/s is the result of dividing time by volume instead, and 2880 comes from multiplying rather than dividing."},
  {q:"A student investigates how acid concentration affects the rate of reaction with marble chips. Which variable must be controlled to make the comparison valid?",opts:["The concentration of the acid","The volume of gas collected","The time the reaction takes","The mass and size of the marble chips used in each run"],c:3,e:"Keeping the chips' mass and size the same fixes the surface area, so any change in rate must be due to concentration alone. Concentration is the independent variable being deliberately changed, so it is the one thing that must NOT be kept constant."},
  {q:"In the mass-loss method, why is a loose plug of cotton wool placed in the neck of the flask?",opts:["To stop the gas escaping so it can be measured","To let the carbon dioxide escape while stopping spray of acid from leaving the flask","To keep dust out of the flask","To absorb the carbon dioxide produced"],c:1,e:"The mass-loss method relies on CO₂ escaping, so the plug must be loose enough to let gas through while trapping acid spray that would cause extra, false mass loss. Sealing the flask completely would stop any mass change at all."},
  {q:"Why must the baseline on a chromatogram be drawn in pencil rather than ink?",opts:["Pencil lines are easier to rub out afterwards","Ink lines are too thick to measure from","Pencil is insoluble in the solvent, so the line does not dissolve and travel up the paper","Pencil reacts with the samples to fix them in place"],c:2,e:"An ink baseline would dissolve in the solvent and separate into its own dyes, contaminating the chromatogram. Pencil (graphite) does not dissolve, so the reference line stays exactly where it was drawn."},
  {q:"When the chromatography paper is lowered into the solvent, why must the solvent surface start below the baseline?",opts:["If the solvent touched the spots, they would dissolve into the solvent in the container instead of moving up the paper","The paper would tear if it got too wet","The solvent would evaporate too quickly","The Rf values would all become greater than 1"],c:0,e:"Spots sitting in the solvent simply wash off into the liquid, ruining the separation before it starts. Rf values are always between 0 and 1 by definition, so they could not all exceed 1."}
]);
