// science-y11-x13.js — Year 11 Science Topic 13 expansion: Physics Required Practicals (extra flashcards and questions for s11i-13-1 .. s11i-13-2)

// ── EXTRA FLASHCARDS ─────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s11i-13-1 — Physics Practicals 1
  {id:"s11fc-13-1-6",islandId:"s11i-13-1",front:"Give three ways to reduce errors in the specific heat capacity practical.",
   back:"1. Wrap the block in insulation (lagging) so less energy escapes to the surroundings.\n2. Put a few drops of oil in the thermometer hole — this improves thermal contact so the thermometer reads the block's true temperature.\n3. After switching off, keep watching the thermometer and record the highest temperature reached, because heat is still spreading from the heater into the block.",difficulty:2,category:"application"},
  {id:"s11fc-13-1-7",islandId:"s11i-13-1",front:"Describe the I–V characteristic of a diode.",
   back:"A diode only conducts in one direction (forward bias).\n\nIn the forward direction, almost no current flows until the potential difference reaches a threshold (about 0.6–0.7 V); after that the current rises steeply.\n\nIn the reverse direction the resistance is extremely high, so the current is effectively zero. This is why you must reverse the battery in the practical — to see both halves of the graph.",difficulty:2,category:"concept"},
  {id:"s11fc-13-1-8",islandId:"s11i-13-1",front:"Why take repeat readings and calculate a mean in the resistance practical?",
   back:"Repeating each measurement and averaging:\n1. Reduces the effect of random errors (small unpredictable variations in readings).\n2. Lets you spot anomalous results, which should be ignored or repeated before calculating the mean.\n\nThis improves the repeatability of the data. Note: repeats do NOT fix systematic errors such as a zero error on the ammeter — those shift every reading by the same amount.",difficulty:2,category:"concept"},

  // s11i-13-2 — Physics Practicals 2
  {id:"s11fc-13-2-6",islandId:"s11i-13-2",front:"What errors can occur when using a displacement can to find volume, and how do you avoid them?",
   back:"1. Can not filled to the spout level — fill it until water just stops dripping before adding the object, or the collected volume will be too small.\n2. Splashing — lower the object slowly on a thread so only displaced water leaves the spout.\n3. Water clinging inside the can or spout — some displaced water never reaches the measuring cylinder, underestimating the volume.\n4. Parallax — read the measuring cylinder at eye level, at the bottom of the meniscus.",difficulty:2,category:"application"},
  {id:"s11fc-13-2-7",islandId:"s11i-13-2",front:"How can you make length readings in the spring (Hooke's law) practical more accurate?",
   back:"1. Use a set square to check the ruler is vertical and to line up the bottom of the spring with the scale.\n2. Attach a horizontal pointer (fiducial marker) to the bottom of the spring so there is a definite position to read.\n3. Read the ruler with your eye level with the pointer to avoid parallax error.\n4. Add masses gently and wait until the spring is completely still before reading.",difficulty:2,category:"application"},
  {id:"s11fc-13-2-8",islandId:"s11i-13-2",front:"Describe how to measure wave speed on a stretched string.",
   back:"1. Attach a string to a vibration generator, pass it over a pulley and hang masses on the end to keep the tension constant.\n2. Adjust the frequency on the signal generator until a clear, stable pattern of loops (a stationary wave) forms.\n3. Measure the length of several loops with a ruler and divide to find one loop. One loop is HALF a wavelength, so wavelength = 2 × loop length.\n4. Read the frequency from the signal generator and calculate v = fλ.",difficulty:2,category:"application"}
);

// ── EXTRA TEST QUESTIONS ─────────────────────────────────────────────────────
QUESTIONS["s11i-13-1"] = (QUESTIONS["s11i-13-1"] || []).concat([
  {q:"In the SHC practical, why are a few drops of oil placed in the thermometer hole of the metal block?",opts:["To lubricate the thermometer so it can be removed easily","To stop the block rusting during the experiment","To improve thermal contact so the thermometer reads the block's true temperature","To slow down the temperature rise so readings are easier to take"],c:2,e:"Air is a poor conductor, so without oil there is a gap between the thermometer and the metal and the reading lags behind the block's real temperature. The oil fills this gap. It is not there for lubrication — that would not affect the measurement at all."},
  {q:"A 48 W heater runs for 250 s inside a 1.5 kg block. The temperature rises by 20 °C. What is the calculated specific heat capacity?",opts:["400 J/kg °C","600 J/kg °C","8000 J/kg °C","240 000 J/kg °C"],c:0,e:"E = P × t = 48 × 250 = 12 000 J. Then c = E / (m × Δθ) = 12 000 / (1.5 × 20) = 12 000 / 30 = 400 J/kg °C. The tempting answer 600 comes from forgetting the mass and dividing by 20 alone — the mass must be included."},
  {q:"In the resistance–length practical, the graph is a straight line but cuts the resistance axis slightly above zero. The most likely cause is:",opts:["A random error in one of the voltmeter readings","The wire heating up at long lengths","Parallax error when reading the ruler","Contact resistance where the crocodile clips grip the wire"],c:3,e:"A constant offset added to every reading is a systematic error, and the clips' contact resistance adds the same small extra resistance at every length — shifting the whole line up. A random error would scatter individual points, not lift the entire line by a fixed amount."},
  {q:"What is the purpose of the variable resistor in the I–V characteristics practical?",opts:["To protect the voltmeter from overheating","To change the current so a wide range of V and I readings can be collected","To keep the potential difference across the component constant","To measure the resistance of the component directly"],c:1,e:"Sliding the variable resistor alters the circuit current, letting you record many different pairs of V and I to plot the full characteristic. It does not measure resistance itself — resistance is calculated afterwards from R = V/I."},
  {q:"Why is the battery (or power supply) reversed partway through the I–V practical?",opts:["To recharge the battery before it runs flat","To reset any zero error on the ammeter","To collect readings for negative values of current and pd, testing the component in both directions","To reduce the temperature of the component"],c:2,e:"Reversing the supply drives current the opposite way, giving the negative quadrant of the I–V graph. This matters most for a diode, which behaves completely differently in reverse. It has nothing to do with recharging — that is not how the practical works."},
  {q:"Which statement correctly describes a diode's behaviour in this practical?",opts:["It conducts in one direction only, and needs about 0.6–0.7 V before significant current flows","It gives a straight line through the origin in both directions","Its resistance falls steadily as it gets hotter, curving the graph","It conducts equally well in both directions at high voltages"],c:0,e:"A diode is forward-biased in one direction only and has a threshold pd before it conducts; in reverse its resistance is extremely high. A straight line through the origin describes an ohmic resistor, not a diode."},
  {q:"During the wire practical a student records V = 3.0 V and I = 0.25 A for one length. What is the resistance?",opts:["0.75 Ω","12 Ω","0.083 Ω","3.25 Ω"],c:1,e:"R = V / I = 3.0 / 0.25 = 12 Ω. The answer 0.75 comes from multiplying V by I, which actually gives power in watts, not resistance."},
  {q:"Which single change would most improve the accuracy of the SHC result for the metal block?",opts:["Using a larger ammeter","Heating the block for a shorter time","Stirring the block during heating","Wrapping the block in an insulating jacket"],c:3,e:"The main systematic error is energy escaping to the surroundings, which makes the calculated SHC too high; insulation cuts this loss directly. A solid block cannot be stirred — stirring only applies to liquids such as water in a beaker."},
  {q:"Before the wire experiment begins, the ammeter reads 0.02 A even though no current is flowing. How should this be treated?",opts:["As a zero error — a systematic error that should be subtracted from every reading","As a random error that will average out over repeats","It can be ignored because it is so small","The ammeter should be shaken until it reads zero"],c:0,e:"A non-zero reading with no current is a zero error, which shifts every measurement by the same amount, so each reading must be corrected by 0.02 A (or the meter re-zeroed). Repeating and averaging cannot remove it, because it affects all readings identically — that only works for random errors."},
  {q:"After the heater is switched off in the SHC practical, the thermometer reading continues to rise for a short time. Why?",opts:["The thermometer is faulty and needs replacing","The insulation is generating its own heat","Heat is still spreading from the hot heater region into the rest of the block","The room temperature suddenly increases"],c:2,e:"The heater is hotter than the surrounding metal when switched off, so conduction continues until the block reaches a uniform temperature — which is why you record the highest reading reached. A rising reading after switch-off is expected behaviour, not a sign of a faulty thermometer."}
]);

QUESTIONS["s11i-13-2"] = (QUESTIONS["s11i-13-2"] || []).concat([
  {q:"An irregular stone has a mass of 135 g and displaces 50 cm³ of water. What is its density?",opts:["0.37 g/cm³","2.7 g/cm³","6750 g/cm³","185 g/cm³"],c:1,e:"ρ = m / V = 135 / 50 = 2.7 g/cm³. The answer 0.37 comes from dividing the wrong way round (volume by mass) — density is always mass divided by volume."},
  {q:"When measuring the displaced water, why must you read the measuring cylinder at eye level, at the bottom of the meniscus?",opts:["To stop the water evaporating","Because the top of the meniscus gives the true volume","To keep the water surface still","To avoid a parallax error giving a false volume reading"],c:3,e:"Viewing the scale from above or below makes the water level appear higher or lower than it really is — a parallax error. The convention is the bottom of the curved meniscus, not the top, so reading the top would also be wrong."},
  {q:"Why should the object be lowered slowly into the displacement can on a thread?",opts:["To prevent splashing, so the collected water equals only the object's true displaced volume","To stop the object dissolving in the water","To give the balance time to settle","To keep the water temperature constant"],c:0,e:"Dropping the object splashes extra water out of the spout, so the measuring cylinder collects more than the displaced volume and the density comes out too low. Most solids used (stone, metal) do not dissolve, so that is not the concern."},
  {q:"In the spring practical, a pointer is fixed to the bottom of the spring and read at eye level. What error does this reduce?",opts:["A zero error on the ruler","Heat loss to the surroundings","Parallax error in the length readings","Random error in the masses"],c:2,e:"A sharp pointer read with the eye level with the scale removes the apparent shift in position caused by viewing at an angle — parallax. Heat loss is irrelevant here; that is an error in the specific heat capacity practical, not a force–extension experiment."},
  {q:"A spring with spring constant 25 N/m supports a 0.30 kg mass (g = 10 N/kg). What is the extension?",opts:["0.012 m","0.12 m","7.5 m","75 m"],c:1,e:"Weight F = mg = 0.30 × 10 = 3.0 N. Then e = F / k = 3.0 / 25 = 0.12 m. The answer 75 comes from multiplying F by k instead of dividing — rearrange F = ke to e = F/k."},
  {q:"At the end of the spring experiment, how can a student check whether the limit of proportionality was exceeded?",opts:["Remove all the masses and check the spring returns to its original unloaded length","Add one more mass and see if the spring snaps","Measure the spring constant with a newton meter","Check whether the final extension was more than 10 cm"],c:0,e:"If the limit was passed the spring is permanently deformed, so it will be longer than its original length once unloaded — comparing with the starting measurement reveals this. There is no fixed extension such as 10 cm at which it happens; it depends on the spring."},
  {q:"In the ripple tank, why is it better to measure the length of ten wavelengths and divide by ten than to measure one wavelength?",opts:["Ten waves travel faster than one","It removes the zero error on the ruler","It changes the frequency of the waves","The ruler's uncertainty becomes a much smaller percentage of the measured distance"],c:3,e:"The ruler's reading uncertainty is fixed (about 1 mm), so spreading it across a distance ten times longer cuts the percentage uncertainty in the wavelength by a factor of ten. It cannot remove a zero error — dividing by ten shrinks that error but a systematic offset is best avoided by measuring between the same features of each wave."},
  {q:"A single wavefront in a ripple tank travels 0.6 m along the tank in 1.5 s. What is the wave speed?",opts:["0.9 m/s","2.5 m/s","0.4 m/s","1.5 m/s"],c:2,e:"v = distance / time = 0.6 / 1.5 = 0.4 m/s. The answer 0.9 comes from multiplying distance by time, which is not a physical quantity here — speed always requires dividing distance by time."},
  {q:"A stationary wave on a stretched string shows 4 equal loops along a length of 0.8 m. What is the wavelength?",opts:["0.8 m","0.4 m","0.2 m","1.6 m"],c:1,e:"Each loop is 0.8 / 4 = 0.2 m long, but one loop is only HALF a wavelength, so λ = 2 × 0.2 = 0.4 m. Choosing 0.2 m is the classic slip — forgetting that a full wavelength spans two loops."},
  {q:"What is the purpose of using a strobe lamp (or a freeze-frame photograph) with the ripple tank?",opts:["It makes the wave pattern appear stationary so the wavelength can be measured","It increases the speed of the waves across the tank","It raises the frequency of the dipper","It heats the water to keep the depth constant"],c:0,e:"Matching the strobe's flash rate to the wave frequency freezes the moving pattern, so the distance between adjacent crests can be measured accurately on the screen below. A lamp only illuminates the waves — it cannot change their speed or frequency."}
]);
