// science-y11-x14.js — Year 11 Science Topic 14 expansion: Exam Technique & Maths in Science (extra flashcards + questions for islands s11i-14-1 .. s11i-14-3)

// ── EXTRA FLASHCARDS ─────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s11i-14-1 — Command Words & 6-Mark Answers
  {id:"s11fc-14-1-6",islandId:"s11i-14-1",front:"What is the difference between 'calculate', 'determine' and 'estimate'?",
   back:"Calculate: use numbers from the question with an equation — show every step of working.\n\nDetermine: use data given in the question, a table or a graph to find a value (you may need to read values off a graph first).\n\nEstimate: give an approximate value using sensible rounding or assumptions — exact precision is not expected, but your reasoning should be visible.",difficulty:2,category:"definition"},
  {id:"s11fc-14-1-7",islandId:"s11i-14-1",front:"What do the command words 'justify' and 'predict' ask you to do?",
   back:"Justify: support a statement or conclusion using evidence — usually data from the question. Quote actual figures where possible.\n\nPredict: say what you think will happen in a situation, based on patterns in data or your scientific knowledge. You usually do not need to give a reason unless the question also says 'explain'.",difficulty:2,category:"definition"},
  {id:"s11fc-14-1-8",islandId:"s11i-14-1",front:"How are 6-mark questions marked using levels?",
   back:"Examiners place your whole answer in a level rather than ticking individual points:\n\nLevel 1 (1–2 marks): isolated relevant points, little logical order.\nLevel 2 (3–4 marks): some linked reasoning, but gaps or errors.\nLevel 3 (5–6 marks): a coherent, logically ordered answer with detailed, accurate science.\n\nTo reach Level 3, connect your points into a chain of reasoning rather than listing facts.",difficulty:3,category:"concept"},

  // s11i-14-2 — Maths Skills in Science
  {id:"s11fc-14-2-6",islandId:"s11i-14-2",front:"How do you find the gradient at a point on a CURVED graph?",
   back:"Draw a tangent — a straight line that touches the curve at that point without crossing it.\n\nThen find the gradient of the tangent:\ngradient = change in y ÷ change in x, using a large triangle on the tangent line.\n\nThis gives the rate of change at that instant — e.g. the rate of a reaction at a chosen time on a mass–time graph.",difficulty:3,category:"calculation"},
  {id:"s11fc-14-2-7",islandId:"s11i-14-2",front:"What do the unit prefixes kilo, mega, milli and micro mean, and how do you convert km/h to m/s?",
   back:"kilo (k) = ×1000\nmega (M) = ×1 000 000\nmilli (m) = ÷1000\nmicro (µ) = ÷1 000 000\n\nkm/h to m/s: multiply by 1000 (km → m) then divide by 3600 (h → s) — overall divide by 3.6.\n\nExample: 36 km/h = 36 ÷ 3.6 = 10 m/s.",difficulty:2,category:"calculation"},
  {id:"s11fc-14-2-8",islandId:"s11i-14-2",front:"How do you calculate a percentage change?",
   back:"percentage change = (change ÷ original value) × 100\n\nAlways divide by the ORIGINAL (starting) value, not the final one.\n\nExample: mass falls from 50 g to 46 g.\nChange = 4 g. Percentage change = (4 ÷ 50) × 100 = 8% decrease.\n\nState whether it is an increase or a decrease.",difficulty:2,category:"calculation"},

  // s11i-14-3 — Exam Practice & Revision Strategies
  {id:"s11fc-14-3-6",islandId:"s11i-14-3",front:"What is interleaving in revision?",
   back:"Interleaving means mixing different topics within one revision session (e.g. some biology, then a physics calculation, then chemistry), instead of spending a whole session on a single topic (blocking).\n\nIt feels harder, but switching forces your brain to retrieve the right method each time — which builds stronger, more flexible memory and mirrors how exams jump between topics.",difficulty:2,category:"concept"},
  {id:"s11fc-14-3-7",islandId:"s11i-14-3",front:"What are the steps for answering a calculation question in the exam?",
   back:"1. Write down the equation you are using.\n2. Convert any units first (e.g. g → kg, minutes → seconds).\n3. Substitute the numbers clearly.\n4. Work out the answer.\n5. Add the correct unit.\n6. Check the number of significant figures matches the data given.\n\nShowing each step protects you — method marks are available even if the final answer is wrong.",difficulty:2,category:"application"},
  {id:"s11fc-14-3-8",islandId:"s11i-14-3",front:"What should you check in the final minutes of the exam?",
   back:"1. Any blank answers — write something for every question.\n2. Calculations — units included? Sensible size? Correct significant figures?\n3. Graphs — axes labelled with quantity and unit, points plotted accurately, line of best fit drawn.\n4. Multiple choice — exactly one box ticked per question.\n5. Extended answers — have you actually answered what was asked?",difficulty:1,category:"application"}
);

// ── EXTRA TEST QUESTIONS ─────────────────────────────────────────────────────
QUESTIONS["s11i-14-1"] = (QUESTIONS["s11i-14-1"] || []).concat([
  {q:"A question says 'Determine the speed of the trolley using the graph.' What does 'determine' tell you to do?",opts:["Guess a sensible value without working","Use data read from the graph to find the value","Write a definition of speed","Describe the shape of the graph"],c:1,e:"'Determine' means use the information given — here, values read from the graph — to find the answer. Guessing without working scores nothing, because the command word requires you to use the data provided."},
  {q:"What does the command word 'estimate' require?",opts:["An exact answer to 3 significant figures","A definition of the quantity","An approximate value found using sensible rounding or assumptions","A labelled diagram"],c:2,e:"'Estimate' asks for an approximate value, often using rounded numbers or stated assumptions. Demanding 3 significant figures misreads the word — precision is not the point, but your reasoning should still be shown."},
  {q:"A question asks you to 'justify' a conclusion from an experiment. The best answer would:",opts:["Repeat the conclusion in different words","Quote specific data from the results that supports the conclusion","Describe the method used","List the equipment"],c:1,e:"'Justify' means back up the statement with evidence — quoting actual figures from the results is the strongest support. Simply rewording the conclusion adds no evidence and earns no marks."},
  {q:"You are asked to 'sketch' a graph. This means:",opts:["Plot every data point precisely on graph paper","Draw a bar chart of the results","Copy a graph from earlier in the paper","Show the general shape and trend with labelled axes"],c:3,e:"'Sketch' asks for the overall shape and key features (axes labelled, correct trend), not precise plotting. 'Plot' is the command word that requires accurate point-by-point drawing."},
  {q:"In levels-based marking of a 6-mark answer, what is the main difference between a Level 2 and a Level 3 response?",opts:["Level 3 is longer","Level 3 shows a coherent, logically linked chain of reasoning with accurate detail","Level 3 uses bullet points","Level 3 includes a diagram"],c:1,e:"Examiners award Level 3 (5–6 marks) for a well-organised answer where points are accurately linked into a logical argument. Length alone does not raise the level — a long list of unconnected facts stays in Level 1 or 2."},
  {q:"What does the command word 'predict' ask for?",opts:["A statement of what you think will happen, based on patterns or knowledge","A full explanation of a mechanism","A calculation with working","A summary of the method"],c:0,e:"'Predict' asks you to say what will happen next or in a new situation, using trends in the data or your scientific understanding. A full explanation is only needed if the question also says 'explain'."},
  {q:"Which set of linking words is most useful in an 'explain' answer?",opts:["Firstly, secondly, finally","Because, so, therefore","Both, whereas, similarly","For example, such as, including"],c:1,e:"'Explain' requires cause-and-effect reasoning, which words like 'because', 'so' and 'therefore' signal clearly. 'Both/whereas/similarly' are comparison links — useful for 'compare' questions, not for giving reasons."},
  {q:"A question begins 'Show that the energy transferred is about 500 J.' What must your answer include?",opts:["Just the final answer of 500 J","The word 'energy' used in a sentence","Full working that leads to a value close to 500 J","A drawing of the apparatus"],c:2,e:"'Show that' means the answer is already given, so the marks are entirely for the working that arrives at it. Writing only '500 J' scores nothing, because you have shown no evidence of how the value was obtained."},
  {q:"What does the command word 'define' require?",opts:["The precise meaning of a term","A worked calculation","A list of advantages and disadvantages","A description of an experiment"],c:0,e:"'Define' asks for the exact meaning of a scientific term, e.g. 'rate of reaction is the change in quantity of reactant or product per unit time'. Advantages and disadvantages belong to 'evaluate' questions instead."},
  {q:"A 6-mark question asks you to 'design an investigation'. Which of these should your plan include?",opts:["Only a list of equipment","Just the expected result","The history of the topic","The independent, dependent and control variables, plus a clear method"],c:3,e:"A planning answer needs the variable you change (independent), the one you measure (dependent), the ones you keep the same (control), and a logical step-by-step method. Equipment alone, with no procedure or variables, cannot reach the higher levels."}
]);

QUESTIONS["s11i-14-2"] = (QUESTIONS["s11i-14-2"] || []).concat([
  {q:"Rearrange the density equation ρ = m/V to find V.",opts:["V = ρm","V = ρ/m","V = m − ρ","V = m/ρ"],c:3,e:"Multiply both sides by V to get ρV = m, then divide both sides by ρ: V = m/ρ. The option V = ρ/m has the fraction upside down — a common slip when rearranging."},
  {q:"How do you find the rate of reaction at one instant from a curved mass–time graph?",opts:["Read the y-value at that time","Draw a tangent at that point and calculate its gradient","Find the total area under the curve","Divide the final mass by the total time"],c:1,e:"On a curve, the gradient changes constantly, so you draw a tangent touching the curve at the chosen time and find the tangent's gradient. Dividing final mass by total time gives only an average rate, not the rate at that instant."},
  {q:"Convert 72 km/h into m/s.",opts:["7.2 m/s","20 m/s","200 m/s","259.2 m/s"],c:1,e:"72 km/h = 72 000 m per 3600 s = 72 000 ÷ 3600 = 20 m/s (or simply 72 ÷ 3.6). The answer 259.2 comes from multiplying by 3.6 instead of dividing — the conversion goes the other way."},
  {q:"A plant's mass decreases from 80 g to 68 g. What is the percentage change?",opts:["12% decrease","17.6% decrease","85% decrease","15% decrease"],c:3,e:"Change = 80 − 68 = 12 g. Percentage change = (12 ÷ 80) × 100 = 15% decrease. Dividing by the final value (12 ÷ 68 ≈ 17.6%) is wrong — always divide by the original value."},
  {q:"A student mixes 20 cm³ of acid with 60 cm³ of water. What is the ratio of acid to water in its simplest form?",opts:["1:3","20:60","3:1","1:4"],c:0,e:"Divide both sides of 20:60 by 20 to get 1:3. The ratio 1:4 confuses the part-to-part ratio with the fraction of acid in the whole mixture (20 out of 80)."},
  {q:"Calculate (3 × 10⁴) × (2 × 10³), giving your answer in standard form.",opts:["6 × 10¹²","5 × 10⁷","6 × 10⁷","6 × 10¹"],c:2,e:"Multiply the numbers (3 × 2 = 6) and add the powers of ten (4 + 3 = 7), giving 6 × 10⁷. The answer 6 × 10¹² comes from multiplying the powers instead of adding them."},
  {q:"How many significant figures are in the measurement 0.02030 kg?",opts:["3","5","2","4"],c:3,e:"Counting starts at the first non-zero digit: 2, 0, 3, then the trailing zero after the decimal point also counts — 4 significant figures. The two leading zeros are not significant, which is why 5 is wrong."},
  {q:"On a straight-line graph, what does the y-intercept represent?",opts:["The gradient of the line","The value of y when x is zero","The maximum value of y","The value of x when y is zero"],c:1,e:"The y-intercept is where the line crosses the y-axis, which is the value of y when x equals zero. The point where y equals zero is the x-intercept — the two are easily mixed up."},
  {q:"Which of these describes a correctly drawn line of best fit?",opts:["A line joining every data point dot-to-dot","A line through the origin in every case","A smooth line with roughly equal numbers of points on each side, ignoring anomalies","A line through the first and last points only"],c:2,e:"A line of best fit shows the overall trend: it should balance the scatter of points and pass close to most of them, leaving anomalies out. Joining points dot-to-dot treats random scatter as real, which misrepresents the pattern."},
  {q:"Four repeat readings of a temperature rise are 12 °C, 14 °C, 13 °C and 25 °C. What is the best value for the mean?",opts:["16 °C","14 °C","13 °C","12 °C"],c:2,e:"The 25 °C reading is an anomaly and should be excluded. Mean = (12 + 14 + 13) ÷ 3 = 39 ÷ 3 = 13 °C. Including the anomaly gives 64 ÷ 4 = 16 °C, which distorts the result."}
]);

QUESTIONS["s11i-14-3"] = (QUESTIONS["s11i-14-3"] || []).concat([
  {q:"What is 'interleaving' as a revision technique?",opts:["Revising one topic until it is perfect before moving on","Mixing different topics within a single revision session","Reading two textbooks at the same time","Highlighting notes in different colours"],c:1,e:"Interleaving means switching between topics in one session, which forces your brain to retrieve the right method each time and builds flexible memory. Studying one topic in a long block feels easier but produces weaker long-term recall."},
  {q:"You have 5 minutes left and an untouched 6-mark question. What is the best strategy?",opts:["Leave it blank and check earlier answers","Write everything you know about the general topic","Write the key scientific points briefly in a logical order","Copy out the question to fill the space"],c:2,e:"Even a condensed answer can climb the levels if the points are relevant and logically linked, so brief targeted points can rescue several marks. Writing everything you know wastes time on material that does not answer the question."},
  {q:"While checking a calculation at the end of the exam, which error is MOST commonly worth fixing?",opts:["A missing unit on the final answer","Untidy handwriting in the working","Using a pen instead of a pencil","Writing the equation on two lines"],c:0,e:"A missing or wrong unit frequently costs a mark and takes seconds to fix, so it is a high-value check. Untidy working loses nothing as long as it is readable."},
  {q:"Why is it useful to do past papers under timed conditions?",opts:["It makes revision quicker overall","Examiners give extra credit for practice","It removes the need to learn the content","You train pacing and recall under the same pressure as the real exam"],c:3,e:"Timed practice builds the skill of allocating roughly a minute per mark and retrieving knowledge under pressure, which untimed practice cannot replicate. It supplements content learning — it does not replace it."},
  {q:"What is a sensible strategy for a multiple-choice question when you are unsure of the answer?",opts:["Always pick the longest option","Eliminate the options you know are wrong, then choose from those left","Leave it blank to avoid losing marks","Pick the same letter as the previous answer"],c:1,e:"Ruling out clearly wrong options raises your odds considerably — often to a 50:50 choice. Leaving it blank is the worst move because multiple-choice questions carry no penalty for a wrong answer."},
  {q:"A question says 'Use the data in Table 1 to evaluate the claim.' What must your answer contain?",opts:["A general opinion about the topic","A description of how the table was produced","Specific figures quoted from the table, weighed up to reach a conclusion","The definition of every column heading"],c:2,e:"'Use the data' is an instruction: marks are reserved for answers that quote actual values from the table and weigh them up. A general opinion with no figures cannot access those marks, however sensible it sounds."},
  {q:"What does the 'forgetting curve' show?",opts:["Memory of new material fades rapidly over time unless it is reviewed","All revision is wasted after a week","Memory improves automatically with age","Difficult topics are forgotten more slowly than easy ones"],c:0,e:"The forgetting curve shows that recall drops steeply within days of learning something, and that each well-timed review flattens the curve. It does not say revision is wasted — it shows exactly why spaced reviews work."},
  {q:"In a calculation question, why should you always show your working?",opts:["It uses up the answer space neatly","The examiner deducts marks for short answers","Working is only needed in maths exams","Method marks can be awarded even if the final answer is wrong"],c:3,e:"Mark schemes award separate marks for the correct equation and substitution, so visible working can earn most of the marks even when the arithmetic slips. A bare wrong answer with no working scores zero."},
  {q:"Which is the better plan for the night before a science exam?",opts:["Stay up late re-reading every topic","A short review of key facts, then a full night's sleep","Learn two new topics you skipped","Do three full past papers after midnight"],c:1,e:"Sleep consolidates memory, so a brief review followed by proper rest leaves you sharper than late-night cramming. Staying up late re-reading adds little new memory and harms concentration the next day."},
  {q:"When self-testing with flashcards, what should you do with the cards you answer correctly with confidence?",opts:["Review them less often, and focus more time on the cards you get wrong","Remove them permanently from your deck","Re-read them immediately five more times","Copy them out into your notes"],c:0,e:"Sorting cards so that weak ones come back sooner and strong ones less often (as in the Leitner system) targets effort where it is needed. Removing strong cards permanently risks forgetting them before the exam — they still need occasional review."}
]);
