// content/y10/science/islands/x01.js — EXPANSION: Topic 1 extra flashcards + questions.
// Loads AFTER t01.js. Authored by the atlas-content skill. All items original.

// ── EXTRA FLASHCARDS ────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s10i-01-1 — Enzymes & Digestion
  {id:"s10fc-01-1-6", islandId:"s10i-01-1", front:"Why does food need to be digested before it can be used by the body?",
   back:"Food molecules such as starch, proteins and lipids are LARGE and INSOLUBLE — too big to pass through the wall of the small intestine into the blood.\n\nDigestion breaks them into SMALL, SOLUBLE molecules (glucose, amino acids, glycerol and fatty acids) that can:\n• be absorbed through the gut wall\n• dissolve in the blood plasma\n• be carried to cells for respiration and building new molecules", difficulty:1, category:"concept"},
  {id:"s10fc-01-1-7", islandId:"s10i-01-1", front:"Outline the required practical investigating the effect of pH on amylase.",
   back:"1. Use buffer solutions to set up a range of pH values\n2. Mix amylase and starch solution at each pH and start the stopwatch\n3. Every 30 seconds, transfer a drop of the mixture onto iodine solution on a spotting tile\n4. While starch remains, the iodine turns blue-black; when all the starch is digested it stays orange-brown\n5. Record the time for starch to disappear at each pH\n\nThe SHORTEST time shows the pH closest to the enzyme's optimum.", difficulty:2, category:"application"},
  {id:"s10fc-01-1-8", islandId:"s10i-01-1", front:"What are the products of digestion used for once absorbed?",
   back:"• Glucose (from starch) — used in respiration to release energy; excess is stored as glycogen\n• Amino acids (from proteins) — reassembled into new proteins the body needs, such as enzymes and muscle\n• Glycerol and fatty acids (from lipids) — used to build cell membranes and new lipids, and as an energy store\n\nKey idea: digestion takes molecules apart so the body can rebuild its OWN versions from the pieces.", difficulty:2, category:"concept"},

  // s10i-01-2 — The Digestive System
  {id:"s10fc-01-2-6", islandId:"s10i-01-2", front:"Define the levels of organisation from cell to organ system, using the digestive system as the example.",
   back:"Cell → Tissue → Organ → Organ system\n\n• Cell: basic unit of life, e.g. a muscle cell in the stomach wall\n• Tissue: a group of similar cells working together, e.g. muscular tissue that churns food\n• Organ: several tissues working together for a function, e.g. the stomach (muscular, glandular and epithelial tissue)\n• Organ system: organs working together, e.g. the whole digestive system", difficulty:1, category:"definition"},
  {id:"s10fc-01-2-7", islandId:"s10i-01-2", front:"How are digested food molecules actually absorbed in the small intestine?",
   back:"Two routes, two mechanisms:\n\n• Glucose and amino acids pass into the blood capillaries of the villi — mainly by diffusion, plus ACTIVE TRANSPORT when the concentration in the gut is lower than in the blood (uses energy from respiration)\n• Fatty acids and glycerol pass into the LACTEAL (a lymph vessel) in the centre of each villus and travel in the lymph before joining the blood", difficulty:2, category:"concept"},
  {id:"s10fc-01-2-8", islandId:"s10i-01-2", front:"Why doesn't the stomach digest itself?",
   back:"The stomach contains hydrochloric acid (about pH 2) and pepsin, a protease — and the stomach wall itself is made of protein.\n\nIt is protected because glandular tissue in the lining secretes a thick layer of MUCUS.\n\nThe mucus coats the wall, forming a barrier that stops the acid and pepsin reaching and breaking down the stomach's own cells.", difficulty:2, category:"concept"},

  // s10i-01-3 — Food Tests & Practical Skills
  {id:"s10fc-01-3-6", islandId:"s10i-01-3", front:"How do you prepare a solid food sample before carrying out food tests?",
   back:"1. Grind the food with a pestle and mortar to break it up\n2. Mix with distilled water to dissolve the soluble substances\n3. Filter (or decant) to remove the solid lumps, leaving a clear solution to test\n\nWhy: the test reagents need to react with molecules IN SOLUTION — lumps of food can hide colour changes and give unreliable results. Distilled water is used because tap water may contain impurities.", difficulty:1, category:"application"},
  {id:"s10fc-01-3-7", islandId:"s10i-01-3", front:"Describe the emulsion test for lipids and explain why ethanol is needed.",
   back:"Method:\n1. Shake the food sample with ethanol — lipids dissolve in ethanol but not in water\n2. Pour the ethanol mixture into a tube of water\n\nPositive result: a milky WHITE emulsion forms (the lipid comes out of solution as tiny droplets that scatter light)\n\nNegative result: the mixture stays clear\n\nSafety: ethanol is highly flammable — keep it well away from naked flames.", difficulty:2, category:"application"},
  {id:"s10fc-01-3-8", islandId:"s10i-01-3", front:"What are the main safety precautions for the food test reagents?",
   back:"• Sodium hydroxide (Biuret test) — corrosive: wear eye protection; rinse skin immediately if splashed\n• Ethanol (emulsion test) — highly flammable: no naked flames nearby\n• Benedict's test — heat using a water bath, not a Bunsen flame directly, and point tubes away from people\n• Iodine solution — can irritate skin and stains clothing\n\nEye protection should be worn throughout all the food tests.", difficulty:1, category:"application"},

  // s10i-01-4 — Transport in Plants
  {id:"s10fc-01-4-6", islandId:"s10i-01-4", front:"How are root hair cells adapted for absorbing water and mineral ions?",
   back:"• Long, thin hair-like projection — gives a LARGE surface area in contact with soil water\n• Thin cell wall and membrane — short pathway for absorption\n• Many mitochondria — release energy by respiration\n\nWater enters by OSMOSIS (down its concentration gradient).\nMineral ions enter by ACTIVE TRANSPORT, because ions are usually MORE concentrated inside the cell than in the soil — moving them in requires energy.", difficulty:2, category:"concept"},
  {id:"s10fc-01-4-7", islandId:"s10i-01-4", front:"Why are most stomata on the LOWER surface of a leaf, and why do they close at night?",
   back:"Lower surface: it is shaded and cooler than the upper surface, so less water evaporates through the stomata — the plant loses less water while still allowing gas exchange.\n\nClosed at night: photosynthesis cannot happen in the dark, so the plant does not need carbon dioxide. Guard cells close the stomata to conserve water when there is no benefit to keeping them open.", difficulty:2, category:"concept"},
  {id:"s10fc-01-4-8", islandId:"s10i-01-4", front:"How do you calculate the rate of water uptake from potometer results?",
   back:"Rate = distance moved by the air bubble ÷ time taken\n\nExample: the bubble moves 36 mm in 4 minutes:\nRate = 36 ÷ 4 = 9 mm per minute\n\nTo make results reliable:\n• Repeat and calculate a mean\n• Reset the bubble using the water reservoir between runs\n• Change only ONE factor (e.g. wind) and control all the others", difficulty:2, category:"calculation"}
);

// ── EXTRA QUESTIONS ─────────────────────────────────────────────────────────
QUESTIONS["s10i-01-1"] = (QUESTIONS["s10i-01-1"] || []).concat([
  {q:"Why must starch be digested before it can enter the bloodstream?",
   opts:["Starch is poisonous to blood cells","Starch molecules are too large and insoluble to be absorbed","Starch reacts with stomach acid","Starch can only travel in the lymph"], c:1,
   e:"Starch molecules are large and insoluble, so they cannot pass through the wall of the small intestine. Digestion breaks starch into small, soluble glucose molecules that can be absorbed. Starch is not poisonous — it simply cannot cross the gut wall in its original form."},
  {q:"Why is each enzyme described as 'specific'?",
   opts:["It only works at exactly 37 degrees Celsius","Its active site is complementary in shape to only one substrate","It can only be used once before breaking down","It is only found in one organ of the body"], c:1,
   e:"An enzyme's active site has a particular shape that only a matching (complementary) substrate can fit into — like a key in a lock. The temperature option is tempting, but enzymes work across a range of temperatures, and many enzymes are made in several organs."},
  {q:"In which organ is amylase NOT produced?",
   opts:["Salivary glands","Pancreas","Small intestine","Stomach"], c:3,
   e:"Amylase is made in the salivary glands, pancreas and small intestine. The stomach produces pepsin (a protease) and hydrochloric acid instead — and the stomach's pH of about 2 would denature amylase anyway, which is why starch digestion pauses there."},
  {q:"After protein is digested, what does the body use the absorbed products for?",
   opts:["They are stored unchanged in the liver","Amino acids are used to build the body's own new proteins","They are converted directly into starch","They are used to emulsify fats"], c:1,
   e:"Protein digestion produces amino acids, which cells reassemble into the body's own proteins, such as enzymes and muscle tissue. They are not converted to starch — starch is a plant storage carbohydrate, and emulsifying fats is the job of bile, not amino acids."},
  {q:"An enzyme-controlled reaction is very slow at 5 degrees Celsius. Why?",
   opts:["The enzyme has been denatured by the cold","Molecules move slowly, so enzyme and substrate collide less often","The active site freezes solid","The substrate dissolves at low temperatures"], c:1,
   e:"At low temperatures, molecules have less kinetic energy, so enzymes and substrates collide less frequently and the reaction is slow. The key distinction: cold does NOT denature enzymes — warming the mixture restores full activity, unlike overheating, which changes the active site permanently."},
  {q:"In the pH-amylase practical, a drop of the reaction mixture added to iodine stays orange-brown. What does this show?",
   opts:["All the starch has been digested","The amylase has been denatured","No reaction has started yet","Glucose has been produced from protein"], c:0,
   e:"Iodine only turns blue-black when starch is present. An orange-brown result means amylase has broken down all the starch, so the reaction is complete. If the amylase had been denatured, starch would remain and the iodine would still turn blue-black."},
  {q:"A student measures the time for amylase to digest starch at three pH values: pH 5 takes 95 s, pH 7 takes 20 s, pH 9 takes 70 s. What can be concluded?",
   opts:["The optimum pH is 5 because the reaction lasted longest","The optimum pH is close to 7 because starch was digested fastest","Amylase works equally well at all three pH values","The optimum pH must be above 9"], c:1,
   e:"The shortest time means the fastest rate, so the enzyme works best near pH 7. A common error is choosing the longest time as 'best' — but a long time means the enzyme was working slowly, not thoroughly. The rate falls on either side of pH 7, so the optimum is unlikely to be above 9."},
  {q:"Lipase digests 0.6 g of fat in 30 seconds. What is the average rate of digestion?",
   opts:["0.02 g per second","0.2 g per second","18 g per second","0.05 g per second"], c:0,
   e:"Rate = amount changed divided by time = 0.6 g divided by 30 s = 0.02 g per second. The distractor 18 comes from multiplying instead of dividing — remember that rate asks how much happens in EACH second, so you divide the amount by the time."},
  {q:"Bile speeds up fat digestion, yet bile is not an enzyme. How does it work?",
   opts:["It breaks the chemical bonds in fat molecules","It emulsifies fat into smaller droplets, increasing the surface area for lipase","It contains a small amount of lipase","It dissolves fat completely into the blood"], c:1,
   e:"Bile physically breaks large fat droplets into many smaller ones (emulsification), giving lipase a much larger surface area to act on. It does not break chemical bonds — only the enzyme lipase does that. This is a physical change helping a chemical one."},
  {q:"A patient's pancreas releases its juices into a small intestine that bile has failed to neutralise, leaving it acidic. Predict the effect on digestion there.",
   opts:["Digestion speeds up because acid activates all enzymes","Pancreatic enzymes work more slowly or are denatured because they need alkaline conditions","Only starch digestion is affected","There is no effect because enzymes work at any pH"], c:1,
   e:"Pancreatic amylase, protease and lipase have an optimum around pH 7 to 8, so an acidic small intestine slows them down and can denature them — affecting starch, protein AND fat digestion, not just starch. Acid only suits pepsin, which works in the stomach."}
]);

QUESTIONS["s10i-01-2"] = (QUESTIONS["s10i-01-2"] || []).concat([
  {q:"What is a tissue?",
   opts:["A single specialised cell","A group of similar cells working together to perform a function","Several organs working together","Any part of the body that contains blood"], c:1,
   e:"A tissue is a group of similar cells working together, such as muscular tissue in the stomach wall. Several organs working together form an organ system — that is one level higher in the hierarchy of organisation."},
  {q:"Why is the stomach classed as an organ rather than a tissue?",
   opts:["Because it is large","Because it contains several different tissues working together","Because it produces acid","Because it is connected to other organs"], c:1,
   e:"An organ is made of more than one tissue working together — the stomach has muscular tissue to churn food, glandular tissue to make acid and pepsin, and epithelial tissue to cover its surfaces. Size and connections are irrelevant to the definition."},
  {q:"How is the stomach wall protected from its own acid and pepsin?",
   opts:["A layer of mucus coats the lining","The wall is made of material that protein cannot stick to","Pepsin is switched off near the stomach wall","Bile constantly neutralises the acid in the stomach"], c:0,
   e:"Glandular tissue in the stomach lining secretes a thick layer of mucus, which forms a barrier between the wall and the acidic, protein-digesting contents. Bile is the tempting wrong answer — but bile is released into the small intestine, not the stomach."},
  {q:"Into which structure are fatty acids and glycerol absorbed inside a villus?",
   opts:["The blood capillaries","The lacteal","The pancreatic duct","The hepatic artery"], c:1,
   e:"Fatty acids and glycerol enter the lacteal, a lymph vessel in the centre of each villus, and travel in the lymph before joining the blood. Glucose and amino acids are the ones absorbed directly into the blood capillaries."},
  {q:"Near the end of a meal's absorption, glucose concentration in the gut falls below that in the blood, yet glucose absorption continues. How?",
   opts:["By diffusion, which works against a gradient","By active transport, using energy from respiration","By osmosis through the villi","Glucose absorption stops completely at this point"], c:1,
   e:"When the gradient runs the wrong way, glucose is moved into the blood by active transport, which uses energy released by respiration. Diffusion can only move substances DOWN a concentration gradient, so it cannot explain absorption here. Osmosis applies to water only."},
  {q:"Which sequence shows the correct route taken by food through the digestive system?",
   opts:["Mouth, stomach, oesophagus, small intestine, large intestine","Mouth, oesophagus, stomach, small intestine, large intestine","Mouth, oesophagus, stomach, large intestine, small intestine","Mouth, oesophagus, small intestine, stomach, large intestine"], c:1,
   e:"Food travels: mouth, oesophagus, stomach, small intestine, large intestine, rectum. A common slip is swapping the small and large intestines — remember that digestion and absorption must finish in the SMALL intestine before water is reclaimed in the large intestine."},
  {q:"A patient has their gallbladder removed. What is the most likely effect on digestion of a fatty meal?",
   opts:["Protein digestion stops completely","Fat digestion is slower because less bile is delivered to emulsify the fat","Starch can no longer be broken down","Food can no longer pass into the small intestine"], c:1,
   e:"The gallbladder stores and releases bile, so without it less bile reaches the small intestine at once. Fat stays in larger droplets with a smaller surface area, so lipase digests it more slowly. The liver still makes bile, so digestion is slower — not impossible — and protein and starch are unaffected."},
  {q:"In coeliac disease the villi become flattened and damaged. Explain why patients may lose weight despite eating normally.",
   opts:["Damaged villi produce too much enzyme","The surface area for absorption is reduced, so fewer nutrients enter the blood","Peristalsis stops working","The stomach can no longer churn food"], c:1,
   e:"Flattened villi mean a much smaller surface area, so digested food is absorbed more slowly and incompletely — nutrients pass out of the body unused, causing weight loss. Peristalsis and churning are muscle actions elsewhere in the gut and are not affected by villus damage."},
  {q:"Astronauts in orbit can swallow and digest food normally even though there is no effective gravity. Why?",
   opts:["Food floats gently down the oesophagus","Peristalsis squeezes food along the gut by muscle contractions, so gravity is not needed","Stomach acid pulls food downwards","Astronauts only eat liquid food"], c:1,
   e:"Peristalsis is the wave of muscular contraction behind the food (with relaxation ahead of it) that pushes food along the gut. Because muscles do the pushing, swallowing works in any orientation — gravity plays no essential part in moving food through the digestive system."},
  {q:"Which adaptation of the villi maintains a steep concentration gradient for absorption?",
   opts:["Their finger-like shape","Their walls being one cell thick","Their rich blood supply constantly carrying absorbed food away","The mucus covering their surface"], c:2,
   e:"The dense capillary network carries absorbed molecules away as soon as they cross, keeping the concentration in the blood low so diffusion continues rapidly. The thin wall is a tempting answer, but it shortens the diffusion DISTANCE — it is the moving blood that maintains the GRADIENT."}
]);

QUESTIONS["s10i-01-3"] = (QUESTIONS["s10i-01-3"] || []).concat([
  {q:"Before testing a piece of bread for nutrients, why is it ground up and mixed with distilled water?",
   opts:["To kill any bacteria in the food","To dissolve the soluble substances so reagents can react with them in solution","To make the bread taste better","To heat the sample evenly"], c:1,
   e:"Grinding breaks the food up and mixing with distilled water dissolves the soluble molecules, giving a solution the reagents can react with so colour changes are clear. Distilled water is used because tap water may contain impurities — but the purpose is dissolving, not sterilising."},
  {q:"In the emulsion test for lipids, what is the correct order of steps?",
   opts:["Shake the food with water, then add ethanol","Shake the food with ethanol, then pour the mixture into water","Heat the food with ethanol in a water bath","Add iodine to the food, then add ethanol"], c:1,
   e:"Lipids dissolve in ethanol but not in water, so you shake the sample with ethanol first, then pour it into water — the lipid comes out of solution as tiny droplets, forming a milky white emulsion. Starting with water is the classic error: the lipid would never dissolve in the first place."},
  {q:"Which safety precaution is essential when carrying out the emulsion test?",
   opts:["Wear gloves because ethanol is corrosive","Keep ethanol away from naked flames because it is highly flammable","Carry out the test in a fume cupboard because ethanol is radioactive","Heat the ethanol strongly before use"], c:1,
   e:"Ethanol is highly flammable, so all naked flames must be extinguished or kept well away. It is not corrosive (that hazard belongs to sodium hydroxide in the Biuret test), and heating ethanol over a flame would be dangerous, not helpful."},
  {q:"Which of the four standard food tests requires the sample to be heated?",
   opts:["The iodine test for starch","The Biuret test for protein","The Benedict's test for reducing sugars","The Sudan III test for lipids"], c:2,
   e:"Only Benedict's test needs heating — the tube is placed in a water bath at about 75 degrees Celsius for around 5 minutes before any colour change appears. The starch, protein and lipid tests all work at room temperature; heating them is a common wasted step in exams."},
  {q:"What is the main hazard of the sodium hydroxide used in the Biuret test?",
   opts:["It is highly flammable","It is corrosive and can damage skin and eyes","It gives off a poisonous gas when mixed with food","It stains clothing blue-black"], c:1,
   e:"Sodium hydroxide is corrosive, so eye protection must be worn and any splashes rinsed off immediately. Flammability is ethanol's hazard, and staining is associated with iodine — mixing up the hazards of the different reagents is a frequent exam slip."},
  {q:"A food sample turns iodine blue-black, turns Biuret reagent purple, and leaves heated Benedict's solution blue. What does it contain?",
   opts:["Starch and protein, but no reducing sugar","Reducing sugar and protein, but no starch","Starch only","Protein and reducing sugar only"], c:0,
   e:"Blue-black with iodine shows starch; purple with Biuret shows protein; Benedict's staying blue after heating shows no reducing sugar. The trap is misreading the Benedict's result — blue is the NEGATIVE colour, so the sample cannot contain reducing sugar."},
  {q:"A fizzy drink tastes very sweet, yet a heated Benedict's test on it stays blue. What is the best explanation?",
   opts:["The test was carried out wrongly","The drink contains sucrose, a non-reducing sugar that Benedict's cannot detect","Sweet things never contain sugar","The drink contains protein instead"], c:1,
   e:"Benedict's solution only detects REDUCING sugars such as glucose. Sucrose is a non-reducing sugar, so a sucrose-sweetened drink gives a negative result even though it is sweet. Assuming the test failed is tempting, but a correct test can genuinely give this result."},
  {q:"Two milk samples are tested with Benedict's solution: sample P turns brick red, sample Q turns green. What can be concluded?",
   opts:["P contains more reducing sugar than Q","Q contains more reducing sugar than P","P contains protein and Q does not","Both contain the same amount of sugar"], c:0,
   e:"The colour sequence runs blue to green to yellow to orange to brick red as sugar concentration increases, so brick red (P) indicates more reducing sugar than green (Q). Choosing Q is the classic error from forgetting that green is near the START of the sequence."},
  {q:"A student adds Benedict's solution to a glucose solution but forgets to heat it. The mixture stays blue. What kind of result is this?",
   opts:["A true negative — there is no sugar present","A false negative — sugar is present but the test conditions were wrong","A false positive — the test wrongly detected sugar","A true positive — blue confirms glucose"], c:1,
   e:"Glucose IS present, but without heating the reaction does not happen, so no colour change appears — a false negative. It is not a true negative, because the blue colour reflects the missing heating step, not the actual absence of sugar."},
  {q:"A student tests one tube containing only distilled water alongside the food samples in every test. What is the purpose of this tube?",
   opts:["To clean the reagents before use","To act as a control showing the negative result colour for comparison","To dilute the food samples","To speed up the colour changes"], c:1,
   e:"The water-only tube is a control: it shows what a negative result looks like, so any colour change in the food tubes can be confidently attributed to the nutrient, not to the reagent or the method. It does not dilute or clean anything — it is there purely for comparison."}
]);

QUESTIONS["s10i-01-4"] = (QUESTIONS["s10i-01-4"] || []).concat([
  {q:"By which process does water enter a root hair cell from the soil?",
   opts:["Active transport","Osmosis","Transpiration","Translocation"], c:1,
   e:"Water moves into the root hair cell by osmosis, from the dilute soil water into the more concentrated cell contents — no energy is needed because water moves down its concentration gradient. Active transport is for mineral IONS; transpiration and translocation happen elsewhere in the plant."},
  {q:"Why must root hair cells use active transport to absorb mineral ions?",
   opts:["Ions are too large to diffuse","Ions are usually more concentrated inside the cell than in the soil, so they must be moved against the gradient","Ions can only move when it is dark","Osmosis only works for ions"], c:1,
   e:"Mineral ions are typically at a higher concentration inside the root hair cell than in the dilute soil water, so they must be moved AGAINST their concentration gradient — this needs active transport, using energy from respiration. Osmosis applies only to water, never to ions."},
  {q:"Why are most stomata found on the lower surface of a leaf?",
   opts:["The lower surface receives more sunlight","The lower surface is shaded and cooler, so less water is lost through the stomata","Carbon dioxide is heavier than air and sinks","Guard cells cannot survive in direct light"], c:1,
   e:"The underside of the leaf is shaded and cooler, so water evaporates more slowly from stomata positioned there — the plant gets gas exchange with less water loss. The carbon dioxide answer sounds scientific but gas mixing in air means gases reach both surfaces equally well."},
  {q:"What is the role of lignin in xylem vessels?",
   opts:["It transports the dissolved sugars","It strengthens the walls so the vessels do not collapse","It pumps water upwards","It stores energy for the plant"], c:1,
   e:"Lignin is the tough material that strengthens xylem walls, letting the hollow tubes withstand the pressures of the transpiration stream without collapsing. Nothing pumps the water — it is pulled up by evaporation from the leaves — and sugars travel in the phloem, not the xylem."},
  {q:"Why do stomata generally close at night?",
   opts:["To stop oxygen entering the leaf","Photosynthesis stops in the dark, so the plant closes them to conserve water","Guard cells die at night and regrow in the morning","To prevent insects entering the leaf"], c:1,
   e:"In darkness there is no photosynthesis, so the leaf does not need to take in carbon dioxide. Closing the stomata cuts water loss with no cost to the plant. Guard cells are living cells that change shape to open and close the pore — they certainly do not die each night."},
  {q:"In a potometer experiment, the air bubble moves 45 mm in 3 minutes. What is the rate of water uptake?",
   opts:["135 mm per minute","15 mm per minute","42 mm per minute","48 mm per minute"], c:1,
   e:"Rate = distance divided by time = 45 mm divided by 3 minutes = 15 mm per minute. The answer 135 comes from multiplying instead of dividing — a rate always asks how far the bubble moves in ONE unit of time, so divide the distance by the time."},
  {q:"A student coats the lower surface of a plant's leaves with petroleum jelly and finds that mass loss almost stops. What does this show?",
   opts:["The jelly poisons the plant","Most water vapour is lost through stomata on the lower leaf surface","The plant has stopped photosynthesising permanently","Water is mainly lost through the stem"], c:1,
   e:"The jelly blocks the stomata. Because covering only the LOWER surface nearly stopped the mass loss, most of the stomata — and therefore most transpiration — must be on the underside of the leaves. The jelly does not poison the plant; it simply seals the pores."},
  {q:"When setting up a potometer, why is the shoot cut and assembled under water?",
   opts:["To wash the leaves","To stop air entering the xylem and breaking the continuous column of water","To cool the shoot down","To dissolve more minerals into the stem"], c:1,
   e:"If air enters the cut xylem, it creates an air lock that breaks the unbroken column of water, so the shoot can no longer draw water up and the readings fail. Cutting and connecting everything under water keeps the column continuous. Washing or cooling the shoot is not the purpose."},
  {q:"On a hot, windy day a gardener notices her plants wilting even though the soil is moist. What is the best explanation?",
   opts:["The roots have stopped absorbing water completely","Water is being lost by transpiration faster than the roots can replace it","The xylem has reversed direction","The phloem is carrying water out of the leaves"], c:1,
   e:"Heat and wind both increase the rate of transpiration, so on a hot, windy day water can leave the leaves faster than the roots can take it up — cells lose water and the plant wilts. The roots are still working, and neither xylem flow reversing nor phloem carrying water is correct biology."},
  {q:"In autumn, a potato plant moves sugars from its leaves down to its underground tubers for storage. Which tissue carries the sugars, and what is the process called?",
   opts:["Xylem; transpiration","Phloem; translocation","Xylem; translocation","Phloem; transpiration"], c:1,
   e:"Sugars made in photosynthesis travel in the phloem, and their transport around the plant — including DOWN to storage organs like tubers — is called translocation. Xylem is the tempting distractor because the flow is downwards, but xylem only ever carries water and minerals upwards."}
]);
