// content/y10/science/islands/x02.js — EXPANSION: Topic 2 extra flashcards + questions.
// Loads AFTER t02.js. Authored by the atlas-content skill. All items original.

FLASHCARDS.push(
  // s10i-02-1 — The Heart & Blood Vessels
  {id:"s10fc-02-1-6", islandId:"s10i-02-1", front:"Trace the full path of a blood cell from the body, through the heart and back to the body.",
   back:"1. Deoxygenated blood enters the right atrium through the vena cava.\n2. It passes into the right ventricle.\n3. The right ventricle pumps it through the pulmonary artery to the lungs, where it picks up oxygen.\n4. Oxygenated blood returns through the pulmonary vein to the left atrium.\n5. It passes into the left ventricle.\n6. The left ventricle pumps it through the aorta to the body.\n\nNote the blood passes through the heart twice in one circuit — a double circulatory system.", difficulty:3, category:"application"},
  {id:"s10fc-02-1-7", islandId:"s10i-02-1", front:"Compare stents and statins as treatments for coronary heart disease.",
   back:"Both reduce the risk of a heart attack, but work differently.\n\n• Stents are wire mesh tubes surgically inserted to physically hold a narrowed coronary artery open, restoring blood flow immediately. They do not treat the underlying cause and there is a risk from surgery.\n\n• Statins are drugs taken regularly that lower blood cholesterol (specifically LDL), slowing the build-up of fatty material. They act long-term but can have side effects and must be taken for life.", difficulty:3, category:"concept"},
  {id:"s10fc-02-1-8", islandId:"s10i-02-1", front:"What is the natural pacemaker and how can an artificial one help?",
   back:"The natural pacemaker is a group of cells in the wall of the right atrium that produces a regular electrical impulse. This impulse spreads across the heart muscle, making it contract and setting the resting heart rate.\n\nIf the natural pacemaker produces an irregular rhythm, an artificial pacemaker can be fitted. This is a small electrical device, usually placed under the skin near the collarbone, that sends regular electrical impulses to keep the heart beating steadily.", difficulty:2, category:"concept"},

  // s10i-02-2 — Blood & Its Components
  {id:"s10fc-02-2-6", islandId:"s10i-02-2", front:"How does haemoglobin transport oxygen?",
   back:"Haemoglobin is the red protein found inside red blood cells.\n\n• In the lungs, where oxygen concentration is high, haemoglobin binds with oxygen to form oxyhaemoglobin.\n• In the body's respiring tissues, where oxygen concentration is low, oxyhaemoglobin breaks down, releasing the oxygen to the cells.\n\nThis binding is reversible, which allows the same molecule to pick up and release oxygen repeatedly.", difficulty:2, category:"concept"},
  {id:"s10fc-02-2-7", islandId:"s10i-02-2", front:"How do lymphocytes differ from phagocytes in fighting disease?",
   back:"Both are white blood cells, but they defend the body in different ways.\n\n• Phagocytes carry out phagocytosis — they engulf and digest any pathogen. This is a non-specific defence.\n\n• Lymphocytes are specific: they recognise a particular antigen on a pathogen and produce matching antibodies that lock onto and destroy it. Some lymphocytes produce antitoxins that neutralise toxins released by bacteria. Lymphocytes also provide long-term immunity through memory cells.", difficulty:3, category:"concept"},
  {id:"s10fc-02-2-8", islandId:"s10i-02-2", front:"Describe the sequence of events when blood clots.",
   back:"1. A blood vessel is damaged, exposing the tissue beneath.\n2. Platelets gather at the wound and release chemicals.\n3. These chemicals trigger a series of reactions.\n4. The soluble protein fibrinogen is converted into insoluble fibrin.\n5. Fibrin forms a mesh of threads across the wound.\n6. The mesh traps red blood cells, forming a clot that dries into a scab.\n\nThe clot prevents further blood loss and stops pathogens entering the body.", difficulty:2, category:"application"},

  // s10i-02-3 — Lungs & Gas Exchange
  {id:"s10fc-02-3-6", islandId:"s10i-02-3", front:"How does the composition of inhaled air differ from exhaled air?",
   back:"Inhaled (breathed in) air contains roughly:\n• 21% oxygen\n• 0.04% carbon dioxide\n• 78% nitrogen\n\nExhaled (breathed out) air contains roughly:\n• 16% oxygen\n• 4% carbon dioxide\n• 78% nitrogen (unchanged)\n\nThe lungs remove only some of the oxygen from each breath and add carbon dioxide from respiration. Exhaled air is also warmer and more saturated with water vapour.", difficulty:2, category:"concept"},
  {id:"s10fc-02-3-7", islandId:"s10i-02-3", front:"Explain how pressure changes drive air into and out of the lungs.",
   back:"Air always moves from a region of higher pressure to lower pressure.\n\n• Inhalation: muscles contract, the thorax volume increases, so the pressure inside the lungs falls below atmospheric pressure. Air flows in.\n\n• Exhalation: muscles relax, the thorax volume decreases, so the pressure inside the lungs rises above atmospheric pressure. Air flows out.\n\nThe lungs themselves contain no muscle — they are inflated and deflated by the movement of the diaphragm and intercostal muscles.", difficulty:3, category:"application"},
  {id:"s10fc-02-3-8", islandId:"s10i-02-3", front:"What is breathing rate and how does exercise affect it?",
   back:"Breathing rate is the number of breaths taken per minute. It can be calculated as:\n\nbreathing rate = number of breaths / time in minutes\n\nDuring exercise, muscles respire faster and need more oxygen while producing more carbon dioxide. Both breathing rate and the depth of each breath increase, so more air is exchanged each minute. This keeps the supply of oxygen and the removal of carbon dioxide matched to the body's demand.", difficulty:2, category:"application"},

  // s10i-02-4 — Health, Disease & Risk Factors
  {id:"s10fc-02-4-6", islandId:"s10i-02-4", front:"What are the human and financial costs of non-communicable diseases?",
   back:"Non-communicable diseases such as cardiovascular disease, type 2 diabetes and cancer carry costs at several levels.\n\n• To the individual: reduced quality of life, shorter lifespan, lost income.\n• To families: emotional strain and loss of earnings if a member cannot work.\n• To the wider community and country: high costs of treatment and research for health services, and reduced productivity in the workforce.\n\nUnderstanding risk factors helps target prevention and reduce these costs.", difficulty:2, category:"application"},
  {id:"s10fc-02-4-7", islandId:"s10i-02-4", front:"How can smoking and diet during pregnancy affect an unborn baby?",
   back:"Some risk factors affect not only the person but also a developing fetus.\n\n• Smoking during pregnancy reduces the oxygen reaching the fetus (carbon monoxide binds to haemoglobin), which can lead to low birth weight and premature birth.\n• A poor diet, or alcohol, can affect the baby's development and growth.\n\nThis shows that risk factors can have effects across more than one generation.", difficulty:2, category:"application"},
  {id:"s10fc-02-4-8", islandId:"s10i-02-4", front:"How is sampling used to investigate risk factors in a population?",
   back:"Scientists cannot study everyone, so they study a sample — a smaller group meant to represent the whole population.\n\n• A larger sample size gives more reliable results and reduces the effect of chance.\n• The sample should be chosen to avoid bias (for example, a fair mix of ages, sexes and lifestyles).\n• Results from a good sample can be used to estimate the rate of disease and its risk factors across the whole population.\n\nThis is how large studies have linked factors such as smoking to disease.", difficulty:3, category:"concept"}
);

QUESTIONS["s10i-02-1"] = (QUESTIONS["s10i-02-1"] || []).concat([
  {q:"Which blood vessel returns oxygenated blood from the lungs to the heart?",
   opts:["Pulmonary artery","Pulmonary vein","Vena cava","Aorta"], c:1,
   e:"The pulmonary vein carries oxygenated blood from the lungs to the left atrium. It is the only vein that carries oxygenated blood. The pulmonary artery does the opposite — it carries deoxygenated blood from the heart to the lungs."},
  {q:"Into which chamber does the vena cava deliver blood?",
   opts:["Right atrium","Left atrium","Right ventricle","Left ventricle"], c:0,
   e:"The vena cava returns deoxygenated blood from the body to the right atrium. From there it passes to the right ventricle, which pumps it to the lungs. It does not enter the left side, which handles oxygenated blood."},
  {q:"Why does the heart muscle need its own blood supply from the coronary arteries?",
   opts:["To cool the heart down","To supply oxygen and glucose for respiration","To remove blood clots","To produce new red blood cells"], c:1,
   e:"The coronary arteries supply the heart muscle with the oxygen and glucose it needs for aerobic respiration to release energy for continuous contraction. The blood inside the chambers cannot supply the muscle wall itself."},
  {q:"What is the role of the septum in the heart?",
   opts:["To prevent oxygenated and deoxygenated blood mixing","To control heart rate","To pump blood into the aorta","To store oxygen"], c:0,
   e:"The septum is the muscular wall separating the left and right sides of the heart, keeping oxygenated and deoxygenated blood apart. It does not pump blood — that is the job of the ventricles."},
  {q:"Where in the heart is the natural pacemaker found?",
   opts:["The left ventricle","The wall of the right atrium","The aorta","The septum"], c:1,
   e:"The natural pacemaker is a group of cells in the wall of the right atrium. It produces the electrical impulse that sets the resting heart rate. It is not located in the ventricles or the major vessels."},
  {q:"What is the main purpose of fitting a stent in a coronary artery?",
   opts:["To lower blood cholesterol","To hold a narrowed artery open and keep blood flowing","To replace a faulty heart valve","To speed up the heart rate"], c:1,
   e:"A stent is a mesh tube that physically holds a narrowed coronary artery open so blood can keep reaching the heart muscle. Lowering cholesterol is the job of statins, a separate treatment."},
  {q:"A person has a stroke volume of 80 cm3 and a heart rate of 75 beats per minute. What is their cardiac output? (cardiac output = stroke volume x heart rate)",
   opts:["155 cm3/min","6000 cm3/min","1.07 cm3/min","9375 cm3/min"], c:1,
   e:"Cardiac output = 80 x 75 = 6000 cm3/min. The tempting wrong answer 155 comes from adding the two values instead of multiplying them."},
  {q:"Arteries have thick, elastic, muscular walls mainly because they must withstand:",
   opts:["Low pressure from the veins","High pressure from blood leaving the heart","The pull of valves","The flow of lymph"], c:1,
   e:"Arteries carry blood pumped directly from the heart at high pressure, so thick elastic muscular walls stop them bursting and recoil to smooth the flow. Veins carry low-pressure blood, which is why they instead rely on valves."},
  {q:"A patient's resting heart rate rises from 70 to 84 beats per minute. By what percentage has it increased?",
   opts:["14%","20%","84%","16.7%"], c:1,
   e:"The increase is 84 - 70 = 14 beats. Percentage increase = (14 / 70) x 100 = 20%. The answer 14% wrongly uses the raw difference as if it were the percentage."},
  {q:"Statins are sometimes preferred to stents for managing coronary heart disease because statins:",
   opts:["Work instantly during a heart attack","Replace the coronary arteries","Tackle the build-up of fatty material over the long term without surgery","Increase blood cholesterol"], c:2,
   e:"Statins lower blood cholesterol over time, slowing the fatty build-up that narrows arteries, and avoid the risks of surgery. They are not an emergency treatment — a stent gives the immediate physical widening of an artery."}
]);

QUESTIONS["s10i-02-2"] = (QUESTIONS["s10i-02-2"] || []).concat([
  {q:"What is formed when haemoglobin binds with oxygen in the lungs?",
   opts:["Carboxyhaemoglobin","Oxyhaemoglobin","Fibrin","Plasma"], c:1,
   e:"In the lungs, haemoglobin binds reversibly with oxygen to form oxyhaemoglobin, which is carried to the tissues. Fibrin is a clotting protein and plasma is the liquid part of blood, neither involves oxygen binding."},
  {q:"Why do mature red blood cells have no nucleus?",
   opts:["To make them lighter","To leave more room for haemoglobin","To help them divide quickly","To produce antibodies"], c:1,
   e:"Having no nucleus leaves more space inside the cell for haemoglobin, so each red blood cell can carry more oxygen. Red blood cells cannot divide, and they do not produce antibodies — that is the role of lymphocytes."},
  {q:"Which white blood cells produce antibodies against a specific pathogen?",
   opts:["Phagocytes","Lymphocytes","Platelets","Erythrocytes"], c:1,
   e:"Lymphocytes recognise specific antigens and produce matching antibodies. Phagocytes instead engulf and digest pathogens non-specifically, and erythrocytes (red blood cells) carry oxygen."},
  {q:"During clotting, the soluble protein fibrinogen is converted into:",
   opts:["Haemoglobin","Plasma","Antitoxin","Insoluble fibrin"], c:3,
   e:"Fibrinogen is converted into insoluble fibrin, which forms a mesh of threads to trap blood cells and seal the wound. Haemoglobin carries oxygen and antitoxins neutralise bacterial toxins — neither forms the clot mesh."},
  {q:"Approximately what percentage of blood volume is plasma?",
   opts:["5%","25%","55%","95%"], c:2,
   e:"Plasma makes up roughly 55% of blood volume, with cells and platelets making up the rest. Choosing 95% wrongly assumes blood is almost entirely liquid."},
  {q:"What does plasma carry from the liver to the kidneys for removal?",
   opts:["Oxygen","Haemoglobin","Platelets","Urea"], c:3,
   e:"Plasma transports urea, a waste product made in the liver, to the kidneys where it is excreted in urine. Oxygen is carried by haemoglobin inside red blood cells, not dissolved in plasma."},
  {q:"Oxyhaemoglobin breaks down to release oxygen in respiring tissues mainly because there the oxygen concentration is:",
   opts:["High","Low","The same as in the lungs","Zero everywhere"], c:1,
   e:"In respiring tissues oxygen concentration is low, so oxyhaemoglobin breaks down and releases oxygen to the cells. In the lungs oxygen is high, which is why haemoglobin binds it there instead."},
  {q:"A blood sample contains 5,000,000 red blood cells and 7,000 white blood cells per cubic millimetre. Roughly how many times more red than white cells are there?",
   opts:["About 7 times","About 70 times","About 700 times","About 7000 times"], c:2,
   e:"5,000,000 divided by 7,000 is about 714, which is roughly 700 times. This shows red blood cells massively outnumber white blood cells, matching their role in oxygen transport."},
  {q:"A person at high altitude produces more red blood cells over several weeks. The most likely benefit is:",
   opts:["Faster blood clotting","Greater capacity to carry oxygen where air is thin","More antibody production","Lower blood pressure"], c:1,
   e:"At high altitude the air contains less oxygen, so making more red blood cells increases the blood's oxygen-carrying capacity. Clotting and antibody production are functions of platelets and lymphocytes, not red blood cells."},
  {q:"Carbon monoxide from cigarette smoke binds firmly to haemoglobin. The main consequence is that the blood:",
   opts:["Clots more slowly","Produces more white blood cells","Carries less oxygen to the tissues","Loses its plasma"], c:2,
   e:"Carbon monoxide binds to haemoglobin in place of oxygen and does not release easily, so the blood carries less oxygen to respiring tissues. It does not affect clotting or the volume of plasma."}
]);

QUESTIONS["s10i-02-3"] = (QUESTIONS["s10i-02-3"] || []).concat([
  {q:"Roughly what percentage of inhaled air is oxygen?",
   opts:["4%","16%","21%","78%"], c:2,
   e:"Inhaled air is about 21% oxygen. The value 16% is the oxygen content of exhaled air, and 78% is the proportion of nitrogen, which stays the same."},
  {q:"Compared with inhaled air, exhaled air contains:",
   opts:["More oxygen and less carbon dioxide","Less oxygen and more carbon dioxide","More nitrogen","No water vapour"], c:1,
   e:"Exhaled air has less oxygen (about 16% versus 21%) and more carbon dioxide (about 4% versus 0.04%) because respiration uses oxygen and produces carbon dioxide. Nitrogen is unchanged and exhaled air is more, not less, saturated with water vapour."},
  {q:"What happens to the volume of the thorax during inhalation?",
   opts:["It decreases","It increases","It stays the same","It increases then immediately decreases"], c:1,
   e:"During inhalation the diaphragm and intercostal muscles contract, increasing the thorax volume. This lowers the pressure inside the lungs so air flows in. The volume decreases during exhalation."},
  {q:"Air moves into the lungs during inhalation because the pressure inside the lungs becomes:",
   opts:["Higher than atmospheric pressure","Lower than atmospheric pressure","Equal to atmospheric pressure","Zero"], c:1,
   e:"Increasing the thorax volume lowers the pressure inside the lungs below atmospheric pressure, so air flows in from high to low pressure. If lung pressure were higher than atmospheric, air would flow out instead."},
  {q:"Which structure keeps the trachea open during breathing?",
   opts:["C-shaped rings of cartilage","Cilia","Valves","Alveoli"], c:0,
   e:"C-shaped rings of cartilage support the trachea and stop it collapsing as air pressure changes. Cilia help sweep mucus and trapped particles upward but do not provide structural support."},
  {q:"Which feature of alveoli most directly increases the rate of diffusion by maintaining a steep concentration gradient?",
   opts:["A moist lining","A rich network of capillaries","A layer of cartilage","Cilia on the surface"], c:1,
   e:"A rich capillary network constantly removes oxygenated blood and brings deoxygenated blood, keeping the concentration gradient steep so diffusion stays rapid. A moist lining helps gases dissolve but does not maintain the gradient."},
  {q:"A person takes 36 breaths in 3 minutes. What is their breathing rate?",
   opts:["12 breaths per minute","36 breaths per minute","108 breaths per minute","33 breaths per minute"], c:0,
   e:"Breathing rate = 36 / 3 = 12 breaths per minute. The answer 108 wrongly multiplies the breaths by the minutes instead of dividing."},
  {q:"During vigorous exercise, breathing rate and depth increase mainly to:",
   opts:["Cool the body down","Increase the number of alveoli","Supply more oxygen and remove more carbon dioxide","Lower the blood pressure"], c:2,
   e:"Exercising muscles respire faster, so they need more oxygen and produce more carbon dioxide. Faster, deeper breathing increases gas exchange to match this demand. The number of alveoli does not change with exercise."},
  {q:"In a model lung, pulling down a rubber sheet (the diaphragm) makes the balloons (lungs) inflate. This shows that the lungs inflate when:",
   opts:["Pressure in the bell jar increases","The volume increases and pressure falls","The balloons contract","Cartilage rings collapse"], c:1,
   e:"Pulling the rubber sheet down increases the volume inside the jar, lowering the pressure so air pushes the balloons open, modelling inhalation. The lungs contain no muscle of their own, so they cannot contract to inflate."},
  {q:"A patient with emphysema has many alveoli walls broken down into fewer, larger air spaces. This reduces gas exchange mainly because it:",
   opts:["Increases the surface area for diffusion","Decreases the surface area for diffusion","Removes all the capillaries instantly","Makes the diffusion distance shorter"], c:1,
   e:"Breaking many small alveoli into fewer large spaces decreases the total surface area available for diffusion, so less oxygen enters the blood each second. A smaller surface area slows diffusion, the opposite of what efficient gas exchange needs."}
]);

QUESTIONS["s10i-02-4"] = (QUESTIONS["s10i-02-4"] || []).concat([
  {q:"Which of these is a communicable disease?",
   opts:["Measles","Type 2 diabetes","Coronary heart disease","Lung cancer"], c:0,
   e:"Measles is caused by a virus (a pathogen) and can spread between people, so it is communicable. Type 2 diabetes, coronary heart disease and lung cancer are non-communicable and cannot be passed from person to person."},
  {q:"A risk factor is best described as something that:",
   opts:["Always causes a disease","Is linked to an increased rate of a disease","Cures a disease","Only affects communicable diseases"], c:1,
   e:"A risk factor is linked to an increased rate of a disease but does not guarantee it. Many people exposed to a risk factor never develop the disease, which is why 'always causes' is wrong."},
  {q:"Why can a virus living inside cells be relevant to cancer?",
   opts:["It always cures tumours","It can act as a trigger for some cancers","It only causes allergies","It replaces white blood cells"], c:1,
   e:"Some viruses living inside cells can act as a trigger for certain cancers, an example of one disease type influencing another. Viruses do not cure tumours, and causing cancer is different from causing allergies."},
  {q:"Smoking during pregnancy can lead to a low birth weight baby mainly because:",
   opts:["The mother eats less","Carbon monoxide reduces the oxygen reaching the fetus","The baby produces too many platelets","Nicotine increases the baby's appetite"], c:1,
   e:"Carbon monoxide in tobacco smoke binds to haemoglobin, reducing the oxygen carried to the fetus, which slows growth and can cause low birth weight. The effect is about oxygen supply, not the mother's appetite."},
  {q:"Why does a larger sample size usually make the results of a health study more reliable?",
   opts:["It makes the study cheaper","It reduces the effect of chance and unusual individuals","It guarantees a causal mechanism","It removes the need for a control group"], c:1,
   e:"A larger sample reduces the impact of chance variation and unusual individuals, giving results that better represent the population. It does not by itself prove a causal mechanism, which still requires understanding how a factor causes the disease."},
  {q:"Which combination of risk factors is most strongly linked to type 2 diabetes?",
   opts:["Smoking and ionising radiation","Poor diet, obesity and lack of exercise","Drinking alcohol and viral infection","Inherited genes only"], c:1,
   e:"Poor diet, obesity and lack of exercise together are the risk factors most strongly linked to type 2 diabetes. Smoking and ionising radiation are linked more to cancer and lung disease, not primarily to diabetes."},
  {q:"In a town of 20,000 people, 1,500 are recorded as having a particular disease. What is the rate of the disease?",
   opts:["1.5%","7.5%","13.3%","15%"], c:1,
   e:"Rate = (1500 / 20000) x 100 = 7.5%. The answer 15% comes from misplacing the decimal point when dividing."},
  {q:"A graph shows that as average daily exercise increases, the rate of cardiovascular disease falls. This shows a:",
   opts:["Positive correlation","Negative correlation","Proven cause","Random pattern"], c:1,
   e:"As one variable goes up the other goes down, which is a negative correlation. A correlation, positive or negative, does not by itself prove cause without an understood mechanism."},
  {q:"Which statement about benign tumours is correct?",
   opts:["They spread through the blood to form secondary tumours","They grow in one place and do not invade other tissues","They are always more dangerous than malignant tumours","They are caused only by viruses"], c:1,
   e:"Benign tumours grow in one place, often within a membrane, and do not invade other tissues, so they are usually less dangerous. It is malignant tumours that spread through the blood to form secondary tumours."},
  {q:"Non-communicable diseases create a financial cost to a country mainly because:",
   opts:["They spread quickly between people","They are caused by pathogens","They only affect older people","Treatment is expensive and ill workers are less productive"], c:3,
   e:"Non-communicable diseases are costly because long-term treatment and research are expensive and affected workers may be unable to work, reducing productivity. They are not spread between people and are not caused by pathogens."}
]);
