// content/y10/science/islands/x03.js — EXPANSION: Topic 3 extra flashcards + questions.
// Loads AFTER t03.js. Authored by the atlas-content skill. All items original.

FLASHCARDS.push(
  // s10i-03-1 — Pathogens & Transmission
  {id:"s10fc-03-1-6", islandId:"s10i-03-1", front:"What does the term communicable disease mean, and how does it differ from a non-communicable disease?",
   back:"A communicable (infectious) disease is one that can be spread from one organism to another. It is caused by a pathogen.\n\nExamples: measles, malaria, salmonella.\n\nA non-communicable disease cannot be passed on. It is not caused by a pathogen and is usually long-lasting (chronic).\n\nExamples: heart disease, type 2 diabetes, most cancers.", difficulty:1, category:"definition"},
  {id:"s10fc-03-1-7", islandId:"s10i-03-1", front:"How is HIV transmitted, and what happens if it is not treated?",
   back:"HIV is a virus spread by sexual contact and by the exchange of body fluids such as blood (for example when drug users share needles).\n\nAt first it causes a mild, flu-like illness.\n\nIf it is not controlled with antiretroviral drugs, the virus attacks and destroys the body's immune cells. Eventually the immune system is so badly damaged that the body cannot fight off other infections or cancers. This late stage is called AIDS.", difficulty:2, category:"application"},
  {id:"s10fc-03-1-8", islandId:"s10i-03-1", front:"Why are poultry in the UK vaccinated against Salmonella?",
   back:"Salmonella bacteria living in poultry can contaminate eggs and meat. If people eat contaminated food the bacteria release toxins, causing food poisoning (fever, vomiting, diarrhoea, cramps).\n\nVaccinating poultry reduces the number of birds carrying Salmonella, so far fewer eggs and less meat are contaminated. This breaks the transmission route to humans and lowers the number of food-poisoning cases.", difficulty:2, category:"application"},

  // s10i-03-2 — The Body's Defences
  {id:"s10fc-03-2-6", islandId:"s10i-03-2", front:"What is the role of lysozyme in tears and saliva?",
   back:"Lysozyme is an enzyme found in tears and saliva.\n\nIt is a non-specific chemical defence. It breaks down (digests) the cell walls of bacteria, causing the bacterial cells to burst and die.\n\nBecause the eyes and mouth are moist openings exposed to the environment, lysozyme helps protect these surfaces from bacterial infection.", difficulty:2, category:"concept"},
  {id:"s10fc-03-2-7", islandId:"s10i-03-2", front:"How does blood clotting help defend the body against pathogens?",
   back:"When the skin is cut, the physical barrier is broken and pathogens could enter the blood.\n\nPlatelets and clotting proteins cause the blood to clot, forming a mesh that seals the wound. The clot dries into a scab.\n\nThis quickly closes the gap in the skin, stopping pathogens from getting in and giving the skin time to repair underneath.", difficulty:2, category:"concept"},
  {id:"s10fc-03-2-8", islandId:"s10i-03-2", front:"What is the difference between an antibody and an antitoxin?",
   back:"Both are produced by lymphocytes (a type of white blood cell).\n\nAn antibody is a protein that locks onto a specific antigen on a pathogen's surface, clumping pathogens together or marking them for destruction.\n\nAn antitoxin is a protein that binds to and neutralises a toxin (a poison) released by bacteria, preventing the toxin from damaging cells.", difficulty:2, category:"concept"},

  // s10i-03-3 — Vaccination & Drugs
  {id:"s10fc-03-3-6", islandId:"s10i-03-3", front:"Name a drug originally extracted from a plant or microorganism and state its source.",
   back:"Many drugs were first discovered in plants and microorganisms:\n\n• Digitalis — a heart drug originally extracted from foxgloves.\n\n• Aspirin — a painkiller originally derived from a chemical found in willow bark.\n\n• Penicillin — the first antibiotic, discovered by Alexander Fleming from the Penicillium mould.", difficulty:1, category:"application"},
  {id:"s10fc-03-3-7", islandId:"s10i-03-3", front:"What three things is a new drug tested for, and what are the main stages of testing?",
   back:"New medical drugs are tested for toxicity (is it harmful?), efficacy (does it work?) and the correct dose.\n\nStages:\n1. Preclinical testing — on cells, tissues and live animals in the laboratory.\n2. Clinical trials — on humans: first healthy volunteers to check safety, then patients to find the optimum dose. Testing starts at a very low dose.\n\nResults are peer reviewed by other scientists before publication to prevent false claims.", difficulty:2, category:"concept"},
  {id:"s10fc-03-3-8", islandId:"s10i-03-3", front:"What is a placebo and what is a double-blind trial?",
   back:"A placebo is a dummy treatment that contains no active drug. Comparing the drug group with the placebo group shows whether the drug itself is causing any effect.\n\nIn a double-blind trial, neither the patients nor the doctors know who has received the real drug and who has received the placebo.\n\nThis prevents bias from affecting how results are recorded or how patients feel.", difficulty:2, category:"application"},

  // s10i-03-4 — Plant Diseases & Defences
  {id:"s10fc-03-4-6", islandId:"s10i-03-4", front:"How is rose black spot spread, and how can it be treated?",
   back:"Rose black spot is a fungal disease.\n\nSpread: fungal spores are carried by water (rain splash) and by wind to other leaves and plants.\n\nTreatment:\n• Remove and destroy the affected leaves so the spores cannot spread.\n• Spray the plant with a fungicide to kill the fungus.", difficulty:2, category:"application"},
  {id:"s10fc-03-4-7", islandId:"s10i-03-4", front:"Give two examples of mechanical defences in plants and explain how each works.",
   back:"Mechanical defences are physical structures or movements that protect a plant from being eaten or infected:\n\n• Thorns and hairs — stop or discourage animals from touching and eating the plant.\n\n• Drooping or curling leaves when touched — can knock off insects or startle a herbivore.\n\n• Mimicry — some plants mimic other organisms or appear unhealthy/dangerous, tricking animals into leaving them alone.", difficulty:2, category:"concept"},
  {id:"s10fc-03-4-8", islandId:"s10i-03-4", front:"Why does a magnesium deficiency reduce the rate of photosynthesis in a plant?",
   back:"Magnesium ions are needed by the plant to make chlorophyll.\n\nChlorophyll is the green pigment that absorbs light energy for photosynthesis.\n\nWithout enough magnesium the plant cannot make enough chlorophyll, so the leaves turn yellow (chlorosis). With less chlorophyll, less light is absorbed, so the rate of photosynthesis falls and growth slows.", difficulty:2, category:"application"},

  // s10i-03-5 — Monoclonal Antibodies
  {id:"s10fc-03-5-6", islandId:"s10i-03-5", front:"What is a hybridoma and why is it useful?",
   back:"A hybridoma is the cell formed by fusing a lymphocyte with a tumour cell.\n\nIt is useful because it combines two helpful properties:\n• From the lymphocyte — it makes the desired specific antibody.\n• From the tumour cell — it divides rapidly and continuously.\n\nThis means a hybridoma can be cloned to make a large amount of one identical (monoclonal) antibody.", difficulty:2, category:"concept"},
  {id:"s10fc-03-5-7", islandId:"s10i-03-5", front:"Why are monoclonal antibodies useful for finding very small amounts of a substance in the blood?",
   back:"Monoclonal antibodies bind to only one specific antigen or molecule at a single binding site.\n\nThis high specificity means they will lock onto the target molecule even when it is present in tiny amounts, and ignore everything else.\n\nA coloured or fluorescent label can be attached to the antibody, so wherever the target is found it is marked and can be detected and measured.", difficulty:2, category:"application"},
  {id:"s10fc-03-5-8", islandId:"s10i-03-5", front:"Why is a mouse used in the first stage of making monoclonal antibodies?",
   back:"To make an antibody against a chosen target, the immune system must first be exposed to that target.\n\nA mouse is injected with the antigen. The mouse's immune system responds by making lymphocytes that produce the specific antibody against that antigen.\n\nThese lymphocytes are then removed and fused with tumour cells. The mouse simply provides the lymphocytes that already make the correct antibody.", difficulty:2, category:"concept"}
);

QUESTIONS["s10i-03-1"] = (QUESTIONS["s10i-03-1"] || []).concat([
  {q:"Which of the following diseases is communicable?",
   opts:["Type 2 diabetes","Coronary heart disease","Measles","Most cancers"], c:2,
   e:"Measles is caused by a virus that spreads between people, so it is communicable. Diabetes, heart disease and most cancers are not caused by pathogens and cannot be passed on, so they are non-communicable diseases."},
  {q:"Why do antibiotics have no effect on a viral infection such as measles?",
   opts:["Viruses lack the bacterial structures that antibiotics target","The patient is already immune","Antibiotics only work on protists","Viruses are killed by stomach acid first"], c:0,
   e:"Antibiotics work by attacking structures found in bacteria, such as cell walls. Viruses do not have these structures and reproduce inside host cells, so antibiotics cannot affect them. Being immune is not the reason the drug fails."},
  {q:"Which pathogen type causes athlete's foot?",
   opts:["A virus","A fungus","A protist","A bacterium"], c:1,
   e:"Athlete's foot is a fungal infection of the skin. It is not viral, bacterial or caused by a protist. Fungi can grow on the skin and spread by contact, especially in warm, damp conditions."},
  {q:"A mosquito carries the malaria protist from an infected person to a healthy person. What is the correct term for the mosquito's role?",
   opts:["Pathogen","Host","Vector","Antigen"], c:2,
   e:"The mosquito is a vector — an organism that carries and transmits a pathogen without being the cause of the disease itself. The pathogen is the Plasmodium protist; the human is the host."},
  {q:"How is HIV most commonly spread?",
   opts:["By airborne droplets in coughs","Through contaminated drinking water","By the exchange of body fluids such as blood and through sexual contact","By the bite of a mosquito"], c:2,
   e:"HIV is spread through body fluids, for example by sexual contact or by sharing needles. It is not airborne and is not spread by water or mosquitoes, so isolating coughing patients would not prevent it."},
  {q:"What is the main way that bacteria like Salmonella make a person feel ill?",
   opts:["They block the airways physically","They digest the person's red blood cells","They release toxins that damage cells and tissues","They use up all the oxygen in the blood"], c:2,
   e:"Bacteria such as Salmonella produce toxins that damage cells, causing symptoms like fever, vomiting and diarrhoea. They do not block airways or directly consume blood cells; the toxins are the main cause of the illness."},
  {q:"A village has a high rate of cholera, which is spread through contaminated water. Which measure would most directly reduce its spread?",
   opts:["Distributing mosquito nets","Providing clean, treated drinking water","Vaccinating cattle in the area","Spraying insecticide on crops"], c:1,
   e:"Cholera is a water-borne bacterial disease, so providing clean drinking water removes the transmission route. Mosquito nets and insecticide target vector-borne diseases like malaria, which is not how cholera spreads."},
  {q:"A scientist finds that a new plant disease produces a mosaic pattern of discolouration but cannot be treated with fungicide. Which pathogen type is the most likely cause?",
   opts:["A fungus","A virus","A protist","A bacterium"], c:1,
   e:"A mosaic discolouration pattern is characteristic of tobacco mosaic virus, and a virus would not respond to fungicide. Rose black spot, a fungus, causes spots rather than a mosaic and would be affected by fungicide."},
  {q:"In a country, malaria cases fall sharply after stagnant ponds near homes are drained. Which idea best explains this result?",
   opts:["Draining ponds kills the Plasmodium protist directly in the water","Mosquitoes breed in stagnant water, so removing it reduces their numbers and fewer bites occur","People drink less contaminated water once ponds are gone","The protist needs standing water to survive outside a host"], c:1,
   e:"Mosquitoes lay eggs and breed in stagnant water, so draining it reduces the mosquito population and therefore the number of infective bites. The protist is spread by bites, not by drinking water, so option about drinking is wrong."},
  {q:"Why is isolating an infected person an effective way to control a disease like measles but less useful for controlling a non-communicable disease?",
   opts:["Non-communicable diseases are always more dangerous","Isolation cures measles but not other diseases","Non-communicable diseases are only caught from animals","Measles is passed between people, but non-communicable diseases are not caused by a pathogen and cannot be passed on"], c:3,
   e:"Isolation stops a pathogen passing from one person to another, so it works for communicable measles. A non-communicable disease is not caused by a pathogen and cannot be transmitted, so isolation cannot prevent its spread."}
]);

QUESTIONS["s10i-03-2"] = (QUESTIONS["s10i-03-2"] || []).concat([
  {q:"Which substance in tears and saliva destroys bacteria?",
   opts:["Hydrochloric acid","Lysozyme","Mucus","Bile"], c:1,
   e:"Tears and saliva contain the enzyme lysozyme, which breaks down bacterial cell walls so the bacteria burst. Hydrochloric acid is found in the stomach, and mucus traps pathogens rather than destroying them chemically."},
  {q:"How does the formation of a blood clot help protect the body from infection?",
   opts:["It produces antibodies against pathogens","It engulfs and digests pathogens","It seals a wound so pathogens cannot enter","It neutralises bacterial toxins"], c:2,
   e:"A clot seals a break in the skin, restoring the physical barrier and stopping pathogens entering through the wound. It does not make antibodies, carry out phagocytosis or neutralise toxins — those are roles of white blood cells."},
  {q:"What is the difference in function between an antibody and an antitoxin?",
   opts:["Antibodies neutralise toxins; antitoxins bind to antigens","Antibodies bind to antigens on pathogens; antitoxins neutralise toxins released by bacteria","Both are made by phagocytes","Antibodies kill bacteria directly with acid"], c:1,
   e:"Antibodies lock onto specific antigens on pathogens, while antitoxins neutralise the poisons (toxins) bacteria release. Both are made by lymphocytes, not phagocytes, and neither uses acid to kill bacteria."},
  {q:"Which sequence correctly describes phagocytosis?",
   opts:["Recognise antigen, produce antibody, form memory cell","Detect pathogen, engulf pathogen, digest pathogen","Produce antitoxin, neutralise toxin, leave the body","Clump pathogens, burst host cells, release histamine"], c:1,
   e:"In phagocytosis a phagocyte detects, engulfs and then digests the pathogen. Producing antibodies and forming memory cells are roles of lymphocytes, not the steps of phagocytosis."},
  {q:"Why is the skin described as a non-specific defence?",
   opts:["It only protects against one named pathogen","It acts as a barrier against all types of pathogen, whatever they are","It produces antibodies tailored to each pathogen","It only works after a vaccination"], c:1,
   e:"The skin blocks the entry of pathogens in general, regardless of type, so it is non-specific. Producing tailored antibodies is the specific response carried out by lymphocytes, not the skin."},
  {q:"What is the function of mucus in the airways?",
   opts:["To kill bacteria using acid","To produce antibodies","To trap pathogens and dust so they can be removed","To transport oxygen to the blood"], c:2,
   e:"Mucus traps pathogens and dust particles in inhaled air; cilia then sweep the mucus up to the throat. Mucus does not use acid, make antibodies or carry oxygen."},
  {q:"A person recovers from chicken pox and does not catch it again. Which cells are responsible for the rapid second response?",
   opts:["Phagocytes","Red blood cells","Memory lymphocytes","Platelets"], c:2,
   e:"Memory lymphocytes remain after the first infection and quickly produce large amounts of the correct antibody if the pathogen returns. Phagocytes act non-specifically, red blood cells carry oxygen and platelets help clotting."},
  {q:"A graph shows that after a second exposure to the same pathogen, antibodies are produced faster and reach a higher concentration than after the first exposure. What best explains this?",
   opts:["The pathogen has become weaker over time","Antibiotics taken earlier are still working","Memory cells from the first infection respond quickly to the same antigen","The skin has become a stronger barrier"], c:2,
   e:"The faster, larger second response is due to memory cells recognising the antigen and rapidly producing antibodies. It is not caused by a weaker pathogen, leftover antibiotics or changes in the skin."},
  {q:"Why can a specific antibody bind to one type of pathogen but not another?",
   opts:["Antibodies are complementary in shape to a particular antigen","Antibodies are larger than all pathogens","Each antibody contains acid that only some pathogens resist","Antibodies are made from the pathogen itself"], c:0,
   e:"An antibody has a shape complementary to a specific antigen, so it only fits that antigen, like a lock and key. Antibodies are not made from the pathogen and do not rely on size or acid to be selective."},
  {q:"Cilia in the trachea of a smoker can be damaged. Suggest why this makes lung infections more likely.",
   opts:["Less stomach acid is produced","Antibodies can no longer be produced","The skin barrier is weakened","Mucus and trapped pathogens are not swept out of the airways and build up in the lungs"], c:3,
   e:"If cilia are damaged they cannot sweep mucus and trapped pathogens up to the throat, so mucus collects in the lungs where pathogens can multiply. Stomach acid, antibody production and the skin are unaffected by ciliary damage."}
]);

QUESTIONS["s10i-03-3"] = (QUESTIONS["s10i-03-3"] || []).concat([
  {q:"Which heart drug was originally extracted from foxgloves?",
   opts:["Aspirin","Penicillin","Digitalis","Insulin"], c:2,
   e:"Digitalis, used to treat heart conditions, was originally extracted from foxgloves. Aspirin came from willow, penicillin from the Penicillium mould, and insulin is a hormone, not a plant extract."},
  {q:"Who discovered penicillin, and from what source?",
   opts:["Edward Jenner, from cowpox","Alexander Fleming, from the Penicillium mould","Louis Pasteur, from willow bark","Gregor Mendel, from pea plants"], c:1,
   e:"Alexander Fleming discovered penicillin, the first antibiotic, from the Penicillium mould. Jenner is linked to early vaccination, Pasteur to germ theory, and Mendel to genetics, none of which is penicillin's source."},
  {q:"In drug testing, what is the purpose of a placebo?",
   opts:["To increase the dose given to patients","To replace the active drug permanently","To act as a dummy treatment so the drug's real effect can be measured","To cure the disease faster"], c:2,
   e:"A placebo contains no active drug, so comparing it with the real drug shows whether the drug itself causes any effect. It is not used to increase doses or to cure anything; it is a comparison."},
  {q:"What is tested during the preclinical stage of developing a new drug?",
   opts:["The drug is tested on cells, tissues and live animals","The drug is given to thousands of patients","The drug is sold in pharmacies","The drug is tested only on healthy human volunteers"], c:0,
   e:"Preclinical testing uses cells, tissues and live animals in the laboratory. Testing on healthy volunteers and then patients happens later, during clinical trials, not in the preclinical stage."},
  {q:"Why are new drugs given to healthy volunteers before being given to patients in clinical trials?",
   opts:["To find out if the drug cures the disease","To measure how quickly the disease spreads","To create herd immunity","To check the drug is safe and to study side effects"], c:3,
   e:"Healthy volunteers are used first to check the drug is safe and to identify side effects at low doses. Whether the drug works (efficacy) and the best dose are then tested on patients who have the illness."},
  {q:"Why does taking antibiotics for a viral cold contribute to antibiotic resistance without curing the cold?",
   opts:["Antibiotics make viruses reproduce faster","Colds are caused by resistant fungi","Antibiotics cannot kill viruses, but their use still selects for resistant bacteria in the body","Antibiotics turn viruses into bacteria"], c:2,
   e:"Antibiotics do not affect viruses, so they cannot cure a viral cold, yet their use kills non-resistant bacteria and allows resistant ones to survive and multiply. Antibiotics do not change viruses into bacteria."},
  {q:"In a double-blind trial, neither the patient nor the doctor knows who received the real drug. Why is this important?",
   opts:["It makes the trial cheaper to run","It prevents bias affecting how results are judged","It speeds up the immune response","It removes the need for a placebo group"], c:1,
   e:"Keeping both patient and doctor unaware prevents their expectations from biasing how symptoms are reported or recorded. It does not make trials cheaper, change the immune response, or remove the need for a placebo."},
  {q:"A doctor wants to slow the development of antibiotic resistance in the community. Which action would best achieve this?",
   opts:["Prescribe antibiotics for every viral infection","Only prescribe antibiotics when truly needed and tell patients to finish the course","Encourage patients to stop antibiotics as soon as they feel better","Recommend antibiotics in everyday soaps and animal feed"], c:1,
   e:"Limiting antibiotics to genuine bacterial infections and completing the course kills all the bacteria and reduces selection for resistance. Overusing antibiotics or stopping early leaves resistant bacteria to survive and spread."},
  {q:"A vaccination programme protects babies too young to be vaccinated because most older people are immune. What is this effect called?",
   opts:["Phagocytosis","Antibiotic resistance","Active digestion","Herd immunity"], c:3,
   e:"When a high proportion of a population is immune, the pathogen cannot spread easily, indirectly protecting those who cannot be vaccinated. This is herd immunity, not phagocytosis or resistance."},
  {q:"Before the results of a drug trial are published, they are checked by other scientists. Why is this peer review carried out?",
   opts:["To increase the price of the drug","To check the work and prevent false or exaggerated claims","To give the drug to patients sooner","To remove the need for animal testing"], c:1,
   e:"Peer review allows independent scientists to check the methods and conclusions, helping prevent false or exaggerated claims from being published. It does not set prices, skip stages of testing or replace earlier animal testing."}
]);

QUESTIONS["s10i-03-4"] = (QUESTIONS["s10i-03-4"] || []).concat([
  {q:"How are the spores of rose black spot fungus spread between plants?",
   opts:["By mosquitoes","Through the soil only","By water and wind","By direct root contact"], c:2,
   e:"Rose black spot spreads when its fungal spores are carried by water (rain splash) and by wind. It is not spread by mosquitoes, and although fungi grow on the plant, spores travel mainly through water and air, not roots."},
  {q:"Which of these is a chemical defence used by some plants?",
   opts:["A waxy cuticle","Thorns on the stem","Producing antibacterial substances and poisons","Leaves that droop when touched"], c:2,
   e:"Chemical defences include antibacterial substances that kill bacteria and poisons that deter herbivores. A waxy cuticle is a physical defence, while thorns and drooping leaves are mechanical defences."},
  {q:"A plant has stunted growth but green, healthy-looking leaves. Which mineral ion is it most likely lacking?",
   opts:["Nitrate ions","Magnesium ions","Carbon dioxide","Oxygen"], c:0,
   e:"Nitrate ions are needed to make proteins for growth, so a shortage causes stunted growth while leaves can stay green. A magnesium deficiency would cause yellow leaves (chlorosis), which is not described here."},
  {q:"Why might a gardener send a diseased plant to a laboratory rather than just guessing the cause?",
   opts:["Laboratories make plants grow faster","To identify the exact pathogen so the correct treatment can be chosen","To add nitrate ions to the plant","To increase the waxy cuticle thickness"], c:1,
   e:"A laboratory can identify the specific pathogen, so the right treatment is used. Guessing could lead to the wrong treatment. Laboratories do not speed up growth or add minerals as part of identifying a disease."},
  {q:"Which of the following is a sign that a plant may be diseased?",
   opts:["Thicker waxy cuticle","Areas of discolouration, spots and lesions on leaves","Faster than normal growth","Deeper green colour than usual"], c:1,
   e:"Signs of plant disease include discolouration, spots, lesions, wilting and stunted growth. A thicker cuticle, faster growth and deeper green colour are not signs of disease."},
  {q:"How do thorns and hairs help protect a plant?",
   opts:["They produce antibodies","They physically discourage animals from eating the plant","They absorb extra magnesium ions","They speed up photosynthesis"], c:1,
   e:"Thorns and hairs are mechanical defences that physically deter or stop herbivores from eating the plant. Plants do not make antibodies, and these structures do not absorb minerals or boost photosynthesis."},
  {q:"A scientist tests a leaf with a monoclonal antibody kit that changes colour only when a particular virus is present. The kit shows no colour change. What is the best conclusion?",
   opts:["The plant definitely has a fungal disease","The plant has a magnesium deficiency","That particular virus was not detected in the sample","The kit has identified aphids"], c:2,
   e:"The kit detects one specific virus, so no colour change means that virus was not detected. It cannot confirm a different cause such as a fungus, mineral deficiency or aphids, which it is not designed to detect."},
  {q:"A field of wheat shows widespread yellowing of the leaves but the soil has plenty of nitrate. Which explanation fits best?",
   opts:["A nitrate deficiency is stunting growth","The plants are growing too quickly","A magnesium deficiency is preventing chlorophyll production","The plants have too much chlorophyll"], c:2,
   e:"Yellow leaves (chlorosis) with adequate nitrate point to a magnesium deficiency, since magnesium is needed to make chlorophyll. A nitrate shortage causes stunted growth, and excess chlorophyll would not cause yellowing."},
  {q:"Why does damage to a plant's leaves by aphids reduce the plant's growth?",
   opts:["Aphids add poison that builds new cells","Aphids remove sugary sap, so less energy and material is available for growth","Aphids increase the rate of photosynthesis","Aphids supply the plant with extra nitrate"], c:1,
   e:"Aphids pierce the plant and suck out sugary sap, removing the sugars made in photosynthesis, so the plant has less material and energy for growth. They do not boost photosynthesis or supply nutrients to the plant."},
  {q:"Some plants release chemicals that kill bacteria, while others have a tough waxy cuticle. How are these two defences best classified?",
   opts:["Both are physical defences","The antibacterial chemicals are chemical defences and the waxy cuticle is a physical defence","Both are mechanical defences","The waxy cuticle is a chemical defence and the chemicals are physical"], c:1,
   e:"Antibacterial chemicals act by their chemistry, so they are chemical defences, while the waxy cuticle is a physical barrier. Mechanical defences are structures or movements like thorns and curling leaves, which are different again."}
]);

QUESTIONS["s10i-03-5"] = (QUESTIONS["s10i-03-5"] || []).concat([
  {q:"What is a hybridoma?",
   opts:["A purified antibody","A cell made by fusing a lymphocyte with a tumour cell","A weakened pathogen used in a vaccine","A type of phagocyte"], c:1,
   e:"A hybridoma is formed by fusing a lymphocyte with a tumour cell, so it both makes a specific antibody and divides rapidly. It is not the antibody itself, a vaccine component, or a phagocyte."},
  {q:"Why is a tumour cell used when making monoclonal antibodies?",
   opts:["It produces the specific antibody on its own","It kills the lymphocyte after fusion","It divides rapidly, allowing large numbers of cells to be made","It contains the antigen needed"], c:2,
   e:"Tumour cells divide rapidly and continuously, so fusing them with a lymphocyte gives a cell that can be cloned to make large amounts of antibody. The lymphocyte, not the tumour cell, provides the specific antibody."},
  {q:"What property of monoclonal antibodies makes them so useful in medical tests?",
   opts:["They bind to many different antigens at once","They bind to only one specific antigen","They destroy all cells they touch","They are produced by the patient's own body"], c:1,
   e:"Monoclonal antibodies bind to only one specific antigen at a single site, so they can target one molecule or cell type precisely. They are produced in the laboratory, not by the patient, and do not destroy every cell."},
  {q:"In a pregnancy test, what does a coloured line indicate?",
   opts:["The presence of insulin","A bacterial infection","A magnesium deficiency","The presence of the hormone hCG"], c:3,
   e:"A coloured line appears when monoclonal antibodies bind to the hormone hCG, which is present in the urine of pregnant women. The test does not detect insulin, bacteria or mineral levels."},
  {q:"How can a monoclonal antibody deliver a drug mainly to cancer cells and not healthy cells?",
   opts:["It binds to antigens found on the cancer cells but not on healthy cells","It is attracted to all fast-dividing cells equally","It dissolves only in cancer tissue","It is injected straight into the tumour every time"], c:0,
   e:"The antibody is made to bind to antigens specific to cancer cells, so the attached drug is carried mainly to them, sparing healthy cells that lack the antigen. It does not target all cells equally or rely on dissolving selectively."},
  {q:"Why are monoclonal antibodies not yet used in treatment as widely as scientists first hoped?",
   opts:["They are impossible to produce in large amounts","They only work in mice","They are no longer specific once purified","They caused more, and more severe, side effects than expected"], c:3,
   e:"In treatment, monoclonal antibodies produced more severe side effects, such as fever, vomiting and low blood pressure, than first hoped, limiting their use. They can be mass-produced and remain specific, and they do work in humans for diagnosis."},
  {q:"Place these production steps in the correct order: 1 fuse lymphocyte with tumour cell, 2 inject mouse with antigen, 3 clone the hybridoma, 4 collect and purify antibody.",
   opts:["2, 1, 3, 4","1, 2, 3, 4","2, 3, 1, 4","4, 3, 2, 1"], c:0,
   e:"The mouse is injected with the antigen first so its lymphocytes make the antibody, then the lymphocyte is fused with a tumour cell, the hybridoma is cloned, and finally the antibody is collected and purified. So the order is 2, 1, 3, 4."},
  {q:"A laboratory test uses a monoclonal antibody with a fluorescent label to find a particular protein in a tissue sample. Why is the antibody suitable for this job?",
   opts:["It glows on its own without binding to anything","It binds only to that one protein, so wherever it glows the protein is present","It destroys the protein so it cannot be seen","It binds to every protein in the sample"], c:1,
   e:"Because the antibody binds only to the one target protein, the fluorescent label marks exactly where that protein is. It does not glow without binding, destroy the target, or bind to every protein, which would make the result meaningless."},
  {q:"Why must the mouse first be injected with a specific antigen during monoclonal antibody production?",
   opts:["To make the mouse immune for life","So the mouse's lymphocytes produce the specific antibody that is wanted","To turn the lymphocytes into tumour cells","To supply the fluorescent label"], c:1,
   e:"Injecting the antigen stimulates the mouse's lymphocytes to make the specific antibody against it; these lymphocytes are then used in the fusion. The injection does not create tumour cells or provide a label."},
  {q:"A new monoclonal antibody is designed to measure a hormone present in the blood in tiny amounts. Which feature makes this measurement possible?",
   opts:["The antibody binds to many hormones so it rarely misses any","The antibody breaks the hormone down so it can be weighed","The antibody is highly specific, binding only to that hormone even at low concentration","The antibody is identical to the hormone"], c:2,
   e:"High specificity lets the antibody lock onto only that hormone, so even tiny amounts can be detected and measured. Binding to many hormones would give a false reading, and the antibody neither destroys nor copies the hormone."}
]);
