// content/y10/science/islands/x05.js — EXPANSION: Topic 5 extra flashcards + questions.
// Loads AFTER t05.js. Authored by the atlas-content skill. All items original.

FLASHCARDS.push(
  // s10i-05-1 — The Endocrine System
  {id:"s10fc-05-1-6", islandId:"s10i-05-1", front:"How do the nervous system and the endocrine system compare?",
   back:"Both are communication systems, but they differ:\n\nNervous system:\n• Uses electrical impulses carried by neurones\n• Very fast\n• Short-lived effect\n• Acts on a precise, localised target\n\nEndocrine system:\n• Uses chemical hormones carried in the blood\n• Slower to act\n• Longer-lasting effect\n• Can affect several organs at once\n\nThe two systems work together to coordinate the body.", difficulty:2, category:"concept"},
  {id:"s10fc-05-1-7", islandId:"s10i-05-1", front:"What is negative feedback and why is it important in the endocrine system?",
   back:"Negative feedback is a mechanism that keeps a condition close to a set level. When a level rises too high or falls too low, the body acts to reverse the change and bring it back to normal.\n\nExamples:\n• Blood glucose — insulin lowers it, glucagon raises it\n• Thyroxine — high levels reduce TSH release; low levels increase TSH release\n\nNegative feedback maintains a stable internal environment (homeostasis).", difficulty:2, category:"concept"},
  {id:"s10fc-05-1-8", islandId:"s10i-05-1", front:"How is the release of thyroxine controlled by negative feedback?",
   back:"The thyroid gland releases thyroxine, which controls metabolic rate.\n\n• The pituitary gland releases TSH, which stimulates the thyroid to release thyroxine.\n• When the blood thyroxine level is high enough, it inhibits the release of TSH from the pituitary.\n• Less TSH means the thyroid releases less thyroxine.\n• When thyroxine falls too low, the inhibition stops, so more TSH is released and thyroxine rises again.\n\nThis keeps thyroxine at a steady level.", difficulty:3, category:"concept"},

  // s10i-05-2 — Puberty & the Menstrual Cycle
  {id:"s10fc-05-2-6", islandId:"s10i-05-2", front:"What is the difference between FSH and LH in the menstrual cycle?",
   back:"Both are released by the pituitary gland but have different roles:\n\nFSH (Follicle Stimulating Hormone):\n• Causes an egg to mature inside a follicle in the ovary\n• Stimulates the ovaries to release oestrogen\n\nLH (Luteinising Hormone):\n• Released as a surge around day 14\n• Triggers ovulation (release of the mature egg)\n\nFSH starts the process; LH causes the key mid-cycle event.", difficulty:2, category:"concept"},
  {id:"s10fc-05-2-7", islandId:"s10i-05-2", front:"How do oestrogen and progesterone control FSH and LH?",
   back:"Oestrogen and progesterone act on the pituitary gland to control FSH and LH:\n\n• Oestrogen — inhibits FSH (so no new egg matures) and stimulates the release of LH (triggering ovulation).\n• Progesterone — inhibits both FSH and LH, so no further eggs mature while the lining is maintained.\n\nWhen progesterone falls at the end of the cycle, FSH is no longer inhibited and a new cycle can begin.", difficulty:3, category:"concept"},
  {id:"s10fc-05-2-8", islandId:"s10i-05-2", front:"What are the secondary sexual characteristics controlled by sex hormones?",
   back:"Secondary sexual characteristics develop at puberty under the control of sex hormones.\n\nTestosterone (main male hormone, from the testes):\n• Deepening of the voice\n• Growth of facial and body hair\n• Increased muscle development\n• Stimulates sperm production\n\nOestrogen (main female hormone, from the ovaries):\n• Breast development\n• Widening of the hips\n• Start of the menstrual cycle (periods)", difficulty:1, category:"definition"},

  // s10i-05-3 — Contraception & Fertility Treatments
  {id:"s10fc-05-3-6", islandId:"s10i-05-3", front:"What are the advantages and disadvantages of hormonal contraception?",
   back:"Advantages:\n• Very effective at preventing pregnancy when used correctly\n• Long-acting forms (implant, injection) do not need daily action\n\nDisadvantages:\n• Can cause side effects such as headaches, mood changes or weight gain\n• Must be taken or replaced regularly to stay effective\n• Gives NO protection against sexually transmitted infections (STIs)\n\nWhen evaluating, weigh effectiveness against side effects and STI protection.", difficulty:2, category:"application"},
  {id:"s10fc-05-3-7", islandId:"s10i-05-3", front:"How does an intrauterine device (IUD) work?",
   back:"An intrauterine device (IUD) is a small device placed inside the uterus by a doctor.\n\n• A copper IUD prevents sperm surviving and stops a fertilised egg implanting in the uterus lining.\n• A hormonal IUD (IUS) releases progesterone, which thickens cervical mucus and thins the uterus lining.\n\nIt lasts several years but does not protect against STIs because it forms no barrier to body fluids.", difficulty:2, category:"concept"},
  {id:"s10fc-05-3-8", islandId:"s10i-05-3", front:"What ethical and practical issues surround IVF treatment?",
   back:"IVF helps couples who cannot conceive naturally, but it raises issues:\n\n• Success rates are often low, so several attempts may be needed\n• It is emotionally and physically stressful for the mother\n• Multiple embryos may be transferred, leading to multiple births that are risky for mother and babies\n• Spare embryos may be stored or destroyed, which some people object to on ethical grounds\n• It is expensive\n\nThese points are useful when evaluating IVF.", difficulty:3, category:"application"},

  // s10i-05-4 — Plant Hormones & Tropisms
  {id:"s10fc-05-4-6", islandId:"s10i-05-4", front:"How would you investigate phototropism in seedlings (required practical reasoning)?",
   back:"To investigate the effect of light direction on shoot growth:\n\n• Place seedlings (e.g. cress) in identical conditions but with light coming from different directions (one side, all around, or in the dark).\n• Keep variables the same: temperature, water, type and number of seedlings, time.\n• Observe and measure the direction and angle of bending after a few days.\n\nSeedlings lit from one side bend towards the light; those in even light or darkness grow straight. A control shows what happens without a directional stimulus.", difficulty:3, category:"application"},
  {id:"s10fc-05-4-7", islandId:"s10i-05-4", front:"What did experiments removing or covering the shoot tip show about auxin?",
   back:"Classic experiments showed that the shoot tip is essential for the response to light:\n\n• If the tip is cut off, the shoot does not bend towards light.\n• If the tip is covered with an opaque cap, the shoot does not bend.\n• If only the tip is exposed but the lower shoot is covered, it still bends.\n\nThis shows the tip detects light and produces auxin, which then moves down to cause the lower shoot to bend.", difficulty:3, category:"application"},
  {id:"s10fc-05-4-8", islandId:"s10i-05-4", front:"Why is auxin useful as a selective weedkiller?",
   back:"Auxins can be used as selective herbicides to kill weeds in crops.\n\n• Many weeds are broad-leaved plants, while cereal crops are narrow-leaved.\n• Auxin-based weedkiller makes broad-leaved weeds grow far too quickly in an uncontrolled way, so they use up their resources and die.\n• The narrow-leaved crop plants are largely unaffected.\n\nThis allows weeds to be removed without damaging the crop.", difficulty:2, category:"application"}
);

QUESTIONS["s10i-05-1"] = (QUESTIONS["s10i-05-1"] || []).concat([
  {q:"Which statement correctly compares the nervous and endocrine systems?",
   opts:["The endocrine system uses electrical impulses; the nervous system uses hormones","The nervous system is fast and short-lived; the endocrine system is slower and longer-lasting","Both systems carry messages only in the blood","The nervous system always acts more slowly than the endocrine system"], c:1,
   e:"The nervous system uses fast electrical impulses giving short-lived, precise responses, while the endocrine system uses hormones in the blood giving slower but longer-lasting effects. The nervous system is faster, not slower, so that option is wrong."},
  {q:"Hormones are best described as:",
   opts:["Electrical signals carried by neurones","Chemical messengers carried in the blood","Enzymes that digest food","Cells that fight infection"], c:1,
   e:"Hormones are chemical messengers secreted by glands and carried in the bloodstream to target organs. They are not electrical signals (that is the nervous system) nor enzymes or immune cells."},
  {q:"Adrenaline is released by which gland?",
   opts:["The thyroid gland","The pancreas","The adrenal glands","The pituitary gland"], c:2,
   e:"Adrenaline is produced by the adrenal glands, which sit on top of the kidneys, preparing the body for 'fight or flight'. The pancreas controls blood glucose, and the thyroid produces thyroxine."},
  {q:"When blood thyroxine levels become high, what happens next?",
   opts:["The pituitary releases more TSH","The release of TSH from the pituitary is inhibited","The thyroid releases more thyroxine","The pancreas releases insulin"], c:1,
   e:"High thyroxine inhibits TSH release from the pituitary by negative feedback, which reduces further thyroxine production. It does not increase TSH, and the pancreas is not involved in thyroxine control."},
  {q:"Thyroxine controls the body's:",
   opts:["Blood glucose concentration","Basal metabolic rate","Water balance","Heart rate during exercise only"], c:1,
   e:"Thyroxine controls the basal metabolic rate, the speed of chemical reactions in the body. Blood glucose is controlled by insulin and glucagon, and water balance is controlled by ADH."},
  {q:"What is the function of negative feedback in the endocrine system?",
   opts:["To amplify changes away from the normal level","To keep conditions close to a steady set level","To stop hormones being produced permanently","To speed up the nervous system"], c:1,
   e:"Negative feedback reverses changes to keep a condition near a steady set level, maintaining homeostasis. It does not amplify changes or permanently switch off hormone production."},
  {q:"A person eats a large sugary meal. Which sequence correctly describes the response?",
   opts:["Glucose rises, pancreas releases glucagon, glucose rises further","Glucose rises, pancreas releases insulin, liver stores glucose as glycogen","Glucose falls, pancreas releases insulin, liver releases glucose","Glucose rises, liver releases glucagon, cells release glucose"], c:1,
   e:"A sugary meal raises blood glucose, so the pancreas releases insulin, causing cells to take up glucose and the liver to store it as glycogen. Glucagon would raise glucose further, which is the wrong response here."},
  {q:"A patient with type 1 diabetes is most likely to be treated by:",
   opts:["Eating a low-sugar diet only","Insulin injections matched to diet and activity","Taking glucagon tablets","Increasing exercise to remove the need for any medication"], c:1,
   e:"Type 1 diabetics produce little or no insulin, so they require insulin injections balanced against diet and exercise. Diet or exercise alone cannot replace the missing insulin, and glucagon would raise glucose, worsening the problem."},
  {q:"Why might type 2 diabetes be managed first by changes to diet and exercise rather than insulin injections?",
   opts:["The pancreas produces no insulin at all","The body still produces insulin but cells respond poorly to it","Insulin cannot be injected in adults","Exercise destroys glucose in the blood permanently"], c:1,
   e:"In type 2 diabetes the pancreas still makes insulin but cells have become resistant to it, so reducing sugar intake and losing weight can improve the cells' response. Type 1, not type 2, involves no insulin production."},
  {q:"The pituitary gland releases TSH, FSH and LH. What does this tell us about its role?",
   opts:["It stores hormones made by other glands","It releases hormones that control other glands","It only controls blood glucose","It produces no hormones of its own"], c:1,
   e:"By releasing TSH, FSH and LH the pituitary stimulates other glands such as the thyroid and ovaries, which is why it is called the master gland. It produces its own hormones and does not merely store others'."}
]);

QUESTIONS["s10i-05-2"] = (QUESTIONS["s10i-05-2"] || []).concat([
  {q:"Which hormone causes an egg to mature in the ovary?",
   opts:["LH","Progesterone","FSH","Testosterone"], c:2,
   e:"FSH (follicle stimulating hormone) from the pituitary causes an egg to mature inside a follicle in the ovary. LH triggers the release of the mature egg, while progesterone maintains the lining later in the cycle."},
  {q:"Approximately which day of a 28-day menstrual cycle does ovulation occur?",
   opts:["Day 1","Day 5","Day 14","Day 28"], c:2,
   e:"Ovulation typically occurs around day 14, roughly midway through the cycle, triggered by an LH surge. Day 1 is the start of menstruation and day 28 is the end of the cycle."},
  {q:"During days 1 to 5 of the menstrual cycle, what is happening?",
   opts:["Ovulation","The uterus lining breaks down and is shed","The lining is maintained by progesterone","An LH surge occurs"], c:1,
   e:"Days 1 to 5 are menstruation, when the uterus lining breaks down and is shed. Ovulation and the LH surge happen around day 14, and the lining is maintained by progesterone later in the cycle."},
  {q:"What effect does oestrogen have on LH?",
   opts:["It inhibits LH release","It stimulates LH release","It has no effect on LH","It converts LH into FSH"], c:1,
   e:"Rising oestrogen stimulates the release of LH, producing the surge that triggers ovulation. Oestrogen inhibits FSH, not LH, so the inhibition option is incorrect."},
  {q:"Which hormone is produced by the corpus luteum (the empty follicle) after ovulation?",
   opts:["FSH","Oestrogen","Progesterone","Testosterone"], c:2,
   e:"After ovulation the empty follicle becomes the corpus luteum, which produces progesterone to maintain the uterus lining. FSH and oestrogen dominate the first half of the cycle."},
  {q:"At puberty, what causes the development of male secondary sexual characteristics?",
   opts:["Oestrogen from the ovaries","Progesterone from the testes","Testosterone from the testes","FSH from the testes"], c:2,
   e:"Testosterone, produced by the testes, drives male secondary sexual characteristics such as a deeper voice and facial hair. Oestrogen is the main female sex hormone, and FSH is a pituitary hormone."},
  {q:"A woman's progesterone level falls sharply near the end of her cycle and no fertilised egg has implanted. What happens next?",
   opts:["Ovulation is triggered","The uterus lining is maintained","The uterus lining breaks down and menstruation begins","Oestrogen is no longer produced for life"], c:2,
   e:"When progesterone drops and there is no implantation, the uterus lining can no longer be maintained, so it breaks down and menstruation begins. The fall in progesterone does not trigger ovulation, which is caused by an LH surge."},
  {q:"On a hormone graph, oestrogen peaks just before day 14 and LH spikes sharply at day 14. What does this suggest about their relationship?",
   opts:["LH causes oestrogen to be produced","The oestrogen peak stimulates the LH surge that triggers ovulation","Oestrogen and LH have no connection","Oestrogen prevents ovulation from ever occurring"], c:1,
   e:"The rise in oestrogen stimulates the LH surge, which then triggers ovulation around day 14, matching the graph. Oestrogen does not block ovulation in the normal cycle, and the timing shows oestrogen acts before the LH spike."},
  {q:"Why does progesterone inhibit FSH during the second half of the cycle?",
   opts:["To trigger another ovulation immediately","To prevent further eggs maturing while the lining is maintained","To break down the uterus lining","To increase oestrogen production"], c:1,
   e:"By inhibiting FSH, progesterone prevents new eggs maturing while the lining is maintained for a possible pregnancy. It does not trigger a second ovulation, and it preserves rather than breaks down the lining."},
  {q:"Which statement about FSH and LH is correct?",
   opts:["Both are produced by the ovaries","FSH matures the egg and LH triggers its release","LH matures the egg and FSH triggers ovulation","Both are produced by the testes only"], c:1,
   e:"FSH from the pituitary matures the egg in its follicle and LH triggers ovulation, the release of that egg. Their roles are not reversed, and both are produced by the pituitary gland, not the ovaries."}
]);

QUESTIONS["s10i-05-3"] = (QUESTIONS["s10i-05-3"] || []).concat([
  {q:"Which of these is a hormonal method of contraception?",
   opts:["The condom","The diaphragm","The implant","Sterilisation"], c:2,
   e:"The implant releases hormones (usually progesterone) slowly to prevent ovulation, making it a hormonal method. The condom and diaphragm are barrier methods, and sterilisation is a surgical method."},
  {q:"A key disadvantage shared by all hormonal contraceptives is that they:",
   opts:["Are permanent and cannot be reversed","Do not protect against sexually transmitted infections","Always cause multiple births","Increase the chance of pregnancy"], c:1,
   e:"Hormonal contraceptives prevent pregnancy but offer no protection against STIs because they form no physical barrier. They are not permanent, and they reduce rather than increase the chance of pregnancy."},
  {q:"How does a copper intrauterine device (IUD) help prevent pregnancy?",
   opts:["It releases large amounts of oestrogen","It stops sperm surviving and prevents a fertilised egg implanting","It thickens the uterus lining to support implantation","It permanently removes the ovaries"], c:1,
   e:"A copper IUD prevents sperm surviving and stops a fertilised egg implanting in the uterus lining. A copper IUD releases no hormones, and it prevents rather than supports implantation."},
  {q:"Why might a couple choose to use a condom rather than the pill?",
   opts:["The condom is a hormonal method","The condom also protects against STIs","The condom matures eggs in the ovary","The condom guarantees pregnancy will never occur"], c:1,
   e:"As a barrier method, the condom also protects against STIs, which hormonal methods like the pill do not. The condom is not hormonal and no method offers an absolute guarantee."},
  {q:"In treating infertility, why is LH given alongside FSH in a fertility drug?",
   opts:["LH thickens cervical mucus","LH triggers ovulation once the eggs have matured","LH prevents the eggs from maturing","LH destroys the uterus lining"], c:1,
   e:"FSH matures the eggs and LH then triggers ovulation, the release of those eggs, so both are needed for the woman to conceive naturally. LH does not prevent maturation or destroy the lining."},
  {q:"Which of the following best describes the correct order of steps in IVF?",
   opts:["Eggs implanted, then matured, then collected","FSH and LH given, eggs collected, fertilised in lab, embryos transferred to uterus","Sperm injected into ovary, then eggs released naturally","Embryos grown in lab for nine months, then born"], c:1,
   e:"In IVF the mother is given FSH and LH to mature eggs, the eggs are collected and fertilised in a laboratory, and the resulting embryos are transferred to the uterus. Fertilisation occurs outside the body, and embryos are not grown to term in the lab."},
  {q:"A clinic reports that out of 100 IVF cycles, about 30 result in a live birth. This data best supports which statement?",
   opts:["IVF always works first time","IVF has a relatively low success rate per cycle","IVF protects against STIs","IVF cannot lead to multiple births"], c:1,
   e:"A success of about 30 in 100 shows IVF has a relatively low success rate per cycle, so several attempts may be needed. The data does not suggest it always works, and IVF can lead to multiple births."},
  {q:"Why can fertility drugs containing FSH sometimes lead to multiple births?",
   opts:["They cause one egg to split into several","They can stimulate several eggs to mature and be released at once","They prevent the uterus lining from breaking down","They increase the lifespan of sperm"], c:1,
   e:"FSH can stimulate several eggs to mature and be released together, so more than one can be fertilised, leading to multiple births. The drug does not split a single egg or prolong sperm life."},
  {q:"Which is an advantage of a long-acting hormonal contraceptive such as the implant compared with the pill?",
   opts:["It protects against STIs","It does not need to be remembered daily","It is a barrier method","It is permanent and irreversible"], c:1,
   e:"The implant lasts for years, so it does not need daily action like the pill, reducing the risk of forgetting it. It is not a barrier method, gives no STI protection, and can be removed so is not permanent."},
  {q:"When evaluating which contraceptive method to use, which set of factors is most relevant?",
   opts:["Colour, taste and brand name","Effectiveness, side effects and STI protection","The phase of the moon","The price of food"], c:1,
   e:"Sensible evaluation weighs how effective a method is, its possible side effects, and whether it protects against STIs. The other options are not biologically relevant factors."}
]);

QUESTIONS["s10i-05-4"] = (QUESTIONS["s10i-05-4"] || []).concat([
  {q:"A tropism is best defined as:",
   opts:["A plant moving its whole body to a new place","A growth response towards or away from a stimulus","A chemical that kills weeds","The way leaves change colour in autumn"], c:1,
   e:"A tropism is a directional growth response towards or away from a stimulus such as light or gravity. Plants grow rather than move bodily, and a weedkiller is a use of hormones, not a definition of a tropism."},
  {q:"Roots are described as positively gravitropic. This means roots grow:",
   opts:["Away from gravity, upward","Towards gravity, downward","Towards light","Away from water"], c:1,
   e:"Positively gravitropic means roots grow in the direction of gravity, downward, anchoring the plant and reaching water. Growing upward would be negative gravitropism, shown by shoots."},
  {q:"Auxin controls plant bending by affecting which process?",
   opts:["Cell division only at the roots","Cell elongation","Photosynthesis in the leaves","Water uptake by osmosis"], c:1,
   e:"Auxin controls cell elongation, how much cells lengthen, and uneven distribution of auxin causes one side to grow faster, bending the plant. It is not primarily about photosynthesis or water uptake."},
  {q:"In a root placed horizontally, auxin gathers on the lower side. Because auxin inhibits growth in roots, what happens?",
   opts:["The lower side grows faster, so the root bends upward","The upper side grows faster, so the root bends downward","Both sides grow equally and the root stays straight","The root stops growing completely"], c:1,
   e:"In roots auxin inhibits elongation, so the auxin-rich lower side grows less and the upper side grows faster, bending the root downward towards gravity. This is the opposite of how auxin acts in shoots."},
  {q:"Which plant hormone is used in rooting powder to help cuttings grow roots?",
   opts:["Ethene","Gibberellin","Auxin","Oestrogen"], c:2,
   e:"Auxins are used in rooting powder to encourage cuttings to develop roots quickly. Ethene controls fruit ripening and gibberellins affect germination and flowering; oestrogen is an animal hormone."},
  {q:"Gibberellins are commercially used to:",
   opts:["Ripen fruit during transport","End seed dormancy and promote flowering","Kill broad-leaved weeds","Anchor roots in the soil"], c:1,
   e:"Gibberellins are used to end seed dormancy, promote flowering and increase fruit size. Ripening is controlled by ethene, and selective weedkilling is a use of auxins."},
  {q:"In a phototropism investigation, why should the temperature and amount of water be kept the same for all seedlings?",
   opts:["To make the experiment take longer","So that any difference in growth is due to light direction only","Because seedlings cannot grow in the cold","To stop auxin being produced"], c:1,
   e:"Keeping temperature and water constant means light direction is the only variable changed, so any bending can be attributed to it, making the test fair. These controls do not stop auxin production or prevent growth."},
  {q:"A shoot has an opaque cap placed over its tip and is lit from one side. It does not bend. What does this show?",
   opts:["Light is detected and auxin made at the tip","The roots control the bending","Auxin is produced evenly along the whole shoot","Light has no effect on any plant"], c:0,
   e:"Covering the tip prevents bending, showing the tip detects the light and produces the auxin responsible for the response. If auxin were made evenly along the shoot, covering only the tip would not prevent bending."},
  {q:"Why are auxin-based weedkillers described as selective?",
   opts:["They kill every plant they touch","They mainly affect broad-leaved weeds while leaving narrow-leaved crops largely unharmed","They only work at night","They prevent all seeds from germinating"], c:1,
   e:"Selective auxin weedkillers cause broad-leaved weeds to grow uncontrollably and die, while narrow-leaved cereal crops are largely unaffected. They do not kill every plant or stop germination, which is why crops survive."},
  {q:"Fruit is picked unripe, transported, then exposed to ethene before sale. What is the main advantage of this approach?",
   opts:["Ethene makes the fruit larger","Unripe fruit is firmer and less easily damaged in transport, then ripened on demand","Ethene kills weeds in the orchard","It prevents the fruit from ever ripening"], c:1,
   e:"Picking fruit unripe means it is firmer and travels with less damage, and ethene can then ripen it just before sale. Ethene controls ripening rather than increasing size, and the aim is to ripen, not prevent ripening."}
]);
