// content/y10/science/islands/x06.js — EXPANSION: Topic 6 extra flashcards + questions.
// Loads AFTER t06.js. Authored by the atlas-content skill. All items original.

FLASHCARDS.push(
  // s10i-06-1 — Relative Formula Mass & Moles
  {id:"s10fc-06-1-6", islandId:"s10i-06-1", front:"Calculate the Mr of magnesium nitrate, Mg(NO₃)₂. (Ar: Mg = 24, N = 14, O = 16)",
   back:"Brackets multiply everything inside them.\n\nMg(NO₃)₂ contains: 1 Mg, 2 N and 6 O.\n\nMr = 24 + (2 × 14) + (6 × 16)\n= 24 + 28 + 96\n= 148\n\nCommon error: forgetting that the subscript 2 outside the bracket doubles BOTH the nitrogen and the oxygen atoms.", difficulty:2, category:"calculation"},
  {id:"s10fc-06-1-7", islandId:"s10i-06-1", front:"How do you calculate the number of particles in a sample from the number of moles?",
   back:"number of particles = moles × 6.02 × 10²³\n\nExample: how many molecules are in 0.5 mol of water?\nnumber = 0.5 × 6.02 × 10²³ = 3.01 × 10²³ molecules\n\nWorking the other way:\nmoles = number of particles ÷ 6.02 × 10²³\n\nThe particles can be atoms, molecules or ions — the constant is the same.", difficulty:2, category:"concept"},
  {id:"s10fc-06-1-8", islandId:"s10i-06-1", front:"A 12 g sample of a metal contains 0.5 mol of atoms. Identify the metal.",
   back:"Rearrange moles = mass ÷ Mr to find the relative atomic mass:\n\nAr = mass ÷ moles\nAr = 12 ÷ 0.5 = 24\n\nThe metal with Ar = 24 is magnesium.\n\nThis 'reverse' calculation is a common exam question — you are given two of the three quantities and must find the third.", difficulty:3, category:"calculation"},

  // s10i-06-2 — Reacting Masses
  {id:"s10fc-06-2-6", islandId:"s10i-06-2", front:"2.4 g of Mg is mixed with 0.15 mol of HCl. Mg + 2HCl → MgCl₂ + H₂. Which reactant is limiting?",
   back:"Step 1: moles of Mg = 2.4 ÷ 24 = 0.1 mol\n\nStep 2: The equation needs 2 mol HCl per 1 mol Mg.\nTo react all 0.1 mol of Mg would need 0.2 mol of HCl.\n\nStep 3: Only 0.15 mol HCl is available — less than the 0.2 mol required.\n\nSo HCl is the limiting reactant; the magnesium is in excess.", difficulty:3, category:"calculation"},
  {id:"s10fc-06-2-7", islandId:"s10i-06-2", front:"CaCO₃ → CaO + CO₂. What mass of CaCO₃ is needed to produce 5.6 g of CaO? (Mr: CaCO₃ = 100, CaO = 56)",
   back:"You can work backwards from product to reactant.\n\nStep 1: moles of CaO = 5.6 ÷ 56 = 0.1 mol\n\nStep 2: The ratio is 1:1, so 0.1 mol of CaCO₃ is needed.\n\nStep 3: mass = moles × Mr = 0.1 × 100 = 10 g\n\n10 g of calcium carbonate must be decomposed.", difficulty:3, category:"calculation"},
  {id:"s10fc-06-2-8", islandId:"s10i-06-2", front:"If you add more of the reactant that is in excess, what happens to the amount of product?",
   back:"Nothing — the amount of product stays the same.\n\nThe maximum amount of product is fixed by the limiting reactant, because the reaction stops as soon as the limiting reactant runs out.\n\nAdding more of the excess reactant just leaves more of it unreacted at the end.\n\nTo make more product you must add more of the LIMITING reactant.", difficulty:2, category:"concept"},

  // s10i-06-3 — Concentration & Titrations
  {id:"s10fc-06-3-6", islandId:"s10i-06-3", front:"How do you convert a concentration in g/dm³ into mol/dm³?",
   back:"Divide by the Mr of the solute:\n\nconcentration (mol/dm³) = concentration (g/dm³) ÷ Mr\n\nExample: a solution of NaOH has a concentration of 20 g/dm³.\nMr of NaOH = 23 + 16 + 1 = 40\nconcentration = 20 ÷ 40 = 0.5 mol/dm³\n\nTo go the other way, multiply by the Mr instead.", difficulty:2, category:"concept"},
  {id:"s10fc-06-3-7", islandId:"s10i-06-3", front:"Why are a pipette and a burette used in a titration instead of measuring cylinders?",
   back:"Both pieces of glassware measure volume far more precisely than a measuring cylinder:\n\n• A pipette delivers one fixed volume (e.g. exactly 25.0 cm³) of the solution into the conical flask\n• A burette measures the variable volume added, readable to the nearest 0.05 cm³\n\nA measuring cylinder is typically only accurate to about 1 cm³, which would make the calculated concentration unreliable.", difficulty:2, category:"application"},
  {id:"s10fc-06-3-8", islandId:"s10i-06-3", front:"25.0 cm³ of 0.2 mol/dm³ NaOH is neutralised by 20.0 cm³ of H₂SO₄. Find the concentration of the acid. (2NaOH + H₂SO₄ → Na₂SO₄ + 2H₂O)",
   back:"Step 1: moles of NaOH = 0.2 × (25.0 ÷ 1000) = 0.005 mol\n\nStep 2: Ratio is 2 NaOH : 1 H₂SO₄\nmoles of H₂SO₄ = 0.005 ÷ 2 = 0.0025 mol\n\nStep 3: concentration = moles ÷ volume\n= 0.0025 ÷ (20.0 ÷ 1000)\n= 0.0025 ÷ 0.020 = 0.125 mol/dm³\n\nWatch the 2:1 ratio — forgetting it doubles the answer.", difficulty:3, category:"calculation"},

  // s10i-06-4 — Percentage Yield & Atom Economy
  {id:"s10fc-06-4-6", islandId:"s10i-06-4", front:"20 g of CaCO₃ is decomposed: CaCO₃ → CaO + CO₂. Only 8.4 g of CaO is collected. Calculate the percentage yield. (Mr: CaCO₃ = 100, CaO = 56)",
   back:"Step 1: Theoretical maximum mass\nmoles of CaCO₃ = 20 ÷ 100 = 0.2 mol\n1:1 ratio, so 0.2 mol CaO\ntheoretical mass = 0.2 × 56 = 11.2 g\n\nStep 2: percentage yield = (actual ÷ theoretical) × 100\n= (8.4 ÷ 11.2) × 100 = 75%\n\nThis two-step question — reacting mass first, then yield — is a classic higher-mark exam task.", difficulty:3, category:"calculation"},
  {id:"s10fc-06-4-7", islandId:"s10i-06-4", front:"Calculate the atom economy for making CaO by thermal decomposition: CaCO₃ → CaO + CO₂. (Mr: CaO = 56, CO₂ = 44)",
   back:"atom economy = (Mr of desired product ÷ total Mr of all products) × 100\n\ntotal Mr of products = 56 + 44 = 100\n\natom economy = (56 ÷ 100) × 100 = 56%\n\nJust over half the mass of the reactant ends up as the useful product; the rest is released as carbon dioxide.", difficulty:2, category:"calculation"},
  {id:"s10fc-06-4-8", islandId:"s10i-06-4", front:"When does a reaction have an atom economy of 100%?",
   back:"When the reaction has only ONE product, so every atom of the reactants ends up in the desired product.\n\nExample: the Haber process\nN₂ + 3H₂ → 2NH₃\nAmmonia is the only product, so the atom economy is 100%.\n\nAddition reactions (such as ethene + hydrogen → ethane) also have 100% atom economy.\n\nNote: even with 100% atom economy, the percentage yield can still be low.", difficulty:2, category:"concept"},

  // s10i-06-5 — Molar Gas Volume & Gas Calculations
  {id:"s10fc-06-5-6", islandId:"s10i-06-5", front:"Mg + 2HCl → MgCl₂ + H₂. Calculate the volume of hydrogen produced at rtp when 4.8 g of Mg reacts with excess acid.",
   back:"Step 1: moles of Mg = 4.8 ÷ 24 = 0.2 mol\n\nStep 2: Ratio Mg : H₂ is 1:1\nso moles of H₂ = 0.2 mol\n\nStep 3: volume = moles × 24\n= 0.2 × 24 = 4.8 dm³\n\nThis links the two key formulae: moles = mass ÷ Mr for the solid, then volume = moles × 24 for the gas.", difficulty:3, category:"calculation"},
  {id:"s10fc-06-5-7", islandId:"s10i-06-5", front:"Calculate the mass of 6 dm³ of oxygen gas (O₂) at rtp. (Ar of O = 16)",
   back:"Step 1: moles = volume ÷ 24\n= 6 ÷ 24 = 0.25 mol\n\nStep 2: Mr of O₂ = 2 × 16 = 32\n\nStep 3: mass = moles × Mr\n= 0.25 × 32 = 8 g\n\nGoing from volume to mass always takes two steps: volume → moles → mass.", difficulty:3, category:"calculation"},
  {id:"s10fc-06-5-8", islandId:"s10i-06-5", front:"24 dm³ of hydrogen and 24 dm³ of carbon dioxide are measured at rtp. Compare their moles and masses.",
   back:"Equal volumes of gases at the same temperature and pressure contain EQUAL numbers of molecules.\n\nSo both samples contain exactly 1 mole of gas.\n\nBut their masses are very different:\n• 1 mol H₂ = 2 g\n• 1 mol CO₂ = 44 g\n\nVolume tells you the number of gas particles; mass depends on the Mr of each gas.", difficulty:2, category:"concept"}
);

QUESTIONS["s10i-06-1"] = (QUESTIONS["s10i-06-1"] || []).concat([
  {q:"What is the Mr of magnesium sulfate, MgSO₄? (Ar: Mg = 24, S = 32, O = 16)",
   opts:["72","88","120","104"], c:2,
   e:"Mr = 24 + 32 + (4 × 16) = 24 + 32 + 64 = 120. A common slip is counting only one oxygen (giving 72) — the subscript 4 means four oxygen atoms."},
  {q:"What is the Mr of ammonium sulfate, (NH₄)₂SO₄? (Ar: N = 14, H = 1, S = 32, O = 16)",
   opts:["114","132","118","150"], c:1,
   e:"The bracket with subscript 2 doubles the NH₄ group: (2 × 14) + (8 × 1) + 32 + (4 × 16) = 28 + 8 + 32 + 64 = 132. Forgetting to double the NH₄ gives 114, which is wrong."},
  {q:"How many moles are in 8 g of methane, CH₄? (Mr of CH₄ = 16)",
   opts:["2 mol","0.25 mol","0.5 mol","128 mol"], c:2,
   e:"moles = mass ÷ Mr = 8 ÷ 16 = 0.5 mol. Multiplying instead of dividing gives 128, which is far too large — always divide mass by Mr."},
  {q:"What is the mass of 0.25 mol of calcium carbonate, CaCO₃? (Mr = 100)",
   opts:["25 g","400 g","2.5 g","100 g"], c:0,
   e:"mass = moles × Mr = 0.25 × 100 = 25 g. Dividing instead of multiplying gives 400 g (0.25 into 100), which is incorrect — to go from moles to mass you multiply."},
  {q:"How many molecules are there in 2 mol of water?",
   opts:["6.02 × 10²³","3.01 × 10²³","1.204 × 10²⁴","2 × 10²³"], c:2,
   e:"number of molecules = moles × Avogadro's constant = 2 × 6.02 × 10²³ = 1.204 × 10²⁴. Halving the constant (3.01 × 10²³) would be the answer for 0.5 mol, not 2 mol."},
  {q:"Which 10 g sample contains the greatest number of moles? (Mr: H₂O = 18, CO₂ = 44, NaCl = 58.5, CaCO₃ = 100)",
   opts:["10 g of CO₂","10 g of NaCl","10 g of CaCO₃","10 g of H₂O"], c:3,
   e:"moles = mass ÷ Mr, so for the same mass the substance with the SMALLEST Mr gives the most moles. H₂O has the smallest Mr (18), giving 10 ÷ 18 = 0.56 mol. Picking the largest Mr (CaCO₃) gives the fewest moles, not the most."},
  {q:"0.2 mol of a gas has a mass of 8.8 g. What is the Mr of the gas?",
   opts:["1.76","44","17.6","22"], c:1,
   e:"Mr = mass ÷ moles = 8.8 ÷ 0.2 = 44 (this is carbon dioxide). Multiplying 8.8 by 0.2 gives 1.76, which is the wrong way round — Mr is mass divided by moles."},
  {q:"When magnesium is burned in an open crucible, the solid left behind has a greater mass than the magnesium. Why?",
   opts:["The magnesium atoms get heavier when heated","Oxygen atoms from the air combine with the magnesium","Mass is created during chemical reactions","The crucible loses mass to the magnesium"], c:1,
   e:"The magnesium combines with oxygen from the air to form magnesium oxide, so the oxygen's mass is added to the solid. Mass is never created — the increase is explained by atoms gained from the air, which is consistent with conservation of mass."},
  {q:"What are the units of relative formula mass (Mr)?",
   opts:["grams","grams per mole","kilograms","It has no units"], c:3,
   e:"Mr has no units because it is a ratio — a comparison with one twelfth of the mass of a carbon-12 atom. The mass of one mole of a substance in grams is numerically equal to the Mr, but Mr itself is unitless."},
  {q:"How many moles are in 5.3 g of sodium carbonate, Na₂CO₃? (Ar: Na = 23, C = 12, O = 16)",
   opts:["0.05 mol","0.5 mol","0.062 mol","0.1 mol"], c:0,
   e:"Mr of Na₂CO₃ = (2 × 23) + 12 + (3 × 16) = 46 + 12 + 48 = 106. moles = 5.3 ÷ 106 = 0.05 mol. Using Mr = 85 (forgetting to double the sodium) gives 0.062, which is wrong."}
]);

QUESTIONS["s10i-06-2"] = (QUESTIONS["s10i-06-2"] || []).concat([
  {q:"Fe₂O₃ + 3CO → 2Fe + 3CO₂. What mass of iron is produced from 32 g of Fe₂O₃? (Mr of Fe₂O₃ = 160, Ar of Fe = 56)",
   opts:["11.2 g","44.8 g","22.4 g","56 g"], c:2,
   e:"moles of Fe₂O₃ = 32 ÷ 160 = 0.2 mol. The ratio is 1 Fe₂O₃ : 2 Fe, so 0.4 mol of Fe forms. mass = 0.4 × 56 = 22.4 g. Forgetting the 1:2 ratio gives 11.2 g, which is only half the correct answer."},
  {q:"2H₂ + O₂ → 2H₂O. How many moles of oxygen are needed to react completely with 4 mol of hydrogen?",
   opts:["8 mol","2 mol","4 mol","1 mol"], c:1,
   e:"The ratio is 2 H₂ : 1 O₂, so the moles of oxygen needed are half the moles of hydrogen: 4 ÷ 2 = 2 mol. Doubling instead of halving gives 8 mol, which reverses the ratio."},
  {q:"CuCO₃ → CuO + CO₂. What mass of copper oxide forms when 24.7 g of CuCO₃ decomposes? (Mr: CuCO₃ = 123.5, CuO = 79.5)",
   opts:["12.35 g","24.7 g","7.95 g","15.9 g"], c:3,
   e:"moles of CuCO₃ = 24.7 ÷ 123.5 = 0.2 mol. The 1:1 ratio means 0.2 mol of CuO forms. mass = 0.2 × 79.5 = 15.9 g. The mass cannot stay at 24.7 g because CO₂ gas escapes."},
  {q:"What does it mean if a reactant is described as 'in excess'?",
   opts:["It reacts faster than the other reactants","Some of it is left over when the reaction stops","It is the most concentrated reactant","It produces the most product"], c:1,
   e:"A reactant in excess is present in a greater amount than needed, so some remains unreacted after the limiting reactant is used up. Being in excess says nothing about speed or concentration."},
  {q:"N₂ + 3H₂ → 2NH₃. What mass of ammonia forms from 28 g of nitrogen with excess hydrogen? (Mr: N₂ = 28, NH₃ = 17)",
   opts:["34 g","17 g","28 g","51 g"], c:0,
   e:"moles of N₂ = 28 ÷ 28 = 1 mol. The ratio is 1 N₂ : 2 NH₃, so 2 mol of NH₃ forms. mass = 2 × 17 = 34 g. Choosing 17 g misses the factor of 2 in the mole ratio."},
  {q:"0.4 mol of Mg is added to 0.6 mol of HCl. Mg + 2HCl → MgCl₂ + H₂. Which statement is correct?",
   opts:["Mg is limiting because there is less of it by mass","HCl is limiting because 0.8 mol would be needed to react all the Mg","Both reactants are used up exactly","Mg is limiting because metals always run out first"], c:1,
   e:"To react all 0.4 mol of Mg would need 2 × 0.4 = 0.8 mol of HCl, but only 0.6 mol is available — so the HCl runs out first and is limiting. Comparing raw amounts without using the 1:2 ratio leads to the wrong conclusion."},
  {q:"In a sealed container, 10 g of reactants form products. What is the total mass of the products?",
   opts:["Less than 10 g","Exactly 10 g","More than 10 g","It depends on the catalyst"], c:1,
   e:"The law of conservation of mass states that no atoms are created or destroyed in a chemical reaction, so in a closed system the total mass stays exactly the same. Mass only appears to change in open systems when a gas escapes or is gained."},
  {q:"2Na + Cl₂ → 2NaCl. What mass of sodium chloride forms from 2.3 g of sodium? (Ar: Na = 23, Cl = 35.5)",
   opts:["11.7 g","2.93 g","58.5 g","5.85 g"], c:3,
   e:"moles of Na = 2.3 ÷ 23 = 0.1 mol. The ratio Na : NaCl is 1:1 (2:2 simplified), so 0.1 mol of NaCl forms. mass = 0.1 × 58.5 = 5.85 g. Doubling to 11.7 g misreads the 2:2 ratio as 1:2."},
  {q:"In the equation Fe₂O₃ + 3CO → 2Fe + 3CO₂, what does the '3' in front of CO mean?",
   opts:["There are 3 carbon atoms in each CO molecule","3 moles of CO react for every mole of Fe₂O₃","CO is 3 times heavier than Fe₂O₃","The reaction happens 3 times"], c:1,
   e:"A number in front of a formula (a coefficient) gives the number of moles of that substance in the ratio — here 3 mol of CO per 1 mol of Fe₂O₃. A subscript inside the formula, not the coefficient, would show atoms within a molecule."},
  {q:"CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂. What mass of HCl is needed to react completely with 25 g of CaCO₃? (Mr: CaCO₃ = 100, HCl = 36.5)",
   opts:["9.125 g","18.25 g","36.5 g","73 g"], c:1,
   e:"moles of CaCO₃ = 25 ÷ 100 = 0.25 mol. The ratio is 1 : 2, so 0.5 mol of HCl is needed. mass = 0.5 × 36.5 = 18.25 g. Using a 1:1 ratio gives 9.125 g, which is only half the acid required."}
]);

QUESTIONS["s10i-06-3"] = (QUESTIONS["s10i-06-3"] || []).concat([
  {q:"Convert 500 cm³ into dm³.",
   opts:["50 dm³","5 dm³","0.5 dm³","0.05 dm³"], c:2,
   e:"To convert cm³ to dm³, divide by 1000: 500 ÷ 1000 = 0.5 dm³. Dividing by 100 gives 5, which is a factor of ten too large."},
  {q:"4 g of NaOH is dissolved in 500 cm³ of water. What is the concentration in g/dm³?",
   opts:["8 g/dm³","2 g/dm³","4 g/dm³","0.008 g/dm³"], c:0,
   e:"concentration = mass ÷ volume in dm³ = 4 ÷ 0.5 = 8 g/dm³. Dividing by 500 without converting to dm³ gives 0.008, which is out by a factor of 1000."},
  {q:"How many moles of solute are in 100 cm³ of a 2 mol/dm³ solution?",
   opts:["200 mol","2 mol","0.02 mol","0.2 mol"], c:3,
   e:"moles = concentration × volume in dm³ = 2 × (100 ÷ 1000) = 2 × 0.1 = 0.2 mol. Forgetting to convert cm³ to dm³ gives 200 mol, which is absurdly large."},
  {q:"What volume of a 0.5 mol/dm³ solution contains 0.1 mol of solute?",
   opts:["50 cm³","200 cm³","500 cm³","20 cm³"], c:1,
   e:"volume = moles ÷ concentration = 0.1 ÷ 0.5 = 0.2 dm³ = 200 cm³. Multiplying instead of dividing gives 0.05 dm³ (50 cm³), which is the wrong rearrangement."},
  {q:"What is the end point of a titration?",
   opts:["When all the acid in the burette has been added","The point at which the indicator changes colour","When the solution starts to boil","When the burette reading reaches 50 cm³"], c:1,
   e:"The end point is reached when the indicator changes colour, showing that the acid and alkali have exactly neutralised each other. It has nothing to do with emptying the burette or any fixed reading."},
  {q:"Why is the conical flask placed on a white tile during a titration?",
   opts:["To protect the bench from spills","To keep the flask cool","To make the indicator colour change easier to see","To stop the flask from slipping"], c:2,
   e:"The white background makes the indicator's colour change at the end point much easier to judge, so the titre is read at the right moment. Protecting the bench is a side benefit, not the purpose."},
  {q:"Why is universal indicator unsuitable for a titration?",
   opts:["It is too expensive","It only works with weak acids","It changes colour gradually through many colours, so there is no sharp end point","It is colourless in alkali"], c:2,
   e:"A titration needs a single, sharp colour change at the end point. Universal indicator changes gradually through a range of colours, making the end point impossible to judge precisely. Single indicators like phenolphthalein or methyl orange are used instead."},
  {q:"25.0 cm³ of 0.150 mol/dm³ HCl is neutralised by 30.0 cm³ of NaOH. HCl + NaOH → NaCl + H₂O. What is the concentration of the NaOH?",
   opts:["0.180 mol/dm³","0.125 mol/dm³","0.00375 mol/dm³","0.150 mol/dm³"], c:1,
   e:"moles of HCl = 0.150 × 0.025 = 0.00375 mol. With a 1:1 ratio, moles of NaOH = 0.00375 mol. concentration = 0.00375 ÷ 0.030 = 0.125 mol/dm³. 0.00375 is the number of moles, not the concentration — you must still divide by the volume."},
  {q:"2NaOH + H₂SO₄ → Na₂SO₄ + 2H₂O. What volume of 0.2 mol/dm³ NaOH is neutralised by 20.0 cm³ of 0.1 mol/dm³ H₂SO₄?",
   opts:["10 cm³","40 cm³","20 cm³","5 cm³"], c:2,
   e:"moles of H₂SO₄ = 0.1 × 0.020 = 0.002 mol. The 2:1 ratio means moles of NaOH = 2 × 0.002 = 0.004 mol. volume = 0.004 ÷ 0.2 = 0.02 dm³ = 20 cm³. Ignoring the 2:1 ratio gives 10 cm³, which is half the correct volume."},
  {q:"A solution of NaCl has a concentration of 0.5 mol/dm³. What is its concentration in g/dm³? (Mr of NaCl = 58.5)",
   opts:["117 g/dm³","0.0085 g/dm³","58.5 g/dm³","29.25 g/dm³"], c:3,
   e:"concentration in g/dm³ = concentration in mol/dm³ × Mr = 0.5 × 58.5 = 29.25 g/dm³. Dividing by the Mr instead of multiplying gives 0.0085, which is the conversion in the wrong direction."}
]);

QUESTIONS["s10i-06-4"] = (QUESTIONS["s10i-06-4"] || []).concat([
  {q:"A reaction has a theoretical maximum mass of 40 g, but only 30 g of product is collected. What is the percentage yield?",
   opts:["75%","133%","70%","30%"], c:0,
   e:"percentage yield = (actual ÷ theoretical) × 100 = (30 ÷ 40) × 100 = 75%. Dividing the other way round gives 133%, which is impossible — yield can never be above 100%."},
  {q:"A student collects 7.2 g of product when the theoretical maximum is 12 g. What is the percentage yield?",
   opts:["72%","60%","58%","40%"], c:1,
   e:"percentage yield = (7.2 ÷ 12) × 100 = 0.6 × 100 = 60%. Reading the actual mass as a percentage directly (72%) ignores the theoretical maximum entirely."},
  {q:"A reaction has a percentage yield of 90%. The theoretical maximum mass is 50 g. What mass of product was actually collected?",
   opts:["55.6 g","40 g","45 g","90 g"], c:2,
   e:"actual mass = (yield ÷ 100) × theoretical = 0.9 × 50 = 45 g. Dividing 50 by 0.9 gives 55.6 g, which is more than the maximum — the actual mass must always be less than the theoretical mass."},
  {q:"CaCO₃ → CaO + CO₂. What is the atom economy for producing CO₂? (Mr: CaO = 56, CO₂ = 44)",
   opts:["56%","100%","78.6%","44%"], c:3,
   e:"atom economy = (Mr of desired product ÷ total Mr of all products) × 100 = (44 ÷ (56 + 44)) × 100 = (44 ÷ 100) × 100 = 44%. Using 56 gives the atom economy for CaO, not CO₂ — check which product is wanted."},
  {q:"What is the atom economy of the Haber process, N₂ + 3H₂ → 2NH₃?",
   opts:["50%","100%","33%","17%"], c:1,
   e:"Ammonia is the ONLY product, so every reactant atom ends up in the desired product and the atom economy is 100%. This is true for any reaction with a single product, regardless of the Mr values."},
  {q:"2CuO + C → 2Cu + CO₂. Calculate the atom economy for extracting copper. (Ar: Cu = 63.5; Mr of CO₂ = 44)",
   opts:["59.1%","74.3%","25.7%","63.5%"], c:1,
   e:"Mr of desired product = 2 × 63.5 = 127. Total Mr of products = 127 + 44 = 171. atom economy = (127 ÷ 171) × 100 = 74.3%. Forgetting to double the copper (using 63.5) gives 59.1%, which ignores the coefficient 2 in the equation."},
  {q:"Which statement about percentage yield and atom economy is correct?",
   opts:["Both depend on how carefully the experiment is carried out","Atom economy depends only on the balanced equation; yield depends on the actual experiment","Yield depends only on the balanced equation; atom economy depends on the experiment","They are two names for the same quantity"], c:1,
   e:"Atom economy is fixed by the balanced equation and Mr values — it never changes for a given reaction. Percentage yield varies between experiments because it depends on losses, side reactions and reversibility. They measure different things."},
  {q:"Why might industry choose a reaction route with a lower percentage yield?",
   opts:["Lower yield always means higher atom economy","The lower-yield route may be faster, use cheaper raw materials or allow unreacted reactants to be recycled","Industry prefers to waste product","Reactions with high yields are illegal"], c:1,
   e:"Yield is only one factor — a route may be chosen because it is quicker, uses less energy, has cheaper feedstock, or lets unreacted materials be recycled (as in the Haber process). Low yield does not automatically mean high atom economy."},
  {q:"A student calculates a percentage yield of 108%. What is the most likely explanation?",
   opts:["The reaction created extra atoms","The product is impure or still wet, adding extra mass","The balanced equation was correct","The theoretical mass was measured on a balance"], c:1,
   e:"A yield above 100% is impossible for a pure, dry product — atoms cannot be created. The most likely cause is that the product still contains water or impurities, making its measured mass too high. The product should be dried and purified, then reweighed."},
  {q:"Fe₂O₃ + 3CO → 2Fe + 3CO₂. From 160 g of Fe₂O₃ the theoretical mass of iron is 112 g, but only 84 g is obtained. What is the percentage yield? (Mr of Fe₂O₃ = 160, Ar of Fe = 56)",
   opts:["52.5%","84%","75%","66.7%"], c:2,
   e:"Check the theoretical mass: 160 ÷ 160 = 1 mol Fe₂O₃ → 2 mol Fe = 2 × 56 = 112 g. Then yield = (84 ÷ 112) × 100 = 75%. Dividing 84 by 160 (the reactant mass) gives 52.5%, which compares the wrong quantities."}
]);

QUESTIONS["s10i-06-5"] = (QUESTIONS["s10i-06-5"] || []).concat([
  {q:"What volume does 0.75 mol of nitrogen gas occupy at rtp?",
   opts:["32 dm³","24 dm³","18 dm³","7.5 dm³"], c:2,
   e:"volume = moles × 24 = 0.75 × 24 = 18 dm³. Dividing 24 by 0.75 gives 32 dm³, which is the wrong rearrangement — multiply moles by the molar gas volume."},
  {q:"How many moles of gas are in 600 cm³ at rtp?",
   opts:["0.025 mol","25 mol","0.25 mol","0.0025 mol"], c:0,
   e:"Convert first: 600 cm³ = 0.6 dm³. moles = 0.6 ÷ 24 = 0.025 mol. Forgetting to convert cm³ to dm³ gives 25 mol, which is out by a factor of 1000."},
  {q:"What is the mass of 12 dm³ of carbon dioxide at rtp? (Mr of CO₂ = 44)",
   opts:["44 g","22 g","88 g","12 g"], c:1,
   e:"moles = 12 ÷ 24 = 0.5 mol. mass = 0.5 × 44 = 22 g. Choosing 44 g assumes a whole mole, but 12 dm³ is only half the molar gas volume."},
  {q:"What volume does 8 g of oxygen gas (O₂) occupy at rtp? (Ar of O = 16)",
   opts:["12 dm³","24 dm³","3 dm³","6 dm³"], c:3,
   e:"Mr of O₂ = 32, so moles = 8 ÷ 32 = 0.25 mol. volume = 0.25 × 24 = 6 dm³. Using Ar = 16 instead of Mr = 32 gives 0.5 mol and 12 dm³ — remember oxygen gas is diatomic."},
  {q:"Which 1 g sample of gas occupies the greatest volume at rtp? (Mr: H₂ = 2, N₂ = 28, O₂ = 32, CO₂ = 44)",
   opts:["1 g of CO₂","1 g of H₂","1 g of O₂","1 g of N₂"], c:1,
   e:"Equal moles of gas occupy equal volumes, so for the same mass the gas with the smallest Mr has the most moles and the largest volume. 1 g of H₂ = 0.5 mol = 12 dm³, far more than the others. Picking the heaviest gas (CO₂) gives the smallest volume."},
  {q:"CaCO₃ → CaO + CO₂. What volume of CO₂ at rtp is produced when 25 g of CaCO₃ fully decomposes? (Mr of CaCO₃ = 100)",
   opts:["24 dm³","2.4 dm³","6 dm³","0.25 dm³"], c:2,
   e:"moles of CaCO₃ = 25 ÷ 100 = 0.25 mol. The 1:1 ratio gives 0.25 mol of CO₂. volume = 0.25 × 24 = 6 dm³. The answer 0.25 is the number of moles, not the volume — you must still multiply by 24."},
  {q:"What conditions does 'rtp' refer to?",
   opts:["0 °C and 1 atmosphere","100 °C and 1 atmosphere","20 °C and 1 atmosphere","20 °C and 2 atmospheres"], c:2,
   e:"Room temperature and pressure means about 20 °C and 1 atmosphere. 0 °C describes standard conditions used in other contexts, not rtp — and the molar gas volume of 24 dm³ applies only at rtp."},
  {q:"Two identical flasks at the same temperature and pressure contain hydrogen and carbon dioxide. Which statement is correct?",
   opts:["The flask of CO₂ contains more molecules","Both flasks contain the same number of molecules","The flask of H₂ contains more molecules","The number of molecules cannot be compared"], c:1,
   e:"Equal volumes of any gases at the same temperature and pressure contain equal numbers of molecules. The CO₂ flask has a greater MASS because each molecule is heavier, but the number of molecules is identical."},
  {q:"Mg + 2HCl → MgCl₂ + H₂. What volume of hydrogen at rtp is produced from 1.2 g of magnesium with excess acid? (Ar of Mg = 24)",
   opts:["1200 cm³","2400 cm³","600 cm³","120 cm³"], c:0,
   e:"moles of Mg = 1.2 ÷ 24 = 0.05 mol. The 1:1 ratio gives 0.05 mol of H₂. volume = 0.05 × 24 = 1.2 dm³ = 1200 cm³. Doubling to 2400 cm³ wrongly applies the 2 in front of HCl to the hydrogen gas."},
  {q:"2H₂ + O₂ → 2H₂O. What volume of oxygen at rtp reacts completely with 48 dm³ of hydrogen at rtp?",
   opts:["96 dm³","48 dm³","12 dm³","24 dm³"], c:3,
   e:"At the same conditions, gas volumes react in the same ratio as moles: 2 volumes of H₂ need 1 volume of O₂, so 48 ÷ 2 = 24 dm³. Doubling to 96 dm³ reverses the 2:1 ratio."}
]);
