// content/y10/science/islands/x07.js — EXPANSION: Topic 7 extra flashcards + questions.
// Loads AFTER t07.js. Authored by the atlas-content skill. All items original.

FLASHCARDS.push(
  // s10i-07-1 — The Reactivity Series
  {id:"s10fc-07-1-6", islandId:"s10i-07-1", front:"Why is potassium more reactive than copper, in terms of ions?",
   back:"A metal's reactivity depends on how easily its atoms lose electrons to form positive ions.\n\nPotassium atoms lose their outer electron very easily, so potassium forms K⁺ ions readily and reacts vigorously.\n\nCopper atoms hold on to their electrons much more strongly, so copper forms ions reluctantly and is unreactive.\n\nKey idea: more reactive = forms positive ions more easily.", difficulty:2, category:"concept"},
  {id:"s10fc-07-1-7", islandId:"s10i-07-1", front:"What are the products when a metal reacts with a dilute acid, and how is the gas tested?",
   back:"metal + acid → salt + hydrogen\n\nExample: Mg + 2HCl → MgCl₂ + H₂\n(magnesium + hydrochloric acid → magnesium chloride + hydrogen)\n\nTest for hydrogen: hold a lit splint at the mouth of the tube — it burns with a squeaky pop.\n\nThe more reactive the metal, the faster the fizzing. Metals below hydrogen in the series (e.g. copper) do not react with dilute acids.", difficulty:1, category:"definition"},
  {id:"s10fc-07-1-8", islandId:"s10i-07-1", front:"Describe what you would see when calcium is added to cold water.",
   back:"Calcium reacts steadily (less violently than potassium or sodium):\n\n• Bubbles of hydrogen gas form on the metal\n• The calcium may sink then rise as bubbles lift it\n• The water turns cloudy because calcium hydroxide is only slightly soluble\n\nEquation: Ca + 2H₂O → Ca(OH)₂ + H₂\n\nCompare: magnesium barely reacts with cold water but reacts quickly with steam.", difficulty:2, category:"application"},

  // s10i-07-2 — Extraction of Metals
  {id:"s10fc-07-2-6", islandId:"s10i-07-2", front:"Why are gold and platinum found in the Earth as the metals themselves?",
   back:"Gold and platinum are at the very bottom of the reactivity series.\n\nThey are so unreactive that they do not combine with oxygen or other elements in the ground, so they exist 'native' (uncombined) as the pure metal.\n\nThis is also why unreactive metals like gold were discovered and used thousands of years ago, while reactive metals like aluminium and sodium were only isolated after electricity was available.", difficulty:1, category:"concept"},
  {id:"s10fc-07-2-7", islandId:"s10i-07-2", front:"Why do the carbon anodes in aluminium extraction have to be replaced regularly?",
   back:"During the electrolysis of aluminium oxide, oxygen gas is produced at the positive carbon anodes.\n\nAt the high operating temperature (about 950 °C), this oxygen reacts with the hot carbon:\n\nC + O₂ → CO₂\n\nThe anodes gradually burn away and must be replaced, which adds to the cost of producing aluminium.", difficulty:2, category:"concept"},
  {id:"s10fc-07-2-8", islandId:"s10i-07-2", front:"Why is extraction by electrolysis more expensive than reduction with carbon?",
   back:"Electrolysis costs more because:\n\n• Large amounts of electrical energy are needed to pass the current\n• Energy is also needed to melt the compound (or dissolve it in molten cryolite) so the ions can move\n• Electrodes may need replacing (e.g. carbon anodes in aluminium extraction)\n\nCarbon (coke) is cheap, so metals below carbon in the reactivity series are extracted by heating with carbon instead. This is one reason recycling aluminium saves so much energy.", difficulty:2, category:"concept"},

  // s10i-07-3 — Electrolysis
  {id:"s10fc-07-3-6", islandId:"s10i-07-3", front:"Why are inert electrodes such as graphite or platinum used in electrolysis experiments?",
   back:"Inert electrodes conduct electricity but do not react with the electrolyte or the products.\n\n• Graphite: conducts (delocalised electrons), very high melting point, cheap\n• Platinum: conducts and is extremely unreactive, but expensive\n\nIf a reactive electrode were used, it could dissolve or react, changing the products. (Copper electrodes are deliberately chosen as NON-inert electrodes when purifying copper.)", difficulty:2, category:"concept"},
  {id:"s10fc-07-3-7", islandId:"s10i-07-3", front:"What are the products of electrolysing dilute sulfuric acid (acidified water)?",
   back:"Dilute sulfuric acid contains H⁺, SO₄²⁻ and OH⁻ ions.\n\nAt the cathode: 2H⁺ + 2e⁻ → H₂ (hydrogen gas)\nAt the anode: 4OH⁻ → O₂ + 2H₂O + 4e⁻ (oxygen gas — no halide present)\n\nTwice the volume of hydrogen forms compared with oxygen, because the equations show 2H₂ produced for every O₂. Overall, water is decomposed: 2H₂O → 2H₂ + O₂.", difficulty:3, category:"application"},
  {id:"s10fc-07-3-8", islandId:"s10i-07-3", front:"Predict the electrode products for copper(II) chloride solution.",
   back:"Ions present: Cu²⁺, Cl⁻, plus H⁺ and OH⁻ from water.\n\nAt the cathode: copper is LESS reactive than hydrogen, so copper metal is deposited:\nCu²⁺ + 2e⁻ → Cu (pink-brown coating)\n\nAt the anode: a halide ion is present, so chlorine gas forms:\n2Cl⁻ → Cl₂ + 2e⁻\n\nTest for chlorine: it bleaches damp litmus paper white.", difficulty:2, category:"application"},

  // s10i-07-4 — Acids, Bases & Making Salts
  {id:"s10fc-07-4-6", islandId:"s10i-07-4", front:"Give the laboratory tests for hydrogen and for carbon dioxide.",
   back:"Hydrogen: hold a burning splint at the mouth of the test tube — the gas ignites with a squeaky pop.\n\nCarbon dioxide: bubble the gas through limewater (calcium hydroxide solution) — it turns milky/cloudy white.\n\nThese tests identify the gases from acid + metal (hydrogen) and acid + carbonate (carbon dioxide).", difficulty:1, category:"definition"},
  {id:"s10fc-07-4-7", islandId:"s10i-07-4", front:"What is the difference between a base and an alkali?",
   back:"A base is any substance that neutralises an acid — usually a metal oxide or metal hydroxide (e.g. copper oxide, zinc hydroxide).\n\nAn alkali is a base that DISSOLVES in water, releasing hydroxide ions (OH⁻).\n\nExamples of alkalis: sodium hydroxide, potassium hydroxide, calcium hydroxide.\n\nAll alkalis are bases, but not all bases are alkalis — copper oxide is a base but it is insoluble, so it is not an alkali.", difficulty:2, category:"definition"},
  {id:"s10fc-07-4-8", islandId:"s10i-07-4", front:"How can the pH of a solution be measured, and which method is more accurate?",
   back:"Two methods:\n\n1. Universal indicator — add a few drops (or use paper) and match the colour to a pH chart. Gives an approximate, whole-number value.\n\n2. pH probe/meter — place the probe in the solution and read the value from the meter. Gives a precise numerical reading (e.g. pH 4.7), so it is more accurate and avoids human error in judging colour.\n\nThe probe should be rinsed with distilled water between samples.", difficulty:2, category:"application"},

  // s10i-07-5 — Oxidation, Reduction & Redox
  {id:"s10fc-07-5-6", islandId:"s10i-07-5", front:"Explain why the reaction of magnesium with hydrochloric acid is a redox reaction.",
   back:"Mg + 2HCl → MgCl₂ + H₂\n\nIn terms of electrons:\n• Magnesium atoms lose 2 electrons: Mg → Mg²⁺ + 2e⁻ (OXIDISED)\n• Hydrogen ions gain electrons: 2H⁺ + 2e⁻ → H₂ (REDUCED)\n\nBecause oxidation and reduction happen together, every metal + acid reaction is a redox reaction. The chloride ions are spectator ions.", difficulty:3, category:"application"},
  {id:"s10fc-07-5-7", islandId:"s10i-07-5", front:"Where do oxidation and reduction take place during electrolysis?",
   back:"Electrolysis is a redox process:\n\n• At the CATHODE (negative electrode): positive ions GAIN electrons → REDUCTION\n  e.g. Pb²⁺ + 2e⁻ → Pb\n\n• At the ANODE (positive electrode): negative ions LOSE electrons → OXIDATION\n  e.g. 2Br⁻ → Br₂ + 2e⁻\n\nMemory aid: RED CAT — REDuction at the CAThode; AN OX — ANode is OXidation.", difficulty:2, category:"concept"},
  {id:"s10fc-07-5-8", islandId:"s10i-07-5", front:"What is a spectator ion, and how is one identified in a displacement reaction?",
   back:"A spectator ion is an ion that is present in the mixture but unchanged by the reaction — it appears identical on both sides of the equation.\n\nExample: Fe + CuSO₄ → FeSO₄ + Cu\nWritten with ions: Fe + Cu²⁺ + SO₄²⁻ → Fe²⁺ + SO₄²⁻ + Cu\n\nThe sulfate ion (SO₄²⁻) starts and finishes dissolved and unchanged, so it is a spectator ion and is left out of the ionic equation:\nFe + Cu²⁺ → Fe²⁺ + Cu", difficulty:2, category:"concept"}
);

QUESTIONS["s10i-07-1"] = (QUESTIONS["s10i-07-1"] || []).concat([
  {q:"Why is sodium more reactive than iron?",
   opts:["Sodium atoms lose electrons to form positive ions more easily","Sodium atoms gain electrons more easily","Sodium has a higher melting point","Sodium atoms are heavier than iron atoms"], c:0,
   e:"Reactivity in metals depends on how readily atoms lose electrons to form positive ions — sodium does this far more easily than iron. Gaining electrons is what non-metals do when they react, not metals."},
  {q:"Magnesium ribbon is dropped into dilute hydrochloric acid. Which products form?",
   opts:["Magnesium chloride and water","Magnesium chloride and hydrogen","Magnesium oxide and hydrogen","Magnesium chloride and carbon dioxide"], c:1,
   e:"metal + acid → salt + hydrogen, so Mg + 2HCl → MgCl₂ + H₂. Water forms when an acid reacts with a base, not a metal, and carbon dioxide only comes from carbonates."},
  {q:"Which of these metals does NOT react with dilute sulfuric acid?",
   opts:["Zinc","Magnesium","Copper","Iron"], c:2,
   e:"Copper sits below hydrogen in the reactivity series, so it cannot displace hydrogen from an acid and there is no reaction. Zinc, magnesium and iron are all above hydrogen, so they fizz and release hydrogen gas."},
  {q:"A small piece of sodium is placed on cold water. Which set of observations is correct?",
   opts:["It sinks and slowly dissolves with no gas","It floats, fizzes rapidly and may melt into a ball that moves around","It glows red and gives off brown fumes","Nothing happens until the water is heated to steam"], c:1,
   e:"Sodium is less dense than water, so it floats; it reacts rapidly, releasing hydrogen (fizzing), and the heat released melts it into a shiny ball that darts across the surface. Only mid-series metals like magnesium need steam to react quickly."},
  {q:"Powdered aluminium is heated with iron(III) oxide. What happens?",
   opts:["No reaction, because both are metals","Aluminium displaces the iron, because aluminium is more reactive","Iron displaces the aluminium, because iron is more reactive","The two metals simply melt and mix together"], c:1,
   e:"Aluminium is above iron in the reactivity series, so it takes the oxygen from iron oxide: 2Al + Fe₂O₃ → Al₂O₃ + 2Fe. Displacement works in compounds containing a less reactive metal — it is not blocked just because two metals are involved."},
  {q:"In the ionic equation Mg + Cu²⁺ → Mg²⁺ + Cu, which ion has been left out because it is a spectator?",
   opts:["The magnesium ion","The copper ion","The sulfate ion from the copper sulfate solution","The hydrogen ion from the water"], c:2,
   e:"The reaction took place in copper sulfate solution, and the sulfate ion (SO₄²⁻) is unchanged on both sides, so it is omitted as a spectator. Mg²⁺ and Cu²⁺ both take part in the electron transfer, so they must stay in the equation."},
  {q:"A student adds equal-sized pieces of four metals to dilute acid and records the temperature rise: metal W = 2 °C, X = 14 °C, Y = 0 °C, Z = 7 °C. What is the order of reactivity, most reactive first?",
   opts:["Y, W, Z, X","X, Z, W, Y","W, X, Y, Z","X, W, Z, Y"], c:1,
   e:"A more reactive metal reacts faster and releases more energy, giving a larger temperature rise: X (14) > Z (7) > W (2) > Y (0, no reaction). Reading the rises from smallest to largest gives the order the wrong way round."},
  {q:"Metal Q displaces zinc from zinc sulfate solution but does not react with magnesium sulfate solution. Where does Q sit in the reactivity series?",
   opts:["Above magnesium","Between magnesium and zinc","Below zinc","Exactly equal to zinc"], c:1,
   e:"Q must be more reactive than zinc (it displaces it) but less reactive than magnesium (no reaction), so it lies between the two. If Q were above magnesium it would have displaced magnesium as well."},
  {q:"Which half equation correctly shows magnesium being oxidised in a displacement reaction?",
   opts:["Mg²⁺ + 2e⁻ → Mg","Mg → Mg²⁺ + 2e⁻","Mg + 2e⁻ → Mg²⁻","Mg²⁺ → Mg + 2e⁻"], c:1,
   e:"Oxidation is loss of electrons, so the magnesium atom loses two electrons to become Mg²⁺: Mg → Mg²⁺ + 2e⁻. The first option shows electrons being gained, which is reduction."},
  {q:"Magnesium reacts only slowly with cold water but rapidly with steam, forming magnesium oxide. What does this suggest about its position in the reactivity series?",
   opts:["It is among the most reactive metals, like potassium","It is in the middle of the series, below calcium but above copper","It is at the very bottom of the series","It is a non-metal"], c:1,
   e:"Only the top metals (K, Na, Li, Ca) react quickly with cold water; metals like magnesium need steam, placing them in the middle. Bottom-of-series metals such as copper do not react with water or steam at all."}
]);

QUESTIONS["s10i-07-2"] = (QUESTIONS["s10i-07-2"] || []).concat([
  {q:"Why can gold be found in the ground as the pure metal rather than in a compound?",
   opts:["Gold is too dense to form compounds","Gold is so unreactive that it does not combine with other elements","Gold compounds break down in sunlight","Gold is protected by a layer of oxide"], c:1,
   e:"Gold sits at the bottom of the reactivity series, so it does not react with oxygen or other substances in the Earth and stays uncombined (native). An oxide layer is a feature of aluminium, not gold — and it would mean the metal HAD reacted."},
  {q:"Which of these metals could be extracted from its oxide by heating with carbon?",
   opts:["Calcium","Sodium","Zinc","Magnesium"], c:2,
   e:"Zinc is below carbon in the reactivity series, so carbon can remove the oxygen from zinc oxide. Calcium, sodium and magnesium are all above carbon, so they must be extracted by electrolysis instead."},
  {q:"Copper oxide is heated with carbon: 2CuO + C → 2Cu + CO₂. Which statement is correct?",
   opts:["The copper oxide is reduced and the carbon is oxidised","The copper oxide is oxidised and the carbon is reduced","Both substances are reduced","Both substances are oxidised"], c:0,
   e:"The copper oxide loses oxygen, which is reduction; the carbon gains oxygen to become carbon dioxide, which is oxidation. The two processes always happen together — one substance cannot be reduced unless another is oxidised."},
  {q:"What is the purpose of adding limestone to the blast furnace?",
   opts:["It reduces the iron oxide to iron","It reacts with sandy impurities to form slag, which is removed","It provides the heat for the furnace","It dissolves the molten iron"], c:1,
   e:"Limestone decomposes and reacts with acidic impurities (mainly silica from the ore) to form molten slag, which floats on the iron and is tapped off. The reduction itself is done by carbon monoxide, not limestone."},
  {q:"During the purification of copper by electrolysis, where do the insoluble impurities from the impure copper end up?",
   opts:["They are deposited on the cathode with the pure copper","They dissolve into the electrolyte permanently","They fall to the bottom of the cell as a sludge beneath the anode","They escape as a gas at the anode"], c:2,
   e:"As the impure copper anode dissolves, impurities that do not form ions simply drop off and collect as sludge under the anode. Only Cu²⁺ ions travel to the cathode, which is why the cathode copper is so pure."},
  {q:"Which factor adds MOST to the cost of extracting aluminium compared with extracting iron?",
   opts:["Aluminium ore is rarer than iron ore","The large amount of electrical energy needed for electrolysis","Aluminium must be cooled very slowly","Aluminium ore must be imported by sea"], c:1,
   e:"Electrolysis consumes huge quantities of electricity, both to keep the mixture molten and to drive the current — this dominates the cost. Bauxite is actually plentiful, so scarcity of ore is not the reason."},
  {q:"In the aluminium electrolysis cell, the positive carbon electrodes slowly lose mass. Why?",
   opts:["Aluminium dissolves them","The oxygen produced at the anode reacts with the hot carbon to form carbon dioxide","The cryolite is corrosive to carbon","Electrons leaving the electrode carry carbon atoms away"], c:1,
   e:"Oxygen forms at the anode (2O²⁻ → O₂ + 4e⁻) and, at about 950 °C, it burns the carbon electrode: C + O₂ → CO₂. Electrons have a tiny mass and do not carry atoms — that distractor confuses charge flow with chemical reaction."},
  {q:"The oxide of a newly discovered metal, M, shows no change when heated strongly with carbon. What can be concluded?",
   opts:["M is below carbon in the reactivity series","M is above carbon, so electrolysis would be needed to extract it","M is not a real metal","Carbon is more reactive than M"], c:1,
   e:"If carbon cannot remove the oxygen, the metal must hold it more strongly — M is more reactive than carbon, so extraction needs electrolysis. Had M been below carbon, the carbon would have displaced it and a reaction would have been seen."},
  {q:"A table shows when metals were first extracted: gold (ancient times), iron (about 3000 years ago), aluminium (1800s). What best explains this pattern?",
   opts:["The least reactive metals were usable earliest because they need little or no extraction","Older civilisations preferred shiny metals","Aluminium was only discovered underground recently","Iron is rarer than gold"], c:0,
   e:"Gold occurs native, iron needs only carbon reduction (possible in early furnaces), but aluminium is above carbon and had to wait for electricity and electrolysis in the 1800s. The pattern tracks reactivity, not fashion or rarity."},
  {q:"Why is recycling aluminium much cheaper than extracting it from its ore?",
   opts:["Recycled aluminium is purer than extracted aluminium","Melting scrap aluminium uses far less energy than electrolysing aluminium oxide","Recycling does not require any heating","Aluminium ore has run out"], c:1,
   e:"Re-melting scrap avoids the enormous electrical energy of electrolysis — only the energy to melt the metal is needed, a small fraction of the extraction cost. Recycling still requires heating, so the third option goes too far."}
]);

QUESTIONS["s10i-07-3"] = (QUESTIONS["s10i-07-3"] || []).concat([
  {q:"Copper(II) chloride solution is electrolysed with inert electrodes. What forms at the cathode?",
   opts:["Hydrogen gas","Chlorine gas","Copper metal","Oxygen gas"], c:2,
   e:"Copper is less reactive than hydrogen, so Cu²⁺ ions are discharged in preference to H⁺ and a pink-brown copper coating forms on the cathode. Hydrogen would only form if the metal in the solution were more reactive than hydrogen, e.g. sodium."},
  {q:"Which statement about the anode in any electrolysis cell is correct?",
   opts:["It is the negative electrode where reduction occurs","It is the positive electrode where negative ions lose electrons","It is the positive electrode where positive ions gain electrons","It is the negative electrode where atoms gain electrons"], c:1,
   e:"The anode is positive; anions are attracted to it and are oxidised by losing electrons there. Reduction (gaining electrons) happens at the cathode — mixing up the two electrodes is the classic error."},
  {q:"Molten zinc chloride is electrolysed. What are the products?",
   opts:["Zinc at the cathode and chlorine at the anode","Hydrogen at the cathode and chlorine at the anode","Zinc at the anode and chlorine at the cathode","Zinc and oxygen"], c:0,
   e:"A molten salt contains only its own ions — Zn²⁺ and Cl⁻ — so zinc metal forms at the cathode and chlorine gas at the anode. Hydrogen is only a possible product in aqueous solutions, where water supplies H⁺ ions."},
  {q:"How would you confirm that the gas produced at an anode is chlorine?",
   opts:["A lit splint gives a squeaky pop","It relights a glowing splint","It bleaches damp litmus paper white","It turns limewater milky"], c:2,
   e:"Chlorine bleaches damp litmus (it may turn red briefly first). The squeaky pop identifies hydrogen, a relit glowing splint identifies oxygen, and milky limewater identifies carbon dioxide."},
  {q:"Electrolysis of which solution would produce hydrogen at the cathode?",
   opts:["Copper sulfate solution","Silver nitrate solution","Sodium sulfate solution","Copper chloride solution"], c:2,
   e:"Sodium is more reactive than hydrogen, so in sodium sulfate solution H⁺ ions from water are discharged instead and hydrogen gas forms. Copper and silver are both less reactive than hydrogen, so those solutions deposit the metal."},
  {q:"Why does solid sodium chloride NOT conduct electricity, even though molten sodium chloride does?",
   opts:["The solid contains no ions","The ions in the solid are fixed in a lattice and cannot move","Electrons are destroyed in the solid state","The solid is too cold to carry any energy"], c:1,
   e:"Ionic solids contain ions, but they are locked in position in the giant lattice; only when molten (or dissolved) are the ions free to move and carry charge. Saying the solid 'contains no ions' is the trap — the ions exist, they just cannot travel."},
  {q:"Dilute sulfuric acid is electrolysed and the gases are collected. After some time there is 24 cm³ of gas above the cathode. Roughly what volume of gas would be above the anode?",
   opts:["48 cm³","24 cm³","12 cm³","None"], c:2,
   e:"Electrolysing acidified water gives hydrogen and oxygen in a 2:1 ratio by volume (2H₂O → 2H₂ + O₂), so the anode oxygen is half the cathode hydrogen: 12 cm³. Doubling to 48 cm³ applies the ratio the wrong way round."},
  {q:"Which half equation for the discharge of aluminium ions at a cathode is correctly balanced?",
   opts:["Al³⁺ + e⁻ → Al","Al³⁺ + 3e⁻ → Al","Al³⁺ → Al + 3e⁻","Al + 3e⁻ → Al³⁺"], c:1,
   e:"Each Al³⁺ ion carries a 3+ charge, so it must gain three electrons to become a neutral atom: Al³⁺ + 3e⁻ → Al. The version with electrons on the right shows oxidation, which happens at the anode, not the cathode."},
  {q:"In the required practical, a student electrolyses potassium iodide solution with inert electrodes. What should they expect to observe?",
   opts:["Silvery potassium forming at the cathode","Bubbles of hydrogen at the cathode and a brown colour (iodine) near the anode","Bubbles of oxygen at both electrodes","The solution freezing around the electrodes"], c:1,
   e:"Potassium is more reactive than hydrogen, so hydrogen gas bubbles off at the cathode; iodide is a halide, so iodine forms at the anode, colouring the solution brown. Potassium metal can never be obtained from an aqueous solution."},
  {q:"A student predicts the products of electrolysing molten magnesium chloride and aqueous magnesium chloride. Which row is correct (cathode product listed first)?",
   opts:["Molten: magnesium, chlorine. Aqueous: hydrogen, chlorine.","Molten: hydrogen, chlorine. Aqueous: magnesium, chlorine.","Molten: magnesium, oxygen. Aqueous: magnesium, chlorine.","Both give magnesium and chlorine."], c:0,
   e:"Molten MgCl₂ has only Mg²⁺ and Cl⁻ ions, giving magnesium and chlorine. In solution, magnesium is more reactive than hydrogen, so hydrogen forms at the cathode instead, while the halide still gives chlorine at the anode."}
]);

QUESTIONS["s10i-07-4"] = (QUESTIONS["s10i-07-4"] || []).concat([
  {q:"A gas produced when dilute acid is added to a metal gives a squeaky pop with a lit splint. The gas is:",
   opts:["Carbon dioxide","Oxygen","Hydrogen","Chlorine"], c:2,
   e:"The squeaky pop with a lit splint is the test for hydrogen, the gas made in acid + metal reactions. Carbon dioxide (from carbonates) turns limewater milky and would put a flame out, not pop."},
  {q:"Marble chips (calcium carbonate) are added to hydrochloric acid. How could the gas given off be identified?",
   opts:["Bubble it through limewater — it turns milky","Hold a lit splint to it — it pops","Hold a glowing splint to it — it relights","Smell it carefully"], c:0,
   e:"Acid + carbonate produces carbon dioxide, which turns limewater milky/cloudy. A glowing splint relighting indicates oxygen, which is not made in this reaction."},
  {q:"Which salt is made when nitric acid is neutralised by potassium hydroxide?",
   opts:["Potassium chloride","Potassium sulfate","Potassium nitrate","Potassium carbonate"], c:2,
   e:"Nitric acid always forms nitrate salts, so KOH + HNO₃ → KNO₃ + H₂O, giving potassium nitrate. Chlorides come from hydrochloric acid and sulfates from sulfuric acid."},
  {q:"Which of these is a weak acid?",
   opts:["Hydrochloric acid","Ethanoic acid","Sulfuric acid","Nitric acid"], c:1,
   e:"Ethanoic acid (in vinegar) only partially ionises in water, so it is a weak acid. Hydrochloric, sulfuric and nitric acids all ionise completely, making them strong acids — 'weak' refers to ionisation, not to dilution."},
  {q:"Copper oxide neutralises acids but is insoluble in water. Copper oxide is therefore:",
   opts:["An alkali but not a base","A base but not an alkali","Both a base and an alkali","Neither a base nor an alkali"], c:1,
   e:"Anything that neutralises an acid is a base; only soluble bases that release OH⁻ ions in water count as alkalis. Since copper oxide does not dissolve, it is a base but not an alkali."},
  {q:"A student wants the most accurate value for the pH of a solution. Which method should they choose?",
   opts:["Universal indicator paper compared with a colour chart","A calibrated pH probe and meter","Adding litmus solution","Tasting a tiny amount"], c:1,
   e:"A pH probe gives a precise numerical reading (e.g. 5.3) and removes the human judgement involved in matching colours, so it is more accurate than universal indicator. Litmus only shows acid or alkali, with no number at all."},
  {q:"The pH of a solution falls from 5 to 2. By what factor has the hydrogen ion concentration increased?",
   opts:["3 times","30 times","100 times","1000 times"], c:3,
   e:"Each drop of one pH unit multiplies the H⁺ concentration by 10, so three units means 10 × 10 × 10 = 1000 times. Simply subtracting the pH values to get '3 times' ignores the scale being based on factors of ten."},
  {q:"When preparing copper sulfate crystals, why is the filtered solution warmed gently to the point of crystallisation rather than boiled until completely dry?",
   opts:["Boiling dry would break up the hydrated crystals and cause spitting, giving a powdery, less pure product","Boiling makes the salt evaporate along with the water","The salt only forms below room temperature","Boiling turns copper sulfate into copper metal"], c:0,
   e:"Slow evaporation followed by cooling lets well-formed hydrated crystals grow; boiling to dryness drives off the water of crystallisation and spits solid out of the dish. Salts do not evaporate with the water — that distractor confuses dissolved solids with volatile liquids."},
  {q:"Which pair of starting substances is suitable for preparing pure magnesium chloride crystals?",
   opts:["Magnesium oxide and dilute sulfuric acid","Magnesium oxide and dilute hydrochloric acid","Copper oxide and dilute hydrochloric acid","Magnesium chloride and water"], c:1,
   e:"The salt takes its metal from the base and its name from the acid: magnesium oxide + hydrochloric acid → magnesium chloride + water. Sulfuric acid would give magnesium sulfate, and copper oxide would give a copper salt."},
  {q:"An indigestion tablet containing magnesium hydroxide is taken to relieve excess stomach acid (hydrochloric acid). Which equation summarises what happens to the acid?",
   opts:["H⁺ + OH⁻ → H₂O","H⁺ + Cl⁻ → HCl","Mg + 2H⁺ → Mg²⁺ + H₂","OH⁻ + Cl⁻ → HOCl"], c:0,
   e:"The hydroxide ions from the tablet neutralise the hydrogen ions of the stomach acid, forming water: H⁺ + OH⁻ → H₂O. The tablet contains magnesium hydroxide (a base), not magnesium metal, so no hydrogen gas is produced."}
]);

QUESTIONS["s10i-07-5"] = (QUESTIONS["s10i-07-5"] || []).concat([
  {q:"Iron filings are stirred into silver nitrate solution and silver metal forms. Which species is reduced?",
   opts:["The iron atoms","The silver ions","The nitrate ions","The water molecules"], c:1,
   e:"The silver ions gain electrons to become silver atoms (Ag⁺ + e⁻ → Ag), which is reduction. The iron is oxidised as it loses electrons, and the nitrate ions are spectators that do not change."},
  {q:"Which half equation shows aluminium being oxidised?",
   opts:["Al³⁺ + 3e⁻ → Al","Al → Al³⁺ + 3e⁻","Al³⁺ → Al + 3e⁻","Al + 3e⁻ → Al³⁻"], c:1,
   e:"Oxidation is loss of electrons: the aluminium atom gives up three electrons to form Al³⁺. The first option is the reverse process (reduction), which is what happens at a cathode during electrolysis."},
  {q:"In the reaction Zn + 2HCl → ZnCl₂ + H₂, which species is reduced?",
   opts:["The zinc atoms","The chloride ions","The hydrogen ions","The zinc chloride"], c:2,
   e:"The H⁺ ions from the acid gain electrons to form hydrogen molecules (2H⁺ + 2e⁻ → H₂) — they are reduced. The zinc is oxidised, and the chloride ions remain unchanged as spectators."},
  {q:"During electrolysis, the process happening at the cathode is always:",
   opts:["Oxidation, because ions lose electrons there","Reduction, because positive ions gain electrons there","Neutralisation, because the charges cancel","Displacement, because metals swap places"], c:1,
   e:"Cations arrive at the negative cathode and pick up electrons — gain of electrons is reduction (RED CAT). Oxidation happens at the anode, where anions give up electrons."},
  {q:"A copper coil is left in colourless silver nitrate solution; the solution slowly turns blue and silver crystals grow. What does the blue colour show?",
   opts:["Silver ions are entering the solution","Copper atoms have been oxidised to copper ions, which colour the solution","The water is being reduced","Nitrate ions are decomposing"], c:1,
   e:"Copper is more reactive than silver, so copper atoms lose electrons (oxidation) and dissolve as blue Cu²⁺ ions while Ag⁺ ions are reduced to silver metal. Silver ions leaving the solution would remove colour, not create it."},
  {q:"Which statement about a redox reaction is always true?",
   opts:["Oxygen must be one of the reactants","Oxidation and reduction occur at the same time","Only metals can take part","A flame is produced"], c:1,
   e:"Redox means electrons are transferred, so whenever one species loses electrons another must gain them — the two processes are inseparable. Oxygen is not required: the electron definition covers reactions like Zn + Cu²⁺ with no oxygen at all."},
  {q:"Aluminium reacts with copper(II) ions: 2Al + 3Cu²⁺ → 2Al³⁺ + 3Cu. How many electrons are transferred for every two aluminium atoms?",
   opts:["2","3","6","12"], c:2,
   e:"Each aluminium atom loses 3 electrons, so two atoms lose 6 — exactly enough for three Cu²⁺ ions to gain 2 each (3 × 2 = 6). Choosing 3 counts the electrons from only one aluminium atom."},
  {q:"Chlorine is bubbled through potassium bromide solution: Cl₂ + 2KBr → 2KCl + Br₂. Which species is oxidised?",
   opts:["The chlorine molecules","The bromide ions","The potassium ions","The water"], c:1,
   e:"Each bromide ion loses an electron to become part of a bromine molecule (2Br⁻ → Br₂ + 2e⁻), so the bromide is oxidised. The chlorine gains those electrons and is reduced; potassium ions are spectators. Redox applies to non-metals too."},
  {q:"Given the half equations Mg → Mg²⁺ + 2e⁻ and Ag⁺ + e⁻ → Ag, how many silver ions react with each magnesium atom in the overall reaction?",
   opts:["One","Two","Three","Four"], c:1,
   e:"Electrons lost must equal electrons gained: magnesium releases 2 electrons, and each silver ion accepts only 1, so 2 silver ions are needed per magnesium atom. Assuming a 1:1 ratio ignores the charge difference between Mg²⁺ and Ag⁺."},
  {q:"Which of these reactions is NOT a redox reaction?",
   opts:["Magnesium reacting with dilute acid","Electrolysis of molten lead bromide","Mixing two salt solutions to form an insoluble precipitate","Chlorine displacing bromine from potassium bromide"], c:2,
   e:"In a precipitation reaction the ions simply pair up and settle out — no electrons are transferred and no oxidation states change. The other three all involve electron transfer, so they are redox reactions."}
]);
