// content/y10/science/islands/x08.js — EXPANSION: Topic 8 extra flashcards + questions.
// Loads AFTER t08.js. Authored by the atlas-content skill. All items original.

FLASHCARDS.push(
  // s10i-08-1 — Exothermic & Endothermic Reactions (extra)
  {id:"s10fc-08-1-6", islandId:"s10i-08-1", front:"Does an endothermic reaction still need activation energy?",
   back:"Yes. Every reaction, whether exothermic or endothermic, needs activation energy.\n\nParticles must collide with at least this minimum energy before any bonds can start to break.\n\nOn an endothermic reaction profile, the curve still rises to a peak above the reactants before settling at the (higher) product level. The activation energy is measured from the reactant level up to the top of the peak — not from the product level.", difficulty:2, category:"concept"},
  {id:"s10fc-08-1-7", islandId:"s10i-08-1", front:"In the temperature-change required practical, a student investigates how the volume of alkali added to a fixed volume of acid affects the temperature change. Name the independent, dependent and control variables.",
   back:"Independent variable: the volume of alkali added (the thing deliberately changed).\n\nDependent variable: the maximum temperature change (the thing measured).\n\nControl variables (kept the same):\n• Volume and concentration of the acid\n• Concentration of the alkali\n• Starting temperature\n• Type of cup and lid (same insulation)\n\nControlling these makes it a fair test, so any change in temperature rise is caused only by the volume of alkali.", difficulty:2, category:"application"},
  {id:"s10fc-08-1-8", islandId:"s10i-08-1", front:"In an energy transfer during a chemical reaction, is energy ever created or destroyed?",
   back:"No. Energy is conserved — the total amount of energy before and after a reaction is the same.\n\nIn an exothermic reaction, energy moves FROM the chemical store of the reacting substances TO the surroundings (which warm up).\n\nIn an endothermic reaction, energy moves FROM the surroundings TO the chemical store of the products (the surroundings cool down).\n\nThe energy is only transferred between stores; none disappears and none appears from nowhere.", difficulty:1, category:"concept"},

  // s10i-08-2 — Bond Energy Calculations (extra)
  {id:"s10fc-08-2-6", islandId:"s10i-08-2", front:"Calculate the energy change for: N₂ + O₂ → 2NO\nBond energies: N≡N = 945 kJ/mol, O=O = 498 kJ/mol, N=O = 607 kJ/mol",
   back:"Bonds broken:\n1 × N≡N = 945 kJ\n1 × O=O = 498 kJ\nTotal in = 1443 kJ\n\nBonds made:\n2 × N=O = 2 × 607 = 1214 kJ\nTotal out = 1214 kJ\n\nΔH = 1443 − 1214 = +229 kJ/mol\n\nPositive value → endothermic. More energy is needed to break the very strong N≡N triple bond than is released forming the new N=O bonds.", difficulty:3, category:"calculation"},
  {id:"s10fc-08-2-7", islandId:"s10i-08-2", front:"How do you count the bonds in a molecule before a bond energy calculation?",
   back:"Draw or picture the structural formula and count every bond line:\n\n• CH₄ has 4 × C–H bonds\n• H₂O has 2 × O–H bonds\n• O₂ has 1 × O=O double bond (count it once, not twice)\n• CO₂ (O=C=O) has 2 × C=O bonds\n• NH₃ has 3 × N–H bonds\n\nThen multiply by any number in front of the formula in the equation: 2H₂O contains 2 × 2 = 4 O–H bonds.\n\nMiscounting bonds is the most common source of error in these calculations.", difficulty:2, category:"calculation"},
  {id:"s10fc-08-2-8", islandId:"s10i-08-2", front:"How does a reaction profile link to bond breaking and bond making?",
   back:"The rising part of the curve (up to the peak) represents bond BREAKING in the reactants — energy is being absorbed, which is why the curve climbs.\n\nThe falling part of the curve (down from the peak) represents new bonds being MADE in the products — energy is being released.\n\nWhere the curve finishes relative to where it started shows the overall result:\n• Finishes lower → more energy released than absorbed → exothermic\n• Finishes higher → more energy absorbed than released → endothermic", difficulty:2, category:"concept"},

  // s10i-08-3 — Cells, Batteries & Fuel Cells (extra)
  {id:"s10fc-08-3-6", islandId:"s10i-08-3", front:"Why does a cell made with two electrodes of the SAME metal produce no voltage?",
   back:"The voltage of a simple cell comes from the DIFFERENCE in reactivity between the two electrode metals.\n\nIf both electrodes are the same metal (e.g. two strips of copper), there is no difference in reactivity, so no overall potential difference is created — the voltmeter reads 0 V.\n\nThis is also why the voltage grows as you choose metals further apart in the reactivity series.", difficulty:2, category:"concept"},
  {id:"s10fc-08-3-7", islandId:"s10i-08-3", front:"Besides the choice of metals, what else affects the voltage of a simple cell, and why does a cell eventually stop producing a voltage?",
   back:"The TYPE of electrolyte also affects the voltage — different dissolved substances give different voltages with the same pair of metals. (Pure water is no good: it contains too few ions to conduct.)\n\nA cell stops producing a voltage when one of the reacting chemicals is used up. In a non-rechargeable cell this is permanent; in a rechargeable cell an external current can reverse the reactions and restore the reactants.", difficulty:2, category:"concept"},
  {id:"s10fc-08-3-8", islandId:"s10i-08-3", front:"A car maker is choosing between hydrogen fuel cells and rechargeable battery packs. What points should they weigh up?",
   back:"For fuel cells:\n• Refuelling with hydrogen takes minutes; recharging a battery takes much longer\n• Lighter for the same energy stored\n• Only water is produced while driving\n\nAgainst fuel cells:\n• Very few hydrogen filling stations exist\n• Hydrogen must be stored at high pressure and is very flammable\n• Most hydrogen is currently made using fossil fuels, so it is not automatically low-carbon\n\nFor batteries: charging points are widespread and electricity can come from renewables — but batteries are heavy, take time to charge, and their materials must be mined and eventually disposed of or recycled.", difficulty:3, category:"application"}
);

QUESTIONS["s10i-08-1"] = (QUESTIONS["s10i-08-1"] || []).concat([
  {q:"A student mixes citric acid with sodium hydrogencarbonate solution and the thermometer reading falls. What type of reaction is this?",
   opts:["Exothermic, because a reaction always gives out heat","Endothermic, because energy is taken in from the surroundings","Neutralisation, so it must be exothermic","No reaction, because the temperature should rise"], c:1,
   e:"The surroundings (the solution and thermometer) lose energy to the reaction, so the temperature falls — this is endothermic. Not every reaction gives out heat: citric acid + sodium hydrogencarbonate is a standard endothermic example, even though many acid reactions are exothermic."},
  {q:"Self-heating coffee cans warm the drink using a chemical reaction in the base of the can. The reaction used must be:",
   opts:["Endothermic","A thermal decomposition","Exothermic","Reversible"], c:2,
   e:"To warm the drink, the reaction must transfer energy TO the surroundings — an exothermic reaction. An endothermic reaction would cool the drink instead; that is the chemistry used in instant cold packs, not self-heating cans."},
  {q:"Reusable hand warmers and sports cold packs both rely on energy changes. Which row is correct?",
   opts:["Hand warmer: endothermic; cold pack: exothermic","Hand warmer: exothermic; cold pack: endothermic","Both are exothermic","Both are endothermic"], c:1,
   e:"A hand warmer must release energy to your hands (exothermic), while a cold pack must absorb energy from the injury (endothermic). Students often swap these because they focus on the pack itself rather than the direction of energy transfer to the surroundings."},
  {q:"During an exothermic reaction, what happens to the energy stored in the reacting chemicals?",
   opts:["It increases, because the mixture gets hot","It decreases, because energy is transferred to the surroundings","It stays the same, because energy is conserved","It is destroyed as heat"], c:1,
   e:"In an exothermic reaction the chemical store loses energy, which is transferred to the surroundings — that is why the surroundings warm up. Energy is never destroyed; it is conserved overall, but the chemical store itself ends up with less."},
  {q:"In the temperature-change practical, why is the polystyrene cup fitted with a lid?",
   opts:["To stop the chemicals reacting too quickly","To keep the mixture sterile","To reduce energy transfer to the surroundings by evaporation and convection","To increase the pressure inside the cup"], c:2,
   e:"The lid limits heat loss from the surface of the liquid, so the recorded maximum temperature is closer to the true value. The lid does not change the rate of the chemical reaction itself — that depends on concentration, temperature and surface area."},
  {q:"Which statement about activation energy is correct?",
   opts:["Only endothermic reactions have an activation energy","Activation energy is the energy released when bonds form","Activation energy is the total energy change of a reaction","All reactions, including exothermic ones, have an activation energy"], c:3,
   e:"Even reactions that release energy overall need an initial input to start breaking bonds — this is why a fuel does not burn until it is ignited. Activation energy is not the overall energy change; that is the difference between reactant and product levels."},
  {q:"A student measures the temperature rise when magnesium reacts with hydrochloric acid of different concentrations. With 0.5 mol/dm³ acid the rise is 4.2 °C; with 1.0 mol/dm³ acid it is 8.4 °C. What is the best conclusion?",
   opts:["Doubling the concentration roughly doubles the temperature rise","Concentration has no effect on temperature rise","The reaction becomes endothermic at higher concentration","The thermometer must be faulty"], c:0,
   e:"4.2 °C doubling to 8.4 °C when the concentration doubles suggests the temperature rise is roughly proportional to concentration — more acid particles means more reacting and more energy released. The reaction stays exothermic throughout; the temperature still rises in both cases."},
  {q:"A solution starts at 21 °C. After a solid is dissolved in it, the temperature is 13 °C. What is the temperature change, and what does it show?",
   opts:["+8 °C; exothermic","−8 °C; endothermic","−13 °C; endothermic","+13 °C; exothermic"], c:1,
   e:"Change = final − start = 13 − 21 = −8 °C. The surroundings cooled, so energy was taken in: endothermic. The change is the difference between the readings, not the final temperature itself, so −13 °C is wrong."},
  {q:"On a reaction profile, the reactants sit at 50 kJ, the peak of the curve is at 120 kJ and the products sit at 30 kJ. What is the activation energy?",
   opts:["120 kJ","90 kJ","70 kJ","20 kJ"], c:2,
   e:"Activation energy is measured from the reactant level to the top of the peak: 120 − 50 = 70 kJ. It is not the height of the peak itself (120 kJ) — the curve starts at the reactant level, not at zero. (The overall change here is 30 − 50 = −20 kJ, exothermic.)"},
  {q:"A student repeats a neutralisation experiment four times and records temperature rises of 6.0 °C, 6.2 °C, 9.8 °C and 6.1 °C. What is the best value to report for the mean rise?",
   opts:["7.0 °C, the mean of all four results","6.1 °C, the mean of the three concordant results","9.8 °C, the largest value recorded","6.0 °C, the first result taken"], c:1,
   e:"9.8 °C is an anomaly — it does not fit the pattern of the other three — so it should be excluded. Mean = (6.0 + 6.2 + 6.1) ÷ 3 = 18.3 ÷ 3 = 6.1 °C. Including the anomaly (giving 7.0 °C) would drag the mean away from the true value."}
]);

QUESTIONS["s10i-08-2"] = (QUESTIONS["s10i-08-2"] || []).concat([
  {q:"How many O–H bonds must be made to form the products in: CH₄ + 2O₂ → CO₂ + 2H₂O?",
   opts:["2","4","6","8"], c:1,
   e:"Each water molecule contains two O–H bonds, and two water molecules are formed: 2 × 2 = 4. A common slip is to count only one O–H per water molecule, or to forget the 2 in front of H₂O in the equation."},
  {q:"A bond energy calculation gives ΔH = +57 kJ/mol. What does this tell you?",
   opts:["The reaction is exothermic","The reaction releases 57 kJ to the surroundings per mole","The reaction is endothermic, taking in 57 kJ per mole overall","The reaction cannot happen"], c:2,
   e:"A positive ΔH means more energy was used breaking bonds than was released making them, so there is a net intake of energy — endothermic. A positive value does not mean the reaction is impossible; thermal decomposition reactions happen all the time with positive energy changes."},
  {q:"In an endothermic reaction, how does the energy needed to break bonds compare with the energy released making bonds?",
   opts:["Breaking < making","Breaking = making","Breaking > making","They cannot be compared"], c:2,
   e:"If bond breaking absorbs more energy than bond making releases, the shortfall is taken from the surroundings — that is exactly what endothermic means. If breaking were less than making, the surplus would be released and the reaction would be exothermic instead."},
  {q:"Why is energy released when a new chemical bond forms?",
   opts:["Because the atoms move to a more stable, lower-energy arrangement","Because the atoms heat up as they collide","Because energy is created by the new bond","Because the electrons are destroyed"], c:0,
   e:"Bonded atoms are at a lower energy than separate atoms, and the difference is released to the surroundings. Energy is never created or destroyed — it is transferred from the chemical store, which is why 'energy is created' is wrong despite sounding plausible."},
  {q:"What are the units of bond energy?",
   opts:["kJ","J/g","°C","kJ/mol"], c:3,
   e:"Bond energy is the energy needed to break one MOLE of a given bond, so the units are kilojoules per mole (kJ/mol). Plain kJ would describe a quantity of energy with no link to the amount of substance involved."},
  {q:"Which bond in this data set would need the most energy to break? C–C = 347 kJ/mol, C=C = 614 kJ/mol, H–H = 436 kJ/mol, C–H = 413 kJ/mol",
   opts:["C–C","C=C","H–H","C–H"], c:1,
   e:"The bond energy IS the energy needed to break the bond, so the largest value, C=C at 614 kJ/mol, is the hardest to break. Do not assume single bonds in the most common molecules are strongest — the double bond holds the atoms together more strongly here."},
  {q:"Calculate ΔH for: H₂ + Br₂ → 2HBr. Bond energies: H–H = 436, Br–Br = 193, H–Br = 366 kJ/mol.",
   opts:["+103 kJ/mol","−263 kJ/mol","−103 kJ/mol","+263 kJ/mol"], c:2,
   e:"Broken: 436 + 193 = 629 kJ. Made: 2 × 366 = 732 kJ. ΔH = 629 − 732 = −103 kJ/mol, exothermic. The +103 answer comes from subtracting the wrong way round (made − broken) — always do broken minus made."},
  {q:"Calculate ΔH for: N₂ + 3H₂ → 2NH₃. Bond energies: N≡N = 945, H–H = 436, N–H = 391 kJ/mol.",
   opts:["−93 kJ/mol","+93 kJ/mol","−965 kJ/mol","+1209 kJ/mol"], c:0,
   e:"Broken: 945 + (3 × 436) = 945 + 1308 = 2253 kJ. Made: 6 × 391 = 2346 kJ (two NH₃ molecules, three N–H bonds each). ΔH = 2253 − 2346 = −93 kJ/mol, exothermic. Counting only three N–H bonds instead of six is the classic error here."},
  {q:"Calculate ΔH for: 2HI → H₂ + I₂. Bond energies: H–I = 298, H–H = 436, I–I = 151 kJ/mol.",
   opts:["−9 kJ/mol","+9 kJ/mol","+298 kJ/mol","−587 kJ/mol"], c:1,
   e:"Broken: 2 × 298 = 596 kJ. Made: 436 + 151 = 587 kJ. ΔH = 596 − 587 = +9 kJ/mol, slightly endothermic. Note the 2 in front of HI means TWO H–I bonds are broken; forgetting it would wrongly make the reaction look strongly exothermic."},
  {q:"A reaction has ΔH = −120 kJ/mol and the total energy needed to break the bonds is 880 kJ. How much energy is released making the new bonds?",
   opts:["760 kJ","880 kJ","1000 kJ","120 kJ"], c:2,
   e:"ΔH = broken − made, so made = broken − ΔH = 880 − (−120) = 1000 kJ. For an exothermic reaction the bonds made must release MORE than the 880 kJ used, so 760 kJ (the result of subtracting 120 instead of adding it) cannot be right."}
]);

QUESTIONS["s10i-08-3"] = (QUESTIONS["s10i-08-3"] || []).concat([
  {q:"A student builds a cell using two strips of copper as the electrodes. What will the voltmeter read?",
   opts:["A large voltage, because copper is a good conductor","0 V, because there is no difference in reactivity between the electrodes","A negative voltage","The same voltage as a zinc–copper cell"], c:1,
   e:"The voltage comes from the reactivity DIFFERENCE between the two metals. Two identical electrodes have no difference, so no voltage is produced. Being a good electrical conductor is not enough — conduction alone does not drive the chemical reaction."},
  {q:"Which combination is essential for a simple cell to produce a voltage?",
   opts:["Two different metals dipped in an electrolyte","Two different metals dipped in distilled water","Two identical metals dipped in salt solution","One metal dipped in an acid"], c:0,
   e:"A cell needs two metals of different reactivity AND an electrolyte to carry charge between them. Distilled water contains almost no ions, so it cannot act as an electrolyte even with two suitable metals."},
  {q:"What is the role of the electrolyte in a chemical cell?",
   opts:["It glues the electrodes together","It stops the metals corroding","It contains ions that allow charge to flow through the solution","It supplies oxygen to the electrodes"], c:2,
   e:"The electrolyte is an ionic solution: its ions move and complete the circuit between the electrodes, allowing the cell to push current round the external wire. Far from preventing corrosion, the electrolyte takes part in reactions with the electrode metals."},
  {q:"How does recharging restore a rechargeable cell?",
   opts:["It refills the cell with fresh electrolyte","An external current reverses the cell's chemical reactions, re-forming the original reactants","It heats the cell so the products decompose","It replaces the electrodes with new metal"], c:1,
   e:"Connecting the cell to an external power supply drives the reactions backwards, turning the products back into the original reactants. Nothing is physically replaced or refilled — the same chemicals are recycled inside the sealed cell."},
  {q:"Which substance is produced at the point of use by a hydrogen–oxygen fuel cell?",
   opts:["Carbon dioxide","Hydrogen peroxide","Water only","Water and carbon monoxide"], c:2,
   e:"The overall reaction is 2H₂ + O₂ → 2H₂O, so water is the only product made by the cell itself. No carbon compounds can form because no carbon enters the cell — carbon dioxide may be released earlier, when the hydrogen is manufactured, but not by the cell."},
  {q:"Why does a hydrogen fuel cell never need recharging?",
   opts:["Its reactions reverse themselves automatically","Its reactants, hydrogen and oxygen, are supplied continuously from outside","It stores an unlimited amount of energy","It does not use any chemical reactions"], c:1,
   e:"Unlike a battery, a fuel cell does not store its reactants internally — fresh hydrogen and oxygen flow in for as long as the cell runs, so the reactants are never used up. It still relies entirely on a chemical (electrochemical) reaction; the reaction simply never runs out of fuel."},
  {q:"A student pairs different metals with copper and measures the cell voltage: magnesium 2.7 V, zinc 1.1 V, iron 0.8 V. What do these results show?",
   opts:["Iron is the most reactive of the three metals","Magnesium is the most reactive, because the biggest reactivity difference gives the biggest voltage","Copper is more reactive than magnesium","Voltage is unrelated to reactivity"], c:1,
   e:"The larger the gap in reactivity between the two metals, the larger the voltage. Magnesium–copper gives the biggest voltage, so magnesium is furthest from copper in the reactivity series, i.e. the most reactive. Iron gives the smallest voltage, so it is the least reactive of the three tested."},
  {q:"Using the same copper-based cells (magnesium 2.7 V, zinc 1.1 V, iron 0.8 V), a tin–copper cell measures 0.5 V. Where should tin be placed in the reactivity series?",
   opts:["Above magnesium","Between magnesium and zinc","Between zinc and iron","Below iron but above copper"], c:3,
   e:"Tin's voltage (0.5 V) is smaller than iron's (0.8 V), so tin's reactivity is closer to copper's than iron's is — tin sits below iron. It must still be above copper, because a cell with two equally reactive metals would give 0 V, and tin gives a measurable voltage."},
  {q:"A model vehicle needs a supply of at least 7 V. How many 1.2 V rechargeable cells must be connected in series?",
   opts:["5","6","7","8"], c:1,
   e:"Cells in series add their voltages: 5 cells give 5 × 1.2 = 6.0 V, which is not enough; 6 cells give 6 × 1.2 = 7.2 V, which meets the requirement. Always round UP to the next whole cell when a minimum voltage must be reached."},
  {q:"A newspaper claims hydrogen fuel cell cars are completely carbon-free. Why might this claim be misleading?",
   opts:["Fuel cells release carbon dioxide from their exhaust","Most hydrogen is currently produced using energy from fossil fuels, releasing carbon dioxide at that stage","Hydrogen contains carbon atoms","Fuel cells burn petrol as a backup"], c:1,
   e:"The car itself emits only water, but the hydrogen has to be manufactured first — and most production methods today rely on fossil fuels, so carbon dioxide is released earlier in the chain. Hydrogen (H₂) contains no carbon, so the cell's own exhaust genuinely cannot release carbon dioxide."}
]);
