// content/y10/science/islands/x09.js — EXPANSION: Topic 9 extra flashcards + questions.
// Loads AFTER t09.js. Authored by the atlas-content skill. All items original.

// ── EXTRA FLASHCARDS ────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s10i-09-1 — Factors Affecting Rate
  {id:"s10fc-09-1-6", islandId:"s10i-09-1", front:"Describe three practical methods for measuring the rate of a reaction in the lab.",
   back:"1. Gas syringe — collect the gas produced and record the volume at regular time intervals\n2. Mass loss — stand the flask on a balance and record the decrease in mass as gas escapes\n3. Disappearing cross — time how long it takes for a precipitate to make the mixture cloudy enough to hide a cross drawn under the flask\n\nThe first two give a set of readings over time (good for graphs); the disappearing cross gives a single time for comparison between runs.", difficulty:2, category:"concept"},
  {id:"s10fc-09-1-7", islandId:"s10i-09-1", front:"Why does increasing the pressure speed up a reaction between gases?",
   back:"Increasing the pressure squeezes the same number of gas particles into a smaller volume.\n\nThe particles are closer together, so they collide more frequently. More collisions per second means more successful collisions per second, so the rate increases.\n\nThis is the gas equivalent of increasing the concentration of a solution. Pressure has no effect on reactions involving only solids and liquids.", difficulty:2, category:"concept"},
  {id:"s10fc-09-1-8", islandId:"s10i-09-1", front:"Why are catalysts so important in industry? Give an example of a biological catalyst.",
   back:"Catalysts let reactions happen faster, or at lower temperatures and pressures. This:\n• Reduces energy costs (less fuel burned)\n• Increases the amount of product made per day\n• Is sustainable — the catalyst is not used up, so a small amount lasts a long time\n\nEnzymes are biological catalysts. They are proteins that catalyse reactions in living cells, and they are also used industrially, for example in making alcoholic drinks by fermentation.", difficulty:2, category:"concept"},

  // s10i-09-2 — Collision Theory & Rate Graphs
  {id:"s10fc-09-2-6", islandId:"s10i-09-2", front:"Define activation energy.",
   back:"Activation energy is the minimum amount of energy that colliding particles must have in order to react.\n\nIf a collision has less energy than the activation energy, the particles simply bounce apart unchanged.\n\nA catalyst lowers the activation energy by providing an alternative pathway, so a greater proportion of collisions become successful.", difficulty:1, category:"definition"},
  {id:"s10fc-09-2-7", islandId:"s10i-09-2", front:"Describe a graph of the MASS of a reaction mixture against time when a gas is given off. Why is a cotton wool plug used?",
   back:"The mass falls steeply at first (fast rate, gas escaping quickly), then the curve becomes shallower and finally levels off when the reaction finishes.\n\nThe mass decreases because the gas produced escapes from the flask.\n\nA cotton wool plug in the neck of the flask lets the gas out but stops droplets of liquid spraying out — so the only mass lost is the gas itself, keeping the readings accurate.", difficulty:2, category:"concept"},
  {id:"s10fc-09-2-8", islandId:"s10i-09-2", front:"A flask loses 0.48 g of mass in 120 seconds as carbon dioxide escapes. Calculate the mean rate.",
   back:"Mean rate = mass of product released ÷ time taken\n= 0.48 g ÷ 120 s\n= 0.004 g/s\n\nNotice the units: because the measurement was mass, the rate is in g/s, not cm³/s. Always match the unit of rate to the quantity you measured.", difficulty:2, category:"calculation"},

  // s10i-09-3 — Reversible Reactions & Dynamic Equilibrium
  {id:"s10fc-09-3-6", islandId:"s10i-09-3", front:"What happens when ammonium chloride is heated, and why is this a reversible reaction?",
   back:"Heating white ammonium chloride makes it break down (thermally decompose) into two gases: ammonia and hydrogen chloride.\n\nNH₄Cl ⇌ NH₃ + HCl\n\nWhen the gases cool — for example on the cooler upper walls of the test tube — they recombine to re-form white ammonium chloride.\n\nBecause the products react together to re-form the reactant, the reaction is reversible and is written with the ⇌ symbol.", difficulty:2, category:"concept"},
  {id:"s10fc-09-3-7", islandId:"s10i-09-3", front:"What is meant by the 'position of equilibrium'?",
   back:"The position of equilibrium describes the relative amounts of reactants and products in the equilibrium mixture.\n\n• Equilibrium 'lies to the right' — the mixture contains mostly products\n• Equilibrium 'lies to the left' — the mixture contains mostly reactants\n\nThe position depends on the reaction conditions (temperature, pressure, concentration) and can be shifted by changing them.", difficulty:1, category:"definition"},
  {id:"s10fc-09-3-8", islandId:"s10i-09-3", front:"How can anhydrous copper(II) sulfate be used as a chemical test for water?",
   back:"Add the liquid being tested to white anhydrous copper(II) sulfate powder.\n\nIf water is present, the powder turns blue as hydrated copper(II) sulfate forms. The change is also exothermic, so the tube warms up.\n\nThis works because the dehydration of copper sulfate is reversible — adding water simply drives the reverse reaction. Note: the test shows water is present, but not that the liquid is pure water.", difficulty:2, category:"concept"},

  // s10i-09-4 — Le Chatelier's Principle
  {id:"s10fc-09-4-6", islandId:"s10i-09-4", front:"Why do industrial processes often use 'compromise' conditions rather than the conditions giving the highest equilibrium yield?",
   back:"For an exothermic forward reaction, a LOW temperature gives the highest equilibrium yield — but the rate would be far too slow to be profitable.\n\nA moderate temperature is chosen as a compromise: a slightly lower yield, but reached much more quickly.\n\nSimilarly, very high pressures may favour the product but are expensive and dangerous to maintain, so a moderate pressure is often used. Industry balances yield, rate, safety and cost.", difficulty:3, category:"concept"},
  {id:"s10fc-09-4-7", islandId:"s10i-09-4", front:"What happens to the position of equilibrium if pressure is changed but both sides of the equation have the same number of gas molecules?",
   back:"Nothing — the position of equilibrium does not move.\n\nExample: H₂(g) + I₂(g) ⇌ 2HI(g) has 2 molecules of gas on each side, so changing the pressure has no effect on the position of equilibrium.\n\nAlways count the moles of GAS on each side before predicting a pressure effect. Solids and liquids in the equation are not counted.", difficulty:3, category:"concept"},
  {id:"s10fc-09-4-8", islandId:"s10i-09-4", front:"2SO₂(g) + O₂(g) ⇌ 2SO₃(g) — the forward reaction is exothermic. Which conditions give the maximum equilibrium yield of SO₃?",
   back:"• LOW temperature — shifts equilibrium in the exothermic (forward) direction, making more SO₃\n• HIGH pressure — 3 gas molecules on the left, 2 on the right, so high pressure shifts equilibrium to the right\n\nIn practice a moderate temperature is used because a low temperature would make the rate too slow — another example of compromise conditions.", difficulty:3, category:"concept"}
);

// ── EXTRA QUESTIONS ─────────────────────────────────────────────────────────
QUESTIONS["s10i-09-1"] = (QUESTIONS["s10i-09-1"] || []).concat([
  {q:"Two gases react inside a sealed container. Increasing the pressure makes the reaction faster because:",
   opts:["The gas particles are squeezed closer together, so they collide more often","The activation energy is lowered","The gas particles gain more energy","The gas particles become smaller"], c:0,
   e:"Higher pressure forces the same number of particles into a smaller volume, so collisions happen more frequently. The particles' energy and the activation energy are unchanged — only temperature changes particle energy, and only a catalyst lowers activation energy."},
  {q:"A reaction is catalysed by 0.5 g of manganese dioxide. At the end of the reaction, the manganese dioxide:",
   opts:["Has all been converted into product","Has been used up completely","Is chemically unchanged and still weighs 0.5 g","Weighs less because some has dissolved into the products"], c:2,
   e:"A catalyst speeds up a reaction without being chemically changed or used up, so all 0.5 g can be recovered at the end. It is tempting to think it must be consumed like a reactant, but a catalyst only provides an alternative pathway — it does not appear in the overall equation."},
  {q:"Enzymes are best described as:",
   opts:["Reactants found only in plants","Biological catalysts made of protein","Products of respiration","Acids that speed up digestion"], c:1,
   e:"Enzymes are biological catalysts — proteins that speed up reactions in living organisms without being used up. They are not reactants or products of the reactions they catalyse, and although some work in acidic conditions, they are not themselves acids."},
  {q:"In the reaction between sodium thiosulfate solution and hydrochloric acid, the rate is usually measured by:",
   opts:["Collecting the gas in a gas syringe","Recording the temperature rise with a thermometer","Weighing the flask every 10 seconds","Timing how long it takes for a cross under the flask to disappear from view"], c:3,
   e:"This reaction forms a fine precipitate of sulfur that gradually makes the mixture cloudy. The rate is found by timing how long the cross beneath the flask takes to become invisible — a shorter time means a faster rate. No useful volume of gas is collected, so a gas syringe is not suitable here."},
  {q:"Excess magnesium reacts with 25 cm³ of dilute hydrochloric acid. The experiment is repeated with the same acid at a higher temperature. Compared with the first experiment, the total volume of hydrogen produced will be:",
   opts:["Greater, because the reaction is faster","The same, because the amount of acid has not changed","Smaller, because hydrogen escapes more easily when hot","Double, because rate doubles with every 10 °C rise"], c:1,
   e:"Temperature only changes how FAST the product forms, not how MUCH forms. The total volume of hydrogen depends on the moles of the limiting reactant (the acid), which is identical in both runs. The tempting answer is 'greater because faster', but speed and total yield are independent."},
  {q:"Why does the rate of a reaction decrease as the reaction proceeds?",
   opts:["The activation energy increases over time","The reactants are being used up, so their concentration falls and collisions become less frequent","The products act as inhibitors","The temperature always drops during a reaction"], c:1,
   e:"As reactants are consumed, fewer reactant particles remain in the mixture, so collisions between them happen less often and the rate falls. The activation energy is fixed for a given reaction, and products do not generally block the reaction."},
  {q:"A student investigates how acid concentration affects the rate of reaction with magnesium ribbon. Which set of variables must be kept the same?",
   opts:["Acid concentration and reaction time","Volume of gas collected and concentration","Temperature, length of magnesium ribbon and volume of acid","Only the type of gas syringe used"], c:2,
   e:"To make it a fair test, everything except the concentration must be controlled: temperature, the mass and surface area of magnesium (same length of ribbon) and the volume of acid. Reaction time and gas volume are results you measure, not variables you control."},
  {q:"In a disappearing cross experiment, run A at 20 °C takes 80 s and run B at 40 °C takes 20 s. Which statement is correct?",
   opts:["Run B is slower because it finished sooner","Run B is faster; rate can be compared using 1 divided by the time taken","Run A is faster because it ran for longer","Both runs have the same rate because the same cross was used"], c:1,
   e:"A shorter time for the cross to disappear means a faster reaction, and rate is proportional to 1/time (1/20 is larger than 1/80, so B is four times faster). Do not confuse a longer time with a faster rate — running for longer means the reaction was slower."},
  {q:"A reaction mixture is cooled from 50 °C to 10 °C. The rate decreases because:",
   opts:["Particles collide less often AND a smaller proportion of collisions have energy above the activation energy","The particles get bigger and block each other","The activation energy increases as the mixture cools","The reactant concentration decreases as it cools"], c:0,
   e:"Cooling lowers the kinetic energy of particles: they move more slowly, collide less frequently, and a smaller fraction of those collisions reach the activation energy. The activation energy itself does not change with temperature, and cooling does not change concentration."},
  {q:"Marble chips react with dilute acid, releasing carbon dioxide. Which measurement would allow the rate to be followed during the reaction?",
   opts:["Measuring the height of the marble chips with a ruler","Recording the colour of the acid every minute","Recording the decrease in mass of the flask on a balance","Measuring the pH of the carbon dioxide gas"], c:2,
   e:"As carbon dioxide escapes, the flask gets lighter, so recording mass against time on a balance tracks the rate directly. The acid is colourless throughout, the chips' height tells you little, and pH is a property of solutions, not a useful gas measurement here."}
]);

QUESTIONS["s10i-09-2"] = (QUESTIONS["s10i-09-2"] || []).concat([
  {q:"Activation energy is best defined as:",
   opts:["The energy released when a reaction finishes","The total energy of all the particles in a reaction","The minimum energy colliding particles need in order to react","The energy a catalyst adds to the particles"], c:2,
   e:"Activation energy is the minimum energy a collision must have for the particles to react — below it, particles bounce apart unchanged. It is not energy released by the reaction, and a catalyst does not add energy; it lowers the activation energy needed."},
  {q:"A flask of acid and marble chips stands on a balance with a cotton wool plug in its neck. The reading on the balance falls because:",
   opts:["The acid evaporates through the cotton wool","Carbon dioxide gas escapes through the cotton wool","The marble dissolves and becomes weightless","The flask gets hotter and hot objects weigh less"], c:1,
   e:"The mass lost is the carbon dioxide gas escaping; the cotton wool lets gas through while stopping liquid spray from being lost, which would make readings inaccurate. Dissolved substances still have mass, and temperature does not change an object's mass."},
  {q:"During an experiment, a reaction mixture loses 1.5 g of mass in 50 seconds. The mean rate of reaction is:",
   opts:["75 g/s","0.3 g/s","33.3 g/s","0.03 g/s"], c:3,
   e:"Mean rate = mass lost divided by time = 1.5 g divided by 50 s = 0.03 g/s. The tempting error is 0.3 g/s from a slip in the division — always check the decimal place, and never multiply mass by time."},
  {q:"Which best describes a graph of the MASS of a reaction mixture against time, when a gas is produced and escapes?",
   opts:["A straight line going upwards","A curve that falls steeply at first, then levels off","A horizontal line throughout","A curve that rises slowly then falls"], c:1,
   e:"Mass is lost fastest at the start when the rate is highest, so the curve drops steeply, then flattens as reactants run out and the reaction stops. Volume-of-gas graphs rise, but mass graphs fall — do not mix up the two."},
  {q:"Two volume–time curves, X and Y, are drawn for the same amounts of the same reactants. Curve X is steeper than Y at the start, and both level off at the same final volume. The most likely explanation is:",
   opts:["X used a higher temperature or concentration than Y","X used twice as much reactant as Y","Y had a catalyst and X did not","X produced a different gas from Y"], c:0,
   e:"A steeper initial gradient with the same final volume means X reacted faster but made the same total product — exactly what higher temperature or concentration does. If X had used more reactant, its final volume would be higher; if Y had the catalyst, Y would be the steeper curve."},
  {q:"A tangent drawn on a volume–time curve passes through the points (10 s, 20 cm³) and (30 s, 60 cm³). The rate of reaction at that moment is:",
   opts:["3 cm³/s","2 cm³/s","40 cm³/s","0.5 cm³/s"], c:1,
   e:"Gradient = change in y divided by change in x = (60 − 20) divided by (30 − 10) = 40 divided by 20 = 2 cm³/s. A common slip is inverting the fraction to get 0.5, so always put the volume change on top and the time change underneath."},
  {q:"Reactant particles collide constantly, yet most collisions do not produce a reaction. Why not?",
   opts:["Most particles are too large to react","Most collisions lack sufficient energy or have the wrong orientation","Collisions only count if a catalyst is present","Particles must collide three at a time to react"], c:1,
   e:"Only collisions with at least the activation energy AND the correct orientation are successful — the vast majority fail one of these tests. A catalyst is not required for a reaction; it simply increases the proportion of successful collisions."},
  {q:"A fixed mass of magnesium (the limiting reactant) reacts with excess acid. The experiment is repeated with acid of double the concentration. On a volume–time graph, the second curve will:",
   opts:["Be steeper at the start and level off at double the volume","Be identical to the first curve","Be steeper at the start but level off at the same final volume","Be shallower and level off at the same final volume"], c:2,
   e:"Doubling the acid concentration roughly doubles the collision frequency, so the initial gradient is steeper. But the total hydrogen depends on the limiting magnesium, which is unchanged, so the final volume is the same. 'Double the volume' wrongly assumes concentration changes the amount of product."},
  {q:"A rate experiment follows the change in concentration of a reactant in solution. The most appropriate unit for the rate is:",
   opts:["mol/dm³/s","cm³/s","g/s","degrees per second"], c:0,
   e:"Rate units match the quantity measured: concentration change gives mol/dm³/s. Use cm³/s only for gas volume measurements and g/s only for mass measurements."},
  {q:"Curve B levels off at exactly half the final volume of curve A, with both experiments run under identical conditions. The most likely difference is:",
   opts:["Experiment B was carried out at a lower temperature","Experiment B used half the amount of the limiting reactant","Experiment B used a catalyst","Experiment B used powdered reactant instead of lumps"], c:1,
   e:"The final volume depends only on the amount of limiting reactant, so half the final volume means half the limiting reactant was used. Temperature, catalysts and surface area change how fast the curve climbs, but they cannot change the final volume reached."}
]);

QUESTIONS["s10i-09-3"] = (QUESTIONS["s10i-09-3"] || []).concat([
  {q:"White ammonium chloride is heated in a test tube. It breaks down into ammonia and hydrogen chloride gases, and a white solid re-forms on the cooler upper walls of the tube. This shows that the decomposition is:",
   opts:["Irreversible","Reversible — the products recombine on cooling","A combustion reaction","An example of catalysis"], c:1,
   e:"The two gases recombine where the tube is cooler, re-forming ammonium chloride: NH₄Cl ⇌ NH₃ + HCl. Because the products react together to re-form the reactant, the reaction is reversible. Nothing is burning, so it is not combustion."},
  {q:"A student adds a few drops of a liquid to white anhydrous copper(II) sulfate, which turns blue. What does this show?",
   opts:["The liquid is pure water","The liquid contains water","The liquid is an acid","The copper sulfate has decomposed"], c:1,
   e:"The colour change from white to blue shows water is present, because water re-forms blue hydrated copper(II) sulfate. The test cannot prove the liquid is PURE water — any mixture containing water gives the same result. To check purity you would measure the boiling point."},
  {q:"The forward reaction of a reversible reaction releases 26 kJ of energy. The reverse reaction:",
   opts:["Releases 26 kJ","Absorbs 26 kJ","Absorbs 52 kJ","Releases an unpredictable amount of energy"], c:1,
   e:"In a reversible reaction, energy transferred one way is exactly matched in the other direction: an exothermic forward reaction releasing 26 kJ means an endothermic reverse reaction absorbing 26 kJ. The amounts are always equal, never doubled."},
  {q:"A chemist says 'the equilibrium lies to the left' for a particular reaction. This means the equilibrium mixture contains:",
   opts:["Mostly reactants","Mostly products","Equal amounts of reactants and products","No products at all"], c:0,
   e:"'To the left' means the left-hand side of the equation — the reactants — dominates the mixture. Some product is still present (it is never zero at equilibrium), but the position describes which side is favoured."},
  {q:"A closed flask initially contains only reactants. As the system moves towards equilibrium:",
   opts:["The forward rate increases and the reverse rate decreases","The forward rate decreases and the reverse rate increases, until they become equal","Both rates stay constant from the start","The reverse reaction cannot begin until the forward reaction finishes"], c:1,
   e:"At the start, reactant concentration is high so the forward rate is at its fastest; as products build up, the reverse rate grows while the forward rate falls. Equilibrium is reached when the two rates meet. The reverse reaction begins as soon as any product exists — it does not wait."},
  {q:"Blue hydrated copper(II) sulfate is heated strongly in an OPEN boiling tube. Why does the reaction go to completion instead of reaching equilibrium?",
   opts:["The reaction is not reversible when heated strongly","Open tubes increase the activation energy","Equilibrium only happens in industrial reactors","The water vapour escapes, so the reverse reaction cannot occur"], c:3,
   e:"Equilibrium needs a closed system. In an open tube the water vapour escapes into the air, so it can never recombine with the anhydrous solid — the reverse reaction is impossible and all the solid eventually turns white. The reaction itself is still reversible; the conditions just prevent equilibrium."},
  {q:"A sealed flask contains brown nitrogen dioxide in equilibrium with a colourless gas. After a while, the brown colour stops changing. This shows that:",
   opts:["Both reactions have stopped","All the nitrogen dioxide has been used up","The forward and reverse reactions are still occurring at equal rates","The flask has developed a leak"], c:2,
   e:"A constant colour means constant concentrations — the definition of dynamic equilibrium. Both reactions continue, but at equal rates, so there is no net change. If the reactions had stopped or all the brown gas had reacted, the colour would not simply hold steady at an intermediate shade."},
  {q:"Which of the following changes is NOT reversible?",
   opts:["Heating hydrated copper(II) sulfate","Burning methane in air","Heating ammonium chloride","The reaction of nitrogen and hydrogen to form ammonia"], c:1,
   e:"Combustion is effectively irreversible: carbon dioxide and water do not recombine into methane under any practical conditions. The other three are classic reversible reactions written with the ⇌ symbol."},
  {q:"In the equation A + B ⇌ C, what does the right-to-left direction represent?",
   opts:["The forward reaction making C","The reverse reaction, in which C breaks down to re-form A and B","The reaction stopping","C being removed from the system"], c:1,
   e:"Reading the ⇌ symbol from right to left gives the reverse reaction: the product C reacting to re-form the reactants A and B. The left-to-right direction is the forward reaction. Neither direction means the reaction has stopped."},
  {q:"A student claims: 'Once equilibrium is reached, the reaction has finished, so nothing more can ever happen in the flask.' Why is this claim wrong?",
   opts:["Equilibrium reactions finish only when heated","The forward and reverse reactions are both still occurring, so the system can respond if conditions change","Equilibrium means the products have all escaped","The claim is correct — equilibrium means the reaction is over"], c:1,
   e:"Equilibrium is dynamic: particles are continually reacting in both directions at equal rates. Because the reactions have not stopped, changing the conditions (such as adding more reactant) will disturb the balance and the system will respond. 'No visible change' is not the same as 'no reaction'."}
]);

QUESTIONS["s10i-09-4"] = (QUESTIONS["s10i-09-4"] || []).concat([
  {q:"In the equilibrium N₂O₄(g) ⇌ 2NO₂(g), the forward reaction is endothermic and NO₂ is dark brown. Heating the sealed flask will make the mixture:",
   opts:["Paler, as equilibrium shifts left","Darker, as equilibrium shifts right in the endothermic direction","Stay the same colour","Colourless, as all the gas decomposes"], c:1,
   e:"Raising the temperature shifts equilibrium in the endothermic direction to absorb the added heat — here that is the forward direction, making more brown NO₂ and darkening the mixture. Shifting left would happen on cooling, not heating."},
  {q:"For the equilibrium 2NO₂(g) ⇌ N₂O₄(g), increasing the pressure shifts the equilibrium:",
   opts:["To the left, because NO₂ is a smaller molecule","To the left, towards more gas molecules","To the right, towards the side with fewer gas molecules","Nowhere, because pressure never affects equilibria"], c:2,
   e:"There are 2 gas molecules on the left and 1 on the right, so increasing pressure shifts equilibrium right — the side with fewer gas molecules — to reduce the pressure. Molecule size is irrelevant; only the NUMBER of gas molecules on each side matters."},
  {q:"For the equilibrium H₂(g) + I₂(g) ⇌ 2HI(g), doubling the pressure will:",
   opts:["Shift equilibrium to the right because 2 is bigger than 1","Shift equilibrium to the left towards the elements","Have no effect on the position, because both sides have 2 gas molecules","Stop the reverse reaction"], c:2,
   e:"Count the gas molecules: 1 + 1 = 2 on the left and 2 on the right. With equal numbers on each side, a pressure change cannot be opposed by shifting either way, so the position of equilibrium does not move. The '2HI' coefficient tempts students to think the right side is bigger — but you must total each side."},
  {q:"Adding more of a REACTANT to a system at equilibrium will:",
   opts:["Shift the equilibrium to the left","Shift the equilibrium to the right, using up some of the added reactant","Have no effect, because equilibrium has already been reached","Make the reaction irreversible"], c:1,
   e:"The system opposes the increase by shifting right, converting some of the added reactant into product. Equilibrium is dynamic, so it can always respond to a change — 'already at equilibrium' does not mean the system is frozen."},
  {q:"An equilibrium mixture is cooled. The position of equilibrium shifts:",
   opts:["In the endothermic direction","In the exothermic direction, to release heat and oppose the cooling","Towards the side with fewer molecules","It cannot shift when cooled"], c:1,
   e:"Cooling removes heat, so the system opposes this by shifting in the exothermic direction, which releases heat. The endothermic direction is favoured by HEATING. The number of molecules matters for pressure changes, not temperature changes."},
  {q:"The forward reaction of an industrial equilibrium is exothermic. A low temperature would give the highest yield, yet a moderate temperature of around 450 °C is used. Why?",
   opts:["High temperatures shift the equilibrium to the right","At low temperatures the rate would be too slow to be economical, so yield is traded for speed","The catalyst only works above 450 °C in every reaction","Low temperatures make the reaction dangerous"], c:1,
   e:"This is the classic compromise: low temperature favours the exothermic forward reaction (higher yield) but makes all particles move slowly, so equilibrium takes far too long to reach. A moderate temperature accepts a lower yield in exchange for a workable rate. High temperature actually shifts this equilibrium LEFT, reducing yield."},
  {q:"Increasing the concentration of a PRODUCT in an equilibrium mixture will:",
   opts:["Shift the equilibrium to the right","Increase the yield of product","Shift the equilibrium to the left, removing some of the added product","Have no effect"], c:2,
   e:"The system opposes the increase in product by shifting left, converting some product back into reactants. It is tempting to think adding product means more product overall, but the shift partially undoes the addition — to increase yield you should REMOVE product, not add it."},
  {q:"Changing the pressure can shift the position of an equilibrium only if:",
   opts:["The reaction involves gases and the two sides have different numbers of gas molecules","The reaction is exothermic","A catalyst is present","The reaction takes place in solution"], c:0,
   e:"Pressure changes matter only for gaseous equilibria, and only when the numbers of gas molecules on the two sides differ — otherwise there is no way for a shift to oppose the change. Reactions in solution respond to concentration, not pressure, and a catalyst never affects the position."},
  {q:"The moment extra reactant is added to a system at equilibrium, what happens to the rates of the forward and reverse reactions?",
   opts:["Both rates instantly fall to zero","The forward rate increases immediately; the system shifts right until the two rates become equal again","The reverse rate increases first, then the forward rate","Both rates stay exactly the same"], c:1,
   e:"Extra reactant means more reactant collisions, so the forward rate jumps at once while the reverse rate is initially unchanged. As more product forms, the reverse rate climbs until the two rates balance at a new equilibrium. The rates never drop to zero — equilibrium is dynamic."},
  {q:"For 2SO₂(g) + O₂(g) ⇌ 2SO₃(g), where the forward reaction is exothermic, which combination of conditions gives the highest equilibrium yield of SO₃?",
   opts:["High temperature and low pressure","High temperature and high pressure","Low temperature and high pressure","Low temperature and low pressure"], c:2,
   e:"Low temperature shifts the equilibrium in the exothermic (forward) direction, and high pressure shifts it towards the right because there are 3 gas molecules on the left but only 2 on the right. High temperature would speed up the reaction but shift the equilibrium left, cutting the yield — do not confuse a faster rate with a bigger yield."}
]);
