// content/y10/science/islands/x10.js — EXPANSION: Topic 10 extra flashcards + questions.
// Loads AFTER t10.js. Authored by the atlas-content skill. All items original.

// ── EXTRA FLASHCARDS ────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s10i-10-1 — Crude Oil & Fractional Distillation
  {id:"s10fc-10-1-6", islandId:"s10i-10-1", front:"What are the products of the complete combustion of a hydrocarbon fuel?",
   back:"When a hydrocarbon burns completely in a good supply of air:\n\nhydrocarbon + oxygen → carbon dioxide + water\n\n• The carbon atoms are oxidised to carbon dioxide\n• The hydrogen atoms are oxidised to water\n\nExample: CH₄ + 2O₂ → CO₂ + 2H₂O\n\nCombustion releases energy, which is why hydrocarbons are such important fuels.", difficulty:2, category:"concept"},
  {id:"s10fc-10-1-7", islandId:"s10i-10-1", front:"Apart from fuels, what else is crude oil used to make?",
   back:"Crude oil is the main feedstock (raw material) for the petrochemical industry.\n\nProducts made from crude oil fractions include:\n• Solvents\n• Lubricants\n• Detergents\n• Polymers (plastics)\n\nThis is one reason chemists argue crude oil is too valuable simply to burn — modern life depends on the materials made from it.", difficulty:1, category:"definition"},
  {id:"s10fc-10-1-8", islandId:"s10i-10-1", front:"Why does each fraction from crude oil boil over a range of temperatures?",
   back:"A fraction is not a pure compound — it is a mixture of hydrocarbons with similar (but not identical) numbers of carbon atoms.\n\nEach hydrocarbon in the fraction has its own boiling point, so the fraction as a whole boils over a range of temperatures.\n\nA pure substance, by contrast, boils at one fixed temperature. This is why boiling range can be used to judge how pure a substance is.", difficulty:2, category:"concept"},

  // s10i-10-2 — Alkanes, Alkenes & Cracking
  {id:"s10fc-10-2-6", islandId:"s10i-10-2", front:"What is a homologous series?",
   back:"A homologous series is a family of organic compounds that:\n\n• share the same general formula (e.g. CₙH₂ₙ₊₂ for alkanes)\n• differ from the next member by a CH₂ unit\n• show a gradual trend in physical properties (e.g. boiling point rises along the series)\n• have similar chemical reactions\n\nThe alkanes, alkenes, alcohols and carboxylic acids are all homologous series.", difficulty:2, category:"definition"},
  {id:"s10fc-10-2-7", islandId:"s10i-10-2", front:"How do you balance a cracking equation?",
   back:"In cracking, the atoms in the starting alkane are simply rearranged into smaller molecules — no atoms are gained or lost.\n\nMethod:\n1. Count the carbon atoms on each side — they must match\n2. Count the hydrogen atoms — they must match too\n\nExample: C₁₂H₂₆ → C₈H₁₈ + C₄H₈\nCarbon: 12 = 8 + 4 ✔  Hydrogen: 26 = 18 + 8 ✔\n\nIf one product is known, subtract its atoms from the starting molecule to find the other.", difficulty:3, category:"application"},
  {id:"s10fc-10-2-8", islandId:"s10i-10-2", front:"Why are alkanes useful as fuels?",
   back:"Alkanes burn readily in oxygen, releasing large amounts of energy:\n\nalkane + oxygen → carbon dioxide + water\n\n• Short-chain alkanes (e.g. methane, propane, butane) ignite easily and burn with clean flames\n• They are easy to transport and store (bottled gas)\n\nApart from combustion, alkanes are fairly unreactive because their C–C and C–H single bonds are strong, which makes them safe to handle as fuels.", difficulty:2, category:"concept"},

  // s10i-10-3 — Alcohols, Carboxylic Acids & Esters
  {id:"s10fc-10-3-6", islandId:"s10i-10-3", front:"How are esters named?",
   back:"The name has two parts:\n\n1. The alcohol gives the first word, ending in -yl\n   (methanol → methyl, ethanol → ethyl, propanol → propyl)\n2. The carboxylic acid gives the second word, ending in -anoate\n   (ethanoic acid → ethanoate, butanoic acid → butanoate)\n\nExamples:\n• ethanol + ethanoic acid → ethyl ethanoate\n• methanol + butanoic acid → methyl butanoate", difficulty:2, category:"application"},
  {id:"s10fc-10-3-7", islandId:"s10i-10-3", front:"What type of solution do alcohols form in water?",
   back:"The first four alcohols (methanol, ethanol, propanol, butanol) dissolve in water to form NEUTRAL solutions (pH about 7).\n\nKey point: the –OH group in an alcohol is NOT the same as the hydroxide ion (OH⁻) in an alkali — alcohols do not release OH⁻ ions.\n\nContrast: carboxylic acids dissolve in water to form weakly ACIDIC solutions, because their –COOH group partially ionises to release H⁺ ions.", difficulty:2, category:"concept"},
  {id:"s10fc-10-3-8", islandId:"s10i-10-3", front:"Write and balance the equation for the complete combustion of ethanol.",
   back:"C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O\n\nCheck the atoms:\n• Carbon: 2 = 2 ✔\n• Hydrogen: 6 = 6 ✔\n• Oxygen: 1 + 6 = 7 on the left; 4 + 3 = 7 on the right ✔\n\nCommon error: forgetting that ethanol itself contains one oxygen atom, which changes the number of O₂ molecules needed.\n\nClean combustion is why ethanol is used as a fuel and fuel additive.", difficulty:3, category:"application"},

  // s10i-10-4 — Polymers: Addition & Condensation
  {id:"s10fc-10-4-6", islandId:"s10i-10-4", front:"How do amino acids form proteins?",
   back:"Amino acids are unusual monomers: each ONE molecule carries two different functional groups —\n\n• an amine group (–NH₂) at one end\n• a carboxylic acid group (–COOH) at the other\n\nThe –COOH of one amino acid reacts with the –NH₂ of the next, releasing a water molecule each time. This is condensation polymerisation.\n\nThe chain formed is a polypeptide; one or more polypeptide chains fold to make a protein.", difficulty:3, category:"concept"},
  {id:"s10fc-10-4-7", islandId:"s10i-10-4", front:"How is the repeating unit of an addition polymer related to its monomer?",
   back:"The repeating unit contains exactly the same atoms as the monomer — nothing is lost.\n\nThe only change: the C=C double bond of the monomer becomes a C–C single bond in the chain, with bonds extending out of the brackets on each side.\n\nExample: propene (C₃H₆) → poly(propene), repeating unit –(C₃H₆)–\n\nTo find the monomer from a repeating unit, do the reverse: put the double bond back between the two backbone carbons.", difficulty:2, category:"concept"},
  {id:"s10fc-10-4-8", islandId:"s10i-10-4", front:"Why are polymers solid at room temperature when their monomers are often gases?",
   back:"Polymer molecules are extremely long chains.\n\nThe intermolecular forces between long chains are much stronger overall than between small monomer molecules, so a lot more energy is needed to separate the chains.\n\nResult: most polymers are solids with relatively high melting points, while small monomers such as ethene and propene are gases at room temperature.\n\nNote: the forces between chains are still intermolecular forces — the chains are not ionically bonded to each other.", difficulty:2, category:"concept"},

  // s10i-10-5 — Reactions of Alkenes (Addition)
  {id:"s10fc-10-5-6", islandId:"s10i-10-5", front:"How do alkenes react with chlorine and the other halogens?",
   back:"All the halogens (chlorine, bromine, iodine) add across the C=C double bond of an alkene in an addition reaction.\n\nOne halogen atom bonds to each of the two carbons of the double bond.\n\nExample: ethene + chlorine → 1,2-dichloroethane\nC₂H₄ + Cl₂ → C₂H₄Cl₂\n\nThe pattern is the same as the reaction with bromine — the double bond opens and the product is saturated.", difficulty:2, category:"application"},
  {id:"s10fc-10-5-7", islandId:"s10i-10-5", front:"How do alkenes burn compared with alkanes?",
   back:"Alkenes burn in air with smokier, more luminous flames than alkanes.\n\nReason: alkenes have a higher ratio of carbon to hydrogen, and they tend to undergo INCOMPLETE combustion in air.\n\nIncomplete combustion can produce:\n• carbon monoxide (a toxic gas)\n• carbon particles (soot — the smoke you see)\n\nThis is one reason alkenes are not used as fuels, even though they release energy when burned — they are far more valuable for making polymers and other chemicals.", difficulty:2, category:"concept"},
  {id:"s10fc-10-5-8", islandId:"s10i-10-5", front:"How do you predict the product of an addition reaction for any alkene?",
   back:"Use the pattern: the double bond opens and the small molecule splits across it.\n\n• + hydrogen → the matching alkane (propene → propane)\n• + steam → the matching alcohol (butene + H₂O → butanol, C₄H₉OH)\n• + a halogen → a di-halo compound (propene + Br₂ → C₃H₆Br₂)\n\nQuick check: in every case the product is saturated and contains ALL the atoms of both reactants — addition reactions have only one product.", difficulty:3, category:"application"},

  // s10i-10-6 — Industrial Ethanol: Fermentation vs Hydration
  {id:"s10fc-10-6-6", islandId:"s10i-10-6", front:"Why does fermentation eventually stop on its own?",
   back:"Two main reasons:\n\n1. Ethanol is toxic to yeast. As the ethanol concentration rises (to roughly 15%), the yeast cells are killed and fermentation stops — even if sugar remains. This is why stronger drinks must be made by distillation.\n\n2. The sugar may run out — no glucose means no reaction.\n\nTemperature also matters: too cold and the enzymes work very slowly; too hot and the enzymes in the yeast are denatured.", difficulty:2, category:"concept"},
  {id:"s10fc-10-6-7", islandId:"s10i-10-6", front:"Why is ethanol from fermentation sometimes described as a carbon-neutral fuel?",
   back:"The argument:\n• The sugar crops (e.g. sugar cane) absorb carbon dioxide from the air by photosynthesis as they grow\n• Burning the ethanol releases carbon dioxide back\n• In theory the two cancel out — no net increase in atmospheric CO₂\n\nIn practice it is not perfectly carbon neutral: fossil fuels are often used for farming machinery, transport and the distillation step, so some extra CO₂ is released overall.", difficulty:3, category:"concept"},
  {id:"s10fc-10-6-8", islandId:"s10i-10-6", front:"Compare the atom economy of the two ethanol routes.",
   back:"Hydration of ethene:\nC₂H₄ + H₂O → C₂H₅OH\nEthanol is the ONLY product, so the atom economy is 100% — every atom of the reactants ends up in the desired product.\n\nFermentation:\nC₆H₁₂O₆ → 2C₂H₅OH + 2CO₂\nAtom economy = (2 × 46) ÷ 180 × 100 ≈ 51%\nNearly half the mass of the glucose is lost as carbon dioxide.\n\nSo hydration wins on atom economy, even though fermentation wins on renewable raw materials.", difficulty:3, category:"application"}
);

// ── EXTRA QUESTIONS ─────────────────────────────────────────────────────────
QUESTIONS["s10i-10-1"] = (QUESTIONS["s10i-10-1"] || []).concat([
  {q:"Which elements are present in a hydrocarbon molecule?",
   opts:["Carbon and hydrogen only","Carbon, hydrogen and oxygen","Carbon plus any other element","Hydrogen and oxygen only"], c:0,
   e:"A hydrocarbon contains atoms of carbon and hydrogen and nothing else. The tempting mistake is to include oxygen — but a molecule like ethanol (C₂H₅OH), which contains oxygen, is an alcohol, not a hydrocarbon."},
  {q:"When a hydrocarbon fuel burns completely in plenty of air, the products are:",
   opts:["Carbon monoxide and hydrogen","Carbon dioxide and water","Carbon (soot) and steam","Carbon dioxide only"], c:1,
   e:"Complete combustion oxidises the carbon atoms to carbon dioxide and the hydrogen atoms to water. Carbon monoxide and soot only form during incomplete combustion, when the air supply is limited."},
  {q:"Which crude oil fraction is the most viscous?",
   opts:["Petrol","Kerosene","Diesel","Bitumen"], c:3,
   e:"Bitumen contains the longest hydrocarbon chains, giving it the strongest intermolecular forces and the highest viscosity — it is thick enough to surface roads. Petrol, with short chains, is the runniest of the four."},
  {q:"Why does a fraction such as petrol boil over a range of temperatures rather than at one fixed temperature?",
   opts:["It contains dissolved impurities such as salt","It is a mixture of hydrocarbons with similar but not identical chain lengths","Fractional distillation lowers all the boiling points","Petrol is a single pure compound"], c:1,
   e:"Each fraction is still a mixture — the hydrocarbons in it have similar numbers of carbon atoms but not the same number, so each component has its own boiling point. Only a pure compound boils at one fixed temperature, so option four cannot be right."},
  {q:"Crude oil is described as a feedstock for the petrochemical industry. Which group of products is made from it?",
   opts:["Solvents, lubricants and polymers","Iron, steel and aluminium","Glass and ceramics","Limestone and cement"], c:0,
   e:"Fractions from crude oil are the raw materials for solvents, lubricants, detergents and polymers (plastics). Metals like iron come from ores, not crude oil — a common mix-up, since both are extracted from the ground."},
  {q:"Propane burns completely: C₃H₈ + ?O₂ → 3CO₂ + 4H₂O. How many molecules of oxygen are needed to balance the equation?",
   opts:["3","4","5","10"], c:2,
   e:"The right-hand side contains (3 × 2) + (4 × 1) = 10 oxygen atoms, which is 5 molecules of O₂. Choosing 10 is the classic slip — that is the number of oxygen ATOMS, not O₂ molecules."},
  {q:"Four hydrocarbons have boiling points of −42 °C, 36 °C, 174 °C and 343 °C. Which one condenses nearest the bottom of a fractionating column?",
   opts:["The one boiling at −42 °C","The one boiling at 36 °C","The one boiling at 174 °C","The one boiling at 343 °C"], c:3,
   e:"The bottom of the column is hottest, so only the hydrocarbon with the highest boiling point (343 °C) condenses there — everywhere higher up is below its boiling point. Students often pick the lowest boiling point, but that compound stays as a gas almost to the top."},
  {q:"A liquid collected from a fractionating column is pale, flows very easily and ignites with a single spark. What does this suggest about its molecules?",
   opts:["They are very long-chain hydrocarbons","They are short-chain hydrocarbons","They must contain oxygen atoms","They are polymer molecules"], c:1,
   e:"Low viscosity (runny), light colour and high flammability are all properties of short-chain hydrocarbons. Long chains would give the opposite pattern: dark, thick and hard to ignite."},
  {q:"Methane (Mᵣ = 16) burns completely: CH₄ + 2O₂ → CO₂ + 2H₂O. What mass of carbon dioxide (Mᵣ = 44) forms when 16 g of methane burns?",
   opts:["44 g","28 g","16 g","60 g"], c:0,
   e:"16 g of methane is 1 mole, and the equation shows 1 mole of methane gives 1 mole of CO₂, which is 44 g. Choosing 60 g comes from wrongly adding the two relative masses (16 + 44) instead of using the mole ratio."},
  {q:"Why is crude oil not burned directly as a fuel without separation?",
   opts:["Its components have very different properties, so the raw mixture burns inefficiently and unpredictably","It contains no flammable molecules at all","It is a solid at room temperature","Mixtures can never be burned"], c:0,
   e:"Crude oil contains everything from light gases to heavy tars; the heavy components do not vaporise or ignite easily, so the raw mixture makes a poor fuel. It is certainly flammable — the problem is matching properties to a purpose, which is exactly what separating it into fractions achieves."}
]);

QUESTIONS["s10i-10-2"] = (QUESTIONS["s10i-10-2"] || []).concat([
  {q:"What is the general formula for alkenes?",
   opts:["CₙH₂ₙ₊₂","CₙH₂ₙ₋₂","CₙHₙ₊₂","CₙH₂ₙ"], c:3,
   e:"Alkenes follow CₙH₂ₙ — ethene is C₂H₄, propene is C₃H₆. CₙH₂ₙ₊₂ is the alkane formula; an alkene has two fewer hydrogens because of its C=C double bond."},
  {q:"What is the molecular formula of butane?",
   opts:["C₄H₈","C₄H₁₀","C₃H₈","C₄H₆"], c:1,
   e:"Butane has 4 carbon atoms, so using CₙH₂ₙ₊₂ it has (2 × 4) + 2 = 10 hydrogens: C₄H₁₀. C₄H₈ is butene, the alkene — the most common mix-up between the two families."},
  {q:"Propene is an alkene containing three carbon atoms. What is its formula?",
   opts:["C₃H₈","C₃H₄","C₃H₆","C₂H₆"], c:2,
   e:"Using the alkene general formula CₙH₂ₙ with n = 3 gives C₃H₆. C₃H₈ is propane, the saturated alkane — watch the difference one hydrogen pair makes."},
  {q:"Neighbouring members of the same homologous series, such as the alkanes, differ by which unit?",
   opts:["CH₂","CH₄","C₂H₂","OH"], c:0,
   e:"Each member of a homologous series differs from the next by one CH₂ unit — methane CH₄, ethane C₂H₆, propane C₃H₈. CH₄ is methane itself, not the step between members."},
  {q:"In catalytic cracking, the vaporised hydrocarbon is passed over:",
   opts:["Cold water","A nickel catalyst at about 150 °C","A hot zeolite catalyst at about 600 °C","Steam at room temperature"], c:2,
   e:"Catalytic cracking uses a hot catalyst such as zeolite at around 600 °C. The nickel catalyst at 150 °C belongs to hydrogenation of alkenes — a different reaction entirely."},
  {q:"Which pair of products could come from cracking a single alkane molecule?",
   opts:["Two alkanes only","A shorter alkane and an alkene","Hydrogen and pure carbon","An alcohol and water"], c:1,
   e:"Cracking splits a long alkane into a shorter alkane plus at least one alkene. Two alkanes alone is impossible — there are not enough hydrogen atoms for every fragment to satisfy CₙH₂ₙ₊₂."},
  {q:"Dodecane is cracked: C₁₂H₂₆ → C₈H₁₈ + X. What is X?",
   opts:["C₄H₁₀","C₃H₆","C₄H₆","C₄H₈"], c:3,
   e:"Subtract the atoms: carbon 12 − 8 = 4, hydrogen 26 − 18 = 8, so X is C₄H₈ (butene). C₄H₁₀ looks tempting because it is a real molecule (butane), but it would give 28 hydrogens in total, not 26."},
  {q:"A molecule of C₁₄H₃₀ is cracked: C₁₄H₃₀ → 2C₂H₄ + Y. What is Y?",
   opts:["C₁₀H₂₂","C₁₀H₂₀","C₁₂H₂₆","C₁₀H₂₄"], c:0,
   e:"Two ethene molecules account for 4 carbons and 8 hydrogens, leaving 14 − 4 = 10 carbons and 30 − 8 = 22 hydrogens: C₁₀H₂₂ (decane). C₁₀H₂₀ is the slip of subtracting only one ethene's hydrogens correctly but not checking the total."},
  {q:"A hydrocarbon has the molecular formula C₆H₁₂. What can you conclude at GCSE?",
   opts:["It is an alkane","It fits the alkene general formula CₙH₂ₙ, so it is unsaturated","It must contain oxygen","It cannot react with bromine water"], c:1,
   e:"With 6 carbons, an alkane would be C₆H₁₄. C₆H₁₂ matches CₙH₂ₙ, the alkene formula, so at GCSE you treat it as an unsaturated alkene — and it would decolourise bromine water, which rules out the last option."},
  {q:"A student cracks liquid paraffin over heated broken pottery and collects the gas over water. Why is the first test tube of gas usually thrown away?",
   opts:["It is mostly air that was pushed out of the apparatus","The gas is too hot to test safely","The first gas formed is always poisonous","Bromine water only works on a second sample"], c:0,
   e:"At the start, the apparatus is full of air, which is pushed through first — so the first tube is mainly air rather than the cracked gas. Testing it would give a misleading result, but it is not a safety or toxicity issue."}
]);

QUESTIONS["s10i-10-3"] = (QUESTIONS["s10i-10-3"] || []).concat([
  {q:"What is the name of the ester made from methanol and butanoic acid?",
   opts:["Butyl methanoate","Methyl butanoate","Methanol butanoate","Butane methanoate"], c:1,
   e:"The alcohol gives the first word (methanol → methyl) and the acid gives the second (butanoic acid → butanoate): methyl butanoate. Butyl methanoate gets the two parts the wrong way round — that would come from butanol and methanoic acid."},
  {q:"The first four alcohols dissolve in water to form solutions that are:",
   opts:["Strongly acidic","Weakly acidic","Neutral","Strongly alkaline"], c:2,
   e:"Alcohols form neutral solutions (pH about 7). The –OH group of an alcohol is not the hydroxide ion OH⁻, so alcohols are not alkaline — a very common misconception. It is the carboxylic acids that are weakly acidic."},
  {q:"Which gas is released when a small piece of sodium is added to ethanol?",
   opts:["Hydrogen","Oxygen","Carbon dioxide","Water vapour"], c:0,
   e:"Sodium reacts with the –OH group of ethanol, fizzing and releasing hydrogen gas — similar to (but gentler than) sodium's reaction with water. Carbon dioxide is the gas from acid + carbonate reactions, not this one."},
  {q:"When ethanol is oxidised, which compound forms?",
   opts:["Ethanoic acid","Ethene","Ethane","Ethyl ethanoate"], c:0,
   e:"Oxidation of ethanol produces ethanoic acid — the carbon chain keeps its two carbons but the –OH group becomes –COOH. Ethyl ethanoate is made by a different reaction: combining ethanol with ethanoic acid."},
  {q:"Propanoic acid belongs to which homologous series?",
   opts:["Alcohols","Alkenes","Esters","Carboxylic acids"], c:3,
   e:"The -anoic acid ending shows it is a carboxylic acid, containing the –COOH group (formula C₂H₅COOH). Alcohols end in -anol and esters end in -anoate — the name endings are the quickest way to spot the family."},
  {q:"When making an ester in the laboratory, a few drops of concentrated sulfuric acid are added. What is its role?",
   opts:["It is a reactant that becomes part of the ester","It acts as a catalyst","It neutralises the carboxylic acid","It provides the fruity smell"], c:1,
   e:"The sulfuric acid is a catalyst: it speeds up the reaction between the alcohol and the carboxylic acid but is not used up and does not appear in the ester. It certainly does not neutralise the acid — sulfuric acid is itself an acid."},
  {q:"Ethanol burns completely: C₂H₅OH + ?O₂ → 2CO₂ + 3H₂O. How many O₂ molecules are needed?",
   opts:["2","3","4","7"], c:1,
   e:"The products contain (2 × 2) + 3 = 7 oxygen atoms. Ethanol itself supplies one, so 6 more atoms — that is 3 molecules of O₂ — are needed. Answering 7 comes from forgetting that ethanol already contains an oxygen atom and counting atoms instead of molecules."},
  {q:"Ethanoic acid and hydrochloric acid solutions of equal concentration are each added to marble chips. What would you observe?",
   opts:["Both fizz at exactly the same rate","The hydrochloric acid gives off a different gas","The ethanoic acid does not react at all","The ethanoic acid fizzes more slowly because fewer of its molecules are ionised at any moment"], c:3,
   e:"Ethanoic acid is a weak acid — only partially ionised — so the concentration of H⁺ ions is lower and the fizzing is slower. It still reacts (it is a genuine acid), and both acids release the same gas, carbon dioxide, from the carbonate."},
  {q:"A colourless liquid fizzes when sodium carbonate solution is added and turns universal indicator orange. Which could it be?",
   opts:["Butanol","Butane","Butanoic acid","Butene"], c:2,
   e:"Fizzing with a carbonate (releasing carbon dioxide) plus an orange indicator colour points to a weak acid — butanoic acid fits both clues. Butanol sounds similar but is a neutral alcohol that gives no reaction with carbonates."},
  {q:"A bottle of cider left open to the air for several weeks tastes sour and vinegary. What has happened?",
   opts:["The ethanol evaporated, leaving acid behind","Microbes used oxygen from the air to oxidise the ethanol to ethanoic acid","The water reacted with the glass bottle","Sour-smelling esters formed on their own"], c:1,
   e:"With air present, microbes oxidise the ethanol in the drink to ethanoic acid — the acid in vinegar — making it sour. Evaporation would weaken the drink but cannot create new acid; oxidation is a chemical change producing a new substance."}
]);

QUESTIONS["s10i-10-4"] = (QUESTIONS["s10i-10-4"] || []).concat([
  {q:"Which monomer is used to make poly(propene)?",
   opts:["Propane","Propene","Propanol","Poly(ethene)"], c:1,
   e:"Poly(propene) is made by addition polymerisation of propene, an alkene with a C=C double bond. Propane cannot polymerise — it is saturated, with no double bond to open up."},
  {q:"In an addition polymer, how does the repeating unit compare with the monomer?",
   opts:["It contains the same atoms, but the C=C double bond has become a single bond","It has two fewer hydrogen atoms","It contains an extra oxygen atom","It has lost a water molecule"], c:0,
   e:"Nothing is lost in addition polymerisation, so the repeating unit has exactly the monomer's atoms — only the double bond changes to a single bond. Losing a water molecule happens in condensation polymerisation, not addition."},
  {q:"Which two functional groups does every amino acid contain?",
   opts:["Two –OH groups","Two C=C double bonds","An –NH₂ group and a –COOH group","An –OH group and a C=C bond"], c:2,
   e:"Amino acids carry an amine group (–NH₂) and a carboxylic acid group (–COOH), one at each end, letting a single type of monomer build a polypeptide by condensation. Two –OH groups describes a diol, used for polyesters."},
  {q:"Starch and cellulose are both natural polymers built from which monomer?",
   opts:["Amino acids","Nucleotides","Glucose (a sugar)","Ethene"], c:2,
   e:"Both starch and cellulose are made of glucose monomers joined together. Amino acids build proteins and nucleotides build DNA — keep the three natural polymer families separate."},
  {q:"Why are polymers solid at room temperature while their monomers are often gases?",
   opts:["Polymer chains are held together by ionic bonds","Polymers contain metal atoms","Each monomer molecule weighs more than a polymer chain","The long chains have strong overall intermolecular forces between them"], c:3,
   e:"The very long chains have far more points of contact, so the total intermolecular attraction between chains is large and much energy is needed to separate them. The forces are still intermolecular — not ionic bonds — which is the trap in the first option."},
  {q:"How many strands make up a DNA molecule, and what shape do they form?",
   opts:["One strand in a straight line","Two strands in a double helix","Three strands in a triple coil","Four strands in a square"], c:1,
   e:"DNA consists of two polymer strands, each built from nucleotide monomers, wound around each other in the famous double helix. Remembering 'double' covers both the strand count and the shape."},
  {q:"n molecules of propene (C₃H₆) join by addition polymerisation. What is the formula of the polymer?",
   opts:["–(C₃H₆)ₙ–","–(C₃H₄)ₙ– plus hydrogen","–(C₃H₅)ₙ– plus water","C₃H₆ unchanged"], c:0,
   e:"Addition polymerisation keeps every atom of every monomer, so n propene molecules give –(C₃H₆)ₙ–. Any answer involving a lost molecule (hydrogen or water) confuses this with condensation polymerisation."},
  {q:"As a polyester chain grows, 100 ester links are formed. How many water molecules are released?",
   opts:["None","50","100","200"], c:2,
   e:"In condensation polymerisation, one small molecule — here water — is released every time a link forms, so 100 links means 100 water molecules. 'None' would be true of addition polymerisation, which is the classic mix-up."},
  {q:"A monomer has one –OH group at one end and one –COOH group at the other. Could it form a condensation polymer on its own?",
   opts:["No — condensation polymerisation always needs two different monomers","Yes — it has two functional groups, so each molecule can bond at both ends","No — it would need a C=C double bond","Yes — but only if hydrogen gas is added"], c:1,
   e:"What matters is having two functional groups per molecule, not having two different monomers. The –COOH of one molecule can react with the –OH of the next, releasing water and growing a chain — just as amino acids polymerise on their own."},
  {q:"Ethene has a relative formula mass of 28. If 1000 ethene molecules join by addition polymerisation, what is the relative mass of the chain formed?",
   opts:["280","2800","28 000","10 000"], c:2,
   e:"No atoms are lost in addition polymerisation, so the chain's mass is simply 1000 × 28 = 28 000. Any smaller answer assumes mass is lost — that happens in condensation polymerisation, not here."}
]);

QUESTIONS["s10i-10-5"] = (QUESTIONS["s10i-10-5"] || []).concat([
  {q:"What is formed when propene reacts with hydrogen over a nickel catalyst?",
   opts:["Propanol","Propanoic acid","Propane","Poly(propene)"], c:2,
   e:"Hydrogenation adds H₂ across the C=C double bond, converting the alkene into the matching alkane: propene becomes propane. Propanol would need steam (water), not hydrogen, to be added."},
  {q:"Compared with alkanes, alkenes burn in air with:",
   opts:["A cleaner, less smoky flame","A smokier flame, because they tend to burn incompletely","No flame at all","A bright white flame like burning magnesium"], c:1,
   e:"Alkenes undergo incomplete combustion in air more readily than alkanes, producing carbon particles that make the flame smoky. They certainly do burn — they are just not used as fuels because they are more valuable for making polymers."},
  {q:"What is the product when ethene reacts with chlorine?",
   opts:["Chloroethane","Ethanol","Poly(chloroethene)","1,2-dichloroethane"], c:3,
   e:"Chlorine behaves like bromine: one chlorine atom adds to each carbon of the C=C bond, giving 1,2-dichloroethane (C₂H₄Cl₂). Chloroethane has only one chlorine — but addition of Cl₂ always delivers two atoms, one to each carbon."},
  {q:"What is the functional group present in every alkene?",
   opts:["–OH","C=C double bond","–COOH","C–C single bond"], c:1,
   e:"The C=C double bond is the alkene functional group — it is the reactive site where addition happens. A C–C single bond is not a functional group; it is found throughout alkanes and is unreactive."},
  {q:"Which of these does NOT react with ethene in an addition reaction?",
   opts:["Hydrogen","Steam","Bromine","Sodium chloride solution"], c:3,
   e:"Hydrogen, steam and the halogens all add across the C=C double bond. Sodium chloride solution does not — the chlorine in it exists as unreactive chloride ions, not as chlorine molecules that could add to the double bond."},
  {q:"Hydrogenation of vegetable oils is used industrially to:",
   opts:["Harden the oils to make margarine","Turn the oils into vinegar","Crack the oils into petrol","Convert the oils into perfume esters"], c:0,
   e:"Adding hydrogen across the C=C bonds in vegetable oils raises their melting point, hardening them into spreadable margarine. Vinegar comes from oxidising ethanol — a completely different process."},
  {q:"Butene (C₄H₈) reacts with steam over a suitable catalyst. What is the product?",
   opts:["C₄H₁₀","C₄H₉OH","C₄H₈Br₂","Carbon dioxide and water"], c:1,
   e:"Steam (H₂O) adds across the double bond: the H joins one carbon and the OH the other, giving butanol, C₄H₉OH — count the atoms: C₄H₈ + H₂O contains 4 C, 10 H and 1 O. C₄H₁₀ would come from adding hydrogen, not steam."},
  {q:"Gas X reacts with bromine to form a compound with the formula C₃H₆Br₂. What is X?",
   opts:["Propane","Ethene","Propene","Butene"], c:2,
   e:"Removing Br₂ from C₃H₆Br₂ leaves C₃H₆ — propene. Propane (C₃H₈) is saturated and cannot add bromine; it would also give the wrong hydrogen count."},
  {q:"During incomplete combustion of an alkene, which products may form besides carbon dioxide and water?",
   opts:["Carbon monoxide and carbon (soot)","Hydrogen gas","Extra oxygen gas","Sulfur dioxide"], c:0,
   e:"With limited oxygen, some carbon is only partly oxidised to carbon monoxide, or not oxidised at all, leaving soot. Sulfur dioxide needs sulfur in the fuel — a pure hydrocarbon contains only carbon and hydrogen."},
  {q:"Ethene (Mᵣ = 28) reacts with bromine (Mᵣ = 160) in a 1:1 ratio. What mass of bromine reacts exactly with 14 g of ethene?",
   opts:["14 g","80 g","160 g","320 g"], c:1,
   e:"14 g of ethene is 14 ÷ 28 = 0.5 mol, so 0.5 mol of bromine is needed: 0.5 × 160 = 80 g. Answering 160 g forgets that only half a mole of ethene is present."}
]);

QUESTIONS["s10i-10-6"] = (QUESTIONS["s10i-10-6"] || []).concat([
  {q:"Which gas is given off during fermentation?",
   opts:["Carbon dioxide","Hydrogen","Oxygen","Methane"], c:0,
   e:"Fermentation converts glucose into ethanol and carbon dioxide: C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂. The CO₂ bubbles off — it is what makes bread rise and gives some drinks their fizz. No hydrogen is involved."},
  {q:"Why is fermentation carried out at about 30 °C rather than 80 °C?",
   opts:["The reaction would be dangerously explosive at 80 °C","At high temperatures the enzymes in the yeast are denatured and fermentation stops","Sugar cannot dissolve above 40 °C","Ethanol becomes solid above 80 °C"], c:1,
   e:"Fermentation depends on enzymes in yeast, which work best around 30–35 °C; at much higher temperatures the enzymes are denatured and the process stops. Sugar actually dissolves better in hot water, so the third option has it backwards."},
  {q:"Fermentation can stop even while sugar is still present in the mixture. Why?",
   opts:["The yeast runs out of carbon dioxide","The mixture becomes too cold on its own","All the water is used up","The rising ethanol concentration kills the yeast"], c:3,
   e:"Ethanol is toxic to yeast: once its concentration reaches roughly 15%, the yeast cells die and fermentation halts regardless of remaining sugar. This is why spirits must be concentrated by distillation rather than fermented directly."},
  {q:"Where does the ethene used for the industrial hydration route come from?",
   opts:["Fermenting sugar","The atmosphere","Cracking fractions obtained from crude oil","Burning coal"], c:2,
   e:"Ethene is produced by cracking longer-chain fractions from crude oil — which is why this route depends on a finite resource. Fermentation makes ethanol directly from sugar and involves no ethene at all."},
  {q:"Which statement correctly describes the catalysts used in the two ethanol processes?",
   opts:["Both processes use phosphoric acid","Fermentation uses nickel; hydration uses zeolite","Neither process uses any catalyst","Fermentation relies on enzymes in yeast; hydration uses a phosphoric acid catalyst"], c:3,
   e:"Fermentation is catalysed by enzymes inside yeast cells, while hydration of ethene uses phosphoric acid. Nickel catalyses hydrogenation and zeolite catalyses cracking — both belong to different reactions."},
  {q:"Which process runs as a batch process, stopping and restarting with each fresh mixture?",
   opts:["Hydration of ethene","Catalytic cracking","Fermentation","Fractional distillation of crude oil"], c:2,
   e:"Fermentation is a batch process: a vessel is filled, the yeast works until it dies or the sugar runs out, the vessel is emptied and the cycle restarts. Hydration of ethene runs continuously, which is one of its advantages."},
  {q:"In the hydration of ethene (C₂H₄ + H₂O → C₂H₅OH), ethanol is the only product. What is the atom economy?",
   opts:["25%","50%","75%","100%"], c:3,
   e:"When the desired product is the only product, every atom of the reactants ends up in it, so the atom economy is 100%. Atom economy only drops below 100% when by-products carry some of the atoms away."},
  {q:"For fermentation, C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂, with Mᵣ(glucose) = 180 and Mᵣ(ethanol) = 46. What is the atom economy for ethanol, to the nearest whole number?",
   opts:["26%","46%","51%","92%"], c:2,
   e:"Atom economy = (2 × 46) ÷ 180 × 100 = 92 ÷ 180 × 100 ≈ 51%. Choosing 26% comes from using only one ethanol (46 ÷ 180) and forgetting the 2 in the balanced equation."},
  {q:"90 g of glucose (Mᵣ = 180) ferments completely. What is the maximum mass of ethanol (Mᵣ = 46) produced?",
   opts:["23 g","46 g","92 g","180 g"], c:1,
   e:"90 ÷ 180 = 0.5 mol of glucose, and each glucose gives 2 ethanol molecules, so 1 mol of ethanol forms: 46 g. Answering 23 g forgets the 2:1 ratio; 92 g wrongly starts from a whole mole of glucose."},
  {q:"A country grows large amounts of sugar cane but has no crude oil reserves. Which ethanol route is more suitable, and why?",
   opts:["Hydration, because it gives purer ethanol","Hydration, because it can run continuously","Fermentation, because the raw material is locally grown and renewable","Fermentation, because it needs no energy input at all"], c:2,
   e:"With abundant home-grown sugar and no oil, fermentation uses a cheap, renewable, local raw material, while hydration would require importing ethene or crude oil. The last option overstates the case — fermentation still needs energy for warmth and for distilling the product."}
]);
