// content/y10/science/islands/x11.js — EXPANSION: Topic 11 extra flashcards + questions.
// Loads AFTER t11.js. Authored by the atlas-content skill. All items original.

// ── EXTRA FLASHCARDS ────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s10i-11-1 — Series & Parallel Rules
  {id:"s10fc-11-1-6", islandId:"s10i-11-1", front:"Why is the total resistance of a parallel circuit LESS than the smallest individual resistance?",
   back:"Each branch added in parallel provides an EXTRA PATH for charge to flow.\n\nMore paths means MORE total current is drawn from the supply for the same potential difference.\n\nSince R = V ÷ I, a bigger current at the same pd means a SMALLER total resistance.\n\nSo adding a resistor in parallel always lowers the total resistance — the opposite of adding one in series.", difficulty:2, category:"concept"},
  {id:"s10fc-11-1-7", islandId:"s10i-11-1", front:"How should an ammeter and a voltmeter be connected in a circuit, and why?",
   back:"AMMETER — in SERIES with the component:\n• It measures the current flowing THROUGH the component, so the same current must pass through both\n• It has a very LOW resistance so it barely affects the circuit\n\nVOLTMETER — in PARALLEL across the component:\n• It measures the DIFFERENCE in potential between the two ends of the component\n• It has a very HIGH resistance so almost no current is diverted through it", difficulty:1, category:"definition"},
  {id:"s10fc-11-1-8", islandId:"s10i-11-1", front:"Two 8 Ω resistors are connected in parallel. What is the combined resistance?",
   back:"For TWO IDENTICAL resistors in parallel, the combined resistance is HALF of one of them:\n\nR_total = 8 ÷ 2 = 4 Ω\n\nCheck it makes sense: 4 Ω is less than the smallest branch (8 Ω), as it must be for a parallel combination.\n\nAdding them to get 16 Ω would be the SERIES rule — a common exam slip.", difficulty:2, category:"calculation"},

  // s10i-11-2 — Power & Energy in Circuits
  {id:"s10fc-11-2-6", islandId:"s10i-11-2", front:"State the equation linking charge, current and time, with units.",
   back:"Charge flow = current × time\n\nQ = I × t\n\nWhere:\n• Q = charge in coulombs (C)\n• I = current in amps (A)\n• t = time in seconds (s)\n\nA current of 1 A means 1 coulomb of charge passing a point every second.\n\nExample: a 4 A current flowing for 50 s transfers Q = 4 × 50 = 200 C.", difficulty:1, category:"definition"},
  {id:"s10fc-11-2-7", islandId:"s10i-11-2", front:"A 6 V battery pushes 20 C of charge through a lamp. How much energy is transferred?",
   back:"Energy transferred = charge × potential difference\n\nE = Q × V\nE = 20 × 6\nE = 120 J\n\nThe potential difference tells you the energy transferred PER COULOMB of charge: here each coulomb carries 6 J, and 20 coulombs flow, giving 120 J in total.", difficulty:2, category:"calculation"},
  {id:"s10fc-11-2-8", islandId:"s10i-11-2", front:"How do you find the current drawn by a mains appliance from its power rating?",
   back:"Rearrange P = I × V to make current the subject:\n\nI = P ÷ V\n\nExample: a 1150 W iron on the 230 V mains draws\nI = 1150 ÷ 230 = 5 A\n\nThis calculation matters in practice: the current tells you which fuse to fit and how thick the cable must be.", difficulty:2, category:"calculation"},

  // s10i-11-3 — Mains Electricity & Safety
  {id:"s10fc-11-3-6", islandId:"s10i-11-3", front:"What is the difference between direct current (dc) and alternating current (ac)?",
   back:"DIRECT CURRENT (dc):\n• Flows in ONE direction only\n• Supplied by cells and batteries\n• The pd has a constant sign\n\nALTERNATING CURRENT (ac):\n• Repeatedly REVERSES direction\n• Supplied by the mains\n• UK mains: about 230 V at 50 Hz, so the current completes 50 full cycles every second\n\nOn a voltage–time graph, dc is a flat line; ac is a wave crossing zero.", difficulty:1, category:"definition"},
  {id:"s10fc-11-3-7", islandId:"s10i-11-3", front:"Why is the live wire dangerous even when an appliance is switched off?",
   back:"The live wire is still at about 230 V relative to earth (0 V), even when no current is flowing.\n\nYour body is connected to earth through the ground. If you touch the live wire, there is a large potential difference between your hand and your feet — so a current flows THROUGH YOU to earth.\n\nThis is why a switch (and the fuse) must be placed in the LIVE wire: a switch in the neutral wire would stop the current but leave the appliance connected to the dangerous live supply.", difficulty:2, category:"concept"},
  {id:"s10fc-11-3-8", islandId:"s10i-11-3", front:"Describe how to choose the correct fuse for an appliance.",
   back:"1. Calculate the normal operating current:\n   I = P ÷ V\n2. Choose the standard fuse (3 A, 5 A or 13 A) rated JUST ABOVE this current\n\nExample: a 1200 W microwave on the 230 V mains:\nI = 1200 ÷ 230 ≈ 5.2 A\nA 5 A fuse would blow in normal use, so fit a 13 A fuse.\n\nToo low a rating: the fuse blows constantly.\nToo high a rating: a fault current could overheat the cable before the fuse melts.", difficulty:2, category:"application"},

  // s10i-11-4 — Circuit Components & I–V Characteristics
  {id:"s10fc-11-4-6", islandId:"s10i-11-4", front:"How do you find the resistance of a non-ohmic component at one point on its I–V graph?",
   back:"Read off the pair of values at that point and use:\n\nR = V ÷ I\n\nExample: if a filament lamp passes 0.3 A when the pd is 6 V, then R = 6 ÷ 0.3 = 20 Ω at that point.\n\nIMPORTANT: for a curved (non-ohmic) graph you must use V ÷ I at the chosen point — you cannot use the gradient of the curve, and there is no single value of R that applies to the whole graph.", difficulty:2, category:"calculation"},
  {id:"s10fc-11-4-7", islandId:"s10i-11-4", front:"What is an LED and why are LEDs so widely used?",
   back:"An LED (light-emitting diode) is a diode that EMITS LIGHT when current flows through it in the forward direction.\n\nLike all diodes, it only conducts one way round.\n\nAdvantages:\n• Needs only a small current, so very little power is wasted\n• Much more efficient and longer-lasting than filament lamps\n• Used for indicator lights, displays and low-energy room lighting\n\nA resistor is usually placed in series with an LED to limit the current and prevent damage.", difficulty:1, category:"application"},
  {id:"s10fc-11-4-8", islandId:"s10i-11-4", front:"A thermistor is connected to a supply with a fixed pd. What happens to the current as the temperature rises?",
   back:"As temperature rises, the thermistor's resistance FALLS.\n\nWith the pd fixed, I = V ÷ R, so a smaller resistance means the current INCREASES.\n\nThis is the basis of electronic temperature sensing: a thermostat circuit can detect the rising current and switch a heater off (or a cooling fan on) at a set temperature.", difficulty:2, category:"concept"},

  // s10i-11-5 — Static Electricity & Electric Fields
  {id:"s10fc-11-5-6", islandId:"s10i-11-5", front:"Why does a charged object attract an UNCHARGED object, such as small scraps of paper?",
   back:"The charged object's electric field acts on the charges inside the neutral object.\n\nElectrons in the paper are pushed or pulled slightly, so the side NEAREST the charged object gains a small charge OPPOSITE to it. This is called an INDUCED charge.\n\nThe opposite charges attract, and because the induced charge is on the nearer side, the attraction outweighs the repulsion of the far side — so the paper jumps to the charged object.", difficulty:2, category:"concept"},
  {id:"s10fc-11-5-7", islandId:"s10i-11-5", front:"Why is static electricity a hazard when refuelling aircraft and tankers, and how is the risk removed?",
   back:"Fuel rubbing against the pipe transfers electrons, so static charge builds up on the pipe, the vehicle and the fuel.\n\nIf enough charge builds up, the strong electric field could ionise the air and cause a SPARK — which could ignite the fuel vapour and cause an explosion.\n\nPrevention: the aircraft or tanker is connected to EARTH with a conductor (a bonding wire) before and during refuelling, so charge flows harmlessly away as fast as it is made and can never build up.", difficulty:2, category:"application"},
  {id:"s10fc-11-5-8", islandId:"s10i-11-5", front:"Why do insulators hold static charge while conductors do not?",
   back:"INSULATORS (e.g. polythene, acetate, rubber):\n• Electrons cannot move through the material\n• Charge transferred by friction STAYS where it is put — it builds up as static\n\nCONDUCTORS (e.g. metals):\n• Contain free electrons that move easily\n• Any transferred charge immediately flows through the conductor (and through your body, if held) to earth\n\nThat is why rubbing a metal rod held in your hand leaves it uncharged — not because no electrons are transferred, but because they instantly drain away.", difficulty:2, category:"concept"}
);

// ── EXTRA QUESTIONS ─────────────────────────────────────────────────────────
QUESTIONS["s10i-11-1"] = (QUESTIONS["s10i-11-1"] || []).concat([
  {q:"How should an ammeter and a voltmeter be connected to measure the current through, and the potential difference across, a lamp?",
   opts:["Ammeter in parallel with the lamp, voltmeter in series","Both in series with the lamp","Ammeter in series with the lamp, voltmeter in parallel across it","Both in parallel with the lamp"], c:2,
   e:"The ammeter goes in series so the same current flows through it as through the lamp; the voltmeter goes in parallel to compare the potential at the lamp's two ends. Swapping them is the classic error — a voltmeter in series would almost stop the current because of its very high resistance."},
  {q:"One lamp in a series circuit of three lamps breaks. What happens to the other two?",
   opts:["They go out, because the single current path is broken","They get brighter","They stay lit at the same brightness","They flicker but stay on"], c:0,
   e:"A series circuit has only one path. A broken filament leaves a gap, so no current can flow anywhere and every lamp goes out. Lamps staying lit independently is the behaviour of a parallel circuit, where each lamp has its own branch."},
  {q:"Why are mains sockets in a house wired in parallel rather than in series?",
   opts:["Parallel wiring uses less copper","Each appliance receives the full 230 V and can be switched on and off independently","Parallel wiring increases the total resistance, making it safer","So the current is the same through every appliance"], c:1,
   e:"In parallel, every socket is connected directly across the supply, so each appliance gets the full 230 V and works whether or not the others are on. Identical current through every appliance is a series property, and parallel wiring actually lowers the total resistance rather than raising it."},
  {q:"Two 1.5 V cells are connected in series, both facing the same way. What is the total potential difference?",
   opts:["1.5 V","0.75 V","2.25 V","3.0 V"], c:3,
   e:"Potential differences of cells in series add: 1.5 + 1.5 = 3.0 V. Staying at 1.5 V would be the result of connecting the cells in parallel, which increases how long they last rather than the pd."},
  {q:"A second resistor is added in parallel with the first across a battery. What happens to the total resistance and the total current?",
   opts:["Resistance increases, current decreases","Resistance decreases, current increases","Both stay the same","Resistance decreases, current decreases"], c:1,
   e:"An extra parallel branch gives charge another path, so more total current is drawn from the battery. Since R = V ÷ I, more current at the same supply pd means a lower total resistance. Resistance only increases when resistors are added in series."},
  {q:"Two 10 Ω resistors are connected in parallel. What is their combined resistance?",
   opts:["20 Ω","10 Ω","5 Ω","100 Ω"], c:2,
   e:"Two identical resistors in parallel have half the resistance of one: 10 ÷ 2 = 5 Ω. Adding the values to get 20 Ω is the series rule — in parallel the combined resistance must come out less than the smallest branch."},
  {q:"A 3 Ω resistor and a 9 Ω resistor are connected in series with a 6 V battery. What is the current in the circuit?",
   opts:["0.5 A","2 A","0.67 A","72 A"], c:0,
   e:"Total resistance = 3 + 9 = 12 Ω, so I = V ÷ R = 6 ÷ 12 = 0.5 A. Getting 2 A comes from using only the 3 Ω resistor — in series you must add the resistances before applying V = IR."},
  {q:"In the same circuit (3 Ω and 9 Ω in series carrying 0.5 A), what is the potential difference across the 9 Ω resistor?",
   opts:["6 V","4.5 V","1.5 V","18 V"], c:1,
   e:"V = I × R = 0.5 × 9 = 4.5 V. The other 1.5 V is across the 3 Ω resistor, and 4.5 + 1.5 = 6 V matches the supply. The full 6 V would only appear across one component if it were the only one in the circuit."},
  {q:"A 4 Ω resistor and a 6 Ω resistor are connected in parallel across a 12 V supply. What is the current through the 4 Ω resistor?",
   opts:["1.2 A","2 A","3 A","5 A"], c:2,
   e:"In parallel each branch has the full supply pd across it, so I = V ÷ R = 12 ÷ 4 = 3 A. Assuming the 12 V is shared between the two resistors is the series rule applied in the wrong place."},
  {q:"For the same parallel circuit (4 Ω and 6 Ω across 12 V), what total current is drawn from the supply?",
   opts:["5 A","2.5 A","1.2 A","6 A"], c:0,
   e:"The branch currents are 12 ÷ 4 = 3 A and 12 ÷ 6 = 2 A. In parallel the branch currents add, so the supply delivers 3 + 2 = 5 A. Current is only the same at every point in a series circuit, not a parallel one."}
]);

QUESTIONS["s10i-11-2"] = (QUESTIONS["s10i-11-2"] || []).concat([
  {q:"What does a power rating of 1 watt mean?",
   opts:["1 joule of energy is transferred every second","1 amp flows for 1 second","1 coulomb of charge flows every second","1 volt is supplied for 1 second"], c:0,
   e:"Power is the rate of energy transfer: 1 W = 1 joule per second. One coulomb per second describes a current of 1 amp, which is a flow of charge, not a rate of energy transfer."},
  {q:"What is the unit of electric charge?",
   opts:["The amp","The volt","The coulomb","The joule"], c:2,
   e:"Charge is measured in coulombs (C). The amp is the unit of current — the rate of flow of charge — where 1 A means 1 coulomb passing a point each second."},
  {q:"What exactly is one kilowatt-hour?",
   opts:["The power used in one hour","1000 joules","The cost of one unit of electricity","The energy transferred by a 1 kW appliance running for one hour"], c:3,
   e:"A kilowatt-hour is a unit of ENERGY: the amount transferred by a 1 kW device in one hour (3.6 million joules). It is not a unit of power, and 1000 J is only a kilojoule — far smaller."},
  {q:"The current through a fixed resistor is doubled. What happens to the power dissipated?",
   opts:["It doubles","It quadruples","It halves","It stays the same"], c:1,
   e:"P = I²R, so power depends on the SQUARE of the current: doubling I makes I² four times bigger. Thinking it merely doubles comes from using P = IV while forgetting that the pd across the resistor doubles as well."},
  {q:"A current of 2 A flows for 120 seconds. How much charge passes?",
   opts:["60 C","240 C","122 C","0.017 C"], c:1,
   e:"Q = I × t = 2 × 120 = 240 C. Dividing time by current (giving 60) is a wrong rearrangement — charge is current MULTIPLIED by time, and adding them (122) mixes up quantities entirely."},
  {q:"50 C of charge flows through a motor with a potential difference of 12 V across it. How much energy is transferred?",
   opts:["4.2 J","62 J","600 J","0.24 J"], c:2,
   e:"E = Q × V = 50 × 12 = 600 J. The pd tells you the energy transferred per coulomb, so you multiply by the number of coulombs — dividing gives the small, wrong values."},
  {q:"A television has a power of 460 W and runs from the 230 V mains. What current does it draw?",
   opts:["2 A","0.5 A","105800 A","230 A"], c:0,
   e:"Rearranging P = IV gives I = P ÷ V = 460 ÷ 230 = 2 A. Dividing the wrong way round gives 0.5 A, and multiplying gives an absurdly large value — always sense-check the size of the answer."},
  {q:"A 12 V supply drives a current of 2 A through a heater for 30 s. How much energy is transferred?",
   opts:["24 J","720 J","180 J","44 J"], c:1,
   e:"E = I × V × t = 2 × 12 × 30 = 720 J. Stopping at P = IV = 24 W gives the POWER, not the energy — you must multiply by the time to find the energy transferred."},
  {q:"Which appliance transfers the most energy?",
   opts:["500 W lamp for 3 hours","100 W bulb for 10 hours","3 kW kettle for half an hour","2 kW heater for 1 hour"], c:3,
   e:"Convert each to kilowatt-hours: 0.5 × 3 = 1.5 kWh; 0.1 × 10 = 1 kWh; 3 × 0.5 = 1.5 kWh; 2 × 1 = 2 kWh. The heater transfers the most. A high power rating alone is not enough — the running time matters just as much."},
  {q:"A 150 W games console transfers 9000 J of energy. For how long was it running?",
   opts:["1350000 s","600 s","60 s","0.017 s"], c:2,
   e:"Rearranging E = Pt gives t = E ÷ P = 9000 ÷ 150 = 60 s. Multiplying instead of dividing gives the enormous first option, which is clearly not sensible for 9000 J at 150 W."}
]);

QUESTIONS["s10i-11-3"] = (QUESTIONS["s10i-11-3"] || []).concat([
  {q:"What colour is the neutral wire in a UK three-pin plug?",
   opts:["Brown","Blue","Green and yellow","Black"], c:1,
   e:"The neutral wire is blue. Brown is the live wire and green-and-yellow stripes mark the earth wire. Black is an old colour code that is no longer used in new UK wiring."},
  {q:"What is the approximate potential of the neutral wire?",
   opts:["230 V","115 V","0 V","50 V"], c:2,
   e:"The neutral wire is at, or very close to, 0 V (earth potential). It is the LIVE wire that alternates around 230 V. The number 50 is the mains frequency in hertz, not a voltage."},
  {q:"Why is the fuse connected in the live wire rather than the neutral wire?",
   opts:["The live wire is thicker","Fuses only work with current flowing in one direction","The neutral wire gets too hot for a fuse","So that when the fuse blows, the appliance is cut off from the dangerous high-voltage supply"], c:3,
   e:"The live wire carries the high alternating voltage. A fuse in the live wire disconnects the appliance from this danger when it blows. A fuse in the neutral wire would stop the current but leave the whole appliance still connected to the live supply — a serious shock hazard."},
  {q:"Which statement correctly compares battery and mains supplies?",
   opts:["A battery supplies direct current; the mains supplies alternating current","Both supply alternating current","A battery supplies alternating current; the mains supplies direct current","Both supply direct current"], c:0,
   e:"A battery drives current in one direction only (dc). The UK mains is ac at 50 Hz: the current direction reverses repeatedly, completing 50 full cycles every second."},
  {q:"Why does an RCD give better protection against electrocution than a fuse?",
   opts:["It detects a live–neutral current imbalance and switches off within milliseconds, far faster than a fuse can melt","It melts at a lower current than a fuse","It increases the resistance of the circuit","It works by cooling the wires down"], c:0,
   e:"An RCD compares the currents in the live and neutral wires; any difference means current is leaking — possibly through a person — and it breaks the circuit in milliseconds, then can be reset. A fuse has to heat up and melt, which is slower. RCDs do not work by melting or cooling anything."},
  {q:"A 2300 W kettle runs from the 230 V mains. Which fuse (3 A, 5 A or 13 A) should be fitted?",
   opts:["3 A","5 A","13 A","Any of them would work"], c:2,
   e:"I = P ÷ V = 2300 ÷ 230 = 10 A, so the fuse rated just above the normal current is the 13 A one. A 3 A or 5 A fuse would melt the moment the kettle was switched on — the rating is not a free choice."},
  {q:"A hair dryer has a power of 1840 W on the 230 V mains. What current does it draw?",
   opts:["8 A","0.125 A","4 A","423200 A"], c:0,
   e:"I = P ÷ V = 1840 ÷ 230 = 8 A. Dividing the wrong way round gives 0.125 A and multiplying gives the enormous final option — neither is a sensible current for a household appliance."},
  {q:"A kettle draws 10 A for 5 minutes. How much charge flows through it?",
   opts:["50 C","2 C","500 C","3000 C"], c:3,
   e:"Convert the time to seconds first: 5 minutes = 300 s. Q = I × t = 10 × 300 = 3000 C. Using 5 instead of 300 gives 50 C — forgetting to convert minutes to seconds is the most common slip in charge calculations."},
  {q:"An appliance draws 2 A from the 230 V mains. What is its power?",
   opts:["115 W","232 W","460 W","0.0087 W"], c:2,
   e:"P = I × V = 2 × 230 = 460 W. Dividing voltage by current (115) actually gives the resistance in ohms, not the power, and adding them (232) mixes up two different quantities."},
  {q:"A 2300 W kettle takes 180 s to boil some water. How much energy does it transfer?",
   opts:["12.8 J","414000 J","2480 J","2300 J"], c:1,
   e:"E = P × t = 2300 × 180 = 414000 J (414 kJ). The value 2300 J would be the energy transferred in just one second — you must multiply the power by the full time."}
]);

QUESTIONS["s10i-11-4"] = (QUESTIONS["s10i-11-4"] || []).concat([
  {q:"What happens to the resistance of a thermistor as it cools down?",
   opts:["It decreases","It stays constant","It drops to zero","It increases"], c:3,
   e:"A thermistor's resistance falls as temperature rises, so cooling does the opposite: the resistance increases. Constant resistance describes an ohmic resistor, not a thermistor."},
  {q:"What is an LED?",
   opts:["A diode that emits light when current flows through it in the forward direction","A resistor whose resistance depends on light level","A component that stores charge","A type of fuse"], c:0,
   e:"A light-emitting diode (LED) gives out light when current flows in its forward direction, and like all diodes it conducts one way only. The component whose resistance depends on light is the LDR — it detects light rather than producing it."},
  {q:"At one point on a filament lamp's I–V graph, the current is 0.2 A when the pd is 4 V. What is the lamp's resistance at this point?",
   opts:["0.8 Ω","0.05 Ω","20 Ω","4.2 Ω"], c:2,
   e:"R = V ÷ I = 4 ÷ 0.2 = 20 Ω. Multiplying V and I gives 0.8 — but that is the power in watts — and dividing the wrong way gives 0.05. Resistance is always pd divided by current."},
  {q:"An ohmic resistor carries 0.5 A when the pd across it is 10 V. What current flows when the pd is increased to 15 V?",
   opts:["1.5 A","0.75 A","0.33 A","0.5 A"], c:1,
   e:"R = 10 ÷ 0.5 = 20 Ω, and for an ohmic resistor this stays constant. So I = 15 ÷ 20 = 0.75 A. The current would only fail to rise in proportion if the resistance changed with current, as it does in a filament lamp."},
  {q:"A thermistor has a resistance of 1200 Ω at room temperature. With 6 V across it, what current flows?",
   opts:["200 A","0.005 A","7200 A","0.2 A"], c:1,
   e:"I = V ÷ R = 6 ÷ 1200 = 0.005 A (5 mA). Dividing resistance by voltage, or multiplying them, gives impossibly large currents — a small current through a large resistance is exactly what you should expect."},
  {q:"In the I–V characteristics practical, why is the voltmeter connected in parallel with the component?",
   opts:["So all the current flows through the voltmeter","To reduce the resistance of the circuit","Because it measures the difference in potential between the two ends of the component","So it can measure the current as well"], c:2,
   e:"A voltmeter compares the potential at the two ends of a component, so it must connect across (in parallel with) it. Voltmeters are built with very HIGH resistance precisely so that almost no current is diverted through them."},
  {q:"Why is a fixed resistor usually connected in series with an LED?",
   opts:["To make the LED brighter","To allow current to flow both ways through it","To increase the pd across the LED","To limit the current and stop the LED being damaged"], c:3,
   e:"LEDs are damaged by large currents, so a series resistor limits the current to a safe value. It reduces, rather than increases, the pd across the LED, and nothing about it lets current flow backwards through the diode."},
  {q:"A filament lamp carries 0.5 A when the pd is 2 V, and 1.5 A when the pd is 12 V. What happens to its resistance between these two points?",
   opts:["It doubles, from 4 Ω to 8 Ω","It halves, from 8 Ω to 4 Ω","It stays at 4 Ω","It falls to zero"], c:0,
   e:"At 2 V: R = 2 ÷ 0.5 = 4 Ω. At 12 V: R = 12 ÷ 1.5 = 8 Ω. The resistance doubles because the filament is far hotter at the larger current, so the ions vibrate more and obstruct the electrons. Constant resistance would make the lamp ohmic — and it is not."},
  {q:"An LDR is connected to a battery. What happens to the current as night falls?",
   opts:["It decreases, because the LDR's resistance rises in the dark","It increases, because the LDR's resistance falls","It stays the same","It reverses direction"], c:0,
   e:"In darkness an LDR's resistance rises, and with the supply pd unchanged, I = V ÷ R means the current falls. Resistance FALLING in the dark is the rule remembered backwards — LDR resistance falls in bright light."},
  {q:"On a graph of current (y-axis) against potential difference (x-axis), what does the gradient represent?",
   opts:["The resistance, R","The power","1 divided by the resistance (1 ÷ R)","The charge"], c:2,
   e:"Gradient = change in I ÷ change in V = 1 ÷ R, so a STEEPER line means a LOWER resistance. The gradient would only equal R itself if the axes were swapped, with V plotted against I."}
]);

QUESTIONS["s10i-11-5"] = (QUESTIONS["s10i-11-5"] || []).concat([
  {q:"A polythene rod is rubbed with a cloth and gains electrons. What happens to the cloth?",
   opts:["It becomes negatively charged","It stays neutral","It becomes positively charged, with a charge equal in size to the rod's","It gains protons"], c:2,
   e:"The electrons gained by the rod came from the cloth, so the cloth is left with an equal-sized positive charge. Charge is never created or destroyed during charging — only transferred — and protons never move."},
  {q:"Rod A is known to be negatively charged. It repels rod B. What can you conclude about rod B?",
   opts:["B is positively charged","B is negatively charged","B is uncharged","B could be uncharged or positively charged"], c:1,
   e:"Repulsion only ever occurs between like charges, so B must be negative. Repulsion is the only reliable test for charge: attraction proves nothing definite, because an uncharged object can also be attracted through induced charge."},
  {q:"Why can a charged balloon pick up small uncharged pieces of paper?",
   opts:["The balloon's charge induces an opposite charge on the near side of the paper, and the opposite charges attract","The paper is naturally charged","Gravity pulls the paper towards the balloon","The paper gains protons from the balloon"], c:0,
   e:"The balloon's electric field shifts electrons within the paper, leaving the near surface with the opposite charge to the balloon, and these opposite charges attract. The paper starts neutral, and protons are never transferred between objects."},
  {q:"Why must an aircraft or fuel tanker be connected to earth by a conductor during refuelling?",
   opts:["To make the fuel flow faster","To stop the fuel becoming magnetic","To increase the resistance of the fuel pipe","So that static charge built up by friction flows safely to earth instead of causing a spark that could ignite the fuel"], c:3,
   e:"Fuel rubbing along the pipe transfers electrons and builds up static charge. If enough built up, a spark could jump and ignite the fuel vapour. A bonding wire to earth lets the charge drain away harmlessly as fast as it forms. Magnetism has nothing to do with it."},
  {q:"A metal rod held in your bare hand is rubbed with a cloth but does not become charged. Why not?",
   opts:["Metals contain no electrons","Friction cannot transfer electrons to a metal","Any charge transferred flows straight through the metal and your body to earth, because both conduct","The cloth absorbs all the charge"], c:2,
   e:"Electrons are still transferred by the rubbing, but a metal is a conductor — the charge immediately flows away through the rod and your body to earth, so none builds up. Metals are actually full of free electrons; that is exactly why they conduct so well."},
  {q:"A spark carries a current of 0.5 A for 0.004 s. How much charge is transferred?",
   opts:["0.002 C","125 C","0.008 C","2 C"], c:0,
   e:"Q = I × t = 0.5 × 0.004 = 0.002 C. Dividing current by time (giving 125) is a wrong rearrangement — sparks transfer only tiny amounts of charge, just extremely quickly."},
  {q:"A lightning strike transfers 25 C of charge through a potential difference of 100,000,000 V (100 MV). How much energy is transferred?",
   opts:["4,000,000 J","2,500,000,000 J","25,000,000 J","400 J"], c:1,
   e:"E = Q × V = 25 × 100,000,000 = 2,500,000,000 J (2.5 GJ). Dividing the pd by the charge instead gives 4,000,000 J, hugely underestimating it — energy is charge MULTIPLIED by potential difference."},
  {q:"A lightning strike transfers 30 C of charge in 0.002 s. What is the average current?",
   opts:["0.06 A","0.000067 A","15,000 A","60 A"], c:2,
   e:"Rearranging Q = It gives I = Q ÷ t = 30 ÷ 0.002 = 15,000 A. Multiplying charge by time gives 0.06 — far too small. Lightning currents really are tens of thousands of amps, which is why strikes are so destructive."},
  {q:"A Van de Graaff generator's belt delivers 0.06 C of charge to the dome in 30 s. What is the average current?",
   opts:["1.8 A","500 A","0.5 A","0.002 A"], c:3,
   e:"I = Q ÷ t = 0.06 ÷ 30 = 0.002 A (2 mA). Multiplying instead gives 1.8 A — far too large for a demonstration machine, which moves only a trickle of charge each second."},
  {q:"After walking on a carpet you are charged to 5000 V. Touching a door handle discharges 0.000002 C (2 microcoulombs). How much energy is released?",
   opts:["0.01 J","2,500,000,000 J","10 J","0.4 J"], c:0,
   e:"E = Q × V = 0.000002 × 5000 = 0.01 J. The voltage is high but the charge is tiny, so the energy is small — which is why carpet shocks sting but do no harm. Dividing V by Q produces the absurd second option."}
]);
