// content/y10/science/islands/x12.js — EXPANSION: Topic 12 extra flashcards + questions.
// Loads AFTER t12.js. Authored by the atlas-content skill. All items original.

// ── EXTRA FLASHCARDS ────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s10i-12-1 — Density & States of Matter
  {id:"s10fc-12-1-6", islandId:"s10i-12-1", front:"How do you convert a density from g/cm³ to kg/m³?",
   back:"Multiply by 1000.\n\ng/cm³ × 1000 = kg/m³\n\nExamples:\n• Water: 1 g/cm³ = 1000 kg/m³\n• Aluminium: 2.7 g/cm³ = 2700 kg/m³\n• Air: about 0.0012 g/cm³ = 1.2 kg/m³\n\nThis works because 1 kg = 1000 g and 1 m³ = 1 000 000 cm³, so the overall conversion factor is 1 000 000 ÷ 1000 = 1000.", difficulty:2, category:"concept"},
  {id:"s10fc-12-1-7", islandId:"s10i-12-1", front:"Describe how to measure the density of an irregularly shaped solid (required practical).",
   back:"1. Measure the mass of the object using a balance\n2. Fill a eureka (displacement) can with water up to the spout\n3. Gently lower the object in using a thread\n4. Collect the displaced water in a measuring cylinder\n5. The volume of displaced water = the volume of the object\n6. Calculate density using ρ = m ÷ V\n\nAlternative: lower the object into a part-filled measuring cylinder and record the rise in water level.\n\nLower the object gently to avoid splashing, which would make the measured volume too small.", difficulty:2, category:"application"},
  {id:"s10fc-12-1-8", islandId:"s10i-12-1", front:"Use the particle model to explain why a gas is much less dense than the same substance as a solid.",
   back:"The particles themselves are identical — same mass, same size.\n\nIn a gas, the particles are spaced much further apart than in a solid, so the same number of particles (the same mass) occupies a far larger volume.\n\nSince ρ = m ÷ V, a larger volume for the same mass gives a much smaller density.\n\nExample: liquid water is about 1000 kg/m³ but steam is roughly 1000 times less dense, because the particles are around 10 times further apart in each direction.", difficulty:2, category:"concept"},

  // s10i-12-2 — Specific Heat Capacity
  {id:"s10fc-12-2-6", islandId:"s10i-12-2", front:"In the SHC required practical, why does the calculated value of c usually come out HIGHER than the accepted value?",
   back:"Some of the electrical energy supplied is lost to the surroundings (and used to warm the heater itself) instead of heating the block.\n\nSo the energy measured (ΔE) is larger than the energy that actually went into the block, while the temperature rise (Δθ) is smaller than it should be.\n\nSince c = ΔE ÷ (m × Δθ), a too-large ΔE divided by a too-small Δθ gives a value of c that is too high.\n\nImprovements: insulate the block, and start timing only once the block is heating steadily.", difficulty:3, category:"application"},
  {id:"s10fc-12-2-7", islandId:"s10i-12-2", front:"A 0.8 kg copper block (c = 390 J/kg°C) absorbs 6240 J of energy. Calculate the temperature rise.",
   back:"Rearrange ΔE = mcΔθ to make Δθ the subject:\n\nΔθ = ΔE ÷ (m × c)\nΔθ = 6240 ÷ (0.8 × 390)\nΔθ = 6240 ÷ 312\nΔθ = 20 °C\n\nCopper has a low SHC, so a modest amount of energy produces a large temperature rise — this is why copper pans heat up quickly.", difficulty:2, category:"calculation"},
  {id:"s10fc-12-2-8", islandId:"s10i-12-2", front:"Give one use of a material with a HIGH specific heat capacity and one use of a material with a LOW specific heat capacity.",
   back:"HIGH SHC — stores lots of energy per °C:\n• Night storage heaters use bricks or ceramic with a high SHC — they absorb cheap off-peak electricity overnight and release the energy slowly during the day\n• Water in central heating radiators carries a large amount of energy around a house\n\nLOW SHC — heats up and cools down quickly:\n• Copper or aluminium saucepan bases respond rapidly to the hob, giving quick temperature control\n• Heating elements reach working temperature quickly", difficulty:2, category:"application"},

  // s10i-12-3 — Internal Energy & Latent Heat
  {id:"s10fc-12-3-6", islandId:"s10i-12-3", front:"What happens to the energy and temperature of a liquid as it freezes?",
   back:"Freezing is the reverse of melting, so energy is RELEASED to the surroundings.\n\n• The temperature stays CONSTANT at the freezing point until all the liquid has become solid\n• The potential energy of the particles DECREASES as they settle into a fixed, regular arrangement\n• The energy released per kilogram equals the specific latent heat of fusion\n\nOn a cooling curve, freezing appears as a flat (horizontal) section — the substance gives out energy without getting any colder.", difficulty:2, category:"concept"},
  {id:"s10fc-12-3-7", islandId:"s10i-12-3", front:"Calculate the TOTAL energy needed to melt 0.5 kg of ice at 0 °C and then warm the water produced to 20 °C. (Lf = 334 000 J/kg, c of water = 4200 J/kg°C)",
   back:"This is a two-step calculation:\n\nStep 1 — melt the ice (change of state):\nE = m × L = 0.5 × 334 000 = 167 000 J\n\nStep 2 — warm the water (temperature change):\nΔE = m × c × Δθ = 0.5 × 4200 × 20 = 42 000 J\n\nTotal = 167 000 + 42 000 = 209 000 J (209 kJ)\n\nNotice that melting takes about four times more energy than the 20 °C temperature rise — latent heat values are large.", difficulty:3, category:"calculation"},
  {id:"s10fc-12-3-8", islandId:"s10i-12-3", front:"Why does steam at 100 °C cause a much worse scald than the same mass of boiling water at 100 °C?",
   back:"Both are at the same temperature, but the steam must first CONDENSE on the skin.\n\nWhen it condenses, each kilogram of steam releases its specific latent heat of vaporisation — about 2 260 000 J/kg — INTO the skin, before the resulting hot water then cools down and releases even more energy.\n\nThe boiling water only releases energy as it cools.\n\nSo steam transfers far more energy overall, even though the starting temperature is identical. Temperature and energy are not the same thing.", difficulty:3, category:"application"},

  // s10i-12-4 — Particle Motion & Gas Pressure
  {id:"s10fc-12-4-6", islandId:"s10i-12-4", front:"What does the temperature of a gas tell you about its particles?",
   back:"Temperature is related to the AVERAGE KINETIC ENERGY of the particles.\n\n• Higher temperature → particles have a higher average kinetic energy → they move faster on average\n• Lower temperature → lower average kinetic energy → slower average speed\n\nNote the word AVERAGE: at any moment, individual particles in the same gas move at a wide range of different speeds and in random directions.", difficulty:1, category:"definition"},
  {id:"s10fc-12-4-7", islandId:"s10i-12-4", front:"A gas occupies 0.4 m³ at 150 kPa. It expands to 1.2 m³ at constant temperature. Calculate the new pressure.",
   back:"Use p₁V₁ = p₂V₂ (constant temperature, fixed mass):\n\np₂ = (p₁ × V₁) ÷ V₂\np₂ = (150 × 0.4) ÷ 1.2\np₂ = 60 ÷ 1.2\np₂ = 50 kPa\n\nThe volume has tripled, so the pressure falls to one third. The same particles are spread through a larger space, so they collide with the walls less often.", difficulty:2, category:"calculation"},
  {id:"s10fc-12-4-8", islandId:"s10i-12-4", front:"Why does a helium balloon expand as it rises through the atmosphere?",
   back:"Atmospheric pressure DECREASES with height (there is less air above pushing down).\n\nAs the balloon rises:\n• The pressure outside the balloon falls\n• The gas inside pushes outwards more strongly than the air pushes in\n• The balloon expands until the inside and outside pressures balance again\n\nAssuming the temperature stays roughly constant, p × V = constant for the gas inside — as the pressure halves, the volume doubles. Weather balloons can eventually expand so much that they burst.", difficulty:2, category:"application"}
);

// ── EXTRA QUESTIONS ─────────────────────────────────────────────────────────
QUESTIONS["s10i-12-1"] = (QUESTIONS["s10i-12-1"] || []).concat([
  {q:"A steel anchor has a density of 8000 kg/m³ and a volume of 0.002 m³. What is its mass?",
   opts:["4 kg","0.25 kg","16 kg","4 000 000 kg"], c:2,
   e:"Rearrange ρ = m ÷ V to give m = ρ × V = 8000 × 0.002 = 16 kg. Dividing instead of multiplying gives 4 000 000 kg, which is clearly far too large for an anchor."},
  {q:"A sample of aluminium has a mass of 54 g. Its density is 2.7 g/cm³. What is its volume?",
   opts:["20 cm³","145.8 cm³","0.05 cm³","56.7 cm³"], c:0,
   e:"Rearrange ρ = m ÷ V to give V = m ÷ ρ = 54 ÷ 2.7 = 20 cm³. Multiplying mass by density (145.8) is the common error — check the rearrangement: volume must come out smaller than the mass number here because density is greater than 1 g/cm³."},
  {q:"A liquid has a density of 0.5 g/cm³. What is this in kg/m³?",
   opts:["0.0005 kg/m³","50 kg/m³","5 kg/m³","500 kg/m³"], c:3,
   e:"To convert g/cm³ to kg/m³, multiply by 1000: 0.5 × 1000 = 500 kg/m³. Dividing by 1000 (0.0005) is the tempting mistake, but remember water is 1 g/cm³ = 1000 kg/m³, so the kg/m³ number must be bigger."},
  {q:"A measuring cylinder contains 40 cm³ of water. A stone of mass 75 g is lowered in and the level rises to 65 cm³. What is the density of the stone?",
   opts:["1.15 g/cm³","3 g/cm³","1.875 g/cm³","25 g/cm³"], c:1,
   e:"The stone's volume is the rise in level: 65 − 40 = 25 cm³. Then ρ = m ÷ V = 75 ÷ 25 = 3 g/cm³. Using the final reading of 65 cm³ as the volume (75 ÷ 65 ≈ 1.15) is the classic error — you must subtract the starting level."},
  {q:"How much energy is released when 0.05 kg of steam condenses into water at 100 °C? (Lv of water = 2 260 000 J/kg)",
   opts:["45 200 000 J","2 260 000 J","113 000 J","11 300 J"], c:2,
   e:"E = m × L = 0.05 × 2 260 000 = 113 000 J. Condensing releases the same energy per kilogram as boiling absorbs. Forgetting to multiply by the mass gives 2 260 000 J, which is the energy for a whole kilogram."},
  {q:"When a 100 g ice cube melts completely into water, the mass of the water is:",
   opts:["Exactly 100 g","Slightly less than 100 g","Slightly more than 100 g","Roughly half of 100 g"], c:0,
   e:"Mass is conserved during a change of state — no particles are created or destroyed, they simply rearrange. The volume and density change, but the mass stays exactly the same. Thinking some mass is 'used up' as energy is the tempting mistake."},
  {q:"Why is the displacement (eureka can) method used to find the volume of a small statue rather than a ruler?",
   opts:["The statue is too heavy to lift onto a balance","A ruler can only measure volumes of liquids","The statue has an irregular shape, so its volume cannot be calculated from length measurements","Water makes the statue easier to see"], c:2,
   e:"A ruler only works for regular shapes (like cuboids) where the volume can be calculated from the dimensions. An irregular object displaces its own volume of water, which can be collected and measured. The balance is still needed for the mass, so option A confuses the two measurements."},
  {q:"Which state of matter can be compressed easily, and why?",
   opts:["Solid, because its particles vibrate","Liquid, because its particles can flow","Gas, because there are large empty spaces between the particles","Gas, because its particles are smaller than in a solid"], c:2,
   e:"Gas particles are widely spaced, so squeezing pushes them into the empty space between them. The particles themselves are the same size in every state — they do not shrink, which is why the last option is wrong. Solids and liquids have touching particles, so they barely compress."},
  {q:"Which change of state happens when a solid turns directly into a gas?",
   opts:["Evaporation","Condensation","Freezing","Sublimation"], c:3,
   e:"Sublimation is the change directly from solid to gas with no liquid stage — for example, solid carbon dioxide (dry ice) sublimes at room temperature. Evaporation is liquid to gas, so it misses out the key word 'directly from a solid'."},
  {q:"When water freezes into ice it expands slightly. What happens to its density, and what is the consequence?",
   opts:["Density increases, so ice sinks in water","Density decreases, so ice floats on water","Density stays the same, so ice neither floats nor sinks","Density decreases, so ice sinks in water"], c:1,
   e:"The mass is unchanged but the volume increases, so ρ = m ÷ V decreases — ice is about 0.92 g/cm³, less than water's 1 g/cm³, so it floats. The idea that the 'heavier-feeling' solid must sink is the trap: floating depends on density, not on state."}
]);

QUESTIONS["s10i-12-2"] = (QUESTIONS["s10i-12-2"] || []).concat([
  {q:"A kettle transfers 12 600 J of energy to 1.5 kg of water. By how much does the temperature rise? (c of water = 4200 J/kg°C)",
   opts:["2 °C","3 °C","8.4 °C","20 °C"], c:0,
   e:"Δθ = ΔE ÷ (m × c) = 12 600 ÷ (1.5 × 4200) = 12 600 ÷ 6300 = 2 °C. Forgetting the mass and dividing only by 4200 gives 3 °C — always multiply mass and SHC together first."},
  {q:"84 000 J of energy raises the temperature of a sample of water by 10 °C. What is the mass of the water? (c = 4200 J/kg°C)",
   opts:["20 kg","0.5 kg","8.4 kg","2 kg"], c:3,
   e:"Rearrange ΔE = mcΔθ to give m = ΔE ÷ (c × Δθ) = 84 000 ÷ (4200 × 10) = 84 000 ÷ 42 000 = 2 kg. Dividing by 4200 only (20 kg) ignores the temperature change of 10 °C."},
  {q:"A 100 W heater warms a 1 kg metal block for 300 s, raising its temperature by 60 °C. Assuming no energy losses, what is the SHC of the metal?",
   opts:["180 J/kg°C","500 J/kg°C","18 000 J/kg°C","5 J/kg°C"], c:1,
   e:"First find the energy: E = P × t = 100 × 300 = 30 000 J. Then c = ΔE ÷ (m × Δθ) = 30 000 ÷ (1 × 60) = 500 J/kg°C. Using the power instead of the energy (100 ÷ 20 ideas) leads to nonsense values — the heater runs for 300 s, so you must multiply by the time first."},
  {q:"Equal masses of copper (c = 390 J/kg°C) and water (c = 4200 J/kg°C) each receive 9000 J of energy. What happens?",
   opts:["The water's temperature rises more, because it has the higher SHC","Both temperatures rise by the same amount, because the energy is the same","The copper's temperature rises about 11 times more, because its SHC is about 11 times smaller","The copper's temperature rises slightly more, because metals conduct electricity"], c:2,
   e:"Δθ = ΔE ÷ (m × c), so for the same energy and mass, the temperature rise is inversely proportional to c. Copper: 9000 ÷ 390 ≈ 23 °C per kg; water: 9000 ÷ 4200 ≈ 2.1 °C per kg — about 11 times less. A higher SHC means a smaller temperature rise, not a bigger one."},
  {q:"0.5 kg of water in a hot water bottle cools from 80 °C to 30 °C. How much energy does it release? (c = 4200 J/kg°C)",
   opts:["63 000 J","168 000 J","105 000 J","2100 J"], c:2,
   e:"ΔE = mcΔθ = 0.5 × 4200 × (80 − 30) = 0.5 × 4200 × 50 = 105 000 J. The equation works for cooling as well as heating — use the temperature CHANGE (50 °C), not the final temperature of 30 °C (which would give 63 000 J)."},
  {q:"In the SHC practical, a student's calculated value for c is higher than the accepted value. The most likely reason is:",
   opts:["The balance read the mass as too high","Some energy supplied was lost to the surroundings instead of heating the block","The thermometer was too accurate","The block was too small"], c:1,
   e:"Energy lost to the surroundings means the measured ΔE is bigger than the energy that actually heated the block, and Δθ is smaller than it should be. Since c = ΔE ÷ (m × Δθ), both errors push the result too high. A mass error is possible but heat loss is the systematic error this practical is known for."},
  {q:"In the SHC practical, why is a small amount of water or oil placed in the thermometer hole of the metal block?",
   opts:["To cool the block down between readings","To stop the thermometer breaking","To improve thermal contact so the thermometer reads the block's true temperature","To increase the specific heat capacity of the block"], c:2,
   e:"Air is a poor conductor, so an air gap around the thermometer bulb would make it read low. A drop of liquid fills the gap and conducts energy to the bulb, giving an accurate reading of the block's temperature. It is far too little liquid to change the block's overall heating behaviour."},
  {q:"On a sunny day at the beach, the sand feels much hotter than the sea, even though both receive similar energy from the Sun. Why?",
   opts:["Sand has a lower specific heat capacity than water, so its temperature rises more for the same energy","Sand absorbs no energy from the Sun","The sea reflects all the sunlight","Water has a lower boiling point than sand"], c:0,
   e:"Sand's SHC is much lower than water's 4200 J/kg°C, so the same energy input produces a much larger temperature rise in the sand. The sea also mixes and is deeper, but the SHC difference is the key physics. The sea certainly absorbs energy — it just warms slowly."},
  {q:"What is the correct unit for specific heat capacity?",
   opts:["J/kg","J/°C","J","J/kg°C"], c:3,
   e:"SHC is the energy (J) per kilogram (kg) per degree Celsius (°C) of temperature rise, so the unit is J/kg°C. J/kg is the unit of specific latent heat — the most common mix-up — and it lacks the 'per degree' part because latent heat involves no temperature change."},
  {q:"Night storage heaters contain ceramic bricks rather than blocks of copper. The best reason is:",
   opts:["Ceramic bricks conduct electricity better","Ceramic has a much higher specific heat capacity, so the bricks store more energy and release it slowly through the day","Ceramic bricks are shinier","Copper would melt overnight"], c:1,
   e:"A high SHC means each kilogram stores a large amount of energy for every degree it is heated, and releases it gradually as it cools — ideal for storing cheap off-peak electricity. Copper's low SHC (390 J/kg°C) would store little energy and release it too quickly; melting is irrelevant at these temperatures."}
]);

QUESTIONS["s10i-12-3"] = (QUESTIONS["s10i-12-3"] || []).concat([
  {q:"When a gas condenses into a liquid, what happens to its internal energy?",
   opts:["It increases, because the particles speed up","It decreases, because energy is released to the surroundings","It stays the same, because temperature is constant","It becomes zero"], c:1,
   e:"Condensing releases latent heat to the surroundings, so the internal energy falls — specifically the potential energy of the particles decreases as attractions form. Constant temperature does NOT mean constant internal energy: the kinetic part is unchanged but the potential part drops."},
  {q:"A solid is heated and its temperature rises from 20 °C to 50 °C without melting. Which part of its internal energy has increased?",
   opts:["The kinetic energy of the particles","The potential energy of the particles","The chemical energy of the particles","Neither — internal energy is constant"], c:0,
   e:"A temperature rise means the particles vibrate faster, so their kinetic energy increases. Potential energy only changes significantly during a change of state, when the separation and arrangement of the particles change — that is not happening here."},
  {q:"Liquid wax is left to cool and its temperature is recorded. The cooling curve shows a flat section. During this section the wax is:",
   opts:["Boiling and absorbing energy","Cooling faster than before","Freezing and releasing energy at constant temperature","No longer losing any energy"], c:2,
   e:"The flat section is the wax solidifying: it releases latent heat of fusion to the surroundings while staying at its freezing point. Energy IS still being lost — that is exactly why the change of state continues — so the last option is wrong; the temperature just does not fall until freezing is complete."},
  {q:"What is the difference between evaporation and boiling?",
   opts:["They are two words for the same process","Evaporation happens only from the surface and can occur at any temperature; boiling happens throughout the liquid at the boiling point","Boiling can occur at any temperature; evaporation only at 100 °C","Evaporation absorbs energy but boiling releases energy"], c:1,
   e:"Evaporation is the escape of the most energetic particles from the liquid's surface, and it happens at any temperature — a puddle dries on a cold day. Boiling occurs at one fixed temperature, with bubbles of vapour forming throughout the liquid. Both absorb energy, so the last option fails."},
  {q:"Sweating cools the body because:",
   opts:["Sweat is colder than skin","The most energetic water particles evaporate, taking latent heat of vaporisation from the skin","Sweat blocks the Sun's rays","Sweat increases the skin's specific heat capacity"], c:1,
   e:"As sweat evaporates, the fastest particles escape, and the energy needed for this change of state (latent heat) is drawn from the skin, lowering its temperature. Sweat starts at body temperature, so it being 'colder' is not the mechanism — it is the evaporation that does the cooling."},
  {q:"90 000 J of energy melts 0.6 kg of a substance at its melting point. What is its specific latent heat of fusion?",
   opts:["54 000 J/kg","150 000 J/kg","15 000 J/kg","540 000 J/kg"], c:1,
   e:"Rearrange E = mL to give L = E ÷ m = 90 000 ÷ 0.6 = 150 000 J/kg. Multiplying instead of dividing gives 54 000, which has the wrong logic: latent heat is energy PER kilogram, so divide the energy by the mass."},
  {q:"A kettle supplies 1 130 000 J to water already at 100 °C. What mass of water boils away? (Lv = 2 260 000 J/kg)",
   opts:["2 kg","0.2 kg","0.5 kg","5 kg"], c:2,
   e:"Rearrange E = mL to give m = E ÷ L = 1 130 000 ÷ 2 260 000 = 0.5 kg. The energy supplied is exactly half the energy needed for 1 kg, so half a kilogram boils away. Dividing the wrong way round gives 2, which would need twice as much energy as was supplied."},
  {q:"How much energy must a freezer remove to freeze 1.5 kg of water already at 0 °C? (Lf = 334 000 J/kg)",
   opts:["334 000 J","222 667 J","50 100 J","501 000 J"], c:3,
   e:"Freezing releases the same energy per kilogram as melting absorbs: E = mL = 1.5 × 334 000 = 501 000 J, which the freezer must transfer away. No mcΔθ term is needed because the water is already at 0 °C — the temptation to use 334 000 J alone ignores the 1.5 kg mass."},
  {q:"0.1 kg of water at 70 °C is heated to 100 °C and then completely boiled away. What is the TOTAL energy needed? (c = 4200 J/kg°C, Lv = 2 260 000 J/kg)",
   opts:["238 600 J","226 000 J","12 600 J","2 272 600 J"], c:0,
   e:"Two stages: heating, ΔE = 0.1 × 4200 × 30 = 12 600 J; then boiling, E = 0.1 × 2 260 000 = 226 000 J. Total = 12 600 + 226 000 = 238 600 J. Choosing 226 000 J forgets the heating stage; 2 272 600 J comes from forgetting to multiply the latent heat term by the 0.1 kg mass."},
  {q:"A 50 W heater is used to melt 0.05 kg of ice at 0 °C. How long does it take, assuming all the energy goes into the ice? (Lf = 334 000 J/kg)",
   opts:["66.8 s","835 s","334 s","16 700 s"], c:2,
   e:"Energy needed: E = mL = 0.05 × 334 000 = 16 700 J. Time: t = E ÷ P = 16 700 ÷ 50 = 334 s (about 5.6 minutes). The answer 16 700 s confuses the energy in joules with the time in seconds — you must divide by the heater's power."}
]);

QUESTIONS["s10i-12-4"] = (QUESTIONS["s10i-12-4"] || []).concat([
  {q:"The temperature of a gas is directly related to:",
   opts:["The number of particles in the gas","The average kinetic energy of its particles","The size of each particle","The colour of the gas"], c:1,
   e:"Temperature is a measure of the average kinetic energy of the particles — hotter gas means faster average particle speed. The number of particles affects pressure, not temperature, and the particles themselves never change size."},
  {q:"A sealed rigid container of gas is cooled. What happens to the pressure inside, and why?",
   opts:["It increases, because cold gas is denser","It decreases, because the particles move more slowly and collide with the walls less often and less hard","It stays the same, because the volume is fixed","It decreases, because some particles are destroyed by the cold"], c:1,
   e:"Cooling lowers the particles' average kinetic energy, so collisions with the walls become less frequent and less forceful — pressure falls. The volume being fixed does not 'lock' the pressure; pressure depends on the collisions. Particles are never destroyed by cooling."},
  {q:"A sealed packet of crisps is taken up a high mountain and swells noticeably. This is because:",
   opts:["The air inside the packet is heated by the climb","Atmospheric pressure outside the packet is lower at altitude, so the gas inside expands","Gas particles inside the packet multiply at altitude","The packet absorbs air from outside"], c:1,
   e:"Atmospheric pressure falls with height, so the trapped gas pushes outwards more strongly than the thinner outside air pushes in, and the packet expands until the pressures balance. The number of particles inside a sealed packet cannot change, ruling out the multiplying and absorbing options."},
  {q:"Why must an empty aerosol can never be thrown onto a fire?",
   opts:["The metal will rust","Heating the trapped gas raises its pressure at almost constant volume until the can may explode","The paint will fade","Fire removes the gas particles from the can"], c:1,
   e:"The leftover gas is sealed in a rigid can, so heating makes the particles move faster and strike the walls harder and more often — the pressure climbs until the can can rupture violently. This is the constant-volume pressure–temperature effect; rust and fading are irrelevant to the danger."},
  {q:"Gas particles in a container exert pressure that acts:",
   opts:["Only downwards, because of gravity","Only on the base of the container","Equally in all directions, at right angles to every wall","Only on the lid"], c:2,
   e:"The particles move randomly in every direction, so they bombard all the walls equally — the pressure acts at right angles to every surface, in all directions. Gravity's effect on tiny, fast-moving gas particles is negligible here, so 'only downwards' is the trap answer."},
  {q:"A balloon contains 0.3 m³ of gas at 120 kPa. It expands to 0.9 m³ at constant temperature. What is the new pressure?",
   opts:["360 kPa","40 kPa","120 kPa","30 kPa"], c:1,
   e:"p₂ = (p₁ × V₁) ÷ V₂ = (120 × 0.3) ÷ 0.9 = 36 ÷ 0.9 = 40 kPa. The volume has tripled, so the pressure drops to a third. 360 kPa comes from multiplying by 3 instead — but expansion must REDUCE the pressure."},
  {q:"A gas at 250 kPa occupies 0.4 m³. At constant temperature, its pressure falls to 100 kPa. What is the new volume?",
   opts:["0.16 m³","2.5 m³","1.0 m³","0.1 m³"], c:2,
   e:"V₂ = (p₁ × V₁) ÷ p₂ = (250 × 0.4) ÷ 100 = 100 ÷ 100 = 1.0 m³. The pressure has fallen to two fifths of its original value, so the volume grows by the inverse factor (× 2.5). Getting 0.16 m³ means the ratio was applied upside down — lower pressure must mean a LARGER volume."},
  {q:"A sealed syringe holds 60 cm³ of air at 100 kPa. The plunger is pushed until the pressure reads 150 kPa at constant temperature. What is the new volume?",
   opts:["40 cm³","90 cm³","25 cm³","10 cm³"], c:0,
   e:"V₂ = (p₁ × V₁) ÷ p₂ = (100 × 60) ÷ 150 = 6000 ÷ 150 = 40 cm³. Because only the ratio matters, the cm³ units are fine. 90 cm³ would mean the gas expanded when squeezed — increasing the pressure at constant temperature must decrease the volume."},
  {q:"A gas expands at constant temperature from 0.25 m³ to 0.75 m³, and its final pressure is 80 kPa. What was its original pressure?",
   opts:["27 kPa","240 kPa","60 kPa","800 kPa"], c:1,
   e:"p₁ = (p₂ × V₂) ÷ V₁ = (80 × 0.75) ÷ 0.25 = 60 ÷ 0.25 = 240 kPa. The volume tripled, so the original pressure must have been three times the final one. 27 kPa applies the factor of 3 the wrong way — the gas started compressed, at the HIGHER pressure."},
  {q:"A weather balloon has a volume of 2.0 m³ at ground level, where the pressure is 100 kPa. It rises to an altitude where the pressure is 50 kPa. Assuming constant temperature, its new volume is:",
   opts:["1.0 m³","2.0 m³","8.0 m³","4.0 m³"], c:3,
   e:"V₂ = (p₁ × V₁) ÷ p₂ = (100 × 2.0) ÷ 50 = 200 ÷ 50 = 4.0 m³. Halving the pressure doubles the volume. Choosing 1.0 m³ halves the volume instead — but with less outside pressure squashing it, the balloon must get BIGGER, not smaller."}
]);
