// content/y10/science/islands/x13.js — EXPANSION: Topic 13 extra flashcards + questions.
// Loads AFTER t13.js. Authored by the atlas-content skill. All items original.

// ── EXTRA FLASHCARDS ────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s10i-13-1 — Atomic Structure & Radiation Types
  {id:"s10fc-13-1-6", islandId:"s10i-13-1", front:"What is an isotope? Give an example.",
   back:"Isotopes are atoms of the same element with the same number of protons but different numbers of neutrons.\n\n• Same atomic number — so the same element, with identical chemical behaviour\n• Different mass number — because the neutron count differs\n\nExample: carbon-12 and carbon-14 are both carbon (6 protons each), but they have 6 and 8 neutrons respectively.\n\nSome isotopes have unstable nuclei — these are the radioactive isotopes that decay by emitting radiation.", difficulty:1, category:"definition"},
  {id:"s10fc-13-1-7", islandId:"s10i-13-1", front:"Describe how the model of the atom changed over time.",
   back:"1. Dalton — atoms as tiny solid spheres that cannot be divided\n\n2. Thomson (plum pudding model) — a ball of positive charge with negative electrons embedded in it\n\n3. Rutherford (nuclear model) — alpha scattering showed a tiny, dense, positive nucleus with electrons around it\n\n4. Bohr — electrons orbit the nucleus only at specific distances, in fixed energy levels; his calculations agreed with experiments\n\n5. Chadwick — discovered the neutron inside the nucleus, about 20 years after the nucleus itself was accepted", difficulty:2, category:"concept"},
  {id:"s10fc-13-1-8", islandId:"s10i-13-1", front:"How does the size of the nucleus compare with the size of the whole atom?",
   back:"A typical atom has a radius of about 1 × 10⁻¹⁰ m.\n\nThe nucleus has a radius of about 1 × 10⁻¹⁴ m — less than 1/10 000 of the radius of the atom.\n\nDespite being so tiny, the nucleus contains almost all of the atom's mass, because protons and neutrons are nearly 2000 times more massive than electrons.\n\nThis is why most alpha particles passed straight through the gold foil in Rutherford's experiment — the atom is mostly empty space.", difficulty:1, category:"concept"},

  // s10i-13-2 — Half-Life
  {id:"s10fc-13-2-6", islandId:"s10i-13-2", front:"What is the difference between activity and count rate?",
   back:"Activity is the rate at which a source of unstable nuclei decays. It is measured in becquerels (Bq), where 1 Bq = 1 decay per second.\n\nCount rate is the number of decays recorded each second by a detector, such as a Geiger-Müller (GM) tube connected to a counter.\n\nThe count rate is always lower than the activity, because the detector only catches the radiation that happens to enter it — radiation is emitted in all directions.", difficulty:1, category:"definition"},
  {id:"s10fc-13-2-7", islandId:"s10i-13-2", front:"How do you express the net decline of a radioactive source as a ratio?",
   back:"After n half-lives, the fraction of nuclei remaining is (½)ⁿ.\n\nThe net decline can be given as a ratio of remaining to original nuclei:\n\n• After 1 half-life: 1:2\n• After 2 half-lives: 1:4\n• After 3 half-lives: 1:8\n\nExample: a source starts with 8000 undecayed nuclei. After 3 half-lives, 8000 × ⅛ = 1000 remain. The ratio of remaining to original is 1000:8000 = 1:8.", difficulty:2, category:"calculation"},
  {id:"s10fc-13-2-8", islandId:"s10i-13-2", front:"Why must the background count be subtracted in a half-life experiment?",
   back:"A detector records all the ionising radiation entering it — not just radiation from the sample.\n\nBackground radiation comes from radon gas, rocks and soil, cosmic rays, food and medical sources, so the counter would read above zero even with no sample present.\n\nMethod:\n1. Measure the count rate with no sample present (the background count)\n2. Subtract it from every reading taken with the sample\n\nThis gives the corrected count rate due to the sample alone, which is what you use to find the half-life.", difficulty:2, category:"concept"},

  // s10i-13-3 — Uses & Dangers of Radiation
  {id:"s10fc-13-3-6", islandId:"s10i-13-3", front:"What is background radiation and where does it come from?",
   back:"Background radiation is the low-level ionising radiation that is around us all the time.\n\nNatural sources:\n• Radon gas from rocks and soil (the largest source in the UK — levels depend on location)\n• Cosmic rays from space\n• Food and drink (some foods naturally contain radioactive potassium)\n\nArtificial sources:\n• Medical procedures such as X-rays\n• Fallout from past nuclear weapons testing and accidents\n\nThe dose received depends on your location and occupation — aircrew and radiographers receive more than average.", difficulty:1, category:"definition"},
  {id:"s10fc-13-3-7", islandId:"s10i-13-3", front:"What properties should an isotope have to be used as a medical tracer?",
   back:"1. It should emit gamma radiation — gamma passes out of the body so it can be detected externally, and it is the least ionising, minimising cell damage\n\n2. It should have a short half-life (a few hours, e.g. technetium-99m at about 6 hours) — long enough to complete the scan, but short enough that the activity quickly falls to a safe level\n\n3. It should not be toxic, and should be readily flushed out of the body\n\nAlpha emitters would be useless and dangerous: the radiation could not escape the body and would heavily ionise tissue from the inside.", difficulty:2, category:"application"},
  {id:"s10fc-13-3-8", islandId:"s10i-13-3", front:"How is radiation used to control the thickness of paper in a factory?",
   back:"A beta source is placed on one side of the moving paper sheet and a detector on the other.\n\n• If the paper becomes too thick, fewer beta particles get through and the count rate falls — the rollers squeeze closer together\n• If the paper becomes too thin, more beta particles get through and the count rate rises — the rollers move apart\n\nBeta is chosen because it is partially absorbed by paper. Alpha would be completely stopped (no signal at all), and gamma would pass through almost unchanged (no measurable difference), so neither could detect small changes in thickness.", difficulty:2, category:"application"},

  // s10i-13-4 — Nuclear Fission & Fusion
  {id:"s10fc-13-4-6", islandId:"s10i-13-4", front:"List all the products of a typical fission event.",
   back:"When a large nucleus such as uranium-235 absorbs a neutron and splits, it produces:\n\n• Two smaller daughter nuclei (roughly half the size each) — these are usually radioactive themselves\n• Two or three fast-moving neutrons, which can go on to cause further fissions\n• Gamma rays\n• Energy — carried mostly as the kinetic energy of the fragments and neutrons\n\nThe radioactive daughter nuclei are the reason nuclear waste must be stored safely for many years.", difficulty:2, category:"concept"},
  {id:"s10fc-13-4-7", islandId:"s10i-13-4", front:"What is the difference between a controlled and an uncontrolled chain reaction?",
   back:"Controlled (nuclear reactor):\n• On average, exactly ONE neutron from each fission goes on to cause another fission\n• Control rods absorb the surplus neutrons\n• Energy is released at a steady, useful rate\n\nUncontrolled (nuclear weapon):\n• Two or three neutrons from each fission trigger further fissions\n• The number of fissions grows extremely rapidly\n• A huge amount of energy is released almost instantly — an explosion", difficulty:2, category:"concept"},
  {id:"s10fc-13-4-8", islandId:"s10i-13-4", front:"Where does the energy released in nuclear fusion come from?",
   back:"When two light nuclei fuse, the new heavier nucleus has slightly LESS mass than the total mass of the nuclei that formed it.\n\nThat small amount of 'missing' mass is converted into a very large amount of energy.\n\nThis is why fusion releases more energy per kilogram of fuel than fission, and far more than any chemical reaction such as burning.\n\nIn the Sun, hydrogen nuclei fuse to form helium, and the converted mass provides the energy that the Sun radiates.", difficulty:2, category:"concept"}
);

// ── EXTRA QUESTIONS ─────────────────────────────────────────────────────────
QUESTIONS["s10i-13-1"] = (QUESTIONS["s10i-13-1"] || []).concat([
  {q:"What is an isotope?",
   opts:["An atom with the same number of neutrons but a different number of protons","An atom of the same element with the same number of protons but a different number of neutrons","An atom that has lost electrons and become charged","A different element that happens to have the same mass number"], c:1,
   e:"Isotopes are atoms of the same element — same number of protons — with different numbers of neutrons, so their mass numbers differ. An atom that has lost or gained electrons is an ion, not an isotope; the nucleus is unchanged in an ion."},
  {q:"What did Niels Bohr add to the nuclear model of the atom?",
   opts:["The idea that electrons orbit the nucleus at specific distances, in fixed energy levels","The discovery of the neutron","The idea that electrons are embedded in a ball of positive charge","The idea that atoms are indivisible solid spheres"], c:0,
   e:"Bohr proposed that electrons orbit the nucleus only at specific distances (energy levels), and his theoretical calculations agreed with experimental results. The neutron was discovered later by Chadwick, and the 'embedded electrons' idea is the earlier plum pudding model that Rutherford disproved."},
  {q:"Which subatomic particle was discovered last?",
   opts:["The electron","The proton","The neutron","They were all discovered at the same time"], c:2,
   e:"James Chadwick provided the evidence for the neutron in 1932, around 20 years after the nuclear model was accepted. Because the neutron carries no charge, it was much harder to detect than the charged electron and proton, which is why it came last."},
  {q:"The radius of a typical atom is about 1 × 10⁻¹⁰ m. How does the radius of the nucleus compare?",
   opts:["It is about half the radius of the atom","It is about 1/100 of the radius of the atom","It is less than 1/10 000 of the radius of the atom","It is about the same as the radius of the atom"], c:2,
   e:"The nucleus has a radius of about 1 × 10⁻¹⁴ m — less than 1/10 000 of the atom's radius — yet it contains almost all of the atom's mass. 1/100 is far too large: the atom is overwhelmingly empty space, which is why most alpha particles passed straight through Rutherford's gold foil."},
  {q:"What happens to the mass number and atomic number of a nucleus when it emits gamma radiation?",
   opts:["Mass number decreases by 4, atomic number decreases by 2","Mass number stays the same, atomic number increases by 1","Both decrease by 1","Both stay exactly the same"], c:3,
   e:"Gamma emission is the release of surplus energy as an electromagnetic wave — no particles leave the nucleus, so neither number changes and the element stays the same. The option 'mass unchanged, atomic number +1' describes beta decay, not gamma emission."},
  {q:"Why does alpha radiation have such a short range in air — only a few centimetres?",
   opts:["It travels slowly, so it falls to the floor before going far","It is strongly ionising, so it rapidly transfers its energy through collisions with air particles","It has no charge, so the air absorbs it completely","It decays into beta particles as it travels"], c:1,
   e:"Alpha particles are large and carry a +2 charge, so they ionise almost every particle in their path, losing energy with each interaction and stopping within centimetres. Ionising power and penetrating power are inversely related. Alpha does have charge — it is gamma that has none, and gamma travels furthest."},
  {q:"Radon-219 (²¹⁹₈₆Rn) decays by alpha emission. What is the nucleus produced?",
   opts:["Polonium-215 (²¹⁵₈₄Po)","Polonium-217 (²¹⁷₈₄Po)","Radium-215 (²¹⁵₈₈Ra)","Astatine-219 (²¹⁹₈₅At)"], c:0,
   e:"Alpha emission removes 4 from the mass number (219 − 4 = 215) and 2 from the atomic number (86 − 2 = 84), giving polonium-215. Check: mass 219 = 215 + 4; atomic number 86 = 84 + 2. Polonium-217 is tempting but only subtracts 2 from the mass number — an alpha particle carries away 4 mass units, not 2."},
  {q:"Strontium-90 (⁹⁰₃₈Sr) decays by beta emission. Which equation is correct?",
   opts:["⁹⁰₃₈Sr → ⁸⁶₃₆Kr + ⁴₂He","⁹⁰₃₈Sr → ⁹⁰₃₇Rb + ⁰₋₁e","⁹⁰₃₈Sr → ⁹⁰₃₉Y + ⁰₋₁e","⁹⁰₃₈Sr → ⁸⁹₃₈Sr + ¹₀n"], c:2,
   e:"In beta decay a neutron becomes a proton, so the atomic number rises by 1 (38 → 39, yttrium) while the mass number stays at 90. Check the balance: mass 90 = 90 + 0; atomic number 38 = 39 + (−1). The rubidium option wrongly lowers the atomic number — emitting a negative particle must leave the nucleus with one more positive charge, not one fewer."},
  {q:"In the decay ⁶⁰₂₇Co → ⁶⁰₂₈Ni + X, what is particle X?",
   opts:["An alpha particle","A neutron","A proton","A beta particle"], c:3,
   e:"Balance both sides: mass numbers give 60 = 60 + 0 and atomic numbers give 27 = 28 + (−1), so X has mass number 0 and charge −1 — a beta particle (⁰₋₁e). A neutron has mass number 1, which would leave the mass numbers unbalanced."},
  {q:"Polonium-210 (²¹⁰₈₄Po) emits an alpha particle. What are the mass number and atomic number of the nucleus produced?",
   opts:["Mass number 206, atomic number 82","Mass number 208, atomic number 83","Mass number 210, atomic number 82","Mass number 206, atomic number 84"], c:0,
   e:"Alpha decay: mass number 210 − 4 = 206 and atomic number 84 − 2 = 82, giving lead-206. The option with mass 206 but atomic number 84 forgets that the alpha particle also carries away two protons — the atomic number must fall by 2, so the element changes."}
]);

QUESTIONS["s10i-13-2"] = (QUESTIONS["s10i-13-2"] || []).concat([
  {q:"Which of these would change the half-life of a radioactive isotope?",
   opts:["Heating the sample strongly","Increasing the pressure on the sample","Dissolving the sample in acid","None of these — half-life is constant for a given isotope"], c:3,
   e:"Half-life depends only on the stability of the nucleus, which is unaffected by temperature, pressure or chemical reactions — those involve the electrons, not the nucleus. Heating is the most tempting answer because heat speeds up chemical reactions, but radioactive decay is a nuclear process."},
  {q:"Isotope A has a half-life of 4 minutes; isotope B has a half-life of 4000 years. Which statement is correct?",
   opts:["A sample of A loses its activity much faster than an equal sample of B","B emits more strongly ionising radiation than A","Equal samples of A and B decay at the same rate","B will run out of radioactive nuclei before A"], c:0,
   e:"A short half-life means the activity falls quickly — half of A's nuclei decay every 4 minutes, while B takes 4000 years to halve. Half-life tells you nothing about how ionising the radiation is; that depends on whether alpha, beta or gamma is emitted, not on the decay rate."},
  {q:"After 3 half-lives, what is the ratio of remaining radioactive nuclei to the original number?",
   opts:["1:3","1:6","1:8","1:16"], c:2,
   e:"Each half-life halves what remains: (½)³ = 1/8, so the ratio of remaining to original is 1:8. The tempting answer 1:6 comes from multiplying 2 × 3 instead of calculating 2 × 2 × 2 = 8; 1:16 would be correct after 4 half-lives, not 3."},
  {q:"Which instrument is used to detect and count nuclear radiation in a school laboratory?",
   opts:["A thermometer","A Geiger-Müller tube connected to a counter","An ammeter","A light microscope"], c:1,
   e:"A Geiger-Müller (GM) tube detects ionising radiation: each particle or ray entering the tube ionises the gas inside, producing an electrical pulse that the counter records. The reading is the count rate. An ammeter measures current in a circuit, not radiation."},
  {q:"Before using count-rate readings to find a half-life, why must the background count be subtracted?",
   opts:["Because background radiation makes the source decay faster","Because the detector also records radiation from rocks, cosmic rays and other background sources, not just the sample","Because the background count doubles every half-life","Because a GM tube cannot detect anything below the background level"], c:1,
   e:"A detector picks up background radiation — from radon, rocks, cosmic rays and so on — as well as the sample, so the raw readings are too high. Subtracting the background count gives the corrected count rate due to the sample alone. Background radiation has no effect on how fast the source itself decays."},
  {q:"After 2 half-lives, what fraction of the original radioactive nuclei have decayed?",
   opts:["1/2","1/4","2/3","3/4"], c:3,
   e:"After 2 half-lives, (½)² = 1/4 of the nuclei remain, so the fraction that has decayed is 1 − 1/4 = 3/4. The tempting answer 1/4 is the fraction remaining — read carefully whether a question asks for the decayed fraction or the remaining fraction."},
  {q:"The activity of a sample falls from 2000 Bq to 500 Bq in 30 minutes. What is the half-life?",
   opts:["7.5 minutes","10 minutes","15 minutes","30 minutes"], c:2,
   e:"Count the halvings: 2000 → 1000 → 500 is 2 half-lives, so the half-life is 30 ÷ 2 = 15 minutes. Choosing 10 minutes comes from assuming 3 halvings, but 2000 to 500 is a factor of 4, which is exactly 2 half-lives."},
  {q:"A 64 g sample of a radioactive isotope has a half-life of 5 years. What mass of the original isotope remains undecayed after 20 years?",
   opts:["4 g","8 g","16 g","32 g"], c:0,
   e:"Number of half-lives = 20 ÷ 5 = 4. Then 64 → 32 → 16 → 8 → 4, so 4 g remains. Equivalently 64 × (½)⁴ = 64 ÷ 16 = 4 g. The answer 16 g comes from stopping after only 2 half-lives — always divide the total time by the half-life first."},
  {q:"A source has an initial activity of 9600 Bq and a half-life of 6 hours. What is its activity after 1 day?",
   opts:["2400 Bq","1200 Bq","600 Bq","300 Bq"], c:2,
   e:"1 day = 24 hours = 24 ÷ 6 = 4 half-lives. So 9600 → 4800 → 2400 → 1200 → 600 Bq. The answer 2400 Bq comes from halving only twice — convert the day into hours first and count all 4 half-lives."},
  {q:"A sample's activity is measured today as 200 Bq. Its half-life is 10 minutes. What was its activity 30 minutes earlier?",
   opts:["25 Bq","600 Bq","800 Bq","1600 Bq"], c:3,
   e:"Working backwards in time, the activity doubles for each half-life: 30 minutes is 3 half-lives, so 200 × 2 × 2 × 2 = 1600 Bq. The answer 25 Bq is what you get going forwards in time (200 ÷ 8) — the question asks what the activity was before, not after."}
]);

QUESTIONS["s10i-13-3"] = (QUESTIONS["s10i-13-3"] || []).concat([
  {q:"What is the largest source of background radiation for most people in the UK?",
   opts:["Nuclear power stations","Radon gas released from rocks and soil","Mobile phone signals","Aircraft flights"], c:1,
   e:"Radon, a radioactive gas seeping out of rocks and soil, is the biggest contributor to background radiation in the UK, and the dose varies with location. Nuclear power contributes a tiny fraction, and mobile phone signals are non-ionising, so they are not part of background radioactivity at all."},
  {q:"Technetium-99m is widely used as a medical tracer. Which combination of properties makes it suitable?",
   opts:["It emits alpha particles and has a long half-life","It emits gamma rays and has a half-life of a few seconds","It emits beta particles and has a half-life of thousands of years","It emits gamma rays and has a half-life of about 6 hours"], c:3,
   e:"A tracer must emit gamma rays, so the radiation escapes the body and can be detected externally, and have a half-life of a few hours — long enough to complete the scan but short enough for the activity to fall quickly afterwards. A half-life of a few seconds would decay before the scan finished, and an alpha emitter would be trapped inside the body, causing heavy ionisation damage."},
  {q:"A factory uses radiation to monitor the thickness of paper as it is made. Which source is most suitable?",
   opts:["A beta source, because paper partially absorbs beta particles","An alpha source, because alpha is the most ionising","A gamma source, because gamma is the most penetrating","Any source works equally well"], c:0,
   e:"Beta is partially absorbed by paper, so the count rate at the detector changes measurably when the paper gets thicker or thinner, allowing automatic adjustment of the rollers. Alpha would be completely stopped by any thickness of paper and gamma would pass through almost unchanged, so neither could detect small variations."},
  {q:"Why is gamma radiation used to sterilise surgical instruments that are sealed in packaging?",
   opts:["It heats the instruments until all bacteria are burned away","It makes the instruments radioactive so bacteria cannot grow on them","It penetrates the sealed packaging and kills microorganisms without the packet being opened","It is the only type of radiation that is safe for humans"], c:2,
   e:"Gamma's high penetrating power means it passes through the sealed packaging and kills the bacteria inside, so the instruments remain sterile until the packet is opened. Irradiating the instruments does NOT make them radioactive — that is a common misconception; only contamination with radioactive material would do that."},
  {q:"Why is it important that studies into the health effects of radiation are published and peer reviewed?",
   opts:["So that the scientists can patent their discoveries","So other scientists can check the methods and findings, making conclusions about risk reliable and shared","Because the law requires every experiment to be made public","So that the experiments can be repeated on larger groups of volunteers at higher doses"], c:1,
   e:"Peer review means other experts scrutinise the methods and conclusions before publication, so our understanding of radiation doses and risks is based on checked, shared evidence rather than a single unverified claim. It is about reliability and trust, not patents or legal obligations."},
  {q:"Radon is an alpha-emitting gas. Why is breathing it in particularly hazardous?",
   opts:["Alpha radiation passes straight through the lungs and damages other organs","Radon reacts chemically with the oxygen in the lungs","Once inhaled, the radioactive gas contaminates the lungs, where strongly ionising alpha particles damage cells at very short range","Alpha radiation is the most penetrating type of radiation"], c:2,
   e:"Outside the body, alpha is stopped harmlessly by the skin. But inhaled radon is contamination: the source sits inside the lungs, where its strongly ionising alpha particles dump all their energy directly into living tissue. Alpha is actually the LEAST penetrating radiation — and that is exactly why it is so damaging at point-blank range inside the body."},
  {q:"A worker's gloves are splashed with a liquid containing a radioactive isotope. Which statement is correct?",
   opts:["The gloves have been irradiated and have become radioactive themselves","The worker has been irradiated, so removing the gloves makes no difference","Both the gloves and the worker are now permanently radioactive","The gloves are contaminated and will keep emitting radiation until they are cleaned or the isotope decays"], c:3,
   e:"Radioactive material deposited on an object is contamination — the material itself carries on emitting radiation wherever the gloves go, so removing and safely disposing of them removes the hazard. Exposure to radiation (irradiation) does not make gloves or people radioactive; only the presence of radioactive material does."},
  {q:"A patient receives external beam radiotherapy from a gamma source. Immediately after the session, the patient...",
   opts:["has been irradiated but is not radioactive, so poses no radiation risk to others","is radioactive and must be kept in isolation","is contaminated with gamma-emitting material","must avoid contact with other people for several half-lives of the source"], c:0,
   e:"External radiotherapy is irradiation: as soon as the patient leaves the beam the exposure stops, and irradiation does not make the body radioactive. Contamination would only occur if radioactive material were placed on or inside the body, which does not happen with an external beam — the source stays in the machine."},
  {q:"A sealed gamma source is stored in the corner of a laboratory. Which action reduces a technician's dose from this source?",
   opts:["Washing hands thoroughly after every experiment","Opening the windows to ventilate the room","Working on the far side of the room from the source","Wearing a cotton lab coat"], c:2,
   e:"Distance is one of the three key protections — time, distance, shielding — because radiation intensity falls rapidly as you move away from a source. Hand washing and ventilation protect against contamination by loose radioactive material; they do nothing against irradiation from a sealed source, and cotton gives no useful shielding against gamma."},
  {q:"Two incidents occur: in A, a student stands for one minute near a sealed beta source; in B, a student swallows a tiny amount of the same beta-emitting material. Why is B generally more serious?",
   opts:["Beta radiation can only travel through liquids","Standing near a source always gives a larger dose than swallowing material","Beta sources change into gamma sources inside the body","The swallowed material contaminates the body, irradiating internal tissue continuously until it decays or is excreted"], c:3,
   e:"In B the radioactive material is inside the body — contamination — so cells are exposed continuously at zero distance and the student cannot simply move away from the source. In A the irradiation ends after the minute, and a brief external exposure usually gives a far smaller total dose. Radiation type does not change inside the body."}
]);

QUESTIONS["s10i-13-4"] = (QUESTIONS["s10i-13-4"] || []).concat([
  {q:"What is the job of the control rods in a nuclear reactor?",
   opts:["To absorb neutrons so the chain reaction proceeds at a steady, controlled rate","To release extra neutrons into the fuel","To convert the fission energy directly into electricity","To force hydrogen nuclei to fuse together"], c:0,
   e:"Control rods, often made of boron, absorb surplus neutrons. Lowering them into the reactor slows the chain reaction; raising them speeds it up. They do not generate electricity themselves — the energy released heats water to steam, which drives turbines connected to generators."},
  {q:"In what form is most of the energy released by a fission event carried away?",
   opts:["As sound energy","As the kinetic energy of the fission fragments and neutrons","As chemical energy stored in the daughter nuclei","As visible light"], c:1,
   e:"The two daughter nuclei and the released neutrons fly apart at very high speed, so the energy is mostly kinetic, with some carried by gamma rays. In a reactor this kinetic energy becomes heat in the fuel and coolant. Chemical energy involves electron bonds, which play no part in a nuclear process."},
  {q:"As well as two smaller nuclei and two or three neutrons, what else is emitted in a typical fission event?",
   opts:["Alpha particles","Protons","Gamma rays","Electrons from the electron shells"], c:2,
   e:"A fission event releases two daughter nuclei, two or three neutrons, gamma rays and energy. The gamma rays carry away part of the released energy. Free protons and alpha particles are not products of fission."},
  {q:"Which process releases the energy that powers the Sun?",
   opts:["Fission of uranium nuclei in the Sun's core","Fusion of hydrogen nuclei into heavier nuclei","Combustion of hydrogen gas in oxygen","Alpha decay of helium nuclei"], c:1,
   e:"In the Sun's core, the immense temperature and pressure force hydrogen nuclei to fuse into helium, releasing enormous amounts of energy. Combustion is a chemical reaction that needs oxygen and could not supply anything like the Sun's output for billions of years; there is no significant uranium fission in stars like the Sun."},
  {q:"Why must the used fuel from a fission reactor be stored carefully for many years?",
   opts:["It could catch fire spontaneously in air","It contains free neutrons that leak out over time","It becomes more radioactive the longer it is stored","The daughter nuclei produced by fission are themselves radioactive, some with long half-lives"], c:3,
   e:"The fission fragments (daughter nuclei) have unstable nuclei and are radioactive; some have long half-lives, so the waste remains hazardous for a very long time and needs secure shielding and storage. Activity always decreases with time — it never increases in storage."},
  {q:"In a nuclear power station running at a steady output, on average how many neutrons from each fission go on to cause another fission?",
   opts:["Exactly one","None","All of the two or three released","It varies randomly between zero and ten"], c:0,
   e:"For a steady, controlled chain reaction, exactly one neutron per fission must trigger the next fission; the control rods absorb the rest. If all two or three went on to cause fissions, the reaction would grow uncontrollably; if none did, the reaction would die out."},
  {q:"One fission of uranium-235 can be written: ²³⁵₉₂U + ¹₀n → ¹⁴¹₅₆Ba + ⁹²₃₆Kr + x neutrons. What is x?",
   opts:["1","2","3","4"], c:2,
   e:"Balance the mass numbers: the left side totals 235 + 1 = 236; barium and krypton account for 141 + 92 = 233, so the neutrons must carry the remaining 236 − 233 = 3. The atomic numbers already balance: 92 = 56 + 36. Choosing 2 comes from forgetting to include the absorbed neutron on the left-hand side."},
  {q:"In the fusion reaction ²₁H + ³₁H → ⁴₂He + X, what is particle X?",
   opts:["A proton","A beta particle","An alpha particle","A neutron"], c:3,
   e:"Balance the equation: mass numbers give 2 + 3 = 5 on the left and the helium accounts for 4, so X has mass number 1. Atomic numbers give 1 + 1 = 2, all carried by the helium, so X has charge 0. Mass 1 with no charge is a neutron (¹₀n). A proton would unbalance the atomic numbers, since 1 + 1 is not equal to 2 + 1."},
  {q:"Where does the energy released in nuclear fusion come from?",
   opts:["A small amount of the mass of the nuclei is converted into energy","Chemical bonds between the hydrogen atoms breaking","Friction between the fast-moving nuclei","Heat absorbed from the surroundings"], c:0,
   e:"The fused nucleus has slightly less mass than the separate nuclei that formed it, and that lost mass is converted into a very large amount of energy. Chemical bonds involve electrons and release millions of times less energy — fusion is a nuclear process, not a chemical one."},
  {q:"A student claims fusion would be a better power source than fission because the fuel is plentiful. Why is fusion not yet used to generate electricity commercially?",
   opts:["Fusion releases less energy per kilogram of fuel than fission","No isotopes capable of fusing exist on Earth","Creating and containing the extreme temperatures and pressures needed currently uses more energy than practical reactors can return","Fusion reactions only work in the weightless conditions of space"], c:2,
   e:"Because both nuclei are positively charged, they repel strongly, so fusion needs star-core temperatures and pressures; building a reactor that maintains these conditions while producing more energy than it consumes has not yet been achieved at commercial scale. Per kilogram, fusion actually releases MORE energy than fission, and hydrogen isotopes are readily available on Earth."}
]);
