// content/y10/science/islands/x14.js — EXPANSION: Topic 14 extra flashcards + questions.
// Loads AFTER t14.js. Authored by the atlas-content skill. All items original.

// ── EXTRA FLASHCARDS ────────────────────────────────────────────────────────
FLASHCARDS.push(
  // s10i-14-1 — Forces & Moments
  {id:"s10fc-14-1-6", islandId:"s10i-14-1", front:"Why must the distance in M = F × d be the PERPENDICULAR distance?",
   back:"Only the component of the distance at right angles to the force's line of action contributes to the turning effect.\n\n• If the force's line of action passes straight through the pivot, the perpendicular distance is zero — so the moment is zero and there is no turning effect at all.\n• Pushing a door at its hinge does nothing, however hard you push.\n\nAlways measure from the pivot to the line of action of the force, at 90 degrees to that line.", difficulty:2, category:"concept"},
  {id:"s10fc-14-1-7", islandId:"s10i-14-1", front:"A moment of 24 Nm is needed to turn a stiff valve wheel. The force applied is 60 N. How far from the centre must it act?",
   back:"Rearrange M = F × d:\n\nd = M ÷ F\nd = 24 ÷ 60\nd = 0.4 m\n\nThe force must be applied 0.4 m from the centre of the wheel. Applying the force further out would let you use a smaller force for the same moment.", difficulty:2, category:"calculation"},
  {id:"s10fc-14-1-8", islandId:"s10i-14-1", front:"Why is a door handle fitted at the edge of the door, far from the hinges?",
   back:"The hinges act as the pivot. Moment = force × perpendicular distance from the pivot.\n\nPlacing the handle as far from the hinges as possible maximises the distance, so the same push produces the largest possible moment.\n\nThis means only a small force is needed to swing the door open. Pushing near the hinges would need a much larger force for the same turning effect.", difficulty:1, category:"application"},

  // s10i-14-2 — Pressure in Fluids
  {id:"s10fc-14-2-6", islandId:"s10i-14-2", front:"Why are dam walls built much thicker at the bottom than at the top?",
   back:"Pressure in a liquid increases with depth (P = h ρ g).\n\n• At the bottom of the reservoir the water is deepest, so the pressure on the wall is greatest there.\n• The wall must be thickest at the base to withstand this larger sideways force.\n\nNear the surface the pressure is small, so the wall can be thinner at the top.", difficulty:1, category:"application"},
  {id:"s10fc-14-2-7", islandId:"s10i-14-2", front:"The pressure due to the water at the bottom of a swimming pool is 30 000 Pa. How deep is the pool? (ρ = 1000 kg/m³, g = 10 N/kg)",
   back:"Rearrange P = h ρ g:\n\nh = P ÷ (ρ × g)\nh = 30 000 ÷ (1000 × 10)\nh = 30 000 ÷ 10 000\nh = 3 m\n\nThe pool is 3 m deep. Note this uses only the pressure due to the water — atmospheric pressure is not included in the 30 000 Pa.", difficulty:2, category:"calculation"},
  {id:"s10fc-14-2-8", islandId:"s10i-14-2", front:"Does the shape of a container affect the pressure at a given depth in a liquid?",
   back:"No. The pressure at a point in a liquid depends only on:\n\n• the depth below the surface (h)\n• the density of the liquid (ρ)\n• gravitational field strength (g)\n\nP = h ρ g contains no term for the container's shape or width. At the same depth, a narrow tube and a wide tank of the same liquid have exactly the same pressure. Pressure in a liquid also acts equally in all directions at a given depth.", difficulty:2, category:"concept"},

  // s10i-14-3 — Work, Energy & Power
  {id:"s10fc-14-3-6", islandId:"s10i-14-3", front:"You push hard against a wall but it does not move. How much work do you do on the wall?",
   back:"No work is done on the wall.\n\nW = F × s, and the distance moved (s) is zero, so W = F × 0 = 0 J.\n\nWork is only done when a force moves an object through a distance along the line of action of the force. You feel tired because your muscles transfer energy internally, but no mechanical work is done on the wall.", difficulty:2, category:"concept"},
  {id:"s10fc-14-3-7", islandId:"s10i-14-3", front:"A 2 kW electric motor runs for 30 s. How much energy does it transfer?",
   back:"P = E ÷ t, so E = P × t\n\nConvert the power: 2 kW = 2000 W\n\nE = 2000 × 30\nE = 60 000 J (60 kJ)\n\nThe motor transfers 60 000 joules of energy. Always convert kilowatts to watts before substituting.", difficulty:2, category:"calculation"},
  {id:"s10fc-14-3-8", islandId:"s10i-14-3", front:"When a box is lifted at a steady speed, what is the link between the work done and its gravitational potential energy?",
   back:"The work done against gravity equals the gain in gravitational potential energy.\n\nW = F × s = weight × height lifted\n\nFor example, lifting a 50 N box through 2 m:\nW = 50 × 2 = 100 J of work, and the box gains 100 J of gravitational potential energy.\n\nIf the box is lifted at a steady speed, all the work goes to the gravitational store (ignoring air resistance).", difficulty:2, category:"concept"},

  // s10i-14-4 — Elasticity & Hooke's Law
  {id:"s10fc-14-4-6", islandId:"s10i-14-4", front:"In the force–extension required practical, how is the extension of the spring found?",
   back:"Extension = stretched length − natural (original) length\n\nMethod:\n• Measure the natural length of the unloaded spring first, with a metre rule clamped vertically alongside.\n• Add a known mass, calculate its weight (force), and measure the new length.\n• Subtract the natural length to get the extension.\n\nA common error is recording the total length of the spring instead of the extension.", difficulty:1, category:"concept"},
  {id:"s10fc-14-4-7", islandId:"s10i-14-4", front:"A spring with spring constant 300 N/m has a force of 12 N applied. Calculate its extension.",
   back:"F = k e, so e = F ÷ k\n\ne = 12 ÷ 300\ne = 0.04 m (4 cm)\n\nThe spring extends by 0.04 metres. This assumes the spring stays within its limit of proportionality, so Hooke's law applies.", difficulty:2, category:"calculation"},
  {id:"s10fc-14-4-8", islandId:"s10i-14-4", front:"Does Hooke's law apply to compression as well as stretching?",
   back:"Yes. Hooke's law (F = k e) applies to both stretching and compressing, provided the limit of proportionality is not exceeded.\n\n• For compression, e is the decrease in length rather than the increase.\n• The spring constant k measures the stiffness of the spring in both cases: a larger k means a stiffer spring that needs more force per metre of compression or extension.\n\nCar suspension springs, for example, work in compression and obey the same law.", difficulty:2, category:"concept"},

  // s10i-14-5 — Scalars, Vectors & Resultant Forces
  {id:"s10fc-14-5-6", islandId:"s10i-14-5", front:"What is the difference between distance and displacement?",
   back:"• Distance is a scalar: how far an object has moved in total, with no direction.\n• Displacement is a vector: the straight-line distance from start to finish, together with its direction.\n\nExample: an athlete runs one complete lap of a 400 m track.\nDistance travelled = 400 m\nDisplacement = 0, because they finish exactly where they started.", difficulty:1, category:"definition"},
  {id:"s10fc-14-5-7", islandId:"s10i-14-5", front:"If the resultant force on a moving object is zero, what happens to its motion?",
   back:"The object continues moving at a constant velocity — the same speed in the same straight line.\n\n• Zero resultant force does NOT mean the object must be stationary.\n• A stationary object with zero resultant force stays at rest; a moving object with zero resultant force keeps its velocity.\n\nBoth situations are described as equilibrium. A resultant force is needed to change speed or direction, not to keep something moving.", difficulty:2, category:"concept"},
  {id:"s10fc-14-5-8", islandId:"s10i-14-5", front:"Is weight a scalar or a vector? How is it different from mass?",
   back:"Weight is a VECTOR — it is the force of gravity on an object, acting downwards (towards the centre of the Earth).\n\nW = m g\n\nMass is a SCALAR — the amount of matter in an object (kg). It has no direction and does not change with location.\n\nOn the Moon your mass is unchanged, but your weight is smaller because g is smaller there.", difficulty:1, category:"definition"},

  // s10i-14-6 — Levers & Gears
  {id:"s10fc-14-6-6", islandId:"s10i-14-6", front:"How does a wheelbarrow work as a lever?",
   back:"In a wheelbarrow, the wheel is the pivot.\n\n• The load (the contents) sits close to the wheel — a short load arm.\n• The effort is applied at the ends of the long handles — a long effort arm.\n\nBecause effort × effort-arm = load × load-arm, the long handles mean a person can lift a heavy load with a much smaller effort. The wheelbarrow is a force multiplier.", difficulty:2, category:"application"},
  {id:"s10fc-14-6-7", islandId:"s10i-14-6", front:"A bottle opener has a load arm of 0.02 m and an effort arm of 0.12 m. The cap resists with a force of 30 N. What effort is needed?",
   back:"effort × effort-arm = load × load-arm\n\neffort × 0.12 = 30 × 0.02\neffort × 0.12 = 0.6\neffort = 0.6 ÷ 0.12\neffort = 5 N\n\nOnly 5 N of effort removes a cap resisting with 30 N, because the effort arm is six times longer than the load arm.", difficulty:3, category:"calculation"},
  {id:"s10fc-14-6-8", islandId:"s10i-14-6", front:"Why does a cyclist change to a low gear when climbing a steep hill?",
   back:"A low gear makes the rear wheel turn more slowly for each turn of the pedals, but with a LARGER moment (greater turning force).\n\n• Climbing needs a big turning force at the wheel to overcome the slope.\n• The cyclist trades speed for turning force.\n\nOn a flat road, a high gear does the opposite: the wheel turns faster but with a smaller moment, which is fine when little force is needed.", difficulty:2, category:"application"},

  // s10i-14-7 — Floating, Sinking & Upthrust
  {id:"s10fc-14-7-6", islandId:"s10i-14-7", front:"How does a submarine control whether it floats or sinks?",
   back:"A submarine uses ballast tanks to change its weight.\n\n• To dive: the tanks are flooded with seawater, increasing the submarine's weight until it is greater than the upthrust — it sinks.\n• To surface: compressed air pushes the water out of the tanks, reducing the weight until it is less than the upthrust — it rises.\n\nThe upthrust (weight of water displaced by the hull) stays roughly the same; it is the weight that is adjusted.", difficulty:2, category:"application"},
  {id:"s10fc-14-7-7", islandId:"s10i-14-7", front:"An object weighs 10 N in air but a newton meter reads 7 N when it is fully submerged in water. What is the upthrust?",
   back:"Upthrust = weight in air − apparent weight in water\n\nUpthrust = 10 − 7 = 3 N\n\nThe water pushes up on the object with a force of 3 N, which is also equal to the weight of the water the object displaces. The newton meter reads less because the upthrust supports part of the object's weight.", difficulty:2, category:"calculation"},
  {id:"s10fc-14-7-8", islandId:"s10i-14-7", front:"Why does a helium balloon rise through the air?",
   back:"Gases exert upthrust too, because the atmosphere is a fluid.\n\n• The balloon displaces a volume of air, so it experiences an upthrust equal to the weight of that displaced air.\n• Helium is much less dense than air, so the balloon and helium together weigh less than the air they displace.\n• Upthrust is greater than weight, giving a resultant upward force — the balloon accelerates upwards.\n\nIt stops rising when the surrounding air becomes thin enough for the forces to balance.", difficulty:2, category:"concept"}
);

// ── EXTRA QUESTIONS ─────────────────────────────────────────────────────────

// s10i-14-1 — Forces & Moments
QUESTIONS["s10i-14-1"] = (QUESTIONS["s10i-14-1"] || []).concat([
  {q:"What is the unit of a moment?",
   opts:["Newtons (N)","Joules per second (J/s)","Pascals (Pa)","Newton-metres (Nm)"], c:3,
   e:"Moment = force (N) × distance (m), so the unit is the newton-metre (Nm). It is not the same as the joule, even though a joule is also a newton times a metre — moments measure turning effect, not energy transferred."},
  {q:"A force is applied so that its line of action passes directly through the pivot. What is its moment?",
   opts:["Zero","Equal to the force","Maximum possible","Equal to the weight of the object"], c:0,
   e:"The perpendicular distance from the pivot to the line of action is zero, so M = F × 0 = 0. The force may be large, but it creates no turning effect — like pushing a door right at its hinge."},
  {q:"Why is a door handle placed as far from the hinges as possible?",
   opts:["To make the door heavier","So the same force creates a larger moment about the hinges","To reduce the moment needed","Because the hinges would break otherwise"], c:1,
   e:"The hinges are the pivot. Moment = force × distance from the pivot, so a handle far from the hinges gives the largest moment for a given push, making the door easy to open. It does not reduce the moment needed — it reduces the force needed."},
  {q:"Two students push on a balanced beam. To INCREASE the turning effect without pushing harder, a student should:",
   opts:["Push closer to the pivot","Push at a smaller angle to the beam","Push further from the pivot","Push downwards through the pivot"], c:2,
   e:"M = F × d, so for the same force, increasing the perpendicular distance from the pivot increases the moment. Pushing closer to the pivot or through it reduces or removes the turning effect."},
  {q:"A child weighing 300 N sits 1.5 m from the centre of a balanced seesaw. Where must a 450 N child sit on the other side to balance it?",
   opts:["1.5 m from the pivot","2.25 m from the pivot","0.5 m from the pivot","1 m from the pivot"], c:3,
   e:"Balance: 300 × 1.5 = 450 × d, so 450 = 450d and d = 1 m. The heavier child must sit closer to the pivot, not at the same distance — equal distances only balance equal weights."},
  {q:"A force of 8 N acts at a perpendicular distance of 0.5 m from a pivot. Calculate the moment.",
   opts:["16 Nm","4 Nm","8.5 Nm","40 Nm"], c:1,
   e:"M = F × d = 8 × 0.5 = 4 Nm. The tempting answer 16 Nm comes from dividing instead of multiplying — always multiply force by distance."},
  {q:"A moment of 30 Nm is required to loosen a bolt. The spanner is gripped 0.6 m from the bolt. What force is needed?",
   opts:["18 N","5 N","50 N","30.6 N"], c:2,
   e:"Rearranging M = F × d gives F = M ÷ d = 30 ÷ 0.6 = 50 N. Multiplying 30 × 0.6 = 18 is the common error — when finding the force you must divide the moment by the distance."},
  {q:"A force of 90 N produces a moment of 72 Nm about a pivot. What is the perpendicular distance from the pivot?",
   opts:["0.8 m","1.25 m","6480 m","8 m"], c:0,
   e:"d = M ÷ F = 72 ÷ 90 = 0.8 m. Dividing the wrong way round (90 ÷ 72) gives 1.25 m, which is incorrect — the distance is moment divided by force."},
  {q:"On the left of a pivot, a 10 N weight hangs 2 m out and a 5 N weight hangs 1 m out. What single force placed 2.5 m to the right balances the beam?",
   opts:["15 N","25 N","10 N","6 N"], c:2,
   e:"Total anticlockwise moment = (10 × 2) + (5 × 1) = 25 Nm. For balance: F × 2.5 = 25, so F = 10 N. Simply adding the weights (15 N) ignores their different distances from the pivot."},
  {q:"A 20 N force acts at a perpendicular distance of 30 cm from a pivot. What is the moment?",
   opts:["600 Nm","6 Nm","0.6 Nm","66.7 Nm"], c:1,
   e:"Convert first: 30 cm = 0.3 m. M = 20 × 0.3 = 6 Nm. Forgetting to convert centimetres to metres gives the tempting wrong answer of 600 Nm — distances in M = F d must be in metres."}
]);

// s10i-14-2 — Pressure in Fluids
QUESTIONS["s10i-14-2"] = (QUESTIONS["s10i-14-2"] || []).concat([
  {q:"One pascal (Pa) is the same as:",
   opts:["One newton per metre","One newton per square metre","One newton-metre","One kilogram per cubic metre"], c:1,
   e:"Pressure = force ÷ area, so 1 Pa = 1 N/m² (one newton per square metre). One newton-metre is the unit of a moment, and kg/m³ is the unit of density."},
  {q:"Why are dam walls built thicker at the base than at the top?",
   opts:["The water pressure is greater at greater depth","Rain erodes the top of the wall","Atmospheric pressure is higher at the bottom","The water is colder at the bottom"], c:0,
   e:"P = hρg, so pressure increases with depth. The base of the dam must resist the largest sideways push from the water. The change in atmospheric pressure over a dam's height is tiny by comparison."},
  {q:"Two containers — one narrow, one very wide — are filled with water to the same depth. How do the pressures at the bottom compare?",
   opts:["The wide container has greater pressure","The narrow container has greater pressure","The pressures are the same","It depends on the total weight of water"], c:2,
   e:"P = hρg depends only on depth, density and g — not on the container's shape or how much water it holds in total. The wide container holds more water, but that extra weight is spread over a larger base area."},
  {q:"A tractor has very wide tyres. What is the purpose of this design?",
   opts:["To increase the pressure on the soil","To increase the tractor's weight","To increase friction by raising the pressure","To spread the weight over a larger area, reducing the pressure on the soil"], c:3,
   e:"P = F ÷ A. A larger contact area means the tractor's weight produces a lower pressure, so the tyres do not sink into soft ground. Snowshoes work on the same principle. Wide tyres reduce, not increase, the pressure."},
  {q:"At the same depth, in which liquid is the pressure greatest?",
   opts:["The least dense liquid","The most dense liquid","Pressure is the same in all liquids","The liquid with the largest surface area"], c:1,
   e:"P = hρg: at a fixed depth and the same g, pressure is proportional to density ρ. Mercury, for example, produces far more pressure at 1 m depth than water does. Surface area does not appear in the equation."},
  {q:"The air in a tyre exerts a pressure of 2000 Pa on a patch of inner surface with area 0.25 m². What force acts on that patch?",
   opts:["500 N","8000 N","2000.25 N","0.000125 N"], c:0,
   e:"F = P × A = 2000 × 0.25 = 500 N. Dividing pressure by area (8000 N) is the common slip — force is pressure multiplied by area."},
  {q:"Calculate the pressure due to a 2 m deep layer of oil of density 800 kg/m³. (g = 10 N/kg)",
   opts:["1600 Pa","160 000 Pa","8 000 Pa","16 000 Pa"], c:3,
   e:"P = hρg = 2 × 800 × 10 = 16 000 Pa. The answer 1600 Pa comes from forgetting to multiply by g — all three quantities must be multiplied together."},
  {q:"The pressure due to the water at the bottom of a tank is 40 000 Pa. How deep is the water? (ρ = 1000 kg/m³, g = 10 N/kg)",
   opts:["40 m","0.25 m","4 m","400 m"], c:2,
   e:"h = P ÷ (ρg) = 40 000 ÷ (1000 × 10) = 40 000 ÷ 10 000 = 4 m. Dividing by 1000 alone (giving 40 m) misses the factor of g."},
  {q:"A box weighing 900 N exerts a pressure of 4500 Pa on the floor. What is the area of its base?",
   opts:["0.2 m²","5 m²","4 050 000 m²","0.5 m²"], c:0,
   e:"A = F ÷ P = 900 ÷ 4500 = 0.2 m². Dividing the wrong way (4500 ÷ 900 = 5) is the tempting error — area is force divided by pressure."},
  {q:"Taking atmospheric pressure as 101 kPa, what is the TOTAL pressure 3 m below the surface of a lake? (ρ = 1000 kg/m³, g = 10 N/kg)",
   opts:["30 kPa","101 kPa","131 kPa","71 kPa"], c:2,
   e:"Water pressure: P = hρg = 3 × 1000 × 10 = 30 000 Pa = 30 kPa. Total = 30 + 101 = 131 kPa. Quoting 30 kPa alone ignores the atmosphere pressing on the lake's surface, which must be added for total pressure."}
]);

// s10i-14-3 — Work, Energy & Power
QUESTIONS["s10i-14-3"] = (QUESTIONS["s10i-14-3"] || []).concat([
  {q:"What is the unit of power?",
   opts:["The joule (J)","The newton (N)","The newton-metre (Nm)","The watt (W)"], c:3,
   e:"Power is measured in watts, where 1 W = 1 joule per second. The joule is the unit of energy and work, not power — power is the rate of energy transfer."},
  {q:"A student pushes against a parked lorry with a force of 400 N but it does not move. How much work is done on the lorry?",
   opts:["0 J","400 J","4000 J","It depends on the time spent pushing"], c:0,
   e:"W = F × s. The distance moved is zero, so the work done is 0 J regardless of the force or the time. Work requires movement along the line of action of the force."},
  {q:"A box is lifted slowly onto a shelf at a steady speed. Which energy store gains the energy transferred?",
   opts:["The kinetic store of the box","The thermal store of the box","The gravitational potential energy store of the box","The elastic store of the shelf"], c:2,
   e:"Lifting at a steady speed means no gain in kinetic energy; the work done against gravity is transferred to the box's gravitational potential energy store. Thermal transfer by friction is negligible when lifting."},
  {q:"How many watts are there in 3 kW?",
   opts:["30 W","300 W","3000 W","0.003 W"], c:2,
   e:"The prefix kilo means one thousand, so 3 kW = 3 × 1000 = 3000 W. Confusing kilo with one hundred gives the tempting wrong answer of 300 W."},
  {q:"Two identical boxes are pushed with the same force. Box A moves 3 m and box B moves 6 m. Which statement is correct?",
   opts:["Twice as much work is done on box B","Twice as much work is done on box A","The same work is done on both","No work is done on either box"], c:0,
   e:"W = F × s. With equal forces, doubling the distance doubles the work done, so box B has twice as much work done on it. Work depends on distance moved, not just on the force applied."},
  {q:"A cyclist pedals with a driving force of 120 N for 2.5 m. How much work is done?",
   opts:["48 J","122.5 J","300 J","30 J"], c:2,
   e:"W = F s = 120 × 2.5 = 300 J. Dividing force by distance (48 J) or adding them (122.5 J) are the classic slips — work is force multiplied by distance."},
  {q:"600 J of work is done dragging a sledge 12 m at a steady speed. What is the friction force on the sledge?",
   opts:["7200 N","50 N","612 N","0.02 N"], c:1,
   e:"F = W ÷ s = 600 ÷ 12 = 50 N. At steady speed the pulling force balances friction, so friction is also 50 N. Multiplying instead of dividing gives the wrong answer of 7200 N."},
  {q:"A machine does 1500 J of work in 30 s. What is its power output?",
   opts:["45 000 W","1530 W","0.02 W","50 W"], c:3,
   e:"P = W ÷ t = 1500 ÷ 30 = 50 W. Multiplying work by time (45 000) is incorrect — power is work done divided by the time taken."},
  {q:"A 2 kW kettle runs for 60 s. How much energy does it transfer?",
   opts:["120 J","33.3 J","120 000 J","2060 J"], c:2,
   e:"Convert: 2 kW = 2000 W. E = P × t = 2000 × 60 = 120 000 J. The answer 120 J comes from forgetting to convert kilowatts into watts before multiplying."},
  {q:"A weightlifter raises a 200 N barbell through 3 m in 4 s. What is their power output?",
   opts:["600 W","150 W","2400 W","66.7 W"], c:1,
   e:"Work done W = F s = 200 × 3 = 600 J. Power P = W ÷ t = 600 ÷ 4 = 150 W. The value 600 is the work in joules, not the power — you must still divide by the time."}
]);

// s10i-14-4 — Elasticity & Hooke's Law
QUESTIONS["s10i-14-4"] = (QUESTIONS["s10i-14-4"] || []).concat([
  {q:"In the force–extension practical, the extension of the spring is:",
   opts:["The total length of the loaded spring","The stretched length minus the natural length","The natural length minus the stretched length","The length of the ruler used"], c:1,
   e:"Extension = stretched length − natural length. Recording the spring's total length instead of its extension is one of the most common practical errors, which is why the natural length must be measured first."},
  {q:"In the required practical, why should the ruler be read with your eye level with the marker on the spring?",
   opts:["To avoid a parallax error in the reading","To make the spring stretch further","Because the ruler only works at eye level","To keep the spring vertical"], c:0,
   e:"Reading at eye level avoids parallax error, where viewing the scale at an angle makes the reading appear higher or lower than it really is. It has no effect on how far the spring stretches."},
  {q:"On a force–extension graph for a spring, how can the spring constant be found?",
   opts:["The area under the line","The intercept on the extension axis","The highest point of the graph","The gradient of the straight-line section"], c:3,
   e:"With force on the y-axis and extension on the x-axis, the gradient of the linear section equals k (since F = ke). The area under the line gives the elastic potential energy stored, not the spring constant."},
  {q:"A spring is stretched beyond its limit of proportionality and then released. What is observed?",
   opts:["It returns exactly to its natural length","It becomes shorter than its natural length","It is longer than its natural length — it has deformed inelastically","It snaps in every case"], c:2,
   e:"Beyond the limit of proportionality the spring deforms inelastically (plastically), so it stays permanently stretched and does not return to its original length. It does not necessarily snap."},
  {q:"Spring A extends 2 cm and spring B extends 8 cm under the same force. Which statement is correct?",
   opts:["Spring B has the larger spring constant","Spring A has the larger spring constant","Both have the same spring constant","Spring constants cannot be compared this way"], c:1,
   e:"k = F ÷ e: for the same force, a smaller extension means a larger spring constant. Spring A is the stiffer spring. It is tempting to think the spring that stretches more is 'stronger', but a big extension means a small k."},
  {q:"A spring has a spring constant of 150 N/m. What force produces an extension of 0.04 m?",
   opts:["6 N","3750 N","150.04 N","0.6 N"], c:0,
   e:"F = k e = 150 × 0.04 = 6 N. Dividing k by e (3750) is the common error — Hooke's law multiplies the spring constant by the extension."},
  {q:"A force of 30 N is applied to a spring with spring constant 600 N/m. Calculate the extension.",
   opts:["20 m","0.05 m","18 000 m","0.5 m"], c:1,
   e:"e = F ÷ k = 30 ÷ 600 = 0.05 m (5 cm). Dividing the wrong way round (600 ÷ 30 = 20) gives an absurd 20 m extension — always sense-check the size of your answer."},
  {q:"A force of 9 N stretches a spring by 0.03 m. What is the spring constant?",
   opts:["0.27 N/m","27 N/m","300 N/m","3 N/m"], c:2,
   e:"k = F ÷ e = 9 ÷ 0.03 = 300 N/m. Multiplying force by extension (0.27) gives the wrong quantity — the spring constant is force per unit extension."},
  {q:"A spring with spring constant 400 N/m is stretched by 0.05 m within its limit of proportionality. How much elastic potential energy is stored?",
   opts:["20 J","10 J","1 J","0.5 J"], c:3,
   e:"Ee = ½ k e² = 0.5 × 400 × (0.05)² = 0.5 × 400 × 0.0025 = 0.5 J. The answer 10 J comes from forgetting to square the extension — only e is squared, and 0.05² = 0.0025."},
  {q:"A spring extends by 5 cm when a 2 N weight is hung from it. What is its spring constant?",
   opts:["40 N/m","0.4 N/m","10 N/m","2.5 N/m"], c:0,
   e:"Convert first: 5 cm = 0.05 m. k = F ÷ e = 2 ÷ 0.05 = 40 N/m. Using 5 instead of 0.05 gives 0.4 N/m — extensions must be converted to metres before substituting."}
]);

// s10i-14-5 — Scalars, Vectors & Resultant Forces
QUESTIONS["s10i-14-5"] = (QUESTIONS["s10i-14-5"] || []).concat([
  {q:"An athlete runs one complete lap of a 400 m track, finishing where they started. Which statement is correct?",
   opts:["Distance = 0 m and displacement = 400 m","Distance = 400 m and displacement = 0","Both distance and displacement are 400 m","Both distance and displacement are 0"], c:1,
   e:"Distance (a scalar) counts the whole path: 400 m. Displacement (a vector) is the straight line from start to finish, which is zero because they end where they began."},
  {q:"Which of the following is a scalar quantity?",
   opts:["Acceleration","Displacement","Temperature","Momentum"], c:2,
   e:"Temperature has magnitude only, so it is a scalar. Acceleration, displacement and momentum all have a direction as well as a size, making them vectors."},
  {q:"Which statement about mass and weight is correct?",
   opts:["Both are vectors","Mass is a vector; weight is a scalar","Mass is a scalar; weight is a vector acting downwards","Both are scalars"], c:2,
   e:"Mass (kg) is a scalar — an amount of matter with no direction. Weight is the force of gravity (W = mg), and like all forces it is a vector, acting towards the centre of the Earth."},
  {q:"A car travels in a straight line at a constant 20 m/s. What is the resultant force on it?",
   opts:["Equal to the driving force","Equal to its weight","Twice the air resistance","Zero"], c:3,
   e:"Constant velocity means no change in speed or direction, so the resultant force is zero — the driving force exactly balances the resistive forces. A resultant force is only needed to change motion, not to maintain it."},
  {q:"Two tug-of-war teams each pull on a rope with a force of 950 N in opposite directions. What is the resultant force on the rope?",
   opts:["1900 N","950 N","Zero","475 N"], c:2,
   e:"Equal forces in opposite directions cancel: 950 − 950 = 0 N. The rope is in equilibrium. Adding the forces to get 1900 N ignores their opposite directions — direction matters for vectors."},
  {q:"Two people push a car in the same direction with forces of 250 N and 150 N. What is the resultant force?",
   opts:["400 N","100 N","250 N","37 500 N"], c:0,
   e:"Forces along the same line in the same direction simply add: 250 + 150 = 400 N. Subtracting (100 N) would only be correct if the forces acted in opposite directions."},
  {q:"An aircraft has 800 N of thrust forwards and 350 N of drag backwards. What is the resultant force?",
   opts:["450 N forwards","1150 N forwards","450 N backwards","350 N forwards"], c:0,
   e:"Opposite directions, so subtract: 800 − 350 = 450 N, acting in the direction of the larger force — forwards. Adding to get 1150 N treats the opposing drag as if it helped the motion."},
  {q:"Forces of 5 N and 12 N act on an object at right angles to each other. What is the magnitude of the resultant?",
   opts:["17 N","7 N","13 N","60 N"], c:2,
   e:"For perpendicular forces, use Pythagoras (or a scale drawing): √(5² + 12²) = √(25 + 144) = √169 = 13 N. Adding the magnitudes (17 N) is wrong because the forces do not act along the same line."},
  {q:"Three forces act on a box along the same line: 20 N to the right, 5 N to the right and 18 N to the left. What is the resultant?",
   opts:["43 N right","7 N right","7 N left","3 N right"], c:1,
   e:"Total right = 20 + 5 = 25 N; total left = 18 N. Resultant = 25 − 18 = 7 N to the right. Adding all three magnitudes (43 N) ignores the directions of the forces."},
  {q:"An object is in equilibrium. It has 10 N acting up, 10 N acting down and 6 N acting left. What other force must be acting?",
   opts:["6 N to the left","10 N to the right","No other force is needed","6 N to the right"], c:3,
   e:"The vertical forces already balance (10 up, 10 down). For equilibrium the horizontal forces must also balance, so a 6 N force to the right is needed to cancel the 6 N to the left."}
]);

// s10i-14-6 — Levers & Gears
QUESTIONS["s10i-14-6"] = (QUESTIONS["s10i-14-6"] || []).concat([
  {q:"In a wheelbarrow, where is the pivot?",
   opts:["At the handles","In the middle of the load","At the legs","At the wheel"], c:3,
   e:"The wheel is the pivot. The load sits close to the wheel (short load arm) and the effort is applied at the long handles (long effort arm), so a small effort lifts a heavy load."},
  {q:"Why is it easier to undo a tight nut with a long-handled spanner than a short one?",
   opts:["The long spanner weighs more","The same force acts at a greater distance, giving a larger moment","The long spanner increases friction on the nut","The nut becomes weaker with a longer spanner"], c:1,
   e:"M = F × d. A longer handle increases the distance from the pivot (the nut), so the same force produces a bigger turning effect. The spanner's weight is not what loosens the nut."},
  {q:"A cyclist climbing a steep hill selects a low gear. Compared with a high gear, the rear wheel:",
   opts:["Turns more slowly with a larger moment","Turns faster with a smaller moment","Turns faster with a larger moment","Stops turning"], c:0,
   e:"A low gear trades speed for turning force: the wheel rotates more slowly per pedal turn but with a larger moment, which is what is needed to climb against gravity. You cannot gain both speed and moment at once."},
  {q:"A LARGE gear drives a SMALL gear. The small gear:",
   opts:["Turns more slowly with a larger moment","Turns faster with a smaller moment","Turns faster with a larger moment","Turns at the same speed with the same moment"], c:1,
   e:"Driving a smaller gear increases the speed of rotation but reduces the moment. The opposite arrangement (small driving large) gives more turning force but less speed — gears always trade one for the other."},
  {q:"In a pair of tweezers, the effort is applied CLOSER to the pivot than the load. This means:",
   opts:["The effort needed is larger than the load","The effort needed is smaller than the load","The effort equals the load","No effort is needed"], c:0,
   e:"effort × effort-arm = load × load-arm. With a short effort arm and a longer load arm, the effort must be larger than the load. Tweezers sacrifice force for fine control and movement — not every lever is a force multiplier."},
  {q:"A lever lifts a 450 N load with a load arm of 0.5 m. The effort arm is 1.5 m. What effort is needed?",
   opts:["1350 N","225 N","450 N","150 N"], c:3,
   e:"effort × 1.5 = 450 × 0.5 = 225, so effort = 225 ÷ 1.5 = 150 N. Multiplying 450 by 3 instead of dividing by 3 gives 1350 N — the longer effort arm reduces the effort needed."},
  {q:"An effort of 80 N is applied 0.9 m from a pivot. What load can it balance 0.3 m from the pivot on the other side?",
   opts:["26.7 N","240 N","72 N","800 N"], c:1,
   e:"load × 0.3 = 80 × 0.9 = 72, so load = 72 ÷ 0.3 = 240 N. The effort arm is three times the load arm, so the lever multiplies the 80 N effort by three. The answer 26.7 N divides the wrong way."},
  {q:"A 500 N load sits 0.2 m from a pivot. An effort of 125 N is available. How long must the effort arm be to balance the load?",
   opts:["0.05 m","12.5 m","0.8 m","2.5 m"], c:2,
   e:"125 × d = 500 × 0.2 = 100, so d = 100 ÷ 125 = 0.8 m. The load moment is 100 Nm, and dividing by the available effort gives the required arm length."},
  {q:"A bottle opener has a load arm of 0.02 m and an effort arm of 0.10 m. The cap resists with 40 N. What effort removes it?",
   opts:["8 N","200 N","2 N","40 N"], c:0,
   e:"effort × 0.10 = 40 × 0.02 = 0.8, so effort = 0.8 ÷ 0.10 = 8 N. The effort arm is five times the load arm, so the effort is one fifth of the load — 200 N would be the answer if the arms were swapped."},
  {q:"A force of 50 N acts at the edge of a gear wheel of radius 0.06 m. What moment does it produce about the centre?",
   opts:["833 Nm","0.3 Nm","3 Nm","30 Nm"], c:2,
   e:"The radius is the perpendicular distance from the centre, so M = F × d = 50 × 0.06 = 3 Nm. This is why a larger gear wheel (bigger radius) produces a larger moment from the same tooth force."}
]);

// s10i-14-7 — Floating, Sinking & Upthrust
QUESTIONS["s10i-14-7"] = (QUESTIONS["s10i-14-7"] || []).concat([
  {q:"A submarine floods its ballast tanks with seawater. What happens and why?",
   opts:["It rises, because the upthrust increases","It sinks, because its weight becomes greater than the upthrust","It stays level, because the forces stay balanced","It rises, because it becomes less dense"], c:1,
   e:"Flooding the tanks adds water, increasing the submarine's weight while the upthrust on the hull stays roughly the same. Weight now exceeds upthrust, so the resultant force is downwards and it dives."},
  {q:"A helium balloon rises through the air because:",
   opts:["Helium escapes upwards naturally","There is no gravity acting on helium","Hot air pushes it from below","The upthrust from the displaced air is greater than the balloon's weight"], c:3,
   e:"The atmosphere is a fluid, so it exerts upthrust equal to the weight of air displaced. The balloon and helium weigh less than the air they displace, so upthrust exceeds weight and the resultant force is upwards. Gravity still acts on the helium."},
  {q:"A solid object is more dense than the liquid it is placed in. What happens?",
   opts:["It floats fully submerged","It sinks, because its weight exceeds the maximum upthrust","It floats half in and half out","It dissolves"], c:1,
   e:"If the object is denser than the liquid, even when fully submerged the weight of liquid displaced is less than the object's own weight. The maximum upthrust cannot balance the weight, so it sinks."},
  {q:"A floating block is pushed slightly deeper into the water and held. What happens to the upthrust?",
   opts:["It decreases","It stays exactly the same","It increases, because more water is displaced","It becomes zero"], c:2,
   e:"Pushing the block deeper makes it displace a greater volume — and therefore a greater weight — of water, so the upthrust increases. That is why the block springs back up when released."},
  {q:"Why is it easier for a swimmer to float in the Dead Sea than in fresh water?",
   opts:["The salty water is denser, so less of the swimmer's body needs to be submerged to displace their weight in water","The water is warmer","Gravity is weaker there","The swimmer weighs less in salt water"], c:0,
   e:"Salt water is denser than fresh water, so a smaller submerged volume displaces a weight of water equal to the swimmer's weight. The swimmer's actual weight does not change — what changes is how much water must be displaced."},
  {q:"An object weighs 12 N in air. A newton meter reads 9 N when the object is fully submerged in water. What is the upthrust?",
   opts:["21 N","9 N","12 N","3 N"], c:3,
   e:"Upthrust = weight in air − apparent weight in water = 12 − 9 = 3 N. The reading of 9 N is the apparent weight, not the upthrust — the water supports 3 N of the object's weight."},
  {q:"A fully submerged object displaces 0.002 m³ of water. What upthrust acts on it? (ρ = 1000 kg/m³, g = 10 N/kg)",
   opts:["2 N","0.02 N","20 N","200 N"], c:2,
   e:"Mass of displaced water = ρ × V = 1000 × 0.002 = 2 kg. Weight of displaced water = 2 × 10 = 20 N, and the upthrust equals this. The answer 2 N gives the mass in kilograms, not the weight in newtons."},
  {q:"A toy boat weighing 50 N floats at rest on a pond. What is the upthrust on it?",
   opts:["Zero","Less than 50 N","Exactly 50 N","More than 50 N"], c:2,
   e:"A floating object at rest is in equilibrium: upthrust = weight = 50 N. If the upthrust were larger it would rise; smaller and it would sink lower. Floating does not mean there is no upthrust — it means the forces balance."},
  {q:"A cube is submerged with its top face 1 m deep and its bottom face 1.5 m deep in water. What is the pressure DIFFERENCE between the faces? (ρ = 1000 kg/m³, g = 10 N/kg)",
   opts:["5000 Pa","25 000 Pa","15 000 Pa","10 000 Pa"], c:0,
   e:"Difference in depth = 1.5 − 1 = 0.5 m, so pressure difference = 0.5 × 1000 × 10 = 5000 Pa. Using the full 1.5 m depth (15 000 Pa) gives the pressure at the bottom face, not the difference that causes upthrust."},
  {q:"A block of wood has a density of 800 kg/m³ and floats in water of density 1000 kg/m³. Roughly what fraction of the block is submerged?",
   opts:["20%","50%","100%","80%"], c:3,
   e:"Floating: weight of block = weight of water displaced, so the submerged fraction equals the density ratio 800 ÷ 1000 = 0.8, i.e. 80% under water with 20% above. Choosing 20% reverses which part is submerged."}
]);
