// content/y10/science/islands/x15.js — EXPANSION: Topic 15 extra flashcards + questions.
// Loads AFTER t15.js. Authored by the atlas-content skill. All items original.

FLASHCARDS.push(
  // s10i-15-1 — Properties of Transition Metals (extra)
  {id:"s10fc-15-1-6", islandId:"s10i-15-1", front:"Why are Group 1 metals stored under oil, while transition metals such as copper can be left out in the air?",
   back:"Group 1 metals are so reactive that they react rapidly with oxygen and water vapour in the air, so they are stored under oil to keep air and moisture away.\n\nTransition metals are far less reactive:\n• Copper reacts only very slowly with the air.\n• Gold does not react with air at all.\n\nThis low reactivity means transition metals can be stored, handled and used in the open without any special protection.", difficulty:2, category:"concept"},
  {id:"s10fc-15-1-7", islandId:"s10i-15-1", front:"A student is given titanium, a transition metal they have not studied. Predict its physical properties.",
   back:"Because titanium is a transition metal, you can predict it will share the typical transition metal properties:\n\n• Hard and strong\n• High density\n• High melting point\n• A good conductor of heat and electricity\n• Low reactivity with water and oxygen\n\nThis is a useful exam skill — you can predict the properties of any unfamiliar transition metal from its position in the central block of the periodic table.", difficulty:3, category:"application"},
  {id:"s10fc-15-1-8", islandId:"s10i-15-1", front:"Why would sodium be a poor choice of metal for building a bridge, even though it is cheap?",
   back:"Sodium has none of the properties needed for a structural metal:\n\n• It is soft — it can be cut with a knife, so it has very little strength.\n• It has a low melting point and low density.\n• It is extremely reactive — it would react vigorously with rainwater and the oxygen in air.\n\nA bridge needs a hard, strong, unreactive metal with a high melting point — which is why transition metals such as iron (as steel) are used instead.", difficulty:2, category:"application"},

  // s10i-15-2 — Coloured Compounds & Variable Oxidation States (extra)
  {id:"s10fc-15-2-6", islandId:"s10i-15-2", front:"Why must the name of a transition metal compound, such as iron chloride, include a Roman numeral?",
   back:"Because transition metals have variable oxidation states, the name 'iron chloride' on its own is ambiguous — it could be either of two different compounds:\n\n• Iron(II) chloride, FeCl₂, containing Fe²⁺\n• Iron(III) chloride, FeCl₃, containing Fe³⁺\n\nThe Roman numeral states the charge on the metal ion, so the exact compound is clear.\n\nGroup 1 metals never need a Roman numeral, because they only ever form 1+ ions.", difficulty:2, category:"concept"},
  {id:"s10fc-15-2-7", islandId:"s10i-15-2", front:"Use charge balancing to explain why iron(III) oxide has the formula Fe₂O₃.",
   back:"In an ionic compound the total positive charge must balance the total negative charge.\n\n• Iron(III) is Fe³⁺ and oxide is O²⁻.\n• Two Fe³⁺ ions give a total charge of 6+.\n• Three O²⁻ ions give a total charge of 6−.\n\nSo the smallest ratio that balances is 2 iron ions to 3 oxide ions, giving Fe₂O₃.\n\nThe same method works for any oxidation state — iron(II) oxide is simply FeO, because 2+ balances 2−.", difficulty:3, category:"concept"},
  {id:"s10fc-15-2-8", islandId:"s10i-15-2", front:"Give a use of transition metal compounds that depends on their colour.",
   back:"Because transition metal compounds are typically coloured, they are used as pigments:\n\n• In paints and inks\n• In pottery glazes and coloured glass\n\nFor example, copper compounds give blues and greens, while iron compounds give yellows, oranges and browns.\n\nGroup 1 metal compounds could not be used this way, because they are white solids that form colourless solutions.", difficulty:1, category:"application"},

  // s10i-15-3 — Transition Metals as Catalysts (extra)
  {id:"s10fc-15-3-6", islandId:"s10i-15-3", front:"Give two economic or environmental reasons why industry uses transition metal catalysts.",
   back:"Catalysts lower the activation energy of a reaction, which brings real benefits:\n\n• Reactions can run faster, or at lower temperatures and pressures, so less energy is needed.\n• Lower energy use means lower costs and less fossil fuel burned, reducing carbon dioxide emissions.\n• The catalyst is not used up, so a small amount lasts a long time.\n\nThis is why processes such as the Haber and Contact processes would be uneconomical without their catalysts.", difficulty:2, category:"application"},
  {id:"s10fc-15-3-7", islandId:"s10i-15-3", front:"Describe an experiment to show that manganese(IV) oxide acts as a catalyst for the decomposition of hydrogen peroxide.",
   back:"1. Weigh a sample of manganese(IV) oxide, then add it to hydrogen peroxide solution.\n2. Observe that oxygen gas is produced much faster than without it (faster bubbling, or a glowing splint relights).\n3. At the end, filter off the manganese(IV) oxide, dry it and reweigh it.\n\nIf its mass is unchanged and it still speeds up a fresh sample of hydrogen peroxide, it has speeded up the reaction without being used up — the definition of a catalyst.", difficulty:3, category:"application"},
  {id:"s10fc-15-3-8", islandId:"s10i-15-3", front:"What effect does a catalyst have on the overall energy change of a reaction?",
   back:"None — a catalyst does not change the overall energy change of a reaction.\n\n• On a reaction profile, the catalyst lowers the activation energy 'hump' only.\n• The energy levels of the reactants and products stay exactly the same.\n• The same products are made — they are just made faster.\n\nA common exam error is to claim a catalyst makes a reaction 'more exothermic'. It does not — it only provides a lower-energy pathway.", difficulty:2, category:"concept"}
);

QUESTIONS["s10i-15-1"] = (QUESTIONS["s10i-15-1"] || []).concat([
  {q:"Which property of copper makes it especially suitable for electrical wiring?",
   opts:["It is a good conductor of electricity and can be drawn into wires","It has a very low melting point","It reacts quickly with oxygen in the air","It is the densest of all metals"], c:0,
   e:"Copper conducts electricity well and is ductile, so it can be drawn into wires. It is actually unreactive — a metal that reacted quickly with air would corrode and fail."},
  {q:"Which list contains only transition metals?",
   opts:["Sodium, iron, copper","Iron, nickel, copper","Calcium, zinc, lithium","Potassium, gold, magnesium"], c:1,
   e:"Iron, nickel and copper all sit in the central block of the periodic table. Sodium, lithium and potassium are Group 1 metals, and calcium and magnesium are in Group 2."},
  {q:"A small piece of metal is dropped into water. It fizzes violently, moves around the surface and may ignite. What type of metal is it most likely to be?",
   opts:["A transition metal such as copper","An unreactive metal such as gold","A Group 1 metal such as potassium","A transition metal such as iron"], c:2,
   e:"A violent reaction with water is characteristic of the highly reactive Group 1 metals. Transition metals such as copper or iron react slowly with water, if at all."},
  {q:"Compared with a typical Group 1 metal, a typical transition metal has...",
   opts:["a lower density and a lower melting point","a higher density and a higher melting point","a lower density but a higher melting point","a higher density but a lower melting point"], c:1,
   e:"Transition metals are denser and have higher melting points than Group 1 metals (mercury being the one exception for melting point). Group 1 metals are low-density — some even float on water."},
  {q:"Why is steel (mostly iron) used for car bodies rather than a Group 1 metal?",
   opts:["Steel is softer and easier to bend","Steel is strong and hard, while Group 1 metals are soft and too reactive","Group 1 metals are too dense for cars","Steel reacts vigorously with rainwater"], c:1,
   e:"Car bodies need a hard, strong material, and steel provides this. Group 1 metals are soft enough to cut with a knife and would react dangerously with rainwater — and steel does not react vigorously with water, it only rusts slowly."},
  {q:"Which transition metal property explains why saucepans often have copper bases?",
   opts:["Copper is a good conductor of heat","Copper is a liquid at room temperature","Copper reacts rapidly with food","Copper has a very low melting point"], c:0,
   e:"Copper conducts heat well, so the pan heats up quickly and evenly. Mercury, not copper, is the transition metal that is liquid at room temperature."},
  {q:"A metal has a density of 8.9 g/cm³, is hard, has a melting point of 1455 °C and reacts very slowly with dilute acid. Where in the periodic table is it most likely to be found?",
   opts:["Group 1","Group 0","The central block, between Group 2 and Group 3","Group 7"], c:2,
   e:"High density, hardness, a high melting point and low reactivity are the classic properties of a transition metal, which sits in the central block. A Group 1 metal would be soft, low-density and very reactive."},
  {q:"Manganese is a transition metal that students do not usually study directly. Which prediction about manganese is most likely to be correct?",
   opts:["It can be cut with a knife and floats on water","It is hard, dense and has a high melting point","It is a gas at room temperature","It reacts explosively with cold water"], c:1,
   e:"All transition metals (except liquid mercury) are hard, dense solids with high melting points, so this prediction is safe. Cutting with a knife and floating on water describe Group 1 metals, not transition metals."},
  {q:"Iron is left outside for several weeks and slowly forms rust. Sodium reacts within seconds of touching water. What does this comparison show?",
   opts:["Iron is more reactive than sodium","Transition metals are much less reactive than Group 1 metals","Both metals have the same reactivity","Sodium is a transition metal"], c:1,
   e:"Iron's slow rusting against sodium's instant, vigorous reaction shows how much less reactive transition metals are than Group 1 metals. Sodium reacting faster means it is more reactive, not less."},
  {q:"Which statement about mercury is correct?",
   opts:["It is a Group 1 metal with a high melting point","It is a non-metal found in Group 7","It is a typical transition metal: a hard, dense solid","It is a transition metal and the only metal that is liquid at room temperature"], c:3,
   e:"Mercury is a transition metal, but it is the exception to the rule about high melting points — it is liquid at room temperature. It is therefore not a 'typical' hard solid transition metal."}
]);

QUESTIONS["s10i-15-2"] = (QUESTIONS["s10i-15-2"] || []).concat([
  {q:"What is the formula of iron(III) chloride?",
   opts:["FeCl","FeCl₂","FeCl₃","Fe₃Cl"], c:2,
   e:"Iron(III) is Fe³⁺ and chloride is Cl⁻, so three chloride ions are needed to balance one iron ion, giving FeCl₃. FeCl₂ is iron(II) chloride, which contains Fe²⁺."},
  {q:"In copper(II) sulfate, what is the charge on the copper ion?",
   opts:["1+","2+","2−","3+"], c:1,
   e:"The Roman numeral (II) in the name tells you the copper ion has a charge of 2+, i.e. Cu²⁺. The numeral always gives the positive charge on the metal ion, not a negative charge."},
  {q:"A student makes a bright blue solution by dissolving a solid in water. Which solid is most likely?",
   opts:["Sodium chloride","Copper(II) sulfate","Iron(II) sulfate","Potassium nitrate"], c:1,
   e:"Copper(II) compounds typically give blue solutions. Iron(II) sulfate would be pale green, while sodium chloride and potassium nitrate are Group 1 compounds and form colourless solutions."},
  {q:"Why is it not necessary to write 'sodium(I) chloride' for NaCl?",
   opts:["Sodium has no charge in its compounds","Sodium only ever forms 1+ ions, so there is no ambiguity","Sodium can form many different ions","Roman numerals are only used for non-metals"], c:1,
   e:"Group 1 metals have a single fixed oxidation state of 1+, so the Roman numeral adds no information. It is the variable oxidation states of transition metals that make Roman numerals necessary."},
  {q:"What is the oxidation state of manganese in manganese(IV) oxide, MnO₂?",
   opts:["2+","3+","6+","4+"], c:3,
   e:"The Roman numeral (IV) tells you manganese is in the 4+ oxidation state. This balances the two oxide ions (2 × 2− = 4−). The '2' in MnO₂ counts the oxygens — it does not mean manganese is 2+."},
  {q:"Which compound would you expect to be a white solid that dissolves to give a colourless solution?",
   opts:["Iron(III) chloride","Copper(II) sulfate","Potassium chloride","Iron(II) sulfate"], c:2,
   e:"Potassium is a Group 1 metal, and Group 1 compounds are typically white solids forming colourless solutions. The other three are transition metal compounds, which are typically coloured."},
  {q:"A pale green solution of an iron compound is left in air and slowly turns orange-brown. What is the best explanation?",
   opts:["Fe²⁺ ions have been oxidised to Fe³⁺ ions","Fe³⁺ ions have been converted to Fe²⁺ ions","The iron has turned into copper","The solution has become a Group 1 compound"], c:0,
   e:"Pale green indicates iron(II), Fe²⁺, and orange-brown indicates iron(III), Fe³⁺ — so the iron has been oxidised from the 2+ to the 3+ state. The reverse change (Fe³⁺ to Fe²⁺) would turn the solution from orange-brown to pale green."},
  {q:"Iron(II) oxide has the formula FeO, but iron(III) oxide is Fe₂O₃. Why are the formulae different?",
   opts:["Oxygen changes its charge in the two compounds","The iron ions have different charges, so different ratios are needed to balance the 2− oxide ions","Iron(III) oxide contains extra electrons","One compound is ionic and the other is covalent"], c:1,
   e:"Fe²⁺ balances one O²⁻ directly (FeO), but with Fe³⁺ you need two iron ions (6+) to balance three oxide ions (6−), giving Fe₂O₃. Oxide is 2− in both compounds — it is the iron's oxidation state that varies."},
  {q:"Nickel is a transition metal. What is the best prediction about nickel(II) sulfate?",
   opts:["It will be a white solid forming a colourless solution","It will be a coloured compound","Nickel will have a 1+ charge in it","It will behave exactly like sodium sulfate"], c:1,
   e:"Transition metal compounds are typically coloured, so a nickel compound is very likely to be coloured (nickel(II) compounds are in fact green). A white solid and colourless solution would be expected for a Group 1 compound, not a transition metal compound."},
  {q:"Which of the following is a use of transition metal compounds that relies on their typical colours?",
   opts:["As pigments in paints and pottery glazes","As fuels in power stations","As insulators in electrical cables","As the main gas in light bulbs"], c:0,
   e:"Because transition metal compounds are coloured, they are used as pigments in paints, glazes and coloured glass. Compounds are not fuels or filler gases, and metals conduct rather than insulate."}
]);

QUESTIONS["s10i-15-3"] = (QUESTIONS["s10i-15-3"] || []).concat([
  {q:"At the end of a catalysed reaction, what has happened to the mass of the catalyst?",
   opts:["It has all been used up","It has halved","It is unchanged","It has doubled"], c:2,
   e:"A catalyst is not used up in the reaction, so its mass is unchanged at the end and it can be recovered and reused. If the mass fell, the substance would be a reactant, not a catalyst."},
  {q:"On a reaction profile diagram, what change does adding a catalyst make?",
   opts:["It raises the energy of the products","It lowers the activation energy peak only","It lowers the energy of the reactants","It makes the reaction more exothermic"], c:1,
   e:"A catalyst lowers only the activation energy 'hump' by providing an alternative pathway. The energy levels of reactants and products are unchanged, so the overall energy change stays exactly the same."},
  {q:"Why does industry benefit financially from using transition metal catalysts?",
   opts:["Catalysts increase the activation energy, saving fuel","Reactions can run faster or at lower temperatures, so less energy is paid for","Catalysts must be replaced after every reaction","Catalysts change the products into more expensive ones"], c:1,
   e:"By lowering the activation energy, a catalyst lets a reaction run faster or at a lower temperature, cutting energy bills. Catalysts are not used up, so they do not need replacing after every reaction — that is part of the saving."},
  {q:"Which environmental benefit comes from using a catalyst in an industrial process?",
   opts:["More fossil fuel is burned","Less energy is needed, so less fossil fuel is burned and less carbon dioxide is released","The reaction produces more waste products","The catalyst absorbs all the carbon dioxide"], c:1,
   e:"Lower energy demand means less fossil fuel is burned to heat the reaction, cutting carbon dioxide emissions. A catalyst does not absorb carbon dioxide — it simply provides a lower-energy pathway."},
  {q:"Which statement correctly matches an industrial process with its transition metal catalyst?",
   opts:["Haber process — nickel","Contact process — vanadium(V) oxide","Hydrogenation of vegetable oils — iron","Decomposition of hydrogen peroxide — vanadium(V) oxide"], c:1,
   e:"Vanadium(V) oxide catalyses the Contact process (making sulfuric acid). The Haber process uses iron, hydrogenation of oils uses nickel, and hydrogen peroxide decomposition uses manganese(IV) oxide."},
  {q:"Catalytic converters in car exhausts use transition metals such as platinum. What is their job?",
   opts:["To speed up reactions that convert harmful exhaust gases into less harmful ones","To make the engine burn fuel more slowly","To absorb all the exhaust gases permanently","To cool the exhaust gases down"], c:0,
   e:"Transition metals in the converter catalyse reactions that turn pollutants such as carbon monoxide into less harmful gases such as carbon dioxide. The converter speeds up reactions — it does not store the gases or cool them."},
  {q:"A student adds manganese(IV) oxide to hydrogen peroxide. Which observation, on its own, is NOT enough to prove it acted as a catalyst?",
   opts:["The reaction was faster than without the powder","The mass of the powder was unchanged at the end","The powder could be reused to speed up a fresh sample","Bubbles of oxygen were produced faster"], c:1,
   e:"Unchanged mass alone could just mean the powder did nothing at all. To prove catalysis you also need evidence that the reaction speeded up. Faster bubbling shows speeding up but not that the powder survived — proof needs both together."},
  {q:"Does adding a catalyst change the amount of product made by a reaction that goes to completion?",
   opts:["Yes — more product is always made","Yes — different products are made","No — less product is made but more quickly","No — the same amount of the same products is made, just faster"], c:3,
   e:"A catalyst changes only the rate, not the products or the final amount made. Thinking a catalyst 'makes more product' is a common error — it only gets you to the same products sooner."},
  {q:"Why are transition metals better suited to being catalysts than Group 1 metals?",
   opts:["Group 1 metals are too dense to use","Transition metals can use their variable oxidation states to help reactions along, and are stable enough to survive the conditions","Group 1 metals are excellent catalysts but too expensive","Transition metals are used up more slowly than Group 1 metals"], c:1,
   e:"Variable oxidation states let transition metals temporarily gain and lose electrons during a reaction, and their low reactivity means they survive the reaction conditions. Group 1 metals are far too reactive — and a true catalyst is not used up at all, slowly or otherwise."},
  {q:"Without a catalyst, the Haber process would need an even higher temperature to achieve a useful rate. What does the iron catalyst allow?",
   opts:["A useful rate at a lower temperature, saving energy","The reaction to produce a different gas","Nitrogen and hydrogen to be created from nothing","The reaction to release more energy overall"], c:0,
   e:"The iron catalyst lowers the activation energy, so a useful rate is reached at a lower temperature and less energy is wasted. A catalyst never changes the products or the overall energy change of the reaction."}
]);
